import { motionTokens } from "../motion";
import type { ThemeTokens } from "../types";

/** Air — minimal Apple. Flat surfaces, hairlines, system blue accent. */
export const airTheme: ThemeTokens = {
  theme: "air",
  material: "flat",
  colors: {
    bg: "#f5f5f7",
    bgElevated: "#ffffff",
    bgGlass: "#ffffff",
    surface: "#ffffff",
    surfaceBorder: "rgba(0, 0, 0, 0.06)",
    text: "#1d1d1f",
    textMuted: "#6e6e73",
    textSubtle: "#86868b",
    accent: "#007aff",
    accentSolid: "#007aff",
    accentGradient: ["#007aff", "#0066d6"],
    pillActiveBg: "rgba(0, 122, 255, 0.12)",
    pillActiveText: "#004999",
    success: "#34c759",
    warning: "#ff9500",
    danger: "#ff3b30",
    tabInactive: "#8e8e93",
    tabBarBg: "#f9f9fb",
    tabBarBorder: "rgba(0, 0, 0, 0.06)",
    overlay: "rgba(0, 0, 0, 0.4)",
    shadow: "rgba(0, 0, 0, 0.06)",
    logoBase: "#1d1d1f",
    logoAccent: "#007aff",
    statusBar: "dark",
    seekTrack: "rgba(0, 0, 0, 0.08)",
    seekFill: "#007aff",
  },
  typography: {
    display: { fontSize: 32, fontWeight: "700", letterSpacing: -0.6, lineHeight: 36 },
    title: { fontSize: 20, fontWeight: "600", letterSpacing: -0.3 },
    subtitle: { fontSize: 17, fontWeight: "600" },
    body: { fontSize: 17, fontWeight: "400", lineHeight: 24 },
    caption: { fontSize: 13, fontWeight: "400", lineHeight: 18 },
    micro: { fontSize: 11, fontWeight: "500", letterSpacing: 0.2 },
    mono: { fontSize: 13, fontWeight: "400", fontVariant: ["tabular-nums"] },
  },
  radius: { sm: 8, md: 10, lg: 12, xl: 16, cover: 8, pill: 999 },
  elevation: {
    card: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 1,
    },
  },
  motion: {
    pressScale: motionTokens.pressScale,
    pressDuration: motionTokens.pressDuration,
    modalDuration: motionTokens.modalDuration,
  },
  glass: null,
};
