import type { SeoPageConfig } from "@/lib/seoPages";
import { regionalMusicSeoPage } from "@/lib/seoPageFactory";

const ASIA_HUB_RELATED = [
  "asia-music-generator",
  "ai-k-pop-song-generator",
  "ai-j-pop-generator",
  "ai-bollywood-music-generator",
  "ai-bhangra-generator",
  "middle-east-music-generator",
  "ai-khaleeji-song-generator",
  "ai-arabic-pop-generator",
];

const ME_HUB_RELATED = [
  "middle-east-music-generator",
  "ai-khaleeji-song-generator",
  "ai-arabic-pop-generator",
  "ai-mahraganat-generator",
  "ai-dabke-music-generator",
  "ai-turkish-pop-generator",
  "ai-persian-pop-generator",
  "asia-music-generator",
];

export const ASIA_SEO_PAGES: SeoPageConfig[] = [
  {
    path: "/asia-music-generator",
    pathFr: "/generateur-musique-asie-ia",
    slugKey: "asia-music-generator",
    category: "hub",
    relatedLimit: 12,
    relatedSlugKeys: ASIA_HUB_RELATED,
    promptHintEn: 'Genre précis → "K-Pop Idol" or "J-Pop" or "Bollywood" → Song Mode → manual lyrics',
    promptHintFr: 'Genre précis → « K-Pop Idol » ou « J-Pop » ou « Bollywood » → Song Mode → paroles manuelles',
    titleEn: "Asia Music Generator — K-Pop, J-Pop, Bollywood & More | ProducerHit",
    titleFr: "Générateur musique Asie IA — K-Pop, J-Pop, Bollywood & plus | ProducerHit",
    descriptionEn:
      "Asia music generator AI: K-Pop, J-Pop, Bollywood, Bhangra, City Pop, Anison — 25+ dedicated genres. Song Mode with Korean, Japanese, Hindi vocals. Beats Suno's generic « Asian » preset.",
    descriptionFr:
      "Générateur musique Asie IA : K-Pop, J-Pop, Bollywood, Bhangra, City Pop, Anison — 25+ genres dédiés. Song Mode voix coréennes, japonaises, hindi.",
    keywords: [
      "Asia music generator AI",
      "K-Pop AI generator",
      "J-Pop AI generator",
      "Bollywood AI music",
      "Asian song generator AI",
    ],
    h1En: "Asia Music Generator",
    h1Fr: "Générateur musique Asie IA",
    leadEn:
      "The most complete **Asia music generator** in 2026 — **K-Pop Idol**, **J-Pop**, **City Pop**, **Anison**, **Bollywood**, **Bhangra** and more. Not one « Oriental » slider like Suno/Udio.",
    leadFr:
      "Le **générateur musique Asie IA** le plus complet en 2026 — **K-Pop Idol**, **J-Pop**, **City Pop**, **Anison**, **Bollywood**, **Bhangra**. Pas un slider « Oriental » comme Suno/Udio.",
    bulletsEn: [
      "25+ Asia genres (wave 2+3 catalog)",
      "Suno/Udio: ~5 Asian styles · ProducerHit: 25+",
      "K-Pop Idol · Ballad · K-Indie · K-Rock",
      "Seed iteration + Versions×2",
    ],
    bulletsFr: [
      "25+ genres Asie (catalogue vague 2+3)",
      "Suno/Udio : ~5 styles · ProducerHit : 25+",
      "K-Pop Idol · Ballad · K-Indie · K-Rock",
      "Iteration seed + Versions×2",
    ],
    faqEn: [
      { q: "K-Pop AI generator vs Suno?", a: "ProducerHit has K-Pop Idol, K-Pop Ballad, K-Hip-Hop as separate ACE genres — plus seed iteration and beat mode in one studio." },
      { q: "Hindi or Korean lyrics?", a: "Manual lyrics mode auto-detects script. Pick vocal language in Song Mode advanced." },
    ],
    faqFr: [
      { q: "K-Pop IA vs Suno ?", a: "ProducerHit a K-Pop Idol, Ballad, K-Hip-Hop comme genres ACE séparés — plus seed et beat mode." },
      { q: "Paroles hindi ou coréennes ?", a: "Paroles manuelles avec détection auto. Langue vocale en Song Mode avancé." },
    ],
  },
  {
    path: "/middle-east-music-generator",
    pathFr: "/generateur-musique-moyen-orient-ia",
    slugKey: "middle-east-music-generator",
    category: "hub",
    relatedLimit: 12,
    relatedSlugKeys: ME_HUB_RELATED,
    promptHintEn: 'Genre "Khaleeji" or "Arabic Pop" or "Mahraganat" → Song Mode → Arabic lyrics',
    promptHintFr: 'Genre « Khaleeji » ou « Arabic Pop » ou « Mahraganat » → Song Mode → paroles arabes',
    titleEn: "Middle East Music Generator — Khaleeji, Arabic Pop, Mahraganat | ProducerHit",
    titleFr: "Générateur musique Moyen-Orient IA — Khaleeji, Arabic Pop, Mahraganat | ProducerHit",
    descriptionEn:
      "Middle East music generator: Khaleeji, Arabic Pop, Mahraganat, Dabke, Gulf Trap, Persian Pop, Turkish Pop — 13+ ACE genres. Arabic vocals. Free MP3.",
    descriptionFr:
      "Générateur musique Moyen-Orient : Khaleeji, Arabic Pop, Mahraganat, Dabke, Gulf Trap, Persian Pop, Turkish Pop — 13+ genres ACE. Voix arabes. MP3 gratuit.",
    keywords: [
      "Middle East music generator AI",
      "Khaleeji AI generator",
      "Arabic pop AI generator",
      "Mahraganat AI generator",
      "Arabic song generator AI",
    ],
    h1En: "Middle East Music Generator",
    h1Fr: "Générateur musique Moyen-Orient IA",
    leadEn:
      "**13+ Middle East genres** — Khaleeji, Arabic Pop, Mahraganat, Shaabi, Dabke, Gulf Trap — each with darbuka, quarter-tone, and regional groove prompts. Competitors collapse this into « Middle Eastern ».",
    leadFr:
      "**13+ genres Moyen-Orient** — Khaleeji, Arabic Pop, Mahraganat, Shaabi, Dabke, Gulf Trap — prompts darbuka et quarter-tone. Les concurrents fusionnent en « Middle Eastern ».",
    bulletsEn: [
      "13+ Gulf & Levant genres",
      "Mahraganat · Shaabi · Dabke niche",
      "Arabic manual lyrics supported",
      "680+ total genre catalog",
    ],
    bulletsFr: [
      "13+ genres Golfe & Levant",
      "Niche Mahraganat · Shaabi · Dabke",
      "Paroles arabes manuelles",
      "Catalogue 680+ genres total",
    ],
    faqEn: [
      { q: "Khaleeji vs Arabic Pop?", a: "Khaleeji = Gulf romantic groove; Arabic Pop = Levant-Egypt radio crossover — separate genres in catalog." },
      { q: "Persian or Turkish?", a: "Persian Pop and Turkish Pop are dedicated genres with santur/bağlama prompts." },
    ],
    faqFr: [
      { q: "Khaleeji vs Arabic Pop ?", a: "Khaleeji = groove romantique Golfe ; Arabic Pop = crossover Levant-Égypte — genres séparés." },
      { q: "Persan ou turc ?", a: "Persian Pop et Turkish Pop sont des genres dédiés avec prompts santur/bağlama." },
    ],
  },
  {
    path: "/ai-k-pop-song-generator",
    pathFr: "/generateur-k-pop-ia",
    slugKey: "ai-k-pop-song-generator",
    category: "asia",
    prefillGenre: "K-Pop Idol",
    prefillMode: "song",
    relatedSlugKeys: ["asia-music-generator", "ai-j-pop-generator", "ai-bollywood-music-generator", "ai-song-generator"],
    relatedLimit: 8,
    promptHintEn: 'Genre "K-Pop Idol": "stacked harmonies, trap-pop drums, supersaw chorus drop, Korean-English hooks, 124 BPM"',
    promptHintFr: 'Genre « K-Pop Idol » : « harmonies stackées, drums trap-pop, drop supersaw, hooks coréen-anglais, 124 BPM »',
    titleEn: "AI K-Pop Song Generator — Idol Hooks & Korean Vocals (2026) | ProducerHit",
    titleFr: "Générateur K-Pop IA — Hooks idol & voix coréennes (2026) | ProducerHit",
    descriptionEn:
      "AI K-Pop song generator: K-Pop Idol, K-Pop Ballad, K-Indie, K-Rock, K-Hip-Hop. Song Mode with Korean lyrics. Versions×2 beats generic AI pop.",
    descriptionFr:
      "Générateur chanson K-Pop IA : K-Pop Idol, Ballad, K-Indie, K-Rock, K-Hip-Hop. Song Mode paroles coréennes. Versions×2 bat la pop IA générique.",
    keywords: ["AI K-Pop song generator", "K-Pop AI generator", "Korean song AI maker", "K-Pop idol AI music"],
    h1En: "AI K-Pop Song Generator",
    h1Fr: "Générateur K-Pop IA",
    leadEn: "Generate **K-Pop** with dedicated subgenres — Idol, Ballad, K-Indie, K-Rock — not western pop with Hangul pasted on. **680+ genres**, seed lock, community remix.",
    leadFr: "Génère du **K-Pop** avec sous-genres dédiés — Idol, Ballad, K-Indie, K-Rock — pas de la pop occidentale avec du Hangul. **680+ genres**, seed, remix communauté.",
    bulletsEn: ["K-Pop Idol default genre", "K-Pop Ballad · K-Indie · K-Rock", "Manual Korean lyrics", "Beat + Song one studio"],
    bulletsFr: ["Genre par défaut K-Pop Idol", "K-Pop Ballad · K-Indie · K-Rock", "Paroles coréennes manuelles", "Beat + Song un studio"],
    faqEn: [
      { q: "K-Pop vs K-Pop Idol genre?", a: "Core K-Pop for general use; K-Pop Idol for stacked harmonies and music-show production." },
      { q: "Better than Suno for K-Pop?", a: "More subgenres, seed iteration, beat mode, and 680+ catalog vs Suno's single style picker." },
    ],
    faqFr: [
      { q: "K-Pop vs K-Pop Idol ?", a: "K-Pop core pour usage général ; K-Pop Idol pour harmonies stackées et prod music-show." },
      { q: "Mieux que Suno pour K-Pop ?", a: "Plus de sous-genres, seed, beat mode, 680+ catalogue vs un seul picker Suno." },
    ],
  },
  regionalMusicSeoPage({
    slugKey: "ai-khaleeji-song-generator",
    path: "/ai-khaleeji-song-generator",
    pathFr: "/generateur-khaleeji-ia",
    nameEn: "Khaleeji",
    nameFr: "Khaleeji",
    keywordEn: "khaleeji",
    keywordFr: "khaleeji",
    bpm: 98,
    category: "middle-east",
    vocalLangEn: "Arabic Gulf vocals",
    vocalLangFr: "voix arabes du Golfe",
    instrumentsEn: "oud melody, darbuka riq, Gulf romantic melisma",
    instrumentsFr: "mélodie oud, darbuka riq, melisma romantique Golfe",
    promptEn: 'Genre "Khaleeji": "Gulf Arabic pop, oud lead, darbuka pocket, romantic melisma, Dubai radio polish, 98 BPM"',
    promptFr: 'Genre « Khaleeji » : « pop arabe Golfe, lead oud, pocket darbuka, melisma romantique, polish Dubai, 98 BPM »',
    relatedSlugKeys: ["middle-east-music-generator", "ai-arabic-pop-generator", "ai-gulf-trap-generator", "ai-song-generator"],
  }),
  regionalMusicSeoPage({
    slugKey: "ai-arabic-pop-generator",
    path: "/ai-arabic-pop-generator",
    pathFr: "/generateur-arabic-pop-ia",
    nameEn: "Arabic Pop",
    nameFr: "Arabic Pop",
    keywordEn: "Arabic pop",
    keywordFr: "pop arabe",
    bpm: 102,
    category: "middle-east",
    vocalLangEn: "Arabic vocals",
    vocalLangFr: "voix arabes",
    instrumentsEn: "quarter-tone hooks, synth brass, Cairo-Beirut crossover",
    instrumentsFr: "hooks quarter-tone, synth brass, crossover Caire-Beyrouth",
    promptEn: 'Genre "Arabic Pop": "quarter-tone chorus hook, synth brass stabs, Arabic melismatic vocals, 102 BPM"',
    promptFr: 'Genre « Arabic Pop » : « refrain quarter-tone, stabs synth brass, voix melismatiques arabes, 102 BPM »',
    relatedSlugKeys: ["middle-east-music-generator", "ai-khaleeji-song-generator", "ai-mahraganat-generator", "ai-levant-pop-generator"],
  }),
  regionalMusicSeoPage({
    slugKey: "ai-mahraganat-generator",
    path: "/ai-mahraganat-generator",
    pathFr: "/generateur-mahraganat-ia",
    nameEn: "Mahraganat",
    nameFr: "Mahraganat",
    keywordEn: "mahraganat",
    keywordFr: "mahraganat",
    bpm: 128,
    category: "middle-east",
    vocalLangEn: "auto-tuned Arabic vocals",
    vocalLangFr: "voix arabes auto-tune",
    instrumentsEn: "electro-shaabi synth stabs, heavy kick, Cairo street party",
    instrumentsFr: "stabs electro-shaabi, kick lourd, fête rue Caire",
    promptEn: 'Genre "Mahraganat": "Egyptian electro-shaabi, distorted synth lead, auto-tune Arabic chants, 128 BPM"',
    promptFr: 'Genre « Mahraganat » : « electro-shaabi égyptien, synth disto, chants arabes auto-tune, 128 BPM »',
    relatedSlugKeys: ["middle-east-music-generator", "ai-arabic-pop-generator", "ai-shaabi-generator", "ai-song-generator"],
  }),
  regionalMusicSeoPage({
    slugKey: "ai-dabke-music-generator",
    path: "/ai-dabke-music-generator",
    pathFr: "/generateur-dabke-ia",
    nameEn: "Dabke",
    nameFr: "Dabke",
    keywordEn: "dabke",
    keywordFr: "dabke",
    bpm: 120,
    category: "middle-east",
    vocalLangEn: "Arabic group chant vocals",
    vocalLangFr: "chants de groupe arabes",
    instrumentsEn: "mijwiz reed, darbuka stomp-clap, Levant wedding pulse",
    instrumentsFr: "anche mijwiz, stomp-clap darbuka, pulse mariage Levant",
    promptEn: 'Genre "Dabke": "Levantine line-dance groove, mijwiz lead, darbuka stomp-clap, wedding energy, 120 BPM"',
    promptFr: 'Genre « Dabke » : « groove danse en ligne levantine, lead mijwiz, stomp-clap darbuka, énergie mariage, 120 BPM »',
    relatedSlugKeys: ["middle-east-music-generator", "ai-khaleeji-song-generator", "ai-arabic-pop-generator", "ai-song-generator"],
  }),
  regionalMusicSeoPage({
    slugKey: "ai-turkish-pop-generator",
    path: "/ai-turkish-pop-generator",
    pathFr: "/generateur-turkish-pop-ia",
    nameEn: "Turkish Pop",
    nameFr: "Turkish Pop",
    keywordEn: "Turkish pop",
    keywordFr: "pop turque",
    bpm: 108,
    category: "middle-east",
    vocalLangEn: "Turkish vocals",
    vocalLangFr: "voix turques",
    instrumentsEn: "bağlama arpeggios, darbuka drums, Istanbul radio chorus",
    instrumentsFr: "arpèges bağlama, darbuka, refrain radio Istanbul",
    promptEn: 'Genre "Turkish Pop": "Anatolian pop-rock crossover, baglama arpeggios, catchy Turkish chorus, 108 BPM"',
    promptFr: 'Genre « Turkish Pop » : « crossover pop-rock anatolien, arpèges bağlama, refrain turc catchy, 108 BPM »',
    relatedSlugKeys: ["middle-east-music-generator", "ai-persian-pop-generator", "ai-arabic-pop-generator", "asia-music-generator"],
  }),
  regionalMusicSeoPage({
    slugKey: "ai-persian-pop-generator",
    path: "/ai-persian-pop-generator",
    pathFr: "/generateur-persian-pop-ia",
    nameEn: "Persian Pop",
    nameFr: "Persian Pop",
    keywordEn: "Persian pop",
    keywordFr: "pop persane",
    bpm: 92,
    category: "middle-east",
    vocalLangEn: "Farsi vocals",
    vocalLangFr: "voix farsi",
    instrumentsEn: "santur tar pluck, daf groove, Tehran ballad lift",
    instrumentsFr: "pluck santur tar, groove daf, lift ballade Téhéran",
    promptEn: 'Genre "Persian Pop": "Iranian ballad chords, santur accents, emotional Farsi vocals, 92 BPM"',
    promptFr: 'Genre « Persian Pop » : « accords ballade iranienne, accents santur, voix farsi émotionnelles, 92 BPM »',
    relatedSlugKeys: ["middle-east-music-generator", "ai-turkish-pop-generator", "ai-arabic-pop-generator", "ai-song-generator"],
  }),
  regionalMusicSeoPage({
    slugKey: "ai-j-pop-generator",
    path: "/ai-j-pop-generator",
    pathFr: "/generateur-j-pop-ia",
    nameEn: "J-Pop",
    nameFr: "J-Pop",
    keywordEn: "J-pop",
    keywordFr: "J-pop",
    bpm: 128,
    category: "asia",
    vocalLangEn: "Japanese vocals",
    vocalLangFr: "voix japonaises",
    instrumentsEn: "bright Tokyo synth stacks, catchy hooks, anime-opening lift optional",
    instrumentsFr: "stacks synth Tokyo bright, hooks catchy, lift opening anime optionnel",
    promptEn: 'Genre "J-Pop": "bright layered synths, catchy hook melody, Tokyo pop polish, Japanese vocals, 128 BPM"',
    promptFr: 'Genre « J-Pop » : « synths layered bright, mélodie hook catchy, polish pop Tokyo, voix japonaises, 128 BPM »',
    relatedSlugKeys: ["asia-music-generator", "ai-k-pop-song-generator", "ai-anison-generator", "ai-city-pop-generator"],
  }),
  {
    path: "/ai-anison-generator",
    pathFr: "/generateur-anison-ia",
    slugKey: "ai-anison-generator",
    category: "asia",
    prefillGenre: "Anison",
    prefillMode: "song",
    relatedSlugKeys: ["ai-j-pop-generator", "asia-music-generator", "ai-k-pop-song-generator"],
    relatedLimit: 8,
    promptHintEn: 'Genre "Anison": "anime opening energy, heroic chorus lift, fast drums, Japanese vocal belt, 160 BPM"',
    promptHintFr: 'Genre « Anison » : « énergie opening anime, lift refrain héroïque, drums rapides, voix japonaise, 160 BPM »',
    titleEn: "AI Anison Generator — Anime Opening Songs & J-Rock Energy | ProducerHit",
    titleFr: "Générateur Anison IA — Openings anime & énergie J-Rock | ProducerHit",
    descriptionEn: "AI anison generator: anime opening song production, heroic chorus, orchestral hits. Dedicated Anison genre — not generic J-Pop.",
    descriptionFr: "Générateur anison IA : prod opening anime, refrain héroïque, hits orchestraux. Genre Anison dédié — pas J-Pop générique.",
    keywords: ["anison AI generator", "anime opening song AI", "anime music generator AI", "J-anime song maker"],
    h1En: "AI Anison Generator",
    h1Fr: "Générateur Anison IA",
    leadEn: "Dedicated **Anison** genre for anime-opening energy — fast drums, heroic chorus, orchestral accents. Separate from J-Pop in the 680+ catalog.",
    leadFr: "Genre **Anison** dédié pour l'énergie opening anime — drums rapides, refrain héroïque, accents orchestraux. Séparé du J-Pop dans le catalogue 680+.",
    bulletsEn: ["~160 BPM default", "Anime OP / TikTok AMV", "Pairs with J-Pop hub", "Manual Japanese lyrics"],
    bulletsFr: ["~160 BPM par défaut", "OP anime / TikTok AMV", "Hub J-Pop", "Paroles japonaises manuelles"],
    faqEn: [{ q: "Anison vs J-Pop?", a: "Anison = anime opening double-time energy; J-Pop = general Tokyo radio pop." }],
    faqFr: [{ q: "Anison vs J-Pop ?", a: "Anison = énergie opening double-time ; J-Pop = pop radio Tokyo générale." }],
  },
  regionalMusicSeoPage({
    slugKey: "ai-city-pop-generator",
    path: "/ai-city-pop-generator",
    pathFr: "/generateur-city-pop-ia",
    nameEn: "City Pop",
    nameFr: "City Pop",
    keywordEn: "city pop",
    keywordFr: "city pop",
    bpm: 115,
    category: "asia",
    vocalLangEn: "Japanese or English vocals",
    vocalLangFr: "voix japonaises ou anglaises",
    instrumentsEn: "funky bass, synth brass, 80s Tokyo night-drive nostalgia",
    instrumentsFr: "basse funky, synth brass, nostalgie night-drive Tokyo 80s",
    promptEn: 'Genre "City Pop": "80s Japanese city pop revival, funky bass, synth brass, neon night-drive, 115 BPM"',
    promptFr: 'Genre « City Pop » : « revival city pop japonais 80s, basse funky, synth brass, night-drive néon, 115 BPM »',
    relatedSlugKeys: ["asia-music-generator", "ai-j-pop-generator", "ai-k-pop-song-generator", "ai-song-generator"],
  }),
  regionalMusicSeoPage({
    slugKey: "ai-gulf-trap-generator",
    path: "/ai-gulf-trap-generator",
    pathFr: "/generateur-gulf-trap-ia",
    nameEn: "Gulf Trap",
    nameFr: "Gulf Trap",
    keywordEn: "Gulf trap",
    keywordFr: "Gulf trap",
    bpm: 130,
    category: "middle-east",
    prefillMode: "beat",
    vocalLangEn: "Gulf Arabic rap flow",
    vocalLangFr: "flow rap arabe du Golfe",
    instrumentsEn: "808 slides, Arabic scale synth, Dubai night-drive",
    instrumentsFr: "slides 808, synth échelle arabe, night-drive Dubai",
    promptEn: 'Beat mode → Genre "Gulf Trap": "Khaleeji trap crossover, sliding 808, Arabic scale synth lead, 130 BPM"',
    promptFr: 'Beat mode → Genre « Gulf Trap » : « crossover trap khaleeji, 808 slide, lead synth échelle arabe, 130 BPM »',
    relatedSlugKeys: ["middle-east-music-generator", "ai-khaleeji-song-generator", "ai-trap-beat-generator", "ai-song-generator"],
  }),
  regionalMusicSeoPage({
    slugKey: "ai-shaabi-generator",
    path: "/ai-shaabi-generator",
    pathFr: "/generateur-shaabi-ia",
    nameEn: "Shaabi",
    nameFr: "Shaabi",
    keywordEn: "Egyptian shaabi",
    keywordFr: "shaabi égyptien",
    bpm: 115,
    category: "middle-east",
    vocalLangEn: "Arabic call-response vocals",
    vocalLangFr: "voix call-response arabes",
    instrumentsEn: "accordion lead, tabla darbuka, Cairo street party",
    instrumentsFr: "lead accordéon, tabla darbuka, fête rue Caire",
    promptEn: 'Genre "Shaabi": "Egyptian folk-pop, accordion lead, tabla groove, call-response shouts, 115 BPM"',
    promptFr: 'Genre « Shaabi » : « folk-pop égyptien, lead accordéon, groove tabla, shouts call-response, 115 BPM »',
    relatedSlugKeys: ["middle-east-music-generator", "ai-mahraganat-generator", "ai-arabic-pop-generator", "ai-song-generator"],
  }),
  regionalMusicSeoPage({
    slugKey: "ai-levant-pop-generator",
    path: "/ai-levant-pop-generator",
    pathFr: "/generateur-levant-pop-ia",
    nameEn: "Levant Pop",
    nameFr: "Levant Pop",
    keywordEn: "Levant pop",
    keywordFr: "pop levantine",
    bpm: 88,
    category: "middle-east",
    vocalLangEn: "Arabic storytelling vocals",
    vocalLangFr: "voix storytelling arabes",
    instrumentsEn: "piano string pads, soft darbuka, Beirut ballad intimacy",
    instrumentsFr: "pads piano cordes, darbuka soft, intimité ballade Beyrouth",
    promptEn: 'Genre "Levant Pop": "Syrian-Lebanese ballad, piano pads, soft darbuka, emotional Arabic vocals, 88 BPM"',
    promptFr: 'Genre « Levant Pop » : « ballade syro-libanaise, pads piano, darbuka soft, voix arabes émotionnelles, 88 BPM »',
    relatedSlugKeys: ["middle-east-music-generator", "ai-arabic-pop-generator", "ai-dabke-music-generator", "ai-song-generator"],
  }),
];
