import type { SeoPageConfig } from "@/lib/seoPages";
import { latinMusicSeoPage } from "@/lib/seoPageFactory";

const LATIN_RELATED = [
  "latin-music-generator",
  "ai-bachata-song-generator",
  "ai-reggaeton-generator",
  "ai-dembow-beat-generator",
  "ai-salsa-music-generator",
  "ai-kizomba-song-generator",
  "ai-cumbia-generator",
  "ai-corridos-generator",
];

export const LATIN_SEO_PAGES: SeoPageConfig[] = [
  latinMusicSeoPage({
    slugKey: "ai-bachata-song-generator",
    path: "/ai-bachata-song-generator",
    pathFr: "/generateur-bachata-ia",
    nameEn: "Bachata",
    nameFr: "Bachata",
    keywordEn: "bachata",
    keywordFr: "bachata",
    bpm: 130,
    instrumentsEn: "requinto guitar, bongo, güira, romantic Dominican groove",
    instrumentsFr: "guitare requinto, bongo, güira, groove romantique dominicain",
    promptEn:
      'Song Mode → Genre "Bachata": "romantic bachata, nylon guitar arpeggios, bongo tumbao, Spanish love lyrics, 130 BPM"',
    promptFr:
      'Song Mode → Genre « Bachata » : « bachata romantique, arpèges guitare nylon, tumbao bongo, paroles amour espagnoles, 130 BPM »',
    relatedSlugKeys: ["latin-music-generator", "ai-bachata-sensual-generator", "ai-reggaeton-generator", ...LATIN_RELATED.slice(2)],
  }),
  {
    path: "/ai-bachata-sensual-generator",
    pathFr: "/generateur-bachata-sensual-ia",
    slugKey: "ai-bachata-sensual-generator",
    category: "latin",
    prefillGenre: "Bachata Sensual",
    prefillMode: "song",
    relatedSlugKeys: ["ai-bachata-song-generator", "latin-music-generator", "ai-kizomba-song-generator"],
    relatedLimit: 8,
    promptHintEn: 'Genre "Bachata Sensual": "legato electric guitar, sensual slow pulse, partner dance, Spanish vocals, 125 BPM"',
    promptHintFr: 'Genre « Bachata Sensual » : « guitare legato, pulse sensuelle, danse couple, voix espagnoles, 125 BPM »',
    titleEn: "Bachata Sensual AI Generator — Partner Dance Songs | ProducerHit",
    titleFr: "Générateur Bachata Sensual IA — Chansons danse couple | ProducerHit",
    descriptionEn: "Bachata sensual AI generator: legato guitar, body-wave pulse, TikTok dance trend. Song Mode Spanish vocals.",
    descriptionFr: "Générateur bachata sensual IA : guitare legato, pulse body-wave, trend danse TikTok. Song Mode voix espagnoles.",
    keywords: ["bachata sensual AI generator", "bachata sensual song AI", "AI bachata dance music"],
    h1En: "Bachata Sensual AI Generator",
    h1Fr: "Générateur Bachata Sensual IA",
    leadEn: "#BachataSensual trend — generate sensual bachata with legato guitar and close-embrace pulse, not generic Latin pop.",
    leadFr: "Trend #BachataSensual — génère bachata sensual avec guitare legato et pulse close-embrace, pas pop Latin générique.",
    bulletsEn: ["125 BPM sensual pocket", "TikTok dance ready", "Distinct from classic Bachata genre", "Manual Spanish lyrics"],
    bulletsFr: ["Pocket sensuel 125 BPM", "Prêt danse TikTok", "Distinct de Bachata classique", "Paroles espagnoles manuelles"],
    faqEn: [{ q: "Sensual vs classic bachata?", a: "Pick Bachata Sensual genre for legato guitar & slower pulse; Bachata for traditional requinto." }],
    faqFr: [{ q: "Sensual vs bachata classique ?", a: "Choisis Bachata Sensual pour guitare legato ; Bachata pour requinto traditionnel." }],
  },
  latinMusicSeoPage({
    slugKey: "ai-reggaeton-generator",
    path: "/ai-reggaeton-generator",
    pathFr: "/generateur-reggaeton-ia",
    nameEn: "Reggaeton",
    nameFr: "Reggaeton",
    keywordEn: "reggaeton",
    keywordFr: "reggaeton",
    bpm: 92,
    instrumentsEn: "dembow rhythm, 808 sub, perreo club bounce",
    instrumentsFr: "rythme dembow, sub 808, bounce club perreo",
    promptEn:
      'Genre "Reggaeton": "dembow kick pattern, deep 808, syncopated hats, Spanish perreo vocals, dark club 92 BPM"',
    promptFr:
      'Genre « Reggaeton » : « pattern kick dembow, 808 profond, hats syncopés, voix perreo espagnoles, club dark 92 BPM »',
    relatedSlugKeys: ["ai-dembow-beat-generator", "latin-music-generator", "ai-reggaeton-beat-generator", "latin-pop-ai-generator"],
  }),
  {
    path: "/ai-reggaeton-beat-generator",
    pathFr: "/generateur-beat-reggaeton-ia",
    slugKey: "ai-reggaeton-beat-generator",
    category: "latin",
    relatedSlugKeys: ["ai-reggaeton-generator", "ai-dembow-beat-generator", "latin-music-generator", "ai-trap-beat-generator"],
    promptHintEn: 'Beat mode → "Reggaeton" instrumental: "dembow rhythm, 808 bass, no full vocals, perreo instrumental, 95 BPM"',
    promptHintFr: 'Mode Beat → « Reggaeton » instrumental : « rythme dembow, basse 808, sans voix lead, perreo instrumental, 95 BPM »',
    titleEn: "AI Reggaeton Beat Generator — Dembow Instrumentals | ProducerHit",
    titleFr: "Générateur beat reggaeton IA — Instrumentaux dembow | ProducerHit",
    descriptionEn: "AI reggaeton beat generator: dembow riddim, 808 subs, perreo instrumentals. Beat mode — no vocals.",
    descriptionFr: "Générateur beat reggaeton IA : riddim dembow, subs 808, instrumentaux perreo. Mode Beat — sans voix.",
    keywords: ["AI reggaeton beat generator", "reggaeton type beat AI", "dembow beat maker", "perreo instrumental AI"],
    h1En: "AI Reggaeton Beat Generator",
    h1Fr: "Générateur beat reggaeton IA",
    leadEn: "Instrumental **reggaeton beats** for freestyle, content, and lease demos — dembow pocket without generic trap drums.",
    leadFr: "**Beats reggaeton** instrumentaux pour freestyle, contenu et démos — pocket dembow sans drums trap génériques.",
    bulletsEn: ["Beat mode instrumental", "Dembow + 808 focus", "Pairs with reggaeton song page", "Versions×2"],
    bulletsFr: ["Mode Beat instrumental", "Focus dembow + 808", "Lié page chanson reggaeton", "Versions×2"],
    faqEn: [{ q: "Reggaeton beat vs Latin trap?", a: "Reggaeton = dembow riddim; Latin Trap = trap drums + Spanish urban — both in catalog." }],
    faqFr: [{ q: "Beat reggaeton vs Latin trap ?", a: "Reggaeton = riddim dembow ; Latin Trap = drums trap + urbano espagnol." }],
  },
  latinMusicSeoPage({
    slugKey: "ai-dembow-beat-generator",
    path: "/ai-dembow-beat-generator",
    pathFr: "/generateur-dembow-ia",
    nameEn: "Dembow",
    nameFr: "Dembow",
    keywordEn: "dembow",
    keywordFr: "dembow",
    bpm: 103,
    instrumentsEn: "Dominican dembow riddim, 808 slides, perreo energy",
    instrumentsFr: "riddim dembow dominicain, slides 808, énergie perreo",
    promptEn:
      'Genre "Dembow": "Dominican dembow riddim, punchy 808, minimal dark synth, perreo club, Spanish ad-libs, 103 BPM"',
    promptFr:
      'Genre « Dembow » : « riddim dembow dominicain, 808 punchy, synth dark minimal, club perreo, ad-libs espagnols, 103 BPM »',
    relatedSlugKeys: ["ai-reggaeton-generator", "latin-music-generator", "ai-reggaeton-beat-generator"],
  }),
  latinMusicSeoPage({
    slugKey: "ai-salsa-music-generator",
    path: "/ai-salsa-music-generator",
    pathFr: "/generateur-salsa-ia",
    nameEn: "Salsa",
    nameFr: "Salsa",
    keywordEn: "salsa",
    keywordFr: "salsa",
    bpm: 180,
    instrumentsEn: "clave, montuno piano, congas, timbales, brass",
    instrumentsFr: "clave, piano montuno, congas, timbales, cuivres",
    promptEn:
      'Genre "Salsa": "clave-driven salsa, montuno piano, conga tumbao, brass stabs, high energy dance, Spanish coro, 180 BPM"',
    promptFr:
      'Genre « Salsa » : « salsa clave, piano montuno, tumbao congas, stabs cuivres, danse haute énergie, coro espagnol, 180 BPM »',
    relatedSlugKeys: ["latin-music-generator", "ai-bachata-song-generator", "ai-cumbia-generator", "ai-timba-generator"],
  }),
  {
    path: "/ai-timba-generator",
    pathFr: "/generateur-timba-ia",
    slugKey: "ai-timba-generator",
    category: "latin",
    relatedSlugKeys: ["ai-salsa-music-generator", "latin-music-generator", "ai-reggaeton-generator"],
    promptHintEn: 'Genre "Timba": "Cuban timba montuno, aggressive horns, congas at high tempo, Havana dancefloor, 190 BPM"',
    promptHintFr: 'Genre « Timba » : « montuno timba cubain, cuivres agressifs, congas tempo haut, dancefloor Havana, 190 BPM »',
    titleEn: "AI Timba Generator — Cuban Salsa Fusion | ProducerHit",
    titleFr: "Générateur Timba IA — Fusion salsa cubaine | ProducerHit",
    descriptionEn: "AI timba generator: Cuban timba — faster than salsa, horn hits, montuno piano. 190 BPM dance energy.",
    descriptionFr: "Générateur timba IA : timba cubaine — plus rapide que salsa, cuivres, piano montuno. Énergie danse 190 BPM.",
    keywords: ["AI timba generator", "timba music AI", "Cuban timba AI", "salsa cubana AI"],
    h1En: "AI Timba Generator",
    h1Fr: "Générateur Timba IA",
    leadEn: "**Timba** — Cuba's high-energy salsa fusion — dedicated genre with horn stabs and 190 BPM drive.",
    leadFr: "**Timba** — fusion salsa haute énergie de Cuba — genre dédié cuivres et drive 190 BPM.",
    bulletsEn: ["190 BPM timba pocket", "Cuban dancefloor", "Beyond generic salsa", "Song Mode coro space"],
    bulletsFr: ["Pocket timba 190 BPM", "Dancefloor cubain", "Au-delà salsa générique", "Espace coro Song Mode"],
    faqEn: [{ q: "Timba vs salsa?", a: "Timba is faster, more aggressive horns — pick Timba genre vs Salsa for classic clave feel." }],
    faqFr: [{ q: "Timba vs salsa ?", a: "Timba plus rapide, cuivres agressifs — genre Timba vs Salsa pour clave classique." }],
  },
  latinMusicSeoPage({
    slugKey: "ai-kizomba-song-generator",
    path: "/ai-kizomba-song-generator",
    pathFr: "/generateur-kizomba-ia",
    nameEn: "Kizomba",
    nameFr: "Kizomba",
    keywordEn: "kizomba",
    keywordFr: "kizomba",
    bpm: 95,
    instrumentsEn: "slow sensual pulse, romantic chords, Portuguese vocal space",
    instrumentsFr: "pulse sensuelle lente, accords romantiques, voix portugaises",
    promptEn:
      'Genre "Kizomba": "slow kizomba pulse, romantic R&B chords, close-embrace sway, Portuguese love vocals, 95 BPM"',
    promptFr:
      'Genre « Kizomba » : « pulse kizomba lente, accords R&B romantiques, sway close-embrace, voix amour portugaises, 95 BPM »',
    relatedSlugKeys: ["latin-music-generator", "ai-zouk-love-generator", "ai-bachata-sensual-generator"],
  }),
  {
    path: "/ai-zouk-love-generator",
    pathFr: "/generateur-zouk-love-ia",
    slugKey: "ai-zouk-love-generator",
    category: "latin",
    relatedSlugKeys: ["ai-kizomba-song-generator", "latin-music-generator", "ai-bachata-song-generator"],
    promptHintEn: 'Genre "Zouk Love": "French Caribbean bounce, synth brass, romantic seventh chords, 90 BPM, Creole vocal space"',
    promptHintFr: 'Genre « Zouk Love » : « bounce Caraïbes, synth brass, accords septièmes romantiques, 90 BPM, voix créole »',
    titleEn: "AI Zouk Love Generator — Caribbean Romance | ProducerHit",
    titleFr: "Générateur Zouk Love IA — Romance caraïbéenne | ProducerHit",
    descriptionEn: "AI zouk love generator: Martinique-Guadeloupe bounce, romantic synth brass. Pair with kizomba for dance events.",
    descriptionFr: "Générateur zouk love IA : bounce Martinique-Guadeloupe, synth brass romantique. Associe kizomba pour events danse.",
    keywords: ["AI zouk love generator", "zouk music AI", "kizomba zouk generator", "French Caribbean music AI"],
    h1En: "AI Zouk Love Generator",
    h1Fr: "Générateur Zouk Love IA",
    leadEn: "**Zouk Love** + **Kizomba** — two dedicated Lusophone/Caribbean dance genres competitors merge into « slow Latin ».",
    leadFr: "**Zouk Love** + **Kizomba** — deux genres danse dédiés que les concurrents fusionnent en « Latin slow ».",
    bulletsEn: ["90 BPM zouk bounce", "Caribbean synth brass", "Pairs with kizomba hub", "French/Creole vocal space"],
    bulletsFr: ["Bounce zouk 90 BPM", "Synth brass Caraïbes", "Hub kizomba", "Voix français/créole"],
    faqEn: [{ q: "Zouk vs kizomba?", a: "Zouk = French Caribbean bounce; Kizomba = Angolan slow pulse — both separate genres in ProducerHit." }],
    faqFr: [{ q: "Zouk vs kizomba ?", a: "Zouk = bounce Caraïbes ; Kizomba = pulse angolais — deux genres séparés." }],
  },
  latinMusicSeoPage({
    slugKey: "ai-cumbia-generator",
    path: "/ai-cumbia-generator",
    pathFr: "/generateur-cumbia-ia",
    nameEn: "Cumbia",
    nameFr: "Cumbia",
    keywordEn: "cumbia",
    keywordFr: "cumbia",
    bpm: 110,
    instrumentsEn: "guïro, tambora, accordion lead, Colombian shuffle",
    instrumentsFr: "guïro, tambora, accordéon lead, shuffle colombien",
    promptEn:
      'Genre "Cumbia": "cumbia shuffle groove, guiro scrape, tambora accents, accordion hook, festive Spanish vocals, 110 BPM"',
    promptFr:
      'Genre « Cumbia » : « groove shuffle cumbia, scrape guiro, accents tambora, hook accordéon, voix festives espagnoles, 110 BPM »',
    relatedSlugKeys: ["latin-music-generator", "ai-cumbia-sonidera-generator", "ai-reggaeton-generator", "ai-salsa-music-generator"],
  }),
  {
    path: "/ai-cumbia-sonidera-generator",
    pathFr: "/generateur-cumbia-sonidera-ia",
    slugKey: "ai-cumbia-sonidera-generator",
    category: "latin",
    relatedSlugKeys: ["ai-cumbia-generator", "latin-music-generator", "ai-corridos-generator"],
    promptHintEn: 'Genre "Cumbia Sonidera": "Mexican sonidero shuffle, reverb organ stabs, party bass, guiro tambora, 108 BPM"',
    promptHintFr: 'Genre « Cumbia Sonidera » : « shuffle sonidero mexicain, organ reverb, basse party, guiro tambora, 108 BPM »',
    titleEn: "AI Cumbia Sonidera Generator — Mexico City Party Sound | ProducerHit",
    titleFr: "Générateur Cumbia Sonidera IA — Son party Mexico City | ProducerHit",
    descriptionEn: "AI cumbia sonidera generator: sonidero reverb organ, loudspeaker party bass, Mexico-Colombia diaspora sound.",
    descriptionFr: "Générateur cumbia sonidera IA : organ reverb sonidero, basse party, son diaspora Mexico-Colombie.",
    keywords: ["cumbia sonidera AI", "sonidero music generator", "Mexican cumbia AI"],
    h1En: "AI Cumbia Sonidera Generator",
    h1Fr: "Générateur Cumbia Sonidera IA",
    leadEn: "**Cumbia Sonidera** — distinct from Colombian cumbia — for sonidero parties and Mexican diaspora content.",
    leadFr: "**Cumbia Sonidera** — distincte de la cumbia colombienne — pour sonideros et contenu diaspora mexicaine.",
    bulletsEn: ["108 BPM sonidero", "Reverb organ texture", "Separate from Cumbia genre", "Spanish shout hooks"],
    bulletsFr: ["108 BPM sonidero", "Texture organ reverb", "Séparé du genre Cumbia", "Hooks shout espagnols"],
    faqEn: [{ q: "Sonidera vs cumbia?", a: "Use Cumbia Sonidera for Mexican sonidero; Cumbia for Colombian coastal shuffle." }],
    faqFr: [{ q: "Sonidera vs cumbia ?", a: "Cumbia Sonidera pour sonidero mexicain ; Cumbia pour shuffle colombien." }],
  },
  latinMusicSeoPage({
    slugKey: "ai-corridos-generator",
    path: "/ai-corridos-generator",
    pathFr: "/generateur-corridos-ia",
    nameEn: "Corridos",
    nameFr: "Corridos",
    keywordEn: "corridos",
    keywordFr: "corridos",
    bpm: 120,
    instrumentsEn: "nylon guitar narrative, tuba bass, regional Mexican storytelling",
    instrumentsFr: "guitare nylon narrative, basse tuba, storytelling regional Mexican",
    promptEn:
      'Genre "Corridos": "corrido nylon guitar loop, tuba bass octaves, narrative Spanish lyrics, norteño snare, 120 BPM"',
    promptFr:
      'Genre « Corridos » : « boucle guitare nylon corrido, octaves tuba, paroles narrative espagnoles, caisse norteño, 120 BPM »',
    relatedSlugKeys: ["ai-corridos-tumbados-generator", "latin-music-generator", "ai-regional-mexican-generator"],
  }),
  {
    path: "/ai-corridos-tumbados-generator",
    pathFr: "/generateur-corridos-tumbados-ia",
    slugKey: "ai-corridos-tumbados-generator",
    category: "latin",
    relatedSlugKeys: ["ai-corridos-generator", "latin-music-generator", "ai-reggaeton-generator"],
    promptHintEn: 'Genre "Corridos Tumbados": "nylon guitar + trap hat rolls, tuba 808 bounce, melancholic autotune, 88 BPM"',
    promptHintFr: 'Genre « Corridos Tumbados » : « guitare nylon + rolls hats trap, bounce tuba 808, autotune mélancolique, 88 BPM »',
    titleEn: "AI Corridos Tumbados Generator — Peso Pluma Style Fusion | ProducerHit",
    titleFr: "Générateur Corridos Tumbados IA — Fusion style Peso Pluma | ProducerHit",
    descriptionEn: "AI corridos tumbados generator: regional Mexican meets trap. Fastest-growing Latin subgenre. 88 BPM tumbado bounce.",
    descriptionFr: "Générateur corridos tumbados IA : regional Mexican meets trap. Sous-genre Latin fastest-growing. Bounce tumbado 88 BPM.",
    keywords: ["corridos tumbados AI", "AI corridos generator", "regional Mexican trap AI", "tumbados music maker"],
    h1En: "AI Corridos Tumbados Generator",
    h1Fr: "Générateur Corridos Tumbados IA",
    leadEn: "Separate **Corridos** (classic) and **Corridos Tumbados** (trap fusion) — two genres, two SEO intents, two sounds.",
    leadFr: "Sépare **Corridos** (classique) et **Corridos Tumbados** (fusion trap) — deux genres, deux intents SEO, deux sons.",
    bulletsEn: ["88 BPM tumbado", "Trap hats + tuba", "Fastest-growing Latin niche", "Spanish narrative vocals"],
    bulletsFr: ["88 BPM tumbado", "Hats trap + tuba", "Niche Latin fastest-growing", "Voix narrative espagnoles"],
    faqEn: [{ q: "Tumbados vs corridos?", a: "Corridos = classic norteño narrative; Corridos Tumbados adds trap drums and 808 bounce." }],
    faqFr: [{ q: "Tumbados vs corridos ?", a: "Corridos = narrative norteño classique ; Tumbados ajoute drums trap et bounce 808." }],
  },
  {
    path: "/ai-regional-mexican-generator",
    pathFr: "/generateur-regional-mexican-ia",
    slugKey: "ai-regional-mexican-generator",
    category: "latin",
    relatedSlugKeys: ["ai-corridos-generator", "ai-corridos-tumbados-generator", "latin-music-generator"],
    promptHintEn: 'Genre "Regional Mexican": "bajo sexto arpeggios, tuba bass, accordion hooks, banda pocket, Spanish storytelling"',
    promptHintFr: 'Genre « Regional Mexican » : « arpèges bajo sexto, basse tuba, hooks accordéon, pocket banda, storytelling espagnol »',
    titleEn: "AI Regional Mexican Generator — Banda & Norteño | ProducerHit",
    titleFr: "Générateur Regional Mexican IA — Banda & norteño | ProducerHit",
    descriptionEn: "AI regional Mexican generator: +30% streaming growth. Bajo sexto, tuba, accordion. Corridos & banda adjacent.",
    descriptionFr: "Générateur regional Mexican IA : croissance streaming +30%. Bajo sexto, tuba, accordéon. Adjacent corridos & banda.",
    keywords: ["regional Mexican AI generator", "banda music AI", "norteño AI generator", "Mexican music AI"],
    h1En: "AI Regional Mexican Generator",
    h1Fr: "Générateur Regional Mexican IA",
    leadEn: "Capture **regional Mexican** search intent — broader than corridos alone — with bajo sexto, tuba, and banda energy.",
    leadFr: "Capture l'intent **regional Mexican** — plus large que corridos seul — avec bajo sexto, tuba et énergie banda.",
    bulletsEn: ["+30% regional Mexican growth", "Links to corridos pages", "Banda genre also in catalog", "Spanish storytelling"],
    bulletsFr: ["Croissance regional Mexican +30%", "Liens pages corridos", "Genre Banda au catalogue", "Storytelling espagnol"],
    faqEn: [{ q: "Regional Mexican vs mariachi?", a: "Regional Mexican = norteño/banda; Mariachi = trumpet ensemble — both available." }],
    faqFr: [{ q: "Regional Mexican vs mariachi ?", a: "Regional Mexican = norteño/banda ; Mariachi = ensemble trompettes — les deux disponibles." }],
  },
  latinMusicSeoPage({
    slugKey: "latin-pop-ai-generator",
    path: "/latin-pop-ai-generator",
    pathFr: "/generateur-latin-pop-ia",
    nameEn: "Latin Pop",
    nameFr: "Latin Pop",
    keywordEn: "Latin pop",
    keywordFr: "Latin pop",
    bpm: 105,
    instrumentsEn: "bilingual chorus, urbano crossover hooks, glossy pop production",
    instrumentsFr: "refrain bilingue, hooks crossover urbano, production pop glossy",
    promptEn:
      'Genre "Latin Pop": "bilingual catchy chorus, urbano pop crossover, bright synth hooks, Spanish-English vocals, 105 BPM"',
    promptFr:
      'Genre « Latin Pop » : « refrain catchy bilingue, crossover urbano pop, hooks synth bright, voix espagnol-anglais, 105 BPM »',
    relatedSlugKeys: ["latin-music-generator", "ai-reggaeton-generator", "ai-pop-beat-generator", "ai-song-generator"],
  }),
];
