import type { SeoPageConfig } from "@/lib/seoPages";

type IntentOpts = {
  slugKey: string;
  path: string;
  pathFr: string;
  keywordEn: string;
  keywordFr: string;
  intentEn: string;
  intentFr: string;
  moodEn: string;
  moodFr: string;
  relatedSlugKeys: string[];
};

function intentMusicPage(o: IntentOpts): SeoPageConfig {
  return {
    path: o.path,
    pathFr: o.pathFr,
    slugKey: o.slugKey,
    category: "intent",
    relatedSlugKeys: o.relatedSlugKeys,
    promptHintEn: `Example prompt: "${o.moodEn}, instrumental, no vocals, soft dynamics, seamless loop-friendly, 60–90 BPM"`,
    promptHintFr: `Exemple de prompt : « ${o.moodFr}, instrumental, sans voix, dynamique douce, boucle fluide, 60–90 BPM »`,
    titleEn: `${o.intentEn} AI Generator — Create ${o.keywordEn} Online | ProducerHit`,
    titleFr: `Générateur ${o.intentFr} IA — ${o.keywordFr} en ligne | ProducerHit`,
    descriptionEn: `Generate ${o.keywordEn} with AI. Calm, royalty-free backgrounds for ${o.intentEn.toLowerCase()}. Free to start — MP3 export.`,
    descriptionFr: `Génère de la ${o.keywordFr} avec l'IA. Fonds calmes, royalty-free pour ${o.intentFr.toLowerCase()}. Gratuit pour commencer — export MP3.`,
    keywords: [
      `${o.keywordEn} AI generator`,
      `AI ${o.keywordEn}`,
      `generate ${o.keywordEn} online`,
      `free ${o.keywordEn} AI`,
    ],
    h1En: `${o.intentEn} AI Music Generator`,
    h1Fr: `Générateur musique ${o.intentFr} IA`,
    leadEn: `ProducerHit turns text into ${o.keywordEn} for ${o.intentEn.toLowerCase()}. Describe the mood (warm pads, soft piano, rain texture), generate two versions, and export MP3 for YouTube, podcasts, or apps.`,
    leadFr: `ProducerHit transforme du texte en ${o.keywordFr} pour ${o.intentFr.toLowerCase()}. Décris l'ambiance (pads chauds, piano doux, texture pluie), génère deux versions, exporte en MP3 pour YouTube, podcasts ou apps.`,
    bulletsEn: [
      `Built for ${o.intentEn.toLowerCase()} & background listening`,
      "Instrumental-first Song Mode workflow",
      "Versions ×2 to pick the best take",
      "Community inspiration & fast iteration",
    ],
    bulletsFr: [
      `Pensé pour ${o.intentFr.toLowerCase()} & écoute en fond`,
      "Workflow Song Mode instrumental",
      "Versions ×2 pour choisir le meilleur take",
      "Inspiration communauté & itération rapide",
    ],
    faqEn: [
      {
        q: `Can I make long ${o.keywordEn} tracks?`,
        a: "Start with shorter generations, then chain variations with the same seed mood until you lock a seamless vibe.",
      },
      {
        q: "Is it free?",
        a: "Yes — the free plan includes monthly generations and MP3 download. Upgrade for more credits and WAV export.",
      },
    ],
    faqFr: [
      {
        q: `Je peux faire de longs morceaux ${o.keywordFr} ?`,
        a: "Commence par des générations courtes, puis enchaîne des variations avec la même ambiance jusqu'à une vibe fluide.",
      },
      {
        q: "C'est gratuit ?",
        a: "Oui — le plan gratuit inclut des générations mensuelles et le téléchargement MP3. Upgrade pour plus de crédits et le WAV.",
      },
    ],
  };
}

/** Pages ciblant les requêtes « music ai generator » et intentions d'écoute (volume SEO élevé). */
export const MUSIC_AI_PAGES: SeoPageConfig[] = [
  {
    path: "/music-ai-generator",
    pathFr: "/generateur-music-ai",
    slugKey: "music-ai-generator",
    category: "music-ai",
    relatedSlugKeys: ["free-music-ai-generator", "text-to-music-ai-generator", "ai-music-generator", "ai-sleep-music-generator"],
    titleEn: "Music AI Generator — Create Songs & Beats Online | ProducerHit",
    titleFr: "Music AI Generator — Musique IA en ligne | ProducerHit",
    descriptionEn: "Music AI generator for beats and full songs. Text-to-music workflow, free tier, MP3/WAV export. Built for producers and creators.",
    descriptionFr: "Music AI generator pour beats et chansons. Texte vers musique, offre gratuite, export MP3/WAV. Pensé producteurs et créateurs.",
    keywords: ["music ai generator", "music AI generator free", "AI music maker", "generate music with AI"],
    h1En: "Music AI Generator",
    h1Fr: "Music AI Generator",
    leadEn: "ProducerHit is a music AI generator built for real output: type beats, songs with vocals, and ambient beds from one prompt. Generate two versions, autoplay results, export when ready.",
    leadFr: "ProducerHit est un music AI generator orienté résultat : type beats, chansons avec voix et ambiances depuis un prompt. Deux versions, lecture auto, export quand c'est prêt.",
    bulletsEn: ["Exact keyword: music ai generator", "Beats + Song Mode", "Free plan to start", "Producer workflow (seed, variations)"],
    bulletsFr: ["Mot-clé cible : music ai generator", "Beats + Song Mode", "Plan gratuit pour démarrer", "Workflow producteur (seed, variations)"],
    faqEn: [{ q: "Music AI generator vs Suno?", a: "ProducerHit focuses on producer workflows: type beats, stems mindset, variations, and fast iteration—not only full songs." }],
    faqFr: [{ q: "Music AI generator vs Suno ?", a: "ProducerHit vise le workflow producteur : type beats, variations, itération rapide — pas seulement des chansons complètes." }],
  },
  {
    path: "/free-music-ai-generator",
    pathFr: "/generateur-musique-ia-gratuit",
    slugKey: "free-music-ai-generator",
    category: "music-ai",
    relatedSlugKeys: ["music-ai-generator", "generate-beats-online-free", "text-to-music-ai-generator"],
    titleEn: "Free Music AI Generator — Start Creating Online | ProducerHit",
    titleFr: "Générateur musique IA gratuit — Commencer en ligne | ProducerHit",
    descriptionEn: "Free music AI generator: create beats and songs online. Monthly free credits, MP3 download, upgrade for WAV and more generations.",
    descriptionFr: "Générateur musique IA gratuit : crée beats et chansons en ligne. Crédits mensuels, MP3 gratuit, upgrade pour WAV et plus de générations.",
    keywords: ["free music ai generator", "music ai generator free", "free AI music maker"],
    h1En: "Free Music AI Generator",
    h1Fr: "Générateur musique IA gratuit",
    leadEn: "Use ProducerHit as a free music AI generator. Test prompts, generate two takes, download MP3 on the free plan, then upgrade when you need WAV or higher volume.",
    leadFr: "Utilise ProducerHit comme générateur musique IA gratuit. Teste des prompts, génère deux versions, télécharge en MP3 sur le plan free, puis upgrade pour le WAV ou plus de volume.",
    bulletsEn: ["Free monthly generations", "MP3 export on Free", "No credit card to start", "Same studio as paid plans"],
    bulletsFr: ["Générations mensuelles gratuites", "Export MP3 sur Free", "Sans carte bancaire pour démarrer", "Même studio que les plans payants"],
    faqEn: [{ q: "Is music ai generator free forever?", a: "The free tier stays available with monthly limits. Paid plans add credits, priority, and WAV." }],
    faqFr: [{ q: "Le générateur musique IA reste gratuit ?", a: "Le plan free reste disponible avec des limites mensuelles. Les plans payants ajoutent crédits, priorité et WAV." }],
  },
  {
    path: "/text-to-music-ai-generator",
    pathFr: "/texte-en-musique-ia",
    slugKey: "text-to-music-ai-generator",
    category: "music-ai",
    relatedSlugKeys: ["music-ai-generator", "ai-music-generator", "ai-sleep-music-generator"],
    promptHintEn: 'Describe genre, mood, BPM, and instruments — e.g. "ambient study music, soft piano, 72 BPM, no vocals"',
    promptHintFr: 'Décris genre, mood, BPM et instruments — ex. « ambient study, piano doux, 72 BPM, sans voix »',
    titleEn: "Text to Music AI Generator — Prompt to Track | ProducerHit",
    titleFr: "Texte en musique IA — Prompt vers morceau | ProducerHit",
    descriptionEn: "Text to music AI generator: turn descriptions into beats or songs. Best for producers, content creators, and background music.",
    descriptionFr: "Texte en musique IA : transforme une description en beat ou chanson. Idéal producteurs, créateurs et musique de fond.",
    keywords: ["text to music ai generator", "text to music AI", "prompt to music generator"],
    h1En: "Text to Music AI Generator",
    h1Fr: "Générateur texte vers musique IA",
    leadEn: "The fastest text to music AI generator workflow: write mood + genre + tempo, generate, compare two versions, iterate with seed variations.",
    leadFr: "Workflow texte vers musique IA : écris mood + genre + tempo, génère, compare deux versions, itère avec les variations seed.",
    bulletsEn: ["Natural-language prompts", "Beats or full songs", "Reproducible seeds", "Export-ready audio"],
    bulletsFr: ["Prompts en langage naturel", "Beats ou chansons complètes", "Seeds reproductibles", "Audio prêt export"],
    faqEn: [{ q: "Do I need lyrics?", a: "No for instrumentals. Switch to Song Mode when you want vocals and structure." }],
    faqFr: [{ q: "Il faut des paroles ?", a: "Non pour l'instrumental. Passe en Song Mode pour voix et structure." }],
  },
  {
    path: "/best-music-ai-generator",
    pathFr: "/meilleur-generateur-musique-ai",
    slugKey: "best-music-ai-generator",
    category: "music-ai",
    relatedSlugKeys: ["music-ai-generator", "free-music-ai-generator", "ai-music-generator", "ai-beat-generator"],
    titleEn: "Best Music AI Generator for Producers (2026) | ProducerHit",
    titleFr: "Meilleur générateur musique IA pour producteurs (2026) | ProducerHit",
    descriptionEn: "Looking for the best music AI generator? Compare workflow speed, beat quality, variations, and export options with ProducerHit.",
    descriptionFr: "Tu cherches le meilleur générateur musique IA ? Compare vitesse, qualité des beats, variations et exports avec ProducerHit.",
    keywords: ["best music ai generator", "best free music ai generator", "best AI music generator for producers"],
    h1En: "Best Music AI Generator",
    h1Fr: "Meilleur générateur musique IA",
    leadEn: "The best music AI generator for producers prioritizes iteration: Versions×2, seed locking, type beats, and WAV export—not just one-shot songs.",
    leadFr: "Le meilleur générateur musique IA pour producteurs priorise l'itération : Versions×2, seed, type beats et export WAV — pas seulement un one-shot.",
    bulletsEn: ["Built for beatmakers", "Comparison pages vs Suno/Udio", "Community + remix", "Transparent pricing"],
    bulletsFr: ["Pensé beatmakers", "Pages comparatif vs Suno/Udio", "Communauté + remix", "Tarifs transparents"],
    faqEn: [{ q: "Best for beats or songs?", a: "Both — Beat mode for type beats, Song Mode for vocals and hooks." }],
    faqFr: [{ q: "Mieux pour beats ou chansons ?", a: "Les deux — mode Beat pour type beats, Song Mode pour voix et hooks." }],
  },
];

export const INTENT_MUSIC_PAGES: SeoPageConfig[] = [
  intentMusicPage({
    slugKey: "ai-sleep-music-generator",
    path: "/ai-sleep-music-generator",
    pathFr: "/musique-sommeil-ia",
    keywordEn: "sleep music",
    keywordFr: "musique sommeil",
    intentEn: "Sleep",
    intentFr: "sommeil",
    moodEn: "deep sleep ambient, very slow, warm pads, no drums",
    moodFr: "ambient sommeil profond, très lent, pads chauds, sans batterie",
    relatedSlugKeys: ["ai-deep-sleep-music-generator", "ai-relaxing-music-generator", "ai-meditation-music-generator", "music-ai-generator"],
  }),
  intentMusicPage({
    slugKey: "ai-deep-sleep-music-generator",
    path: "/ai-deep-sleep-music-generator",
    pathFr: "/musique-sommeil-profond-ia",
    keywordEn: "deep sleep music",
    keywordFr: "musique sommeil profond",
    intentEn: "Deep Sleep",
    intentFr: "sommeil profond",
    moodEn: "delta-wave friendly ambient, minimal movement, brown noise layer",
    moodFr: "ambient sommeil profond, mouvement minimal, texture bruit doux",
    relatedSlugKeys: ["ai-sleep-music-generator", "ai-relaxing-music-generator", "free-music-ai-generator"],
  }),
  intentMusicPage({
    slugKey: "ai-meditation-music-generator",
    path: "/ai-meditation-music-generator",
    pathFr: "/musique-meditation-ia",
    keywordEn: "meditation music",
    keywordFr: "musique méditation",
    intentEn: "Meditation",
    intentFr: "méditation",
    moodEn: "meditation ambient, singing bowls, slow pads, peaceful",
    moodFr: "ambient méditation, bols tibétains, pads lents, paisible",
    relatedSlugKeys: ["ai-yoga-music-generator", "ai-relaxing-music-generator", "ai-sleep-music-generator"],
  }),
  intentMusicPage({
    slugKey: "ai-study-music-generator",
    path: "/ai-study-music-generator",
    pathFr: "/musique-etude-ia",
    keywordEn: "study music",
    keywordFr: "musique étude",
    intentEn: "Study",
    intentFr: "étude",
    moodEn: "study lofi, soft piano, light vinyl texture, no vocals, 70-80 BPM",
    moodFr: "lofi étude, piano doux, texture vinyle légère, sans voix, 70-80 BPM",
    relatedSlugKeys: ["ai-focus-music-generator", "ai-lofi-music-generator", "ai-lofi-beat-generator"],
  }),
  intentMusicPage({
    slugKey: "ai-focus-music-generator",
    path: "/ai-focus-music-generator",
    pathFr: "/musique-concentration-ia",
    keywordEn: "focus music",
    keywordFr: "musique concentration",
    intentEn: "Focus",
    intentFr: "concentration",
    moodEn: "focus ambient, steady pulse, minimal melody, clean mix, 75 BPM",
    moodFr: "ambient concentration, pulse stable, mélodie minimale, mix clean, 75 BPM",
    relatedSlugKeys: ["ai-study-music-generator", "ai-lofi-music-generator", "text-to-music-ai-generator"],
  }),
  intentMusicPage({
    slugKey: "ai-relaxing-music-generator",
    path: "/ai-relaxing-music-generator",
    pathFr: "/musique-relaxation-ia",
    keywordEn: "relaxing music",
    keywordFr: "musique relaxation",
    intentEn: "Relaxing",
    intentFr: "relaxation",
    moodEn: "relaxing ambient, acoustic guitar, soft strings, calm river mood",
    moodFr: "ambient relaxation, guitare acoustique, cordes douces, ambiance calme",
    relatedSlugKeys: ["ai-meditation-music-generator", "ai-sleep-music-generator", "ai-ambient-music-generator"],
  }),
  intentMusicPage({
    slugKey: "ai-lofi-music-generator",
    path: "/ai-lofi-music-generator",
    pathFr: "/musique-lofi-ia",
    keywordEn: "lo-fi music",
    keywordFr: "musique lofi",
    intentEn: "Lo-Fi",
    intentFr: "lofi",
    moodEn: "lofi hip hop, dusty drums, warm rhodes, chill swing, 82 BPM",
    moodFr: "lofi hip hop, drums dusty, rhodes chaud, swing chill, 82 BPM",
    relatedSlugKeys: ["ai-lofi-beat-generator", "ai-study-music-generator", "ai-chill-music-generator"],
  }),
  intentMusicPage({
    slugKey: "ai-ambient-music-generator",
    path: "/ai-ambient-music-generator",
    pathFr: "/musique-ambient-ia",
    keywordEn: "ambient music",
    keywordFr: "musique ambient",
    intentEn: "Ambient",
    intentFr: "ambient",
    moodEn: "ambient soundscape, evolving pads, subtle textures, cinematic",
    moodFr: "soundscape ambient, pads évolutifs, textures subtiles, cinématique",
    relatedSlugKeys: ["ai-relaxing-music-generator", "ai-meditation-music-generator", "text-to-music-ai-generator"],
  }),
  intentMusicPage({
    slugKey: "ai-yoga-music-generator",
    path: "/ai-yoga-music-generator",
    pathFr: "/musique-yoga-ia",
    keywordEn: "yoga music",
    keywordFr: "musique yoga",
    intentEn: "Yoga",
    intentFr: "yoga",
    moodEn: "yoga flow music, flute and pads, gentle tempo, spa atmosphere",
    moodFr: "musique yoga, flûte et pads, tempo doux, ambiance spa",
    relatedSlugKeys: ["ai-meditation-music-generator", "ai-relaxing-music-generator", "ai-ambient-music-generator"],
  }),
  intentMusicPage({
    slugKey: "ai-chill-music-generator",
    path: "/ai-chill-music-generator",
    pathFr: "/musique-chill-ia",
    keywordEn: "chill music",
    keywordFr: "musique chill",
    intentEn: "Chill",
    intentFr: "chill",
    moodEn: "chill electronic, soft synths, laid-back groove, sunset vibe",
    moodFr: "électro chill, synthés doux, groove relax, vibe sunset",
    relatedSlugKeys: ["ai-lofi-music-generator", "ai-relaxing-music-generator", "ai-rnb-beat-generator"],
  }),
];

export const EXTRA_BEAT_PAGES: SeoPageConfig[] = [
  {
    path: "/ai-lofi-beat-generator",
    pathFr: "/generateur-lofi-ia",
    slugKey: "ai-lofi-beat-generator",
    category: "beat",
    relatedSlugKeys: ["ai-lofi-music-generator", "ai-study-music-generator", "ai-beat-generator"],
    titleEn: "AI Lo-Fi Beat Generator — Chill Hip Hop Online | ProducerHit",
    titleFr: "Générateur beat lofi IA — Chill hip hop en ligne | ProducerHit",
    descriptionEn: "AI lo-fi beat generator: dusty drums, warm chords, study & chill vibes. Generate online free.",
    descriptionFr: "Générateur beat lofi IA : drums dusty, accords chauds, vibes étude & chill. Génère en ligne gratuitement.",
    keywords: ["AI lofi beat generator", "lofi type beat AI", "chill beat maker"],
    h1En: "AI Lo-Fi Beat Generator",
    h1Fr: "Générateur beat lofi IA",
    leadEn: "Create lo-fi beats with AI — swing hats, vinyl texture, mellow keys. Perfect for study streams and chill content.",
    leadFr: "Crée des beats lofi avec l'IA — hats swing, texture vinyle, keys mellow. Parfait streams étude et contenu chill.",
    bulletsEn: ["Study & chill presets via prompt", "Versions ×2", "Seed variations", "MP3 free · WAV Pro"],
    bulletsFr: ["Presets étude & chill via prompt", "Versions ×2", "Variations seed", "MP3 gratuit · WAV Pro"],
    faqEn: [{ q: "Lo-fi beat or lo-fi song?", a: "Start in Beat mode for instrumentals; use Song Mode if you want vocals on top." }],
    faqFr: [{ q: "Beat lofi ou chanson lofi ?", a: "Commence en mode Beat pour l'instrumental ; Song Mode si tu veux des voix." }],
  },
  {
    path: "/ai-phonk-beat-generator",
    pathFr: "/generateur-phonk-ia",
    slugKey: "ai-phonk-beat-generator",
    category: "beat",
    relatedSlugKeys: ["ai-trap-beat-generator", "ai-drill-beat-generator", "ai-beat-generator"],
    titleEn: "AI Phonk Beat Generator — Drift & Memphis Online | ProducerHit",
    titleFr: "Générateur beat phonk IA — Drift & Memphis en ligne | ProducerHit",
    descriptionEn: "AI phonk beat generator: distorted 808s, cowbells, dark Memphis energy. Generate phonk type beats fast.",
    descriptionFr: "Générateur beat phonk IA : 808 disto, cowbells, énergie Memphis dark. Génère des type beats phonk vite.",
    keywords: ["AI phonk beat generator", "phonk type beat AI", "drift phonk beats"],
    h1En: "AI Phonk Beat Generator",
    h1Fr: "Générateur beat phonk IA",
    leadEn: "Generate phonk and drift beats with AI. Describe distorted bass, aggressive hats, and dark samples — iterate with seed variations.",
    leadFr: "Génère des beats phonk et drift avec l'IA. Décris bass disto, hats agressifs et samples dark — itère avec les seeds.",
    bulletsEn: ["Phonk & drift-ready prompts", "140+ BPM friendly", "Dark trap crossover", "Fast type beat workflow"],
    bulletsFr: ["Prompts phonk & drift", "Compatible 140+ BPM", "Crossover trap dark", "Workflow type beat rapide"],
    faqEn: [{ q: "How to get harder phonk 808?", a: "Mention distorted 808, cowbell melody, and minimal melody in your prompt." }],
    faqFr: [{ q: "Comment avoir un 808 phonk plus hard ?", a: "Mentionne 808 disto, mélodie cowbell et mélodie minimale dans ton prompt." }],
  },
];
