import type { SeoPageConfig } from "@/lib/seoPages";
import { countryMusicSeoPage } from "@/lib/seoPageFactory";

const LATIN_HUB_RELATED = [
  "latin-music-generator",
  "ai-bachata-song-generator",
  "ai-reggaeton-generator",
  "ai-dembow-beat-generator",
  "ai-salsa-music-generator",
  "ai-kizomba-song-generator",
  "ai-cumbia-generator",
  "ai-corridos-generator",
  "latin-pop-ai-generator",
  "ai-reggaeton-beat-generator",
];

/** Pages pilier SEO 2026 — volume élevé (AI song, free, country, hubs). */
export const PILLAR_SEO_PAGES: SeoPageConfig[] = [
  {
    path: "/ai-song-generator",
    pathFr: "/generateur-chanson-ia",
    slugKey: "ai-song-generator",
    category: "song",
    relatedSlugKeys: [
      "free-ai-song-generator",
      "ai-song-generator-with-lyrics",
      "ai-music-generator",
      "ai-generated-country-song",
      "latin-music-generator",
      "ai-song-generator-by-genre",
    ],
    relatedLimit: 10,
    promptHintEn:
      'Song Mode → Genre précis → "Melodic Trap" or "Pop": "emotional chorus, modern 2026 mix, English vocals, 140 BPM"',
    promptHintFr:
      'Song Mode → Genre précis → « Melodic Trap » ou « Pop » : « refrain émotionnel, mix 2026, voix anglaises, 140 BPM »',
    titleEn: "AI Song Generator — Create Songs With Vocals Online (2026) | ProducerHit",
    titleFr: "Générateur de chanson IA — Chansons avec voix en ligne (2026) | ProducerHit",
    descriptionEn:
      "AI song generator with real vocals, your lyrics or AI lyrics, 640+ genres. Free to start. Better iteration than Suno for producers — Versions×2, seed lock, MP3/WAV export.",
    descriptionFr:
      "Générateur de chanson IA avec vraies voix, tes paroles ou paroles IA, 640+ genres. Gratuit pour commencer. Meilleure itération que Suno — Versions×2, seed, export MP3/WAV.",
    keywords: [
      "AI song generator",
      "AI song generator free",
      "AI music generator with vocals",
      "generate song with AI",
      "text to song AI",
      "AI song maker online",
    ],
    h1En: "AI Song Generator",
    h1Fr: "Générateur de chanson IA",
    leadEn:
      "ProducerHit is an **AI song generator** built for 2026: full songs with lead vocals, manual or AI lyrics, **640+ genres** (trap, pop, Latin, country, worship), and producer-grade iteration — not one-shot demos.",
    leadFr:
      "ProducerHit est un **générateur de chanson IA** pensé pour 2026 : chansons complètes avec voix lead, paroles manuelles ou IA, **640+ genres** (trap, pop, Latin, country, louange), itération niveau producteur.",
    bulletsEn: [
      "Song Mode — vocals + structure",
      "Manual lyrics (ES/EN/FR/PT) or AI lyrics",
      "Genre précis — 640+ styles",
      "Versions×2 · seed variations · MP3 free",
    ],
    bulletsFr: [
      "Song Mode — voix + structure",
      "Paroles manuelles (ES/EN/FR/PT) ou IA",
      "Genre précis — 640+ styles",
      "Versions×2 · variations seed · MP3 gratuit",
    ],
    faqEn: [
      { q: "AI song generator vs Suno?", a: "ProducerHit adds genre catalog depth, seed iteration, beat+song in one studio, and community remix — ideal when you refine more than one prompt." },
      { q: "Can I use my own lyrics?", a: "Yes — Song Mode → manual lyrics. Pick Genre précis so the instrumental matches your style." },
      { q: "Is the AI song generator free?", a: "Free plan includes monthly generations and MP3 download. Pro adds WAV and more credits." },
    ],
    faqFr: [
      { q: "Générateur chanson IA vs Suno ?", a: "ProducerHit ajoute profondeur de genres, iteration seed, beat+chanson, remix communauté — idéal si tu affines plusieurs prompts." },
      { q: "Mes propres paroles ?", a: "Oui — Song Mode → paroles manuelles + Genre précis pour le style instrumental." },
      { q: "C'est gratuit ?", a: "Le plan free inclut des générations mensuelles et MP3. Pro ajoute WAV et plus de crédits." },
    ],
  },
  {
    path: "/free-ai-song-generator",
    pathFr: "/generateur-chanson-ia-gratuit",
    slugKey: "free-ai-song-generator",
    category: "song",
    relatedSlugKeys: ["ai-song-generator", "free-music-ai-generator", "generate-beats-online-free", "ai-generated-country-song"],
    relatedLimit: 8,
    titleEn: "Free AI Song Generator — Start Creating Songs Online | ProducerHit",
    titleFr: "Générateur de chanson IA gratuit — Commencer en ligne | ProducerHit",
    descriptionEn:
      "Free AI song generator: create songs with vocals online. Monthly free credits, MP3 download, no credit card. Upgrade for WAV and volume.",
    descriptionFr:
      "Générateur chanson IA gratuit : crée des chansons avec voix en ligne. Crédits mensuels, MP3, sans carte. Upgrade pour WAV et volume.",
    keywords: ["free AI song generator", "AI song generator free", "free song maker AI", "generate songs online free"],
    h1En: "Free AI Song Generator",
    h1Fr: "Générateur de chanson IA gratuit",
    leadEn:
      "Use ProducerHit as a **free AI song generator**: test Song Mode, generate two takes, download MP3 on the free tier, then scale when you need WAV or higher volume.",
    leadFr:
      "Utilise ProducerHit comme **générateur chanson IA gratuit** : teste Song Mode, génère deux versions, télécharge MP3 sur le free, upgrade pour WAV ou plus de volume.",
    bulletsEn: ["No credit card to start", "Free monthly generations", "MP3 export on Free", "Same studio as paid plans"],
    bulletsFr: ["Sans carte bancaire", "Générations mensuelles gratuites", "Export MP3 sur Free", "Même studio que les plans payants"],
    faqEn: [
      { q: "Free AI song generator forever?", a: "The free tier stays available with monthly limits. Paid plans add credits, WAV, and priority." },
      { q: "Free vs paid quality?", a: "Same AI engine — paid plans mainly add credits, WAV export, and higher daily volume." },
    ],
    faqFr: [
      { q: "Gratuit pour toujours ?", a: "Le plan free reste avec limites mensuelles. Les plans payants ajoutent crédits, WAV et volume." },
      { q: "Qualité free vs payant ?", a: "Même moteur IA — le payant ajoute surtout crédits, WAV et volume." },
    ],
  },
  {
    path: "/ai-song-generator-with-lyrics",
    pathFr: "/generateur-chanson-paroles-ia",
    slugKey: "ai-song-generator-with-lyrics",
    category: "song",
    relatedSlugKeys: ["ai-song-generator", "free-ai-song-generator", "latin-music-generator", "ai-generated-country-song"],
    promptHintEn: 'Song Mode → Manual lyrics → paste your verse/chorus → Genre précis "Trap Soul" or "Bachata"',
    promptHintFr: 'Song Mode → Paroles manuelles → colle ton couplet/refrain → Genre précis « Trap Soul » ou « Bachata »',
    titleEn: "AI Song Generator With Lyrics — Your Words, AI Vocals | ProducerHit",
    titleFr: "Générateur chanson IA avec paroles — Tes textes, voix IA | ProducerHit",
    descriptionEn:
      "AI song generator with lyrics: paste your words, pick a genre, get full vocals. Manual lyrics + Genre précis = style control Suno can't match.",
    descriptionFr:
      "Générateur chanson IA avec paroles : colle tes textes, choisis un genre, obtiens des voix complètes. Paroles manuelles + Genre précis.",
    keywords: ["AI song generator with lyrics", "AI music with custom lyrics", "generate song from lyrics AI", "text to song with vocals"],
    h1En: "AI Song Generator With Lyrics",
    h1Fr: "Générateur chanson IA avec paroles",
    leadEn:
      "Paste your lyrics, choose **Genre précis**, generate. ProducerHit keeps your words intact (useFormat off for manual lyrics) while the AI performs in trap, pop, Latin, country, or worship styles.",
    leadFr:
      "Colle tes paroles, choisis **Genre précis**, génère. ProducerHit garde ton texte intact tout en jouant trap, pop, Latin, country ou louange.",
    bulletsEn: ["Manual lyrics mode", "Genre drives instrumental", "Auto language detect", "Song duration from lyrics"],
    bulletsFr: ["Mode paroles manuelles", "Le genre pilote l'instrumental", "Détection langue auto", "Durée adaptée aux paroles"],
    faqEn: [{ q: "Will AI rewrite my lyrics?", a: "Manual lyrics mode preserves your text. AI lyrics mode generates new words." }],
    faqFr: [{ q: "L'IA réécrit mes paroles ?", a: "Le mode paroles manuelles préserve ton texte. Le mode paroles IA génère de nouveaux mots." }],
  },
  countryMusicSeoPage({
    slugKey: "ai-generated-country-song",
    path: "/ai-generated-country-song",
    pathFr: "/chanson-country-ia",
    variantEn: "AI Generated Country Song",
    variantFr: "Chanson country IA",
    keywordEn: "AI generated country song",
    keywordFr: "chanson country IA",
    genreValue: "Contemporary Country",
    promptEn:
      'Song Mode → Genre "Contemporary Country": "acoustic guitar storytelling, Nashville chorus, pedal steel accents, English vocals, heartfelt 108 BPM"',
    promptFr:
      'Song Mode → Genre « Contemporary Country » : « storytelling acoustique, refrain Nashville, pedal steel, voix anglaises, 108 BPM »',
    relatedSlugKeys: ["ai-country-song-generator", "free-ai-song-generator", "ai-song-generator", "ai-bluegrass-generator"],
  }),
  countryMusicSeoPage({
    slugKey: "ai-country-song-generator",
    path: "/ai-country-song-generator",
    pathFr: "/generateur-country-ia",
    variantEn: "AI Country Song Generator",
    variantFr: "Country song generator",
    keywordEn: "country song",
    keywordFr: "chanson country",
    genreValue: "Country Pop",
    promptEn:
      'Song Mode → "Country Pop": "catchy radio chorus, acoustic-electric blend, modern Nashville, English vocals, 110 BPM"',
    promptFr:
      'Song Mode → « Country Pop » : « refrain radio catchy, blend acoustique-électrique, Nashville moderne, voix anglaises, 110 BPM »',
    relatedSlugKeys: ["ai-generated-country-song", "ai-song-generator", "contemporary-country-ai-generator"],
  }),
  {
    path: "/contemporary-country-ai-generator",
    pathFr: "/generateur-country-contemporain-ia",
    slugKey: "contemporary-country-ai-generator",
    category: "country",
    relatedSlugKeys: ["ai-generated-country-song", "ai-country-song-generator", "ai-bluegrass-generator"],
    promptHintEn: 'Genre précis → "Contemporary Country" or "Outlaw Country" + English storytelling lyrics',
    promptHintFr: 'Genre précis → « Contemporary Country » ou « Outlaw Country » + paroles storytelling anglaises',
    titleEn: "Contemporary Country AI Generator — Nashville & Radio Ready | ProducerHit",
    titleFr: "Country contemporain IA — Nashville & radio ready | ProducerHit",
    descriptionEn: "Contemporary country AI generator: Nashville pop-country, outlaw twang, acoustic hooks. Song Mode + English vocals.",
    descriptionFr: "Générateur country contemporain IA : pop-country Nashville, twang outlaw, hooks acoustiques. Song Mode + voix anglaises.",
    keywords: ["contemporary country AI", "Nashville country generator AI", "modern country song AI", "country pop AI generator"],
    h1En: "Contemporary Country AI Generator",
    h1Fr: "Générateur country contemporain IA",
    leadEn: "Target the **+23% country streaming growth** with Genre précis: Contemporary Country, Country Pop, Outlaw Country, Bluegrass — all in one studio.",
    leadFr: "Cible la **croissance country +23% streaming** avec Genre précis : Contemporary Country, Country Pop, Outlaw Country, Bluegrass.",
    bulletsEn: ["4 country genres in catalog", "Song + beat modes", "English vocal focus", "Free MP3 start"],
    bulletsFr: ["4 genres country au catalogue", "Modes chanson + beat", "Focus voix anglaises", "Départ MP3 gratuit"],
    faqEn: [{ q: "Country beat or full song?", a: "Beat mode for type beats; Song Mode for vocals and chorus structure." }],
    faqFr: [{ q: "Beat country ou chanson ?", a: "Beat pour type beats ; Song Mode pour voix et refrain." }],
  },
  {
    path: "/ai-bluegrass-generator",
    pathFr: "/generateur-bluegrass-ia",
    slugKey: "ai-bluegrass-generator",
    category: "country",
    relatedSlugKeys: ["ai-generated-country-song", "contemporary-country-ai-generator", "ai-song-generator"],
    promptHintEn: 'Genre "Bluegrass": "banjo rolls, mandolin chop, fiddle breaks, fast 140 BPM, instrumental or vocal harmony"',
    promptHintFr: 'Genre « Bluegrass » : « banjo rolls, mandolin chop, breaks fiddle, 140 BPM, instrumental ou harmonies »',
    titleEn: "AI Bluegrass Generator — Banjo, Fiddle & Fast Picking | ProducerHit",
    titleFr: "Générateur bluegrass IA — Banjo, fiddle & picking rapide | ProducerHit",
    descriptionEn: "AI bluegrass generator: banjo rolls, mandolin, fiddle at 140 BPM. Instrumentals or vocal harmony space.",
    descriptionFr: "Générateur bluegrass IA : banjo rolls, mandolin, fiddle à 140 BPM. Instrumentaux ou harmonies vocales.",
    keywords: ["AI bluegrass generator", "bluegrass AI music", "banjo AI generator", "bluegrass song maker"],
    h1En: "AI Bluegrass Generator",
    h1Fr: "Générateur bluegrass IA",
    leadEn: "Authentic **bluegrass** prompts — banjo, mandolin chop, fiddle breaks — from ProducerHit's 640-genre catalog.",
    leadFr: "Prompts **bluegrass** authentiques — banjo, mandolin chop, breaks fiddle — depuis le catalogue 640 genres.",
    bulletsEn: ["~140 BPM default", "Appalachian folk adjacent", "Instrumental-first workflow", "Seed variations"],
    bulletsFr: ["~140 BPM par défaut", "Adjacent Appalachian folk", "Workflow instrumental", "Variations seed"],
    faqEn: [{ q: "Bluegrass vocals?", a: "Song Mode supports harmony-style vocal space — describe 'bluegrass vocal trio' in your prompt." }],
    faqFr: [{ q: "Voix bluegrass ?", a: "Song Mode supporte les harmonies — décris « trio vocal bluegrass » dans ton prompt." }],
  },
  {
    path: "/ai-song-generator-by-genre",
    pathFr: "/generateur-chanson-ia-par-genre",
    slugKey: "ai-song-generator-by-genre",
    category: "hub",
    relatedLimit: 12,
    relatedSlugKeys: [
      "ai-song-generator",
      "latin-music-generator",
      "ai-generated-country-song",
      "ai-trap-beat-generator",
      "ai-bachata-song-generator",
      "ai-reggaeton-generator",
      "ai-worship-song-generator",
      "ai-phonk-beat-generator",
      "ai-pop-beat-generator",
      "ai-bollywood-music-generator",
      "asia-music-generator",
      "middle-east-music-generator",
      "ai-k-pop-song-generator",
      "free-ai-song-generator",
      "music-ai-generator",
    ],
    titleEn: "AI Song Generator by Genre — 640+ Styles (2026) | ProducerHit",
    titleFr: "Générateur chanson IA par genre — 640+ styles (2026) | ProducerHit",
    descriptionEn:
      "AI song generator by genre: trap, drill, Latin, country, worship, phonk, pop, Bollywood & 640+ more. One studio — Song Mode + Genre précis.",
    descriptionFr:
      "Générateur chanson IA par genre : trap, drill, Latin, country, louange, phonk, pop, Bollywood & 640+ styles. Un studio — Song Mode + Genre précis.",
    keywords: ["AI song generator by genre", "AI music generator genres", "generate song by genre AI", "AI beat generator by genre"],
    h1En: "AI Song Generator by Genre",
    h1Fr: "Générateur chanson IA par genre",
    leadEn:
      "One **AI song generator**, **640+ genres** — from Melodic Trap to Bachata, Contemporary Country to Worship Pop. Pick Genre précis, Song Mode, iterate with seed. This hub links every major genre landing page.",
    leadFr:
      "Un **générateur chanson IA**, **640+ genres** — du Melodic Trap à la Bachata, du Contemporary Country au Worship Pop. Genre précis, Song Mode, seed. Ce hub relie toutes les landing genres.",
    bulletsEn: ["640+ ACE-tuned genres", "Latin · Country · Hip-hop · Worship hubs", "Song + Beat modes", "Internal links for SEO + UX"],
    bulletsFr: ["640+ genres ACE", "Hubs Latin · Country · Hip-hop · Louange", "Modes Song + Beat", "Maillage SEO + UX"],
    faqEn: [
      { q: "How many genres?", a: "640+ including extended catalog: Latin dance, phonk, Afro, rock, wellness, cinematic." },
      { q: "Best genre for TikTok?", a: "Try Viral TikTok, Phonk, Reggaeton, or Melodic Trap — generate short first." },
    ],
    faqFr: [
      { q: "Combien de genres ?", a: "640+ incluant Latin, phonk, Afro, rock, wellness, cinématique." },
      { q: "Meilleur genre TikTok ?", a: "Essaie Viral TikTok, Phonk, Reggaeton ou Melodic Trap — génère court d'abord." },
    ],
  },
  {
    path: "/latin-music-generator",
    pathFr: "/generateur-musique-latine-ia",
    slugKey: "latin-music-generator",
    category: "hub",
    relatedLimit: 12,
    relatedSlugKeys: LATIN_HUB_RELATED,
    promptHintEn: 'Start with Genre précis → "Reggaeton" or "Bachata" → Song Mode → Spanish lyrics',
    promptHintFr: 'Commence par Genre précis → « Reggaeton » ou « Bachata » → Song Mode → paroles espagnoles',
    titleEn: "Latin Music Generator — Reggaeton, Bachata, Salsa & More | ProducerHit",
    titleFr: "Générateur musique latine IA — Reggaeton, Bachata, Salsa & plus | ProducerHit",
    descriptionEn:
      "Latin music generator AI: reggaeton, bachata, salsa, kizomba, dembow, cumbia, corridos — 33+ Latin genres. Songs with vocals or beats. Free to start.",
    descriptionFr:
      "Générateur musique latine IA : reggaeton, bachata, salsa, kizomba, dembow, cumbia, corridos — 33+ genres Latin. Chansons ou beats. Gratuit pour commencer.",
    keywords: [
      "Latin music generator",
      "AI Latin music generator",
      "reggaeton AI generator",
      "bachata AI generator",
      "Latin song generator AI",
      "free Latin music AI",
    ],
    h1En: "Latin Music Generator",
    h1Fr: "Générateur musique latine IA",
    leadEn:
      "The most complete **Latin music generator** in 2026 — **33+ dedicated genres** (not one generic « tropical loop »). Bachata, reggaeton, salsa, kizomba, dembow, cumbia, regional Mexican, worship crossover — Song Mode with Spanish/Portuguese vocals.",
    leadFr:
      "Le **générateur musique latine IA** le plus complet en 2026 — **33+ genres dédiés** (pas une boucle « tropical » générique). Bachata, reggaeton, salsa, kizomba, dembow, cumbia, regional Mexican — Song Mode voix ES/PT.",
    bulletsEn: [
      "33+ Latin genres (wave 1+2 catalog)",
      "Competitors: 5–8 Latin styles · ProducerHit: 33+",
      "Perreo · Dembow · Bachata Sensual",
      "Song Mode + manual Spanish lyrics",
    ],
    bulletsFr: [
      "33+ genres Latin (catalogue vague 1+2)",
      "Concurrents : 5–8 styles · ProducerHit : 33+",
      "Perreo · Dembow · Bachata Sensual",
      "Song Mode + paroles espagnoles manuelles",
    ],
    faqEn: [
      { q: "Latin music generator vs generic AI?", a: "Each genre has ACE-tuned prompts (clave, dembow, bongo tumbao) — not a single « Latin » preset." },
      { q: "Spanish or English vocals?", a: "Both — manual lyrics auto-detect language; pick vocal language in Song Mode advanced." },
    ],
    faqFr: [
      { q: "Générateur Latin vs IA générique ?", a: "Chaque genre a des prompts ACE (clave, dembow, bongo) — pas un preset « Latin » unique." },
      { q: "Voix espagnoles ou anglaises ?", a: "Les deux — paroles manuelles avec détection auto ; langue vocale en Song Mode avancé." },
    ],
  },
  {
    path: "/ai-worship-song-generator",
    pathFr: "/generateur-louange-ia",
    slugKey: "ai-worship-song-generator",
    category: "song",
    relatedSlugKeys: ["ai-song-generator", "free-ai-song-generator", "ai-generated-country-song", "ai-song-generator-by-genre"],
    promptHintEn: 'Genre "Worship Pop": "uplifting major chords, anthemic chorus, congregational hooks, English vocals, 75 BPM"',
    promptHintFr: 'Genre « Worship Pop » : « accords majeurs uplifting, refrain anthemique, hooks congregational, voix anglaises, 75 BPM »',
    titleEn: "AI Worship Song Generator — Christian & Gospel Pop (2026) | ProducerHit",
    titleFr: "Générateur louange IA — Worship & gospel pop (2026) | ProducerHit",
    descriptionEn:
      "AI worship song generator: +18.5% streaming growth genre. Worship Pop, Gospel Worship. English vocals, anthemic choruses. Free to start.",
    descriptionFr:
      "Générateur louange IA : genre en croissance +18,5% streaming. Worship Pop, Gospel Worship. Voix anglaises, refrains anthemiques. Gratuit pour commencer.",
    keywords: ["AI worship song generator", "Christian music AI generator", "gospel song generator AI", "worship music maker online"],
    h1En: "AI Worship Song Generator",
    h1Fr: "Générateur louange IA",
    leadEn: "Ride the **fastest-growing US genre** with Worship Pop & Gospel Worship — Song Mode, English lyrics, major-key anthem structure.",
    leadFr: "Surfe sur le **genre US le plus en croissance** avec Worship Pop & Gospel Worship — Song Mode, paroles anglaises, structure anthemique.",
    bulletsEn: ["Worship Pop + Gospel Worship genres", "TikTok-friendly worship trend", "Congregational chorus space", "Afrobeats Gospel crossover"],
    bulletsFr: ["Genres Worship Pop + Gospel Worship", "Trend worship TikTok", "Espace refrain congregational", "Crossover Afrobeats Gospel"],
    faqEn: [{ q: "Church CCLI licensing?", a: "AI output is your draft — verify licensing with your church workflow before live worship." }],
    faqFr: [{ q: "Licence CCLI église ?", a: "La sortie IA est un brouillon — vérifie la licence avec ton workflow église avant le culte live." }],
  },
  {
    path: "/ai-bollywood-music-generator",
    pathFr: "/generateur-bollywood-ia",
    slugKey: "ai-bollywood-music-generator",
    category: "hub",
    relatedSlugKeys: ["latin-music-generator", "ai-song-generator-by-genre", "ai-song-generator", "ai-bhangra-generator"],
    promptHintEn: 'Genre "Bollywood": "Hindi filmi, sitar and tabla, cinematic strings, emotional chorus, Hindi vocal space"',
    promptHintFr: 'Genre « Bollywood » : « filmi Hindi, sitar et tabla, cordes cinéma, refrain émotionnel, voix Hindi »',
    titleEn: "AI Bollywood Music Generator — Filmi Songs & Beats | ProducerHit",
    titleFr: "Générateur Bollywood IA — Chansons filmi & beats | ProducerHit",
    descriptionEn: "AI Bollywood music generator: sitar, tabla, filmi orchestration. Hindi vocal space. Also Bhangra & Kollywood in catalog.",
    descriptionFr: "Générateur Bollywood IA : sitar, tabla, orchestration filmi. Voix Hindi. Bhangra & Kollywood au catalogue.",
    keywords: ["AI Bollywood music generator", "Bollywood song generator AI", "Hindi song AI maker", "filmi music AI"],
    h1En: "AI Bollywood Music Generator",
    h1Fr: "Générateur Bollywood IA",
    leadEn: "Generate **Bollywood** and **Bhangra** with dedicated genres — not western pop with a sitar emoji.",
    leadFr: "Génère **Bollywood** et **Bhangra** avec genres dédiés — pas de la pop occidentale avec un emoji sitar.",
    bulletsEn: ["Bollywood · Bhangra · Kollywood", "Hindi/Tamil vocal space", "Song Mode", "640+ genre hub"],
    bulletsFr: ["Bollywood · Bhangra · Kollywood", "Voix Hindi/Tamil", "Song Mode", "Hub 640+ genres"],
    faqEn: [{ q: "Hindi lyrics?", a: "Paste Hindi in manual lyrics mode — language auto-detect handles Devanagari script." }],
    faqFr: [{ q: "Paroles Hindi ?", a: "Colle du Hindi en paroles manuelles — détection auto Devanagari." }],
  },
  {
    path: "/ai-bhangra-generator",
    pathFr: "/generateur-bhangra-ia",
    slugKey: "ai-bhangra-generator",
    category: "hub",
    relatedSlugKeys: ["ai-bollywood-music-generator", "ai-song-generator-by-genre", "latin-music-generator"],
    promptHintEn: 'Genre "Bhangra": "Punjabi dhol drive, tumbi pluck, wedding party energy, 125 BPM, Punjabi vocal hooks"',
    promptHintFr: 'Genre « Bhangra » : « dhol Punjabi, tumbi, énergie mariage, 125 BPM, hooks vocaux Punjabi »',
    titleEn: "AI Bhangra Generator — Punjabi Dhol & Wedding Energy | ProducerHit",
    titleFr: "Générateur Bhangra IA — Dhol Punjabi & énergie mariage | ProducerHit",
    descriptionEn: "AI Bhangra generator: dhol drums, tumbi, Punjabi wedding bounce. Song Mode with Punjabi vocal hooks.",
    descriptionFr: "Générateur Bhangra IA : dhol, tumbi, bounce mariage Punjabi. Song Mode hooks vocaux Punjabi.",
    keywords: ["AI bhangra generator", "Punjabi music AI", "bhangra beat maker AI", "dhol AI music"],
    h1En: "AI Bhangra Generator",
    h1Fr: "Générateur Bhangra IA",
    leadEn: "Dedicated **Bhangra** genre with dhol tumbao, tumbi accents, and 125 BPM wedding energy.",
    leadFr: "Genre **Bhangra** dédié avec tumbao dhol, accents tumbi, énergie mariage 125 BPM.",
    bulletsEn: ["125 BPM default", "Wedding & festival use", "Pairs with Bollywood hub", "Manual Punjabi lyrics"],
    bulletsFr: ["125 BPM par défaut", "Mariages & festivals", "Hub Bollywood", "Paroles Punjabi manuelles"],
    faqEn: [{ q: "Bhangra vs Bollywood?", a: "Bhangra = Punjabi dhol dance; Bollywood = Hindi filmi orchestration. Both in catalog." }],
    faqFr: [{ q: "Bhangra vs Bollywood ?", a: "Bhangra = danse dhol Punjabi ; Bollywood = orchestration filmi Hindi. Les deux au catalogue." }],
  },
  {
    path: "/phonk-music-generator",
    pathFr: "/generateur-phonk-complet-ia",
    slugKey: "phonk-music-generator",
    category: "hub",
    relatedLimit: 10,
    relatedSlugKeys: [
      "ai-phonk-beat-generator",
      "ai-trap-beat-generator",
      "ai-song-generator-by-genre",
      "ai-beat-generator",
    ],
    titleEn: "Phonk Music Generator — Drift, Memphis, Brazilian & Gym | ProducerHit",
    titleFr: "Générateur phonk IA — Drift, Memphis, Brazilian & Gym | ProducerHit",
    descriptionEn:
      "Phonk music generator: drift phonk, Memphis phonk, Brazilian phonk, gym phonk, house phonk, atmospheric phonk. Cowbell + 808 workflow.",
    descriptionFr:
      "Générateur phonk IA : drift, Memphis, Brazilian, gym, house, atmospheric phonk. Workflow cowbell + 808.",
    keywords: ["phonk music generator", "drift phonk AI", "Memphis phonk generator", "Brazilian phonk AI", "gym phonk maker"],
    h1En: "Phonk Music Generator",
    h1Fr: "Générateur phonk IA complet",
    leadEn: "Six **phonk** subgenres in one studio — Drift, Memphis, Brazilian, Gym, House, Aggressive — each ACE-tuned. Beat competitors' single « phonk » slider.",
    leadFr: "Six sous-genres **phonk** — Drift, Memphis, Brazilian, Gym, House, Aggressive — chacun ACE. Bat le slider « phonk » unique des concurrents.",
    bulletsEn: ["6 phonk subgenres", "Cowbell + distorted 808 prompts", "TikTok / car edit ready", "Seed variation loop"],
    bulletsFr: ["6 sous-genres phonk", "Prompts cowbell + 808 disto", "Prêt TikTok / car edit", "Boucle variation seed"],
    faqEn: [{ q: "Drift vs Memphis phonk?", a: "Drift = cowbell glide + car-edit energy; Memphis = dusty samples + lo-fi breaks." }],
    faqFr: [{ q: "Drift vs Memphis phonk ?", a: "Drift = glide cowbell + car edit ; Memphis = samples dusty + breaks lo-fi." }],
  },
];
