/** Extended genre catalog — ACE-Step XL 1.5 prompts (musicological). */
import { HIP_HOP_SOUL_GENRES } from "@/lib/genres/hipHopSoulCatalog";
import { LATIN_WORLD_GENRES } from "@/lib/genres/latinWorldCatalog";
import { WORLD_WAVE2_GENRES } from "@/lib/genres/worldWave2Catalog";
import { WORLD_WAVE3_GENRES } from "@/lib/genres/worldWave3Catalog";

export type ExtendedGenreDef = {
  value: string;
  label?: string;
  group: string;
  prompt: string;
  aceTags: string;
  bpm: number;
  sonautoTags: string[];
};

function g(
  value: string,
  group: string,
  prompt: string,
  aceTags: string,
  bpm: number,
  sonautoTags: string[] = ["2020s", "instrumental"],
): ExtendedGenreDef {
  return { value, group, prompt, aceTags, bpm, sonautoTags };
}

export const EXTENDED_GENRES: ExtendedGenreDef[] = [


  // ── DnB / Breaks ──
  g(
    "Liquid DnB",
    "DnB / Breaks",
    "liquid drum and bass, smooth rolling breakbeats, warm sub bass slides, lush pad stacks, melodic reese layers, liquid harmonic swells, sidechain breath, flowing 174 groove",
    "liquid dnb, rolling breaks, warm sub, lush pads, melodic reese",
    174,
    ["dance", "melodic", "smooth", "2020s"],
  ),
  g(
    "Jungle",
    "DnB / Breaks",
    "jungle, classic breakbeat science, chopped amen breaks, heavy sub bass, ragga vocal chop textures, Reese stab layers, raw UK rave energy, warehouse MC-ready tension",
    "jungle, amen breaks, sub bass, ragga chops, UK rave energy",
    170,
    ["dance", "rhythmic", "aggressive", "1990s"],
  ),
  g(
    "Breakcore",
    "DnB / Breaks",
    "breakcore, extreme chopped breakbeats, distorted bass hits, chaotic bar-to-bar edits, high BPM intensity, industrial noise bursts, experimental hardcore adrenaline, relentless edit frenzy",
    "breakcore, extreme breaks, distorted bass, chaotic edits, high energy",
    180,
    ["dance", "aggressive", "experimental", "2020s"],
  ),

  // ── Electronic / Club ──
  g(
    "Future Bass",
    "Electronic / Club",
    "future bass, bright supersaw chord stacks, sidechain pump groove, emotional topline space, crisp trap-influenced drums, wide stereo lead layers, euphoric festival drop lift",
    "future bass, supersaw chords, sidechain pump, emotional leads, festival drop",
    150,
    ["dance", "melodic", "energetic", "2020s"],
  ),
  g(
    "Melodic Dubstep",
    "Electronic / Club",
    "melodic dubstep, emotional minor chord progression, soft sidechain pads, tasteful wobble bass motion, half-time snare pattern, cinematic drop swells, bittersweet lead hook space",
    "melodic dubstep, emotional chords, half-time drums, wobble bass, cinematic drops",
    140,
    ["dance", "melodic", "dark", "2020s"],
  ),
  g(
    "EDM Festival",
    "Electronic / Club",
    "EDM festival anthem, big room chord stabs, massive build-up risers and drops, sidechain pump kick, crowd-ready energy, wide supersaw lead hooks, mainstage peak-hour drive",
    "EDM festival, big room, build-ups and drops, sidechain, crowd energy",
    128,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Tech House",
    "Electronic / Club",
    "tech house, driving four-on-the-floor kick, hypnotic rolling bass groove, minimal percussion layers, hi-hat shuffle swing, warehouse club tension, Berlin tech-house pulse",
    "tech house, four-on-the-floor, hypnotic bass, minimal percussion, club",
    126,
    ["house", "dance", "rhythmic", "2020s"],
  ),
  g(
    "Minimal Techno",
    "Electronic / Club",
    "minimal techno, stripped hypnotic groove, tight kick thump, subtle hi-hat ticks, evolving filter textures, warehouse atmosphere drones, late-night Berlin pulse restraint",
    "minimal techno, hypnotic groove, stripped drums, warehouse vibe",
    124,
    ["dance", "hypnotic", "dark", "2020s"],
  ),
  g(
    "Hard Techno",
    "Electronic / Club",
    "hard techno, pounding distorted kick, industrial metal textures, relentless four-on-the-floor drive, dark warehouse rave tension, aggressive synth stabs, peak-hour endurance energy",
    "hard techno, pounding kick, industrial textures, relentless rave energy",
    145,
    ["dance", "aggressive", "dark", "2020s"],
  ),
  g(
    "Trance",
    "Electronic / Club",
    "trance, uplifting arpeggiated sequences, emotional supersaw lead lines, rolling kick pattern, euphoric build and breakdown arcs, wide stereo delay tails, hands-up festival lift",
    "trance, uplifting arps, supersaw leads, euphoric energy",
    138,
    ["dance", "melodic", "energetic", "2000s"],
  ),
  g(
    "Psytrance",
    "Electronic / Club",
    "psytrance, rolling bassline pulse, psychedelic synth sequence layers, triplet hi-hat feel, hypnotic festival drive, bright squelchy lead motifs, forest-party twilight energy",
    "psytrance, rolling bass, psychedelic synths, hypnotic festival",
    145,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Deep House",
    "Electronic / Club",
    "deep house, warm seventh chord pads, groovy bassline pocket, soft open hi-hats, soulful deep club swing, late-night vinyl warmth, understated vocal chop space",
    "deep house, warm chords, groovy bass, soulful club groove",
    122,
    ["house", "dance", "smooth", "2020s"],
  ),
  g(
    "Tropical House",
    "Electronic / Club",
    "tropical house, bright marimba or pluck melody, relaxed four-on-the-floor kick, sunny major chord lift, gentle shaker rhythm, summer beach sunset groove, breezy topline hooks",
    "tropical house, bright plucks, relaxed groove, sunny summer vibe",
    118,
    ["house", "dance", "happy", "2020s"],
  ),
  g(
    "Organic House",
    "Electronic / Club",
    "organic house, live percussion layers, warm analog chord voicings, earthy shaker and conga groove, natural woodblock accents, deep club pulse, hand-played rhythm human feel",
    "organic house, live percussion, warm chords, earthy groove",
    120,
    ["house", "dance", "smooth", "2020s"],
  ),
  g(
    "Soulful House",
    "Electronic / Club",
    "soulful house, gospel-influenced chord movement, warm round bass, swung hi-hat pattern, emotional vocal sample chops, classic Chicago house piano stabs, joyful dancefloor lift",
    "soulful house, gospel chords, warm bass, vocal chops, classic house",
    124,
    ["house", "soul", "dance", "2000s"],
  ),
  g(
    "French Touch",
    "Electronic / Club",
    "french touch, filtered disco sample chops, sidechain pump groove, funky octave bass line, Daft Punk-inspired filter sweeps, chic Paris club bounce, vocoder hook space optional",
    "french touch, filtered disco, sidechain, funky bass, chic club",
    122,
    ["house", "dance", "2000s"],
  ),
  g(
    "Electro Funk",
    "Electronic / Club",
    "electro funk, syncopated synth bass riff, talkbox-style lead space, tight drum machine groove, neon 80s-influenced chord stabs, robotic clap pattern, dancefloor funk swagger",
    "electro funk, synth bass, tight drums, neon 80s groove",
    115,
    ["dance", "rhythmic", "2000s"],
  ),
  g(
    "Synth Pop",
    "Electronic / Club",
    "synth pop, catchy hook melody, bright analog synth layers, punchy gated snare drums, 80s-inspired chorus chords, modern sheen arps, radio-friendly topline energy",
    "synth pop, catchy hook, analog synths, punchy drums, 80s sheen",
    118,
    ["melodic", "2020s"],
  ),
  g(
    "Chill Electronic",
    "Electronic / Club",
    "chill electronic, soft sidechain pad washes, gentle beat pocket, warm sub bass hum, relaxed texture layers, easy listening groove sway, sunset headphone calm atmosphere",
    "chill electronic, soft pads, gentle beat, relaxed textures",
    100,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Experimental Electronic",
    "Electronic / Club",
    "experimental electronic, unconventional sound design bursts, evolving granular textures, irregular rhythm fractures, futuristic art-forward timbres, aleatoric percussion clusters, gallery-installation spatial depth",
    "experimental electronic, sound design, evolving textures, irregular rhythms",
    110,
    ["atmospheric", "2020s"],
  ),
  g(
    "Underground Club",
    "Electronic / Club",
    "underground club, dark warehouse groove, heavy kick thump, minimal synth stab accents, raw late-night energy, basement reverb tails, stripped hypnotic tension build",
    "underground club, warehouse groove, heavy kick, dark minimal",
    130,
    ["dance", "dark", "2020s"],
  ),

  // ── Pop / Rock / Indie ──
  g(
    "Cyberpunk",
    "Pop / Rock / Indie",
    "cyberpunk electronic, neon synth bass pulse, dystopian pad atmosphere, glitch texture hits, rain-soaked futuristic city vibe, distorted industrial drums, blade-runner night alley tension",
    "cyberpunk, neon synths, dystopian, glitch textures, futuristic",
    128,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Y2K Pop",
    "Pop / Rock / Indie",
    "Y2K pop, glossy 2000s synth layers, catchy hook melody, punchy TR-909-style drums, nostalgic futuristic chord stacks, flip-phone era sparkle, bright major-key dance energy",
    "Y2K pop, glossy 2000s synths, catchy hook, nostalgic futuristic",
    118,
    ["melodic", "2000s"],
  ),
  g(
    "Bedroom Pop",
    "Pop / Rock / Indie",
    "bedroom pop, intimate lo-fi drum pocket, soft acoustic or synth layers, warm close-mic room tone, dreamy minor chord sway, whisper vocal space, late-night diary intimacy",
    "bedroom pop, intimate lo-fi, soft drums, dreamy close feel",
    95,
    ["lo-fi", "melodic", "2020s"],
  ),
  g(
    "Shoegaze",
    "Pop / Rock / Indie",
    "shoegaze, wall of reverb-drenched guitars, hazy chorus textures, slow driving drum groove, dreamy blurred atmosphere, buried vocal wash, melancholic noise-pop immersion",
    "shoegaze, reverb guitars, hazy textures, dreamy blurred vibe",
    110,
    ["atmospheric", "melancholic", "1990s"],
  ),
  g(
    "Indie Rock",
    "Pop / Rock / Indie",
    "indie rock, jangly clean guitar arpeggios, live drum groove pocket, catchy but raw chord movement, modern alternative energy, bass-driven verse lift, festival-ready hook space",
    "indie rock, jangly guitars, live drums, alternative energy",
    128,
    ["rhythmic", "2020s"],
  ),
  g(
    "Psychedelic Rock",
    "Pop / Rock / Indie",
    "psychedelic rock, swirling guitar delays, trippy phaser textures, driving groove pocket, vintage rock organ swells, mind-expanding chord colors, 60s revival atmosphere with weight",
    "psychedelic rock, swirling guitars, trippy delays, vintage rock",
    120,
    ["rhythmic", "atmospheric", "1960s"],
  ),
  g(
    "Alternative Rock",
    "Pop / Rock / Indie",
    "alternative rock, gritty distorted guitar riffs, punchy live snare drums, emotional chord movement, arena-ready dynamic range, 2000s alt-rock angst, anthemic chorus hook lift",
    "alternative rock, gritty guitars, punchy drums, emotional chords",
    132,
    ["rhythmic", "2020s"],
  ),
  g(
    "Acoustic Indie",
    "Pop / Rock / Indie",
    "acoustic indie, fingerpicked nylon or steel guitar, soft brushed percussion, warm intimate room tone, heartfelt melodic motif, gentle vocal storytelling space, campfire sincerity",
    "acoustic indie, fingerpicked guitar, soft percussion, intimate room",
    92,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "J-Pop",
    "Pop / Rock / Indie",
    "J-pop, bright layered synth stacks, catchy hook melody, energetic four-on-the-floor drums, polished Tokyo pop chord voicings, kawaii sparkle optional, anime-opening lift energy",
    "J-pop, bright synths, catchy hook, polished Tokyo pop",
    128,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "K-R&B",
    "Pop / Rock / Indie",
    "K-R&B, sleek modern R&B chord voicings, tight trap-influenced drums, glossy synth texture layers, Seoul night vibe bass glide, smooth falsetto topline space, understated luxury sway",
    "K-R&B, sleek R&B chords, glossy synths, Seoul night vibe",
    92,
    ["r&b/soul", "smooth", "2020s"],
  ),
  g(
    "Future Funk",
    "Pop / Rock / Indie",
    "future funk, disco sample chops, funky octave bass groove, sidechain pump swing, neon 80s nostalgia chords, upbeat dance energy, vocoder hook accents, roller-rink bounce",
    "future funk, disco chops, funky bass, neon 80s nostalgia",
    118,
    ["dance", "rhythmic", "2020s"],
  ),
  g(
    "AI Generated Pop",
    "Pop / Rock / Indie",
    "AI-generated pop aesthetic, futuristic clean synth textures, catchy algorithmic hook contour, hyper-digital chord stacks, synthetic vocal shimmer space, uncanny valley pop sheen, tomorrow-morning radio feel",
    "AI pop, futuristic synths, catchy hook, hyper-modern sheen",
    120,
    ["melodic", "2020s"],
  ),

  // ── Ambient / Cinematic ──
  g(
    "Cinematic Ambient",
    "Ambient / Cinematic",
    "cinematic ambient, evolving orchestral pad layers, wide hall reverb tails, slow emotional harmonic movement, film-score atmosphere drones, sparse piano accents, intimate blockbuster stillness",
    "cinematic ambient, orchestral pads, wide reverb, film-score feel",
    70,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Dark Ambient",
    "Ambient / Cinematic",
    "dark ambient, ominous low drones, sparse metallic textures, deep sub rumble undertow, horror-tinged wide spatial void, slow evolving dread, candle-extinguish silence pockets",
    "dark ambient, ominous drones, sparse textures, deep sub",
    60,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Atmospheric",
    "Ambient / Cinematic",
    "atmospheric instrumental, wide pad washes, gentle pulse undertone, immersive spatial depth, emotional but minimal rhythm, breath-like dynamics, horizon-gazing stillness, slow evolving calm",
    "atmospheric, wide pads, gentle pulse, immersive space",
    80,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Meditation",
    "Ambient / Cinematic",
    "meditation music, soft healing drones, gentle singing bowl or bell accents, slow harmonic shifts, calming breath-paced evolution, temple quietude, mindful single-note focus",
    "meditation, soft drones, gentle bells, calming healing vibe",
    55,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Sleep Music",
    "Ambient / Cinematic",
    "sleep music, ultra-soft texture blankets, minimal or absent percussion, warm low drone hum, deeply calming nocturnal atmosphere, delta-wave slow pulse, pillow-close intimacy",
    "sleep music, ultra-soft textures, warm drones, calming",
    50,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Nature Soundscape",
    "Ambient / Cinematic",
    "nature soundscape, organic field-recording bed, gentle melodic undertones, forest bird or stream ambience, peaceful harmonic stillness, dawn meadow openness, earth-tone pad warmth",
    "nature soundscape, organic ambience, forest or water feel, peaceful",
    65,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Fantasy Soundtrack",
    "Ambient / Cinematic",
    "fantasy soundtrack, orchestral strings and choir pads, magical harp or flute motifs, epic but intimate adventure atmosphere, heroic brass swells restrained, enchanted forest harmonic color",
    "fantasy soundtrack, orchestral strings, magical motifs, adventure",
    90,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Anime OST",
    "Ambient / Cinematic",
    "anime OST, emotional piano and string interplay, bright melodic hook phrases, J-anime drama energy swells, polished cinematic dynamics, bittersweet schoolyard chord turns, opening-theme lift",
    "anime OST, emotional piano, strings, bright melodic hooks",
    100,
    ["melodic", "atmospheric", "2020s"],
  ),
  g(
    "Video Game OST",
    "Ambient / Cinematic",
    "video game OST, loop-friendly catchy motif, chiptune or modern synth layer stacks, level-music energy contour, punchy drum accents, exploration-zone wonder, boss-fight tension optional",
    "video game OST, catchy motif, chiptune or synth layers, loop-friendly",
    128,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Epic Trailer Music",
    "Ambient / Cinematic",
    "epic trailer music, huge orchestral hit accents, rising brass and taiko percussion, dramatic tension crescendo, blockbuster impact swells, heartbeat pulse undertow, final-reveal chord slam",
    "epic trailer, orchestral hits, rising brass, dramatic tension",
    100,
    ["dark", "energetic", "2020s"],
  ),
  g(
    "Orchestral Hybrid",
    "Ambient / Cinematic",
    "orchestral hybrid, live string section blended with modern synth bass and drums, cinematic epic groove pocket, wide dynamic range arcs, trailer-meets-club crossover energy, brass stab punctuation",
    "orchestral hybrid, strings plus synths, cinematic epic groove",
    95,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Dark Cinematic",
    "Ambient / Cinematic",
    "dark cinematic, low brass and string clusters, tense drone undertones, slow-building dread atmosphere, trailer-like shadow space, dissonant cluster resolutions, noir investigation pulse",
    "dark cinematic, low brass, tense drones, shadow atmosphere",
    75,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Sci-Fi Atmosphere",
    "Ambient / Cinematic",
    "sci-fi atmosphere, alien synth texture layers, wide space reverb fields, pulsing sub undertone, futuristic exploratory mood, ion-drive arpeggios, starship corridor humming stillness",
    "sci-fi atmosphere, alien synths, wide space, futuristic mood",
    85,
    ["atmospheric", "2020s"],
  ),
  g(
    "Apocalyptic Ambient",
    "Ambient / Cinematic",
    "apocalyptic ambient, desolate wind drones, distant industrial rumble textures, post-collapse wide spatial void, bleak beauty harmonic minor, ash-fall silence, ruined-city horizon stillness",
    "apocalyptic ambient, desolate drones, industrial rumble, bleak",
    65,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Space Ambient",
    "Ambient / Cinematic",
    "space ambient, cosmic pad evolution, slow stellar texture blooms, deep nebula reverb tails, weightless exploration feel, satellite ping accents sparse, infinite dark-sky drift",
    "space ambient, cosmic pads, stellar reverb, weightless feel",
    60,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Ocean Dreamscape",
    "Ambient / Cinematic",
    "ocean dreamscape, liquid pad motion, gentle wave-like rhythmic sway, underwater reverb blur, serene blue atmosphere chords, distant whale-tone undertones, tidal breathing dynamics",
    "ocean dreamscape, liquid pads, underwater reverb, serene",
    70,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Piano Ambient",
    "Ambient / Cinematic",
    "piano ambient, sparse expressive piano notes, long reverb decay tails, minimal soft pulse undertone, intimate emotional harmonic space, felt-hammer warmth, solitary room reflection",
    "piano ambient, sparse piano, long reverb, intimate emotional",
    65,
    ["melodic", "atmospheric", "2020s"],
  ),
  g(
    "Spiritual Ambient",
    "Ambient / Cinematic",
    "spiritual ambient, healing pad layers, gentle choir texture swells, sacred calm atmosphere, slow harmonic bloom arcs, incense-room stillness, devotional breath-paced evolution",
    "spiritual ambient, healing pads, choir textures, sacred calm",
    60,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Cosmic Synths",
    "Ambient / Cinematic",
    "cosmic synths, arpeggiated space sequences, analog warmth oscillator layers, retro-future stellar groove pulse, nebula filter sweeps, orbital bass undertone, 80s sci-fi optimism",
    "cosmic synths, arpeggiated sequences, analog warmth, retro-future",
    105,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Floating Dreamscape",
    "Ambient / Cinematic",
    "floating dreamscape, weightless pad suspension, soft glitter texture sparkles, slow heartbeat pulse, surreal peaceful immersion, cloud-walk harmonic drift, lucid sleep border atmosphere",
    "floating dreamscape, weightless pads, soft glitter, surreal peace",
    72,
    ["atmospheric", "smooth", "2020s"],
  ),

  // ── Jazz / World / Funk ──
  g(
    "Jazzhop",
    "Jazz / World / Funk",
    "jazzhop, jazzy seventh chord sample chops, boom bap or lo-fi drum pocket, warm upright bass tone, smoky late-night café groove, muted trumpet accent optional, study-session head-nod swing",
    "jazzhop, jazzy chords, lo-fi drums, late-night café groove",
    88,
    ["lo-fi", "jazz", "smooth", "2020s"],
  ),
  g(
    "City Pop",
    "Jazz / World / Funk",
    "city pop, 80s Japanese-inspired groove pocket, funky slap bass line, bright major-ninth chord stacks, slick production sheen, sunset urban nostalgia, coastal highway synth pads",
    "city pop, 80s Japanese groove, funky bass, sunset nostalgia",
    108,
    ["smooth", "melodic", "1980s"],
  ),
  g(
    "Bossa Nova",
    "Jazz / World / Funk",
    "bossa nova, nylon guitar syncopated rhythm pattern, soft brushed snare swing, warm round bass tone, Brazilian relaxed bossa feel, sunny intimate major-seventh chords, beach café breeze",
    "bossa nova, nylon guitar, brushed drums, Brazilian swing",
    115,
    ["smooth", "latin", "2020s"],
  ),
  g(
    "Funk Carioca",
    "Jazz / World / Funk",
    "funk carioca, Brazilian baile funk energy, pounding tamborzão kick pattern, MC-ready drop accents, raw Rio party groove, tamborim shuffle layers, favela block-party intensity",
    "funk carioca, baile funk energy, pounding kick, Rio party",
    130,
    ["latin", "dance", "energetic", "2020s"],
  ),
  g(
    "Lo-Fi Jazz",
    "Jazz / World / Funk",
    "lo-fi jazz, dusty jazz chord voicings, mellow swung drum pocket, vinyl crackle warmth bed, study-night smoky atmosphere, upright bass thump, muted piano comping phrases",
    "lo-fi jazz, dusty chords, mellow drums, vinyl warmth",
    82,
    ["lo-fi", "jazz", "melancholic", "2020s"],
  ),
  g(
    "Gospel Soul",
    "Jazz / World / Funk",
    "gospel soul, uplifting chord movement arcs, Hammond organ textures, powerful rhythmic drive, joyful spiritual energy, choir call-response space, handclap gospel pocket lift",
    "gospel soul, organ textures, uplifting chords, spiritual energy",
    98,
    ["soul", "r&b/soul", "energetic", "2020s"],
  ),
  g(
    "Retro Disco",
    "Jazz / World / Funk",
    "retro disco, four-on-the-floor kick groove, funky octave bass line, orchestral string stab hits, 70s dancefloor nostalgia chords, hi-hat open shimmer, mirror-ball Saturday night lift",
    "retro disco, four-on-the-floor, funky bass, 70s dancefloor",
    118,
    ["dance", "rhythmic", "1970s"],
  ),

  // ── Internet / Aesthetic ──
  g(
    "HexD",
    "Internet / Aesthetic",
    "hexd, distorted digital rap-adjacent energy, bitcrushed drum bursts, chaotic detuned synth stabs, hyper-aggressive internet sound design, clipped 808 undertones, glitch-core edit frenzy",
    "hexd, bitcrushed drums, chaotic synths, hyper-aggressive digital",
    160,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Nightdrive",
    "Internet / Aesthetic",
    "nightdrive synthwave, driving analog bass pulse, neon arpeggiated lead lines, 80s highway atmosphere pads, retro-futuristic four-on-the-floor groove, dashboard glow reverb, midnight coastal road",
    "nightdrive, synthwave, neon arps, 80s highway retro-future",
    110,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Mallsoft",
    "Internet / Aesthetic",
    "mallsoft vaporwave, washed nostalgic muzak Rhodes loops, slow dreamy groove sway, empty mall PA reverb ambience, hazy fluorescent pad wash, food-court echo stillness, escalator drift",
    "mallsoft, vaporwave, nostalgic muzak, empty mall ambience",
    80,
    ["lo-fi", "atmospheric", "2010s"],
  ),
  g(
    "Sigilkore",
    "Internet / Aesthetic",
    "sigilkore, dark internet rap aesthetic, distorted 808 sub hits, occult atmospheric texture drones, underground digital energy, ritualistic chant space, basement cipher dread pulse",
    "sigilkore, distorted 808s, occult textures, underground digital",
    150,
    ["dark", "aggressive", "2020s"],
  ),
  g(
    "Dreamcore",
    "Internet / Aesthetic",
    "dreamcore, surreal nostalgic pad textures, soft unsettling music-box motifs, liminal melody loops, hazy memory-like reverb hall, dissociative corridor atmosphere, sleepwalk harmonic blur",
    "dreamcore, surreal nostalgic, liminal melody, hazy memory",
    85,
    ["atmospheric", "melancholic", "2020s"],
  ),
  g(
    "Weirdcore",
    "Internet / Aesthetic",
    "weirdcore, uncanny nostalgic sound design, glitchy childlike motif stabs, unsettling but playful digital vibe, detuned circus organ accents, wrong-speed tape wobble, surreal valley pocket",
    "weirdcore, uncanny nostalgic, glitchy motifs, unsettling playful",
    90,
    ["atmospheric", "2020s"],
  ),
  g(
    "Liminal",
    "Internet / Aesthetic",
    "liminal ambient, empty transitional space feeling, soft reverb corridor tails, uncanny calm stillness, backrooms-like atmosphere drones, fluorescent hum undertone, no-exit hallway drift",
    "liminal ambient, empty space feeling, uncanny calm, soft reverb",
    70,
    ["atmospheric", "2020s"],
  ),
  g(
    "Analog Horror",
    "Internet / Aesthetic",
    "analog horror, degraded tape texture warble, unsettling low drones, VHS tracking hiss layer, creepy retro broadcast tone, emergency-alert undertone, found-footage basement dread",
    "analog horror, degraded tape, VHS hiss, creepy retro broadcast",
    75,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Nostalgic 2000s",
    "Internet / Aesthetic",
    "nostalgic 2000s, glossy pop-trap crossover synth layers, bright major chord hooks, early internet era emotional vibe, flip-phone notification blips, MySpace glitter arp accents, AIM-era warmth",
    "nostalgic 2000s, glossy synths, early internet emotional vibe",
    105,
    ["melodic", "2000s"],
  ),
  g(
    "Retro Futuristic",
    "Internet / Aesthetic",
    "retro futuristic, 80s analog synth chord stacks, contemporary drum programming pocket, neon arpeggio lead lines, chrome atmosphere pads, optimistic sci-fi tone, gated reverb snare accent",
    "retro futuristic, 80s synth, neon arps, optimistic sci-fi",
    118,
    ["melodic", "2020s"],
  ),
  g(
    "Nostalgic VHS",
    "Internet / Aesthetic",
    "nostalgic VHS aesthetic, magnetic tape warble drift, lo-fi drum machine pocket, warm saturated chord stacks, home-video memory vibe, tracking-line wobble bass, Blockbuster Friday-night feel",
    "nostalgic VHS, tape warble, warm saturated chords, memory vibe",
    92,
    ["lo-fi", "melancholic", "1990s"],
  ),
  g(
    "Dreamy Cassette",
    "Internet / Aesthetic",
    "dreamy cassette, warbled tape pitch flutter, soft brushed drum pocket, intimate bedroom texture warmth, faded photo nostalgia chords, four-track hiss bed, diary-page melodic motif",
    "dreamy cassette, warbled tape, soft drums, faded nostalgia",
    88,
    ["lo-fi", "melancholic", "2020s"],
  ),
  g(
    "Vintage Radio",
    "Internet / Aesthetic",
    "vintage radio, AM bandwidth warmth filter, crackle and hiss texture bed, old broadcast jazz or pop chord tint, nostalgic mono narrow image, dial-tuning static sweeps, living-room evening glow",
    "vintage radio, AM warmth, crackle hiss, old broadcast nostalgia",
    95,
    ["lo-fi", "1990s"],
  ),
  g(
    "Internet Nostalgia",
    "Internet / Aesthetic",
    "internet nostalgia, early web aesthetic texture layers, bitcrushed warmth harmonic bed, emotional digital memory atmosphere, dial-up handshake undertone, GeoCities MIDI chord stab accents",
    "internet nostalgia, early web aesthetic, bitcrushed warmth, digital memory",
    100,
    ["lo-fi", "melancholic", "2010s"],
  ),
  g(
    "Digital Dreamworld",
    "Internet / Aesthetic",
    "digital dreamworld, surreal synth landscape pads, glitter texture sparkle layers, floating rhythm pulse, hyper-real internet fantasy vibe, cloud-render choir washes, lucid screensaver drift",
    "digital dreamworld, surreal synths, glitter pads, internet fantasy",
    105,
    ["atmospheric", "melodic", "2020s"],
  ),

  // ── Lifestyle / Vibe ──
  g(
    "Luxury Lounge",
    "Lifestyle / Vibe",
    "luxury lounge, velvet Rhodes seventh chords, brushed jazz ride sway, upright bass pizzicato, champagne-room sub warmth, soft shaker groove, penthouse candlelight pads, understated wealth vocal space",
    "luxury lounge, Rhodes sevenths, brushed ride, upright bass, penthouse pads",
    95,
    ["smooth", "2020s"],
  ),
  g(
    "Fashion Runway",
    "Lifestyle / Vibe",
    "fashion runway, minimalist Roland drum machine click, catwalk four-on-the-floor under slick 808, glossy synth pads, model-walk tempo swagger, editorial shutter FX, monochrome couture melody pocket",
    "fashion runway, drum machine, catwalk 808, glossy pads, shutter FX",
    120,
    ["rhythmic", "2020s"],
  ),
  g(
    "Gym Phonk",
    "Lifestyle / Vibe",
    "gym phonk, pounding kick-forward phonk drums, cowbell hook stabs, distorted Memphis sub slides, military snare rolls, pre-drop silence gaps, pump-up montage aggression, alpha-edit bass weight",
    "gym phonk, cowbell, Memphis sub, military snares, pump-up drop",
    140,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Rainy Night",
    "Lifestyle / Vibe",
    "rainy night, soft Rhodes minor chords under rainstick percussion, distant thunder FX bed, deep round sub pulse, vinyl crackle haze, melancholic nylon guitar droplets, umbrella-sway slow groove",
    "rainy night, Rhodes minor, rainstick, thunder FX, vinyl crackle",
    78,
    ["lo-fi", "melancholic", "2020s"],
  ),
  g(
    "Late Night Drive",
    "Lifestyle / Vibe",
    "late night drive, neon synth lead over trap hat rolls, highway reverb tail, sliding 808 glide, dashboard glow pad wash, midnight minor chord loop, open-road melancholy pocket",
    "late night drive, neon synth, sliding 808, highway reverb, midnight chords",
    98,
    ["smooth", "atmospheric", "2020s"],
  ),
  g(
    "Sunset Vibes",
    "Lifestyle / Vibe",
    "sunset vibes, golden-hour nylon guitar arps, warm Rhodes sevenths, lazy boom-bap kick, amber pad glow, west-coast slow bounce, fading light shaker rhythm, coastal drift melody",
    "sunset vibes, nylon arps, Rhodes sevenths, amber pads, boom-bap kick",
    102,
    ["smooth", "happy", "2020s"],
  ),
  g(
    "Futuristic Lounge",
    "Lifestyle / Vibe",
    "futuristic lounge, chrome-dipped synth arps, gated luxury 808, holographic pad sheen, orbital Rhodes voicings, soft robotic hat ticks, tomorrow-city lounge pulse, diamond-cut digital warmth",
    "futuristic lounge, chrome arps, holographic pads, orbital Rhodes, gated 808",
    100,
    ["smooth", "atmospheric", "2020s"],
  ),
  g(
    "Luxury Trap",
    "Lifestyle / Vibe",
    "luxury trap, silk-string sample loop, crisp hi-end 808 sparkle, boutique minor chord voicings, cash-register coin FX, velvet bass glide, penthouse night-club swagger, branded-logo synth blips",
    "luxury trap, silk strings, crisp 808, boutique chords, velvet glide",
    138,
    ["trap", "smooth", "2020s"],
  ),
  g(
    "Viral Edit Audio",
    "Lifestyle / Vibe",
    "viral edit audio, razor-sharp hook stabs over tight trap claps, dramatic half-bar stops, impact risers, punchy 808 drops, fifteen-second clip-cut pockets, finger-snap bounce groove",
    "viral edit audio, hook stabs, trap claps, impact risers, clip-cut 808",
    130,
    ["energetic", "2020s"],
  ),
  g(
    "Sad Piano",
    "Lifestyle / Vibe",
    "sad piano, sparse felt piano arpeggios, room reverb tail, gentle string pad swells, slow four-four rimclick pulse, minor ninth voicings, tearful melody space, intimate heartbreak drift",
    "sad piano, felt arps, string swells, rimclicks, minor ninths",
    70,
    ["melancholic", "2020s"],
  ),
  g(
    "Emotional Guitar",
    "Lifestyle / Vibe",
    "emotional guitar, clean nylon fingerpicking motif, chorus-washed electric swells, soft brush snare sway, warm round bass, bittersweet major-seventh resolution, sunset confession vocal room",
    "emotional guitar, nylon picking, chorus swells, brush snare, major sevenths",
    85,
    ["melancholic", "melodic", "2020s"],
  ),
  g(
    "Ethereal Vocals",
    "Lifestyle / Vibe",
    "ethereal vocals, angelic choir pad layers, floating vocoder harmony stacks, airy reverb hall, soft sub drone bed, crystalline bell arp accents, weightless slow tempo halo, celestial topline space",
    "ethereal vocals, choir pads, vocoder stacks, reverb hall, bell arps",
    90,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Tokyo Nightlife",
    "Lifestyle / Vibe",
    "tokyo nightlife, bright city-pop synth brass, tight electronic snare pocket, funky slap bass pops, neon Shibuya chord stabs, eighties-future bounce, izakaya alley reverb, midnight train-platform energy",
    "tokyo nightlife, city-pop brass, slap bass, neon chords, Shibuya energy",
    124,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Seoul Aesthetic",
    "Lifestyle / Vibe",
    "seoul aesthetic, glossy K-pop synth plucks, skippy two-step hats, minor Rhodes stabs, chopped vocal accent chops, sleek sub slides, Gangnam night pulse, pastel chrome melody lead",
    "seoul aesthetic, K-pop plucks, two-step hats, Rhodes stabs, vocal chops",
    118,
    ["melodic", "2020s"],
  ),
  g(
    "Miami Neon",
    "Lifestyle / Vibe",
    "miami neon, tropical house marimba hook, four-on-the-floor kick under trap hats, palm-tree synth pads, coral sunset chord voicings, ocean breeze shaker groove, South Beach neon bass slide",
    "miami neon, marimba hook, tropical kick, palm pads, South Beach bass",
    112,
    ["dance", "happy", "2020s"],
  ),
  g(
    "Paris Fashion Night",
    "Lifestyle / Vibe",
    "paris fashion night, couture harp plucks over slick trap hats, champagne bubble FX, velvet bass glide, front-row minor-key melody, accordion breath sample accents, midnight couture pocket swagger",
    "paris fashion night, harp plucks, champagne FX, velvet 808, accordion accents",
    122,
    ["house", "smooth", "2020s"],
  ),
  g(
    "Desert Sunset",
    "Lifestyle / Vibe",
    "desert sunset, dusty nylon guitar licks, warm tabla percussion accents, amber pad horizon glow, slow hypnotic shaker loop, Phrygian minor chord colors, mirage reverb tail, sand-dune drift groove",
    "desert sunset, nylon licks, tabla accents, amber pads, Phrygian minor",
    88,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Rainy Cyber City",
    "Lifestyle / Vibe",
    "rainy cyber city, neon synth bass grid, holographic pad drizzle, glitch hat ticks, wet pavement reverb, dystopian minor chord loop, chrome rain FX layers, blade-runner night pulse",
    "rainy cyber city, neon bass, holographic pads, glitch hats, blade-runner pulse",
    105,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Surreal Luxury",
    "Lifestyle / Vibe",
    "surreal luxury, detuned music-box melody over velvet 808, dreamlike harp glissandos, gold-leaf brass stabs, uncanny lounge Rhodes, chandelier sparkle hats, baroque-trap aristocratic haze pocket",
    "surreal luxury, music-box, velvet 808, harp gliss, brass stabs",
    98,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Emotional Future",
    "Lifestyle / Vibe",
    "emotional future, glossy FM bell chords, tight electronic drums, warm sine sub bass, shimmering arp layers, minor ninth voicings, neon pulse bounce, vocal-forward heartbreak hooks",
    "emotional future, FM bells, electronic drums, sine sub, shimmer arps",
    128,
    ["melodic", "atmospheric", "2020s"],
  ),
  g(
    "Soft Chaos",
    "Lifestyle / Vibe",
    "soft chaos, gentle glitch percussion bursts, sidechain-warped pad swells, broken music-box motif, hazy detuned synth chords, whisper trap hats, controlled disorder pocket, bittersweet entropy melody",
    "soft chaos, glitch percussion, sidechain pads, broken music-box, whisper hats",
    115,
    ["atmospheric", "2020s"],
  ),

  // ── Internet / Gen Z / Underground ──
  g(
    "Hyperpop 2.0",
    "Internet / Gen Z / Underground",
    "hyperpop 2.0, detuned supersaw chords, bitcrushed 808 distortion, sped vocal chop stutters, maximal sidechain pump, glitter synth arp frenzy, ADHD hook chaos, candy-rave trap fusion",
    "hyperpop 2.0, supersaw, bitcrush 808, vocal chops, sidechain pump",
    165,
    ["energetic", "2020s"],
  ),
  g(
    "Krushclub",
    "Internet / Gen Z / Underground",
    "krushclub, blown-out kick saturation, industrial noise snare hits, crushed sub sine tail, warehouse distortion layers, Berlin basement pulse, concrete reverb slam, brutalist club destruction groove",
    "krushclub, blown kick, industrial snare, crushed sub, warehouse distortion",
    155,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Webcore",
    "Internet / Gen Z / Underground",
    "webcore, dial-up modem scrape texture, GeoCities MIDI chord stab, early GIF-era synth blips, homepage guestbook 808 bounce, hyperlinked percussion clicks, hypertext nostalgia pocket groove",
    "webcore, modem scrape, MIDI stab, GIF synth, homepage 808",
    120,
    ["lo-fi", "melancholic", "2010s"],
  ),
  g(
    "Cybercore",
    "Internet / Gen Z / Underground",
    "cybercore, laser-grid synth bass, orbital pad atmospheres, robotic vocoder chant pockets, ion-drive kick pattern, space-station corridor reverb, tomorrow-city hi-tech percussion grid",
    "cybercore, laser bass, orbital pads, vocoder chant, ion-drive kick",
    150,
    ["aggressive", "dark", "2020s"],
  ),
  g(
    "Scene Revival",
    "Internet / Gen Z / Underground",
    "scene revival, distorted power-chord guitar stabs, double-kick blast accents, emo scream vocal space, breakdown half-time trap drop, MySpace-era synth lead, mall-goth energy pocket",
    "scene revival, power chords, double kick, emo scream, trap breakdown",
    140,
    ["energetic", "melodic", "2010s"],
  ),
  g(
    "Emo Electronic",
    "Internet / Gen Z / Underground",
    "emo electronic, minor piano chord loop, sidechain synth pad pump, trap hat rolls under four-on-floor kick, heart-on-sleeve melody lead, glitch tear-drop FX, bedroom catharsis bounce",
    "emo electronic, minor piano, sidechain pads, trap hats, glitch tears",
    128,
    ["melancholic", "energetic", "2020s"],
  ),
  g(
    "Hypertrap",
    "Internet / Gen Z / Underground",
    "hypertrap, machine-gun hi-hat bursts at double tempo, squealing rage synth lead, distorted 808 chaos, moshing trap drums, ear-splitting drop impact, sped adrenaline hook frenzy",
    "hypertrap, machine-gun hats, rage synth, distorted 808, mosh drums",
    150,
    ["trap", "aggressive", "2020s"],
  ),
  g(
    "Hyperrage",
    "Internet / Gen Z / Underground",
    "hyperrage, ear-splitting rage synth squeal, moshpit trap drum pattern, crowd-noise layer bed, sub-destroyer 808 tail, pre-drop silence choke, edit aggression chaos, machine-gun percussion bursts",
    "hyperrage, rage synth squeal, moshpit drums, crowd noise, sub-destroyer 808",
    155,
    ["trap", "aggressive", "2020s"],
  ),
  g(
    "Terror Plugg",
    "Internet / Gen Z / Underground",
    "terror plugg, detuned bell pluck loop, blown 808 sub rumble, horror-movie sting FX, creepy nursery-rhyme motif, lo-fi tape warble hats, unsettling pluggnb pocket, basement dread bounce",
    "terror plugg, detuned bells, blown 808, horror sting, nursery motif",
    145,
    ["dark", "trap", "2020s"],
  ),
  g(
    "Diary Plugg",
    "Internet / Gen Z / Underground",
    "diary plugg, soft bell pluck melody, bedroom 808 warmth, diary-page flip FX, whispered vocal space, rainy-window pad wash, intimate pluggnb sway, confessional minor chord loop",
    "diary plugg, bell plucks, bedroom 808, diary FX, rainy pads",
    130,
    ["melancholic", "trap", "2020s"],
  ),
  g(
    "Ambient Plugg",
    "Internet / Gen Z / Underground",
    "ambient plugg, floating bell pad drones, submerged 808 pulse, reverb-soaked pluck echoes, nocturnal pluggnb drift, sparse hat whispers, dream-state bass warmth, liminal bedroom haze",
    "ambient plugg, bell drones, submerged 808, reverb plucks, liminal haze",
    125,
    ["atmospheric", "trap", "2020s"],
  ),
  g(
    "Dark Plugg",
    "Internet / Gen Z / Underground",
    "dark plugg, minor bell pluck motif, shadowed 808 sub slides, noir pad undercurrent, late-night pluggnb pocket, muted trap hat ticks, candlelit basement melancholy, velvet dread groove",
    "dark plugg, minor bells, shadow 808, noir pads, basement melancholy",
    138,
    ["dark", "trap", "2020s"],
  ),
  g(
    "Balloon Plugg",
    "Internet / Gen Z / Underground",
    "balloon plugg, bouncy detuned bell lead, helium-pitched vocal feel, playful 808 bounce, circus-tent synth blips, candy-colored chord stabs, whimsical pluggnb pocket, cartoon energy sway",
    "balloon plugg, bouncy bells, helium vocals, playful 808, circus synth",
    132,
    ["trap", "energetic", "2020s"],
  ),
  g(
    "Jerk",
    "Internet / Gen Z / Underground",
    "jerk, off-kilter clap pattern, jerky stop-start drum fills, detuned synth stab hooks, Memphis sample chop accents, bounce-heavy 808 slides, viral dance-move pocket, staccato groove fractures",
    "jerk, off-kilter claps, stop-start fills, detuned stabs, Memphis chop",
    142,
    ["rhythmic", "energetic", "2020s"],
  ),
  g(
    "Glo",
    "Internet / Gen Z / Underground",
    "glo, murky sub-bass drone, dusty vinyl crackle bed, minimal snare crack, hazy minor synth pad fog, Chicago drill-adjacent hat rolls, street-corner numb pocket, smoked-out late-night sway",
    "glo, murky sub, vinyl crackle, minor pads, drill hats",
    135,
    ["atmospheric", "trap", "2020s"],
  ),
  g(
    "Ragewave",
    "Internet / Gen Z / Underground",
    "ragewave, distorted supersaw rage lead, warehouse kick slam, sidechain pump drops every bar, industrial noise percussion, moshpit edit aggression, fluorescent rage synth chaos, basement destruction pulse",
    "ragewave, rage supersaw, warehouse kick, sidechain pump, industrial percussion",
    148,
    ["trap", "dark", "2020s"],
  ),
  g(
    "Hyperdrill",
    "Internet / Gen Z / Underground",
    "hyperdrill, sliding 808 glides at double tempo, rapid triplet hi-hat rolls, dark minor piano stabs, UK drill slide pattern sped, menacing sub weight, hyper-aggressive street pocket",
    "hyperdrill, sliding 808, triplet hats, minor piano, UK drill slide",
    152,
    ["trap", "aggressive", "2020s"],
  ),
  g(
    "Trap Metal",
    "Internet / Gen Z / Underground",
    "trap metal, distorted guitar power-chord riffs, blast-beat trap hybrid drums, screaming vocal space, breakdown half-time 808 drop, mosh-pit aggression layers, industrial metal-trap crossover pocket",
    "trap metal, guitar riffs, blast-beat drums, scream vocals, half-time 808",
    145,
    ["aggressive", "rock", "2020s"],
  ),
  g(
    "Drainwave",
    "Internet / Gen Z / Underground",
    "drainwave, blown-out lo-fi compression, murky detuned synth wash, submerged 808 rumble, drain-gang aesthetic hiss, numb minor chord fog, basement tape degradation, dissociative slow sway",
    "drainwave, lo-fi compression, detuned wash, submerged 808, tape hiss",
    130,
    ["dark", "melancholic", "2020s"],
  ),
  g(
    "Sadboy Aesthetic",
    "Internet / Gen Z / Underground",
    "sadboy aesthetic, emo guitar arpeggio loop, trap hat rolls under soft kick, heartbreak minor piano, autotune vocal space, bedroom reverb haze, Tumblr-era melancholy pocket, tear-stained bounce",
    "sadboy aesthetic, emo guitar, trap hats, minor piano, autotune space",
    128,
    ["melancholic", "trap", "2010s"],
  ),
  g(
    "Doomtrap",
    "Internet / Gen Z / Underground",
    "doomtrap, downtuned guitar drone under trap 808, funeral-doom tempo half-time, ominous church organ swells, apocalyptic snare cracks, end-times bass weight, catastrophic minor chord descent",
    "doomtrap, downtuned guitar, half-time 808, church organ, apocalyptic snare",
    130,
    ["dark", "trap", "2020s"],
  ),
  g(
    "Digital Punk",
    "Internet / Gen Z / Underground",
    "digital punk, bitcrushed power-chord synth stabs, punk drum velocity bursts, glitch bass distortion, cyber riot vocal shout space, anti-corporate noise layers, hacked-system rebellion pocket",
    "digital punk, bitcrush chords, punk drums, glitch bass, riot vocals",
    160,
    ["aggressive", "energetic", "2020s"],
  ),

  // ── TikTok / Viral / Edit ──
  g(
    "Drift Phonk",
    "TikTok / Viral / Edit",
    "drift phonk, drifting cowbell melody over sliding 808 glide, tire-screech FX layers, night highway trap groove, Brazilian phonk swing, car edit energy, smoky bass weight",
    "drift phonk, cowbell glide, 808 slides, tire screech, car edit",
    130,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Edit Audio",
    "TikTok / Viral / Edit",
    "edit audio, razor-sharp hook stabs over tight trap claps, dramatic half-bar stops for meme edits, impact risers, punchy 808 drops built for fifteen-second clip cuts",
    "edit audio, hook stabs, trap claps, impact risers, clip cuts",
    132,
    ["energetic", "2020s"],
  ),
  g(
    "TikTok Sad Edit",
    "TikTok / Viral / Edit",
    "tiktok sad edit, time-stretched vocal texture, cathedral reverb wash over deep 808 pulse, vinyl crackle bed, mournful piano droplets, dreamy half-speed heartbreak edit groove",
    "tiktok sad edit, stretched vocals, deep 808, vinyl piano, heartbreak",
    85,
    ["melancholic", "2020s"],
  ),
  g(
    "Viral Speed Up",
    "TikTok / Viral / Edit",
    "viral speed up, sped-up pitched vocal feel, bright supersaw chords, fast hi-hat rolls at rave tempo, trance-pop trap fusion, euphoric chip-tune arp layer, instant recall hook",
    "viral speed up, pitched vocals, supersaw, fast hats, chip arp",
    145,
    ["energetic", "melodic", "2020s"],
  ),
  g(
    "Slowed + Reverb",
    "TikTok / Viral / Edit",
    "slowed + reverb, time-stretched vocal texture, cathedral reverb wash over deep 808 pulse, vinyl crackle bed, mournful piano droplets, dreamy half-speed heartbreak edit groove",
    "slowed reverb, stretched vocals, cathedral wash, deep 808, vinyl piano",
    70,
    ["melancholic", "atmospheric", "2020s"],
  ),
  g(
    "Nightcore",
    "TikTok / Viral / Edit",
    "nightcore, sped-up pitched vocal feel, bright supersaw chords, fast hi-hat rolls at rave tempo, trance-pop fusion, anime adrenaline rush, euphoric chip-tune arp layer",
    "nightcore, pitched vocals, supersaw, fast hats, chip arp",
    175,
    ["energetic", "melodic", "2010s"],
  ),
  g(
    "Atmospheric Trap",
    "TikTok / Viral / Edit",
    "atmospheric trap, wide reverb synth pad washes, sparse rimclick drums, deep round sub, silver pad glow, whispered minor romance, nocturnal slow sway, cinematic trap pocket",
    "atmospheric trap, reverb pads, rimclicks, round sub, nocturnal sway",
    130,
    ["atmospheric", "trap", "2020s"],
  ),
  g(
    "Sigma Edit Music",
    "TikTok / Viral / Edit",
    "sigma edit music, distorted cowbell lead, Memphis sub slides, military snare rolls, motivational hard-trap drums, gym montage swagger, alpha-edit phonk undertones, chant-ready hook pockets",
    "sigma edit, cowbell, Memphis sub, military snares, gym phonk",
    135,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Drift House",
    "TikTok / Viral / Edit",
    "drift house, four-on-the-floor kick under cowbell hook, phonk-meets-house bass slide, night-drive synth pads, tire-screech FX accents, highway edit energy, smoky club-phonk crossover",
    "drift house, four-on-floor, cowbell hook, phonk bass, highway pads",
    128,
    ["dance", "aggressive", "2020s"],
  ),
  g(
    "Aggressive Bass",
    "TikTok / Viral / Edit",
    "aggressive bass, sub-destroyer sine 808 tail, clipped low-end saturation, meme-edit loud kick thump, distorted bass wobble, ear-rattling sub octaves, minimal midrange pocket",
    "aggressive bass, saturated 808, sub wobble, loud kick, clipped low-end",
    140,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Moshpit Rage",
    "TikTok / Viral / Edit",
    "moshpit rage, squealing rage synth lead, moshing trap drums, crowd noise layers, distorted 808 chaos, mosh-pit edit aggression, machine-gun hi-hat bursts, ear-splitting drop impact",
    "moshpit rage, rage synth, crowd noise, distorted 808, machine-gun hats",
    150,
    ["aggressive", "trap", "2020s"],
  ),
  g(
    "Midnight Drive",
    "TikTok / Viral / Edit",
    "midnight drive, neon synth lead over trap hat rolls, highway reverb tail, sliding 808 glide, dashboard glow pad wash, midnight minor chord loop, open-road melancholy pocket",
    "midnight drive, neon synth, sliding 808, highway reverb, dashboard pads",
    105,
    ["atmospheric", "dark", "2020s"],
  ),
  g(
    "Anime Edit Core",
    "TikTok / Viral / Edit",
    "anime edit core, emotional minor piano chords, orchestral string swells over trap hats, J-rock guitar flick accents, dramatic AMV build, supersaw drop release, bittersweet melody lead",
    "anime edit core, piano strings, trap hats, J-rock guitar, AMV build",
    140,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Cinematic Edit Audio",
    "TikTok / Viral / Edit",
    "cinematic edit audio, taiko drum hits blended with trap 808, brass fanfare stabs, trailer whoosh transitions, epic strings under mumbled rap pocket, movie recap crescendo energy",
    "cinematic edit, taiko drums, brass stabs, trailer whoosh, epic strings",
    110,
    ["dark", "energetic", "2020s"],
  ),
  g(
    "Bass Boosted",
    "TikTok / Viral / Edit",
    "bass boosted, sub-destroyer sine 808 tail, clipped low-end saturation, loud kick thump, distorted bass wobble, ear-rattling sub octaves, minimal midrange pocket, meme-edit loudness",
    "bass boosted, saturated 808, sub wobble, loud kick, clipped low-end",
    128,
    ["aggressive", "2020s"],
  ),
  g(
    "VHS Nostalgia",
    "TikTok / Viral / Edit",
    "vhs nostalgia, magnetic tape wow-flutter drums, warm CRT hiss layer, tracking-line wobble bass, Blockbuster-era chord sample, degraded tracking-head 808, home-video nostalgic pocket",
    "VHS nostalgia, tape wow-flutter, CRT hiss, tracking wobble, home-video 808",
    95,
    ["lo-fi", "melancholic", "1990s"],
  ),
  g(
    "2000s Internet",
    "TikTok / Viral / Edit",
    "2000s internet, AIM doorbell sample hook, dial-up handshake intro texture, MySpace glitter synth arp, LAN-party 808 bounce, pixel-art melody lead, forum nostalgia pocket",
    "2000s internet, AIM bell, dial-up, MySpace arp, LAN-party 808",
    108,
    ["melodic", "2000s"],
  ),

  // ── Global / Rising ──
  g(
    "Drum & Bass Revival",
    "Global / Rising",
    "drum & bass revival, amen break chop pattern, Reese bass wobble, rapid two-step snare rolls, rave pad stabs, 174 BPM jungle energy, modern DnB edit crossover, sub-rattler drop",
    "drum bass revival, amen break, Reese bass, two-step snare, rave pads",
    174,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Jungle Revival",
    "Global / Rising",
    "jungle revival, ragga toast vocal chops, chopped breakbeat layers, sub-bass Reese wobble, dub siren FX, 160 BPM ragga-jungle swing, warehouse revival energy, amen chop frenzy",
    "jungle revival, ragga chops, breakbeat layers, Reese wobble, dub siren",
    172,
    ["dance", "aggressive", "2020s"],
  ),
  g(
    "Melodic Techno",
    "Global / Rising",
    "melodic techno, hypnotic arp sequence loop, four-on-the-floor kick drive, warm analog pad swells, minor melodic hook lead, Berlin afterhours pulse, euphoric breakdown release",
    "melodic techno, arp loop, four-on-floor, analog pads, Berlin pulse",
    124,
    ["dance", "melodic", "2020s"],
  ),
  g(
    "Hard Groove",
    "Global / Rising",
    "hard groove, punchy four-on-the-floor kick, funky acid-tinged bass line, disco clap pattern, soul chord stabs, neon club pulse, dancefloor bounce, vocoder topline space",
    "hard groove, four-on-floor, acid bass, disco claps, soul stabs",
    135,
    ["dance", "aggressive", "2020s"],
  ),
  g(
    "Trance Revival",
    "Global / Rising",
    "trance revival, supersaw chord stacks, rolling bassline drive, gated reverb snare lift, uplifting major progression, 138 BPM euphoric build, hands-up breakdown, rave nostalgia lead",
    "trance revival, supersaw stacks, rolling bass, gated snare, euphoric build",
    140,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Future Garage",
    "Global / Rising",
    "future garage, skippy two-step drums, chopped vocal texture stabs, warm sub bass slides, shuffled percussion swing, UK garage chord stabs, late-night urban pulse, intimate vocal chop space",
    "future garage, two-step drums, vocal chops, sub slides, UK chords",
    130,
    ["dance", "melancholic", "2020s"],
  ),
  g(
    "Latin Trap",
    "Global / Rising",
    "latin trap, dembow rhythm pattern, reggaeton kick bounce, minor brass stab accents, tropical percussion layers, Spanish vocal chant space, club-ready 808 slides, Caribbean night energy",
    "latin trap, dembow rhythm, reggaeton kick, brass stabs, tropical percussion",
    95,
    ["latin", "trap", "2020s"],
  ),
  g(
    "Corridos Tumbados",
    "Global / Rising",
    "corridos tumbados, nylon guitar arpeggio loop, tuba bass line accents, trap hat rolls under corrido rhythm, melancholic minor melody, Mexican regional autotune space, tumbado 808 bounce",
    "corridos tumbados, nylon guitar, tuba bass, trap hats, regional autotune",
    88,
    ["latin", "melancholic", "2020s"],
  ),
  g(
    "City Pop Revival",
    "Global / Rising",
    "city pop revival, bright synth brass stabs, funky slap bass pops, glossy electric piano chords, four-on-the-floor groove, eighties Japanese sunset melody, coastal cruise bounce",
    "city pop revival, synth brass, slap bass, electric piano, sunset melody",
    110,
    ["smooth", "melodic", "1980s"],
  ),

  // ── Aesthetic / Mood ──
  g(
    "Nostalgic Future",
    "Aesthetic / Mood",
    "nostalgic future, AI-smoothed tape hiss, synthetic memory-loop piano, fake-vintage vinyl crackle bed, algorithmic sunset chord progression, simulated childhood 808 warmth, fabricated yesterday pocket",
    "nostalgic future, tape hiss, memory piano, vinyl crackle, sunset chords",
    115,
    ["melodic", "atmospheric", "2020s"],
  ),
  g(
    "Dreamwave",
    "Aesthetic / Mood",
    "dreamwave, analog synth wave chords, slow four-four groove, chorus Rhodes, liquid bass glide, retro drum machine ticks, dreamy pad layers, intimate late-night sway",
    "dreamwave, synth wave, chorus Rhodes, liquid bass, dreamy pads",
    90,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Ocean Ambient",
    "Aesthetic / Mood",
    "ocean ambient, wide chorus-pad tides, gentle surf percussion, rolling sub bass waves, suspended chord swells, breezy nylon picking, tranquil tidal groove, coastal drift atmosphere",
    "ocean ambient, chorus pads, surf percussion, rolling sub, suspended chords",
    68,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Underground Tunnel",
    "Aesthetic / Mood",
    "underground tunnel, damp concrete reverb tail, distant train-rumble sub drone, sparse echo percussion, flickering fluorescent hum pad, claustrophobic minor chord loop, subway passage drift",
    "underground tunnel, concrete reverb, train rumble, echo percussion, fluorescent hum",
    80,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Neon City",
    "Aesthetic / Mood",
    "neon city, bright synth brass stabs, gated reverb snare, purple neon chord glow, funky slap bass pops, city-night pulse, eighties-future bounce, electric avenue energy",
    "neon city, synth brass, gated snare, neon chords, slap bass",
    118,
    ["dance", "atmospheric", "2020s"],
  ),
  g(
    "Seoul Nightlife",
    "Aesthetic / Mood",
    "seoul nightlife, glossy K-pop synth plucks, skippy two-step hats, minor Rhodes stabs, chopped vocal accent chops, sleek sub slides, Gangnam night pulse, pastel chrome melody lead",
    "seoul nightlife, K-pop plucks, two-step hats, Rhodes stabs, Gangnam pulse",
    120,
    ["dance", "smooth", "2020s"],
  ),
  g(
    "Fashion Week Soundtrack",
    "Aesthetic / Mood",
    "fashion week soundtrack, couture harp plucks over slick trap hats, champagne bubble FX, velvet bass glide, front-row minor-key melody, editorial camera-shutter FX, curator-approved pocket",
    "fashion week, harp plucks, champagne FX, velvet 808, shutter FX",
    122,
    ["rhythmic", "smooth", "2020s"],
  ),
  g(
    "Cyber Y2K",
    "Aesthetic / Mood",
    "cyber Y2K, translucent plastic synth chords, frosted-glass digital bell lead, flip-phone notification blips, frosted chrome 808, futuristic 2000s revival pocket, glossy cyber sparkle hats",
    "cyber Y2K, plastic synth, digital bells, flip-phone FX, chrome 808",
    112,
    ["melodic", "2000s"],
  ),
  g(
    "VHS Dream",
    "Aesthetic / Mood",
    "vhs dream, magnetic tape wow-flutter drums, warm CRT hiss layer, tracking-line wobble bass, dreamcore chord haze, degraded tracking-head 808, liminal home-video nostalgic pocket",
    "VHS dream, tape wow-flutter, CRT hiss, tracking wobble, liminal 808",
    88,
    ["lo-fi", "melancholic", "1990s"],
  ),
  g(
    "Digital Nostalgia",
    "Aesthetic / Mood",
    "digital nostalgia, dial-up modem scrape texture, GeoCities MIDI chord stab, early GIF-era synth blips, homepage guestbook 808 bounce, hyperlinked percussion clicks, hypertext pocket groove",
    "digital nostalgia, modem scrape, MIDI stab, GIF synth, homepage 808",
    102,
    ["lo-fi", "melancholic", "2010s"],
  ),
  g(
    "Artificial Nostalgia",
    "Aesthetic / Mood",
    "artificial nostalgia, AI-smoothed tape hiss, synthetic memory-loop piano, fake-vintage vinyl crackle bed, algorithmic sunset chord progression, simulated childhood warmth, fabricated yesterday pocket",
    "artificial nostalgia, AI tape hiss, memory piano, vinyl crackle, sunset chords",
    100,
    ["atmospheric", "melancholic", "2020s"],
  ),
  g(
    "Internet Dreamscape",
    "Aesthetic / Mood",
    "internet dreamscape, cloud-render synth choir, sleep-mode soft 808 pulse, screensaver fractal arp layers, lucid pixel-dream melody, floating notification chime accents, reverie trap pocket",
    "internet dreamscape, synth choir, fractal arp, lucid melody, notification chimes",
    105,
    ["atmospheric", "melodic", "2020s"],
  ),

  // ── Creator / Playlist ──
  g(
    "Sleep Ambient",
    "Creator / Playlist",
    "sleep ambient, soft drone pad layers, barely audible pulse texture, delta-wave sub hum, no percussion, lullaby music-box motif, weightless slow tempo, deep REM drift atmosphere",
    "sleep ambient, drone pads, pulse texture, delta hum, music-box motif",
    50,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Meditation Soundscape",
    "Creator / Playlist",
    "meditation soundscape, singing bowl resonance tones, gentle bamboo flute breath, slow pad swells, Tibetan bell accents, breath-synced rhythm space, mindful silence pockets, zen garden calm",
    "meditation soundscape, singing bowl, bamboo flute, pad swells, Tibetan bells",
    55,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Piano Atmosphere",
    "Creator / Playlist",
    "piano atmosphere, sparse felt piano arpeggios, room reverb tail, gentle string pad swells, slow four-four pulse, suspended minor voicings, contemplative melody drift, intimate stillness",
    "piano atmosphere, felt arps, string swells, suspended minor, stillness",
    72,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "Coffee Shop Lo-Fi",
    "Creator / Playlist",
    "coffee shop lo-fi, dusty vinyl crackle bed, mellow Rhodes loop, lazy boom-bap kick, brushed snare sway, warm round bass, espresso-steam pad haze, study-session pocket groove",
    "coffee shop lo-fi, vinyl crackle, Rhodes loop, boom-bap kick, espresso pads",
    80,
    ["lo-fi", "jazz", "smooth", "2020s"],
  ),
  g(
    "Focus Music",
    "Creator / Playlist",
    "focus music, minimal marimba motif loop, soft pulse kick at low volume, neutral major chord bed, white-noise texture layer, steady four-four tick, distraction-free concentration pocket",
    "focus music, marimba motif, soft pulse kick, major chord bed, white noise",
    85,
    ["smooth", "2020s"],
  ),
  g(
    "Deep Focus",
    "Creator / Playlist",
    "deep focus, binaural drone pad layers, subliminal pulse texture, no melodic distraction, brown-noise bed, ultra-slow tempo drift, flow-state concentration atmosphere, cognitive tunnel groove",
    "deep focus, binaural drones, pulse texture, brown noise, flow-state",
    78,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Spa Ambient",
    "Creator / Playlist",
    "spa ambient, crystal singing bowl tones, gentle water-drop percussion, warm pad swells, bamboo flute breath accents, eucalyptus steam atmosphere, slow breath-synced pulse, wellness sanctuary calm",
    "spa ambient, singing bowl, water drops, bamboo flute, wellness calm",
    60,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Cozy Rain",
    "Creator / Playlist",
    "cozy rain, rainstick percussion bed, soft Rhodes minor chords, fireplace crackle FX layer, warm blanket sub pulse, hearth-side shaker groove, hygge comfort atmosphere, rainy-window pad wash",
    "cozy rain, rainstick, Rhodes minor, fireplace crackle, hygge pads",
    75,
    ["lo-fi", "melancholic", "2020s"],
  ),
  g(
    "Fireplace Lo-Fi",
    "Creator / Playlist",
    "fireplace lo-fi, crackling fire sample texture, mellow upright bass, lazy jazz brush snare, warm Rhodes sevenths, amber pad glow, winter-evening study pocket, hearth-side vinyl haze",
    "fireplace lo-fi, fire crackle, upright bass, brush snare, amber pads",
    78,
    ["lo-fi", "smooth", "2020s"],
  ),
  g(
    "Reading Music",
    "Creator / Playlist",
    "reading music, gentle nylon guitar arpeggios, soft string pad swells, barely-there kick pulse, major-seventh chord warmth, page-turn whisper FX, library-quiet concentration atmosphere",
    "reading music, nylon arps, string swells, major sevenths, library quiet",
    70,
    ["smooth", "melodic", "2020s"],
  ),
  g(
    "Coding Music",
    "Creator / Playlist",
    "coding music, steady electronic tick groove, neutral synth pad bed, subtle arp sequence loop, low-distraction minor chords, terminal-glow atmosphere, keyboard-click percussion accents, flow-state pocket",
    "coding music, electronic tick, synth pad bed, arp loop, terminal glow",
    88,
    ["smooth", "2020s"],
  ),
  g(
    "Chill Gaming",
    "Creator / Playlist",
    "chill gaming, retro console menu pad loop, soft 808 pulse, controller-button click hats, loading-screen orchestral stab, memory-card chime melody, gaming-lounge relaxed pocket groove",
    "chill gaming, menu pads, soft 808, controller clicks, chime melody",
    95,
    ["smooth", "2020s"],
  ),

  // ── Underground Artist 2026 ──
  g(
    "Opium",
    "Underground Artist 2026",
    "opium, dark luxury trap, mahogany Rhodes minor chords, noir saxophone breath samples, shadowed velvet sub, late-night penthouse rain FX, black-tie ominous trap pocket, candlelit melancholy",
    "opium, minor Rhodes, noir sax, velvet sub, penthouse rain",
    145,
    ["dark", "trap", "2020s"],
  ),
  g(
    "Underground Rage",
    "Underground Artist 2026",
    "underground rage, blown-out warehouse kick, industrial noise snare hits, crushed sub sine tail, basement distortion layers, concrete reverb slam, brutalist destruction groove, moshpit aggression",
    "underground rage, warehouse kick, industrial snare, crushed sub, concrete reverb",
    152,
    ["trap", "aggressive", "2020s"],
  ),
  g(
    "Fashion Trap",
    "Underground Artist 2026",
    "fashion trap, couture harp plucks over slick trap hats, champagne bubble FX, velvet bass glide, runway minor-key melody, designer-logo synth blips, exclusive night-club swagger pocket",
    "fashion trap, harp plucks, champagne FX, velvet 808, runway melody",
    140,
    ["trap", "dark", "2020s"],
  ),
  g(
    "Dark Fashion",
    "Underground Artist 2026",
    "dark fashion, noir harp clusters, shadowed velvet 808 sustain, black-tie brass stabs, editorial shutter trap hats, gothic couture minor chords, midnight runway dread pocket",
    "dark fashion, noir harp, velvet 808, gothic chords, runway dread",
    135,
    ["dark", "trap", "2020s"],
  ),
  g(
    "Avant Pop",
    "Underground Artist 2026",
    "avant pop, prepared piano clangs, aleatoric percussion clusters, dissonant harp over sub pulse, gallery-installation spatial delays, unconventional bar lengths, experimental pop rhythmic fractures",
    "avant pop, prepared piano, aleatoric percussion, dissonant harp, experimental bars",
    118,
    ["melodic", "2020s"],
  ),
  g(
    "Experimental Pop",
    "Underground Artist 2026",
    "experimental pop, granular vocal texture chops, unconventional synth timbres, polymetric drum patterns, microtonal chord colors, art-pop hook subversion, gallery-ready sonic collage pocket",
    "experimental pop, granular vocals, microtonal chords, polymetric drums, art-pop",
    120,
    ["melodic", "2020s"],
  ),
  g(
    "Indie Sleaze Revival",
    "Underground Artist 2026",
    "indie sleaze revival, dirty garage guitar fuzz, blown-out drum room, party-rock bass drive, reckless energy stomp, 2010s indie sleaze chord stabs, basement house-party bounce",
    "indie sleaze revival, garage fuzz, blown drums, party bass, basement bounce",
    128,
    ["energetic", "rock", "2010s"],
  ),
  g(
    "Neo Soul Future",
    "Underground Artist 2026",
    "neo soul future, glossy FM bell chords, tight electronic drums, warm sine sub bass, shimmering arp layers, minor ninth voicings, neon pulse bounce, vocal-forward soul hooks",
    "neo soul future, FM bells, electronic drums, sine sub, shimmer arps",
    92,
    ["r&b/soul", "smooth", "2020s"],
  ),
  g(
    "Sad R&B",
    "Underground Artist 2026",
    "sad r&b, soft piano arpeggios, sparse rimclick drums, deep round sub, silver synth pad glow, whispered minor romance, nocturnal slow sway, tear-stained vocal space",
    "sad r&b, piano arps, rimclicks, round sub, minor romance",
    85,
    ["r&b/soul", "melancholic", "2020s"],
  ),
  g(
    "Atmospheric R&B",
    "Underground Artist 2026",
    "atmospheric r&b, wide reverb synth washes, airy choir pads, soft rimshot groove, suspended minor chords, slow tempo drift, floating topline halo, sleepwalk bounce",
    "atmospheric r&b, reverb washes, choir pads, suspended chords, slow drift",
    88,
    ["r&b/soul", "atmospheric", "2020s"],
  ),
  g(
    "Futuristic Soul",
    "Underground Artist 2026",
    "futuristic soul, glossy FM bell chords, tight electronic drums, warm sine sub bass, shimmering arp layers, minor ninth voicings, neon pulse bounce, vocal-forward hooks",
    "futuristic soul, FM bells, electronic drums, sine sub, minor ninths",
    95,
    ["r&b/soul", "melodic", "2020s"],
  ),
  g(
    "Shoegaze Revival",
    "Underground Artist 2026",
    "shoegaze revival, wall-of-sound guitar wash, blown-out reverb drums, buried vocal melody haze, dreamy major chord fog, tremolo pick layers, MBV-inspired texture swirl, slow tidal sway",
    "shoegaze revival, guitar wash, reverb drums, tremolo picks, MBV texture",
    112,
    ["atmospheric", "rock", "2020s"],
  ),
  g(
    "Alternative Indie",
    "Underground Artist 2026",
    "alternative indie, jangly clean guitar arpeggios, organic live drum pocket, melodic bass line, bittersweet major-minor chord shifts, bedroom-studio warmth, introspective vocal-forward hook space",
    "alternative indie, jangly guitar, live drums, melodic bass, bittersweet chords",
    120,
    ["melodic", "2020s"],
  ),
  g(
    "Psychedelic Trap",
    "Underground Artist 2026",
    "psychedelic trap, trippy phaser synth swirls, reversed 808 tail, sitar-tinted melody accents, hallucinogenic pad layers, warped vocal chant space, mind-bend trap hat rolls, cosmic sub drift",
    "psychedelic trap, phaser synths, reversed 808, sitar accents, cosmic sub",
    135,
    ["trap", "atmospheric", "2020s"],
  ),
  ...LATIN_WORLD_GENRES,
  ...WORLD_WAVE2_GENRES,
  ...WORLD_WAVE3_GENRES,
  ...HIP_HOP_SOUL_GENRES,
];

export const EXTENDED_GENRE_VALUES = new Set(EXTENDED_GENRES.map((x) => x.value));

export function extendedGenrePromptMap(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const item of EXTENDED_GENRES) out[item.value] = item.prompt;
  return out;
}

export function extendedGenreAceTagMap(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const item of EXTENDED_GENRES) out[item.value] = item.aceTags;
  return out;
}

export function extendedGenreBpmMap(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const item of EXTENDED_GENRES) out[item.value] = item.bpm;
  return out;
}

export function extendedGenreSonautoMap(): Record<string, string[]> {
  const out: Record<string, string[]> = {};
  for (const item of EXTENDED_GENRES) out[item.value] = item.sonautoTags;
  return out;
}

export function extendedGenreDropdownOptions(): { group: string; value: string; label: string }[] {
  return EXTENDED_GENRES.map((item) => ({
    group: item.group,
    value: item.value,
    label: item.label ?? item.value,
  }));
}
