/** Extended genre catalog — prompts, BPM hints, ACE tags, Sonauto tags. */
import { HIP_HOP_SOUL_GENRES } from "@/lib/genres/hipHopSoulCatalog";

export type ExtendedGenreDef = {
  value: string;
  label?: string;
  group: string;
  prompt: string;
  aceTags: string;
  bpm: number;
  sonautoTags: string[];
};

function g(
  value: string,
  group: string,
  prompt: string,
  aceTags: string,
  bpm: number,
  sonautoTags: string[] = ["2020s", "instrumental"],
): ExtendedGenreDef {
  return { value, group, prompt, aceTags, bpm, sonautoTags };
}

export const EXTENDED_GENRES: ExtendedGenreDef[] = [
  // ── DnB / Breaks ──
  g(
    "Liquid DnB",
    "DnB / Breaks",
    "liquid drum and bass, smooth rolling breakbeats, warm sub bass, lush pads, melodic liquid atmosphere, polished modern mix",
    "liquid dnb, drum and bass, melodic, smooth rolling breaks, warm sub",
    174,
    ["dance", "melodic", "smooth", "2020s"],
  ),
  g(
    "Jungle",
    "DnB / Breaks",
    "jungle, classic breakbeat science, chopped amen breaks, heavy sub bass, ragga vocal chops as texture, raw UK rave energy",
    "jungle, breakbeats, amen breaks, sub bass, UK rave energy",
    170,
    ["dance", "rhythmic", "aggressive", "1990s"],
  ),
  g(
    "Breakcore",
    "DnB / Breaks",
    "breakcore, extreme chopped breakbeats, distorted bass, chaotic edits, high BPM intensity, experimental hardcore energy",
    "breakcore, extreme breakbeats, distorted bass, chaotic edits, high energy",
    180,
    ["dance", "aggressive", "experimental", "2020s"],
  ),

  // ── Electronic / Club ──
  g(
    "Future Bass",
    "Electronic / Club",
    "future bass, bright supersaw chords, sidechain pump, emotional topline space, crisp modern drums, festival polish",
    "future bass, supersaw chords, sidechain, emotional, festival polish",
    150,
    ["dance", "melodic", "energetic", "2020s"],
  ),
  g(
    "Melodic Dubstep",
    "Electronic / Club",
    "melodic dubstep, emotional chord progression, soft sidechain, tasteful wobble bass, half-time drums, cinematic drops",
    "melodic dubstep, emotional chords, half-time drums, wobble bass, cinematic",
    140,
    ["dance", "melodic", "dark", "2020s"],
  ),
  g(
    "EDM Festival",
    "Electronic / Club",
    "EDM festival anthem, big room chords, massive build-ups and drops, sidechain pump, crowd-ready energy, wide mix",
    "EDM festival, big room, build-ups and drops, sidechain, crowd energy",
    128,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Tech House",
    "Electronic / Club",
    "tech house, driving four-on-the-floor kick, hypnotic bass groove, minimal percussion, club-focused energy, clean modern mix",
    "tech house, four-on-the-floor, hypnotic bass, minimal percussion, club",
    126,
    ["house", "dance", "rhythmic", "2020s"],
  ),
  g(
    "Minimal Techno",
    "Electronic / Club",
    "minimal techno, stripped hypnotic groove, tight kick, subtle hi-hats, evolving textures, warehouse atmosphere",
    "minimal techno, hypnotic groove, stripped drums, warehouse vibe",
    124,
    ["dance", "hypnotic", "dark", "2020s"],
  ),
  g(
    "Hard Techno",
    "Electronic / Club",
    "hard techno, pounding kick, industrial textures, relentless energy, dark warehouse rave, aggressive modern mix",
    "hard techno, pounding kick, industrial, relentless rave energy",
    145,
    ["dance", "aggressive", "dark", "2020s"],
  ),
  g(
    "Trance",
    "Electronic / Club",
    "trance, uplifting arpeggios, emotional supersaw leads, rolling kick, euphoric build and breakdown, wide stereo",
    "trance, uplifting arps, supersaw leads, euphoric energy",
    138,
    ["dance", "melodic", "energetic", "2000s"],
  ),
  g(
    "Psytrance",
    "Electronic / Club",
    "psytrance, rolling bassline, psychedelic synth sequences, triplet feel, hypnotic festival energy, bright leads",
    "psytrance, rolling bass, psychedelic synths, hypnotic festival",
    145,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Deep House",
    "Electronic / Club",
    "deep house, warm chords, groovy bassline, soft hats, soulful deep club groove, late-night vibe",
    "deep house, warm chords, groovy bass, soulful club groove",
    122,
    ["house", "dance", "smooth", "2020s"],
  ),
  g(
    "Tropical House",
    "Electronic / Club",
    "tropical house, bright marimba or pluck melody, relaxed four-on-the-floor, sunny feel, clean summer mix",
    "tropical house, bright plucks, relaxed groove, sunny summer vibe",
    118,
    ["house", "dance", "happy", "2020s"],
  ),
  g(
    "Organic House",
    "Electronic / Club",
    "organic house, live percussion layers, warm analog chords, earthy groove, natural textures, modern club polish",
    "organic house, live percussion, warm chords, earthy groove",
    120,
    ["house", "dance", "smooth", "2020s"],
  ),
  g(
    "Soulful House",
    "Electronic / Club",
    "soulful house, gospel-influenced chords, warm bass, swung hats, emotional vocal sample chops, classic house feel",
    "soulful house, gospel chords, warm bass, vocal chops, classic house",
    124,
    ["house", "soul", "dance", "2000s"],
  ),
  g(
    "French Touch",
    "Electronic / Club",
    "French touch, filtered disco samples, sidechain groove, funky bass, Daft Punk-inspired filter sweeps, chic club energy",
    "French touch, filtered disco, sidechain, funky bass, chic club",
    122,
    ["house", "dance", "2000s"],
  ),
  g(
    "Electro Funk",
    "Electronic / Club",
    "electro funk, syncopated synth bass, talkbox-style lead space, tight drums, neon 80s-influenced groove",
    "electro funk, synth bass, tight drums, neon 80s groove",
    115,
    ["dance", "rhythmic", "2000s"],
  ),
  g(
    "Synth Pop",
    "Electronic / Club",
    "synth pop, catchy hook, bright analog synth layers, punchy drums, 80s-inspired polish with modern sheen",
    "synth pop, catchy hook, analog synths, punchy drums, 80s sheen",
    118,
    ["melodic", "2020s"],
  ),
  g(
    "Chill Electronic",
    "Electronic / Club",
    "chill electronic, soft sidechain pads, gentle beat, warm bass, relaxed modern textures, easy listening groove",
    "chill electronic, soft pads, gentle beat, relaxed textures",
    100,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Experimental Electronic",
    "Electronic / Club",
    "experimental electronic, unconventional sound design, evolving textures, irregular rhythms, futuristic art-forward mix",
    "experimental electronic, sound design, evolving textures, irregular rhythms",
    110,
    ["atmospheric", "2020s"],
  ),
  g(
    "Underground Club",
    "Electronic / Club",
    "underground club, dark warehouse groove, heavy kick, minimal synth stabs, raw late-night energy",
    "underground club, warehouse groove, heavy kick, dark minimal",
    130,
    ["dance", "dark", "2020s"],
  ),

  // ── Pop / Rock / Indie ──
  g(
    "Cyberpunk",
    "Pop / Rock / Indie",
    "cyberpunk electronic, neon synth bass, dystopian atmosphere, glitch textures, rain-soaked futuristic city vibe",
    "cyberpunk, neon synths, dystopian, glitch textures, futuristic",
    128,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Y2K Pop",
    "Pop / Rock / Indie",
    "Y2K pop, glossy 2000s production, bright synths, catchy hook, punchy drums, nostalgic futuristic pop sheen",
    "Y2K pop, glossy 2000s synths, catchy hook, nostalgic futuristic",
    118,
    ["melodic", "2000s"],
  ),
  g(
    "Bedroom Pop",
    "Pop / Rock / Indie",
    "bedroom pop, intimate lo-fi production, soft drums, warm guitar or synth, dreamy close-mic feel",
    "bedroom pop, intimate lo-fi, soft drums, dreamy close feel",
    95,
    ["lo-fi", "melodic", "2020s"],
  ),
  g(
    "Shoegaze",
    "Pop / Rock / Indie",
    "shoegaze, wall of reverb guitars, hazy textures, slow driving drums, dreamy blurred atmosphere",
    "shoegaze, reverb guitars, hazy textures, dreamy blurred vibe",
    110,
    ["atmospheric", "melancholic", "1990s"],
  ),
  g(
    "Indie Rock",
    "Pop / Rock / Indie",
    "indie rock, jangly guitars, live drum groove, catchy but raw energy, modern alternative mix",
    "indie rock, jangly guitars, live drums, alternative energy",
    128,
    ["rhythmic", "2020s"],
  ),
  g(
    "Psychedelic Rock",
    "Pop / Rock / Indie",
    "psychedelic rock, swirling guitars, trippy delays, driving groove, vintage rock atmosphere with modern mix",
    "psychedelic rock, swirling guitars, trippy delays, vintage rock",
    120,
    ["rhythmic", "atmospheric", "1960s"],
  ),
  g(
    "Alternative Rock",
    "Pop / Rock / Indie",
    "alternative rock, gritty guitars, punchy drums, emotional chord movement, radio-ready modern rock mix",
    "alternative rock, gritty guitars, punchy drums, emotional chords",
    132,
    ["rhythmic", "2020s"],
  ),
  g(
    "Acoustic Indie",
    "Pop / Rock / Indie",
    "acoustic indie, fingerpicked guitar, soft percussion, warm intimate room tone, heartfelt melodic motif",
    "acoustic indie, fingerpicked guitar, soft percussion, intimate room",
    92,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "J-Pop",
    "Pop / Rock / Indie",
    "J-pop, bright layered synths, catchy hook, energetic drums, polished Tokyo pop production, kawaii energy optional",
    "J-pop, bright synths, catchy hook, polished Tokyo pop",
    128,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "K-R&B",
    "Pop / Rock / Indie",
    "K-R&B, sleek modern R&B chords, tight drums, glossy synth textures, Seoul night vibe, smooth bass",
    "K-R&B, sleek R&B chords, glossy synths, Seoul night vibe",
    92,
    ["r&b/soul", "smooth", "2020s"],
  ),
  g(
    "Future Funk",
    "Pop / Rock / Indie",
    "future funk, disco sample chops, funky bass, sidechain groove, neon 80s nostalgia, upbeat dance energy",
    "future funk, disco chops, funky bass, neon 80s nostalgia",
    118,
    ["dance", "rhythmic", "2020s"],
  ),
  g(
    "AI Generated Pop",
    "Pop / Rock / Indie",
    "AI-generated pop aesthetic, futuristic clean synth textures, catchy algorithmic hook feel, polished hyper-modern mix",
    "AI pop, futuristic synths, catchy hook, hyper-modern polish",
    120,
    ["melodic", "2020s"],
  ),

  // ── Ambient / Cinematic ──
  g(
    "Cinematic Ambient",
    "Ambient / Cinematic",
    "cinematic ambient, evolving orchestral pads, wide reverb, slow emotional harmonic movement, film-score atmosphere",
    "cinematic ambient, orchestral pads, wide reverb, film-score feel",
    70,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Dark Ambient",
    "Ambient / Cinematic",
    "dark ambient, ominous drones, sparse textures, deep sub rumble, horror-tinged wide space, slow evolution",
    "dark ambient, ominous drones, sparse textures, deep sub",
    60,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Atmospheric",
    "Ambient / Cinematic",
    "atmospheric instrumental, wide pads, gentle pulse, immersive spatial mix, emotional but minimal rhythm",
    "atmospheric, wide pads, gentle pulse, immersive space",
    80,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Meditation",
    "Ambient / Cinematic",
    "meditation music, soft drones, gentle bells or bowls, slow harmonic shifts, calming healing atmosphere",
    "meditation, soft drones, gentle bells, calming healing vibe",
    55,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Sleep Music",
    "Ambient / Cinematic",
    "sleep music, ultra-soft textures, minimal percussion, warm low drones, deeply calming nocturnal atmosphere",
    "sleep music, ultra-soft textures, warm drones, calming",
    50,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Nature Soundscape",
    "Ambient / Cinematic",
    "nature soundscape, organic field-recording feel, gentle melodic undertones, forest or water ambience, peaceful mix",
    "nature soundscape, organic ambience, forest or water feel, peaceful",
    65,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Fantasy Soundtrack",
    "Ambient / Cinematic",
    "fantasy soundtrack, orchestral strings and choir pads, magical motifs, epic but intimate adventure atmosphere",
    "fantasy soundtrack, orchestral strings, magical motifs, adventure",
    90,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Anime OST",
    "Ambient / Cinematic",
    "anime OST, emotional piano and strings, bright melodic hooks, J-anime drama energy, polished cinematic mix",
    "anime OST, emotional piano, strings, bright melodic hooks",
    100,
    ["melodic", "atmospheric", "2020s"],
  ),
  g(
    "Video Game OST",
    "Ambient / Cinematic",
    "video game OST, loop-friendly catchy motif, chiptune or modern synth layers, level music energy, clean punchy mix",
    "video game OST, catchy motif, chiptune or synth layers, loop-friendly",
    128,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Epic Trailer Music",
    "Ambient / Cinematic",
    "epic trailer music, huge orchestral hits, rising brass and percussion, dramatic tension, blockbuster cinematic mix",
    "epic trailer, orchestral hits, rising brass, dramatic tension",
    100,
    ["dark", "energetic", "2020s"],
  ),
  g(
    "Orchestral Hybrid",
    "Ambient / Cinematic",
    "orchestral hybrid, live strings blended with modern synths and drums, cinematic epic groove, wide dynamic range",
    "orchestral hybrid, strings plus synths, cinematic epic groove",
    95,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Dark Cinematic",
    "Ambient / Cinematic",
    "dark cinematic, low brass and strings, tense drones, slow-building dread, trailer-like shadow atmosphere",
    "dark cinematic, low brass, tense drones, shadow atmosphere",
    75,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Sci-Fi Atmosphere",
    "Ambient / Cinematic",
    "sci-fi atmosphere, alien synth textures, wide space reverb, pulsing sub, futuristic exploratory mood",
    "sci-fi atmosphere, alien synths, wide space, futuristic mood",
    85,
    ["atmospheric", "2020s"],
  ),
  g(
    "Apocalyptic Ambient",
    "Ambient / Cinematic",
    "apocalyptic ambient, desolate drones, distant industrial rumble, post-collapse wide space, bleak beauty",
    "apocalyptic ambient, desolate drones, industrial rumble, bleak",
    65,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Space Ambient",
    "Ambient / Cinematic",
    "space ambient, cosmic pads, slow evolving textures, deep stellar reverb, weightless exploration feel",
    "space ambient, cosmic pads, stellar reverb, weightless feel",
    60,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Ocean Dreamscape",
    "Ambient / Cinematic",
    "ocean dreamscape, liquid pads, gentle wave-like motion, underwater reverb, serene blue atmosphere",
    "ocean dreamscape, liquid pads, underwater reverb, serene",
    70,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Piano Ambient",
    "Ambient / Cinematic",
    "piano ambient, sparse expressive piano notes, long reverb tail, minimal soft pulse, intimate emotional space",
    "piano ambient, sparse piano, long reverb, intimate emotional",
    65,
    ["melodic", "atmospheric", "2020s"],
  ),
  g(
    "Spiritual Ambient",
    "Ambient / Cinematic",
    "spiritual ambient, healing pads, gentle choir textures, sacred calm atmosphere, slow harmonic bloom",
    "spiritual ambient, healing pads, choir textures, sacred calm",
    60,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Cosmic Synths",
    "Ambient / Cinematic",
    "cosmic synths, arpeggiated space sequences, analog warmth, retro-future stellar groove",
    "cosmic synths, arpeggiated sequences, analog warmth, retro-future",
    105,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Floating Dreamscape",
    "Ambient / Cinematic",
    "floating dreamscape, weightless pads, soft glitter textures, slow pulse, surreal peaceful immersion",
    "floating dreamscape, weightless pads, soft glitter, surreal peace",
    72,
    ["atmospheric", "smooth", "2020s"],
  ),

  // ── Jazz / World / Funk ──
  g(
    "Jazzhop",
    "Jazz / World / Funk",
    "jazzhop, jazzy chord samples, boom bap or lo-fi drums, warm bass, smoky late-night café groove",
    "jazzhop, jazzy chords, lo-fi drums, late-night café groove",
    88,
    ["lo-fi", "jazz", "smooth", "2020s"],
  ),
  g(
    "City Pop",
    "Jazz / World / Funk",
    "city pop, 80s Japanese-inspired groove, funky bass, bright chords, slick production, sunset urban nostalgia",
    "city pop, 80s Japanese groove, funky bass, sunset nostalgia",
    108,
    ["smooth", "melodic", "1980s"],
  ),
  g(
    "Bossa Nova",
    "Jazz / World / Funk",
    "bossa nova, nylon guitar rhythm, soft brushed drums, warm bass, Brazilian relaxed swing, sunny intimate feel",
    "bossa nova, nylon guitar, brushed drums, Brazilian swing",
    115,
    ["smooth", "latin", "2020s"],
  ),
  g(
    "Funk Carioca",
    "Jazz / World / Funk",
    "funk carioca, Brazilian baile funk energy, pounding kick, MC-ready drops, raw Rio party groove",
    "funk carioca, baile funk energy, pounding kick, Rio party",
    130,
    ["latin", "dance", "energetic", "2020s"],
  ),
  g(
    "Lo-Fi Jazz",
    "Jazz / World / Funk",
    "lo-fi jazz, dusty jazz chords, mellow drums, vinyl warmth, study-night smoky atmosphere",
    "lo-fi jazz, dusty chords, mellow drums, vinyl warmth",
    82,
    ["lo-fi", "jazz", "melancholic", "2020s"],
  ),
  g(
    "Gospel Soul",
    "Jazz / World / Funk",
    "gospel soul, uplifting chord movement, organ textures, powerful rhythmic drive, joyful spiritual energy",
    "gospel soul, organ textures, uplifting chords, spiritual energy",
    98,
    ["soul", "r&b/soul", "energetic", "2020s"],
  ),
  g(
    "Retro Disco",
    "Jazz / World / Funk",
    "retro disco, four-on-the-floor groove, funky bass, string stabs, 70s dancefloor nostalgia, modern polish",
    "retro disco, four-on-the-floor, funky bass, 70s dancefloor",
    118,
    ["dance", "rhythmic", "1970s"],
  ),

  // ── Internet / Aesthetic ──
  g(
    "HexD",
    "Internet / Aesthetic",
    "HexD, distorted digital rap-adjacent energy, bitcrushed drums, chaotic synths, hyper-aggressive internet sound",
    "HexD, bitcrushed drums, chaotic synths, hyper-aggressive digital",
    160,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Nightdrive",
    "Internet / Aesthetic",
    "nightdrive synthwave, driving analog bass, neon arps, 80s highway atmosphere, retro-futuristic pulse",
    "nightdrive, synthwave, neon arps, 80s highway retro-future",
    110,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Mallsoft",
    "Internet / Aesthetic",
    "mallsoft vaporwave, washed nostalgic muzak textures, slow dreamy groove, empty mall ambience, hazy reverb",
    "mallsoft, vaporwave, nostalgic muzak, empty mall ambience",
    80,
    ["lo-fi", "atmospheric", "2010s"],
  ),
  g(
    "Sigilkore",
    "Internet / Aesthetic",
    "sigilkore, dark internet rap aesthetic, distorted 808s, occult atmospheric textures, underground digital energy",
    "sigilkore, distorted 808s, occult textures, underground digital",
    150,
    ["dark", "aggressive", "2020s"],
  ),
  g(
    "Dreamcore",
    "Internet / Aesthetic",
    "dreamcore, surreal nostalgic textures, soft unsettling pads, liminal melody, hazy memory-like atmosphere",
    "dreamcore, surreal nostalgic, liminal melody, hazy memory",
    85,
    ["atmospheric", "melancholic", "2020s"],
  ),
  g(
    "Weirdcore",
    "Internet / Aesthetic",
    "weirdcore, uncanny nostalgic sound design, glitchy childlike motifs, unsettling but playful digital vibe",
    "weirdcore, uncanny nostalgic, glitchy motifs, unsettling playful",
    90,
    ["atmospheric", "2020s"],
  ),
  g(
    "Liminal",
    "Internet / Aesthetic",
    "liminal ambient, empty transitional space feeling, soft reverb, uncanny calm, backrooms-like atmosphere",
    "liminal ambient, empty space feeling, uncanny calm, soft reverb",
    70,
    ["atmospheric", "2020s"],
  ),
  g(
    "Analog Horror",
    "Internet / Aesthetic",
    "analog horror, degraded tape textures, unsettling drones, VHS hiss, creepy retro broadcast atmosphere",
    "analog horror, degraded tape, VHS hiss, creepy retro broadcast",
    75,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Nostalgic 2000s",
    "Internet / Aesthetic",
    "nostalgic 2000s, glossy pop-trap crossover textures, bright synths, early internet era emotional vibe",
    "nostalgic 2000s, glossy synths, early internet emotional vibe",
    105,
    ["melodic", "2000s"],
  ),
  g(
    "Retro Futuristic",
    "Internet / Aesthetic",
    "retro futuristic, 80s synth meets modern production, neon arps, chrome atmosphere, optimistic sci-fi tone",
    "retro futuristic, 80s synth, neon arps, optimistic sci-fi",
    118,
    ["melodic", "2020s"],
  ),
  g(
    "Nostalgic VHS",
    "Internet / Aesthetic",
    "nostalgic VHS aesthetic, tape warble, lo-fi drums, warm saturated chords, home-video memory vibe",
    "nostalgic VHS, tape warble, warm saturated chords, memory vibe",
    92,
    ["lo-fi", "melancholic", "1990s"],
  ),
  g(
    "Dreamy Cassette",
    "Internet / Aesthetic",
    "dreamy cassette, warbled tape pitch, soft drums, intimate bedroom texture, faded photo nostalgia",
    "dreamy cassette, warbled tape, soft drums, faded nostalgia",
    88,
    ["lo-fi", "melancholic", "2020s"],
  ),
  g(
    "Vintage Radio",
    "Internet / Aesthetic",
    "vintage radio, AM bandwidth warmth, crackle and hiss, old broadcast jazz or pop tint, nostalgic mono feel",
    "vintage radio, AM warmth, crackle hiss, old broadcast nostalgia",
    95,
    ["lo-fi", "1990s"],
  ),
  g(
    "Internet Nostalgia",
    "Internet / Aesthetic",
    "internet nostalgia, early web aesthetic textures, bitcrushed warmth, emotional digital memory atmosphere",
    "internet nostalgia, early web aesthetic, bitcrushed warmth, digital memory",
    100,
    ["lo-fi", "melancholic", "2010s"],
  ),
  g(
    "Digital Dreamworld",
    "Internet / Aesthetic",
    "digital dreamworld, surreal synth landscapes, glitter pads, floating rhythm, hyper-real internet fantasy vibe",
    "digital dreamworld, surreal synths, glitter pads, internet fantasy",
    105,
    ["atmospheric", "melodic", "2020s"],
  ),

  // ── Lifestyle / Vibe ──
  g(
    "Luxury Lounge",
    "Lifestyle / Vibe",
    "luxury lounge, smooth jazzy chords, polished drums, expensive hotel bar atmosphere, upscale late-night groove",
    "luxury lounge, smooth jazz chords, upscale late-night groove",
    95,
    ["smooth", "2020s"],
  ),
  g(
    "Fashion Runway",
    "Lifestyle / Vibe",
    "fashion runway, minimal chic groove, confident bass, sharp percussion, high-end catwalk energy",
    "fashion runway, minimal chic groove, catwalk energy, sharp percussion",
    120,
    ["rhythmic", "2020s"],
  ),
  g(
    "Gym Phonk",
    "Lifestyle / Vibe",
    "gym phonk, aggressive cowbell patterns, distorted bass, hard drums, high-intensity workout energy",
    "gym phonk, cowbell patterns, distorted bass, workout energy",
    140,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Rainy Night",
    "Lifestyle / Vibe",
    "rainy night vibe, soft lo-fi drums, warm chords, rain ambience, cozy melancholic city window atmosphere",
    "rainy night, lo-fi drums, warm chords, cozy melancholic city",
    78,
    ["lo-fi", "melancholic", "2020s"],
  ),
  g(
    "Late Night Drive",
    "Lifestyle / Vibe",
    "late night drive, smooth synth pads, steady mid-tempo groove, neon highway reflection mood",
    "late night drive, smooth synths, neon highway mood, steady groove",
    98,
    ["smooth", "atmospheric", "2020s"],
  ),
  g(
    "Sunset Vibes",
    "Lifestyle / Vibe",
    "sunset vibes, warm golden chords, relaxed groove, beach horizon feel, feel-good evening energy",
    "sunset vibes, warm golden chords, beach horizon feel-good",
    102,
    ["smooth", "happy", "2020s"],
  ),
  g(
    "Futuristic Lounge",
    "Lifestyle / Vibe",
    "futuristic lounge, sleek synth chords, minimal modern drums, upscale sci-fi hotel bar atmosphere",
    "futuristic lounge, sleek synths, upscale sci-fi bar atmosphere",
    100,
    ["smooth", "atmospheric", "2020s"],
  ),
  g(
    "Luxury Trap",
    "Lifestyle / Vibe",
    "luxury trap, polished 808s, elegant minor chords, expensive nightlife vibe, clean high-end mix",
    "luxury trap, polished 808s, elegant chords, expensive nightlife",
    138,
    ["trap", "smooth", "2020s"],
  ),
  g(
    "Viral Edit Audio",
    "Lifestyle / Vibe",
    "viral edit audio, punchy hook stabs, edit-friendly transitions, loud clean mix, TikTok clip energy",
    "viral edit audio, punchy hook stabs, edit-friendly, TikTok clip energy",
    130,
    ["energetic", "2020s"],
  ),
  g(
    "Sad Piano",
    "Lifestyle / Vibe",
    "sad piano, sparse emotional piano melody, minimal soft pulse, intimate heartbreak atmosphere",
    "sad piano, sparse emotional melody, intimate heartbreak",
    70,
    ["melancholic", "2020s"],
  ),
  g(
    "Emotional Guitar",
    "Lifestyle / Vibe",
    "emotional guitar, clean or slightly driven guitar motif, warm reverb, heartfelt instrumental atmosphere",
    "emotional guitar, heartfelt motif, warm reverb, intimate feel",
    85,
    ["melancholic", "melodic", "2020s"],
  ),
  g(
    "Ethereal Vocals",
    "Lifestyle / Vibe",
    "ethereal vocal texture instrumental, wordless airy vocal pads as texture, wide reverb, angelic atmosphere",
    "ethereal vocal pads, wordless airy texture, wide reverb, angelic",
    90,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Tokyo Nightlife",
    "Lifestyle / Vibe",
    "Tokyo nightlife, neon city pop and electronic blend, bright synth leads, energetic Shibuya crossing vibe",
    "Tokyo nightlife, neon city pop blend, Shibuya energy",
    124,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Seoul Aesthetic",
    "Lifestyle / Vibe",
    "Seoul aesthetic, sleek K-pop influenced production, glossy synths, clean tight drums, modern Korean urban vibe",
    "Seoul aesthetic, glossy K-pop influenced synths, clean tight drums",
    118,
    ["melodic", "2020s"],
  ),
  g(
    "Miami Neon",
    "Lifestyle / Vibe",
    "Miami neon, tropical bass, bright synth stabs, palm-tree nightlife energy, warm sunset club vibe",
    "Miami neon, tropical bass, bright synths, sunset club vibe",
    112,
    ["dance", "happy", "2020s"],
  ),
  g(
    "Paris Fashion Night",
    "Lifestyle / Vibe",
    "Paris fashion night, chic minimal house groove, elegant bass, sophisticated European club atmosphere",
    "Paris fashion night, chic minimal house, sophisticated European club",
    122,
    ["house", "smooth", "2020s"],
  ),
  g(
    "Desert Sunset",
    "Lifestyle / Vibe",
    "desert sunset, warm analog synths, sparse percussion, golden hour wide space, meditative heat shimmer",
    "desert sunset, warm analog synths, golden hour wide space",
    88,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Rainy Cyber City",
    "Lifestyle / Vibe",
    "rainy cyber city, blade-runner rain ambience, neon bass pulse, dystopian wet streets atmosphere",
    "rainy cyber city, neon bass pulse, dystopian wet streets",
    105,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Surreal Luxury",
    "Lifestyle / Vibe",
    "surreal luxury, opulent synth textures, unexpected harmonic twists, high-fashion dreamlike atmosphere",
    "surreal luxury, opulent synths, high-fashion dreamlike atmosphere",
    98,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Emotional Future",
    "Lifestyle / Vibe",
    "emotional future, futuristic synth design with heartfelt chord progression, modern cinematic pop-trap hybrid",
    "emotional future, futuristic synths, heartfelt chords, cinematic hybrid",
    128,
    ["melodic", "atmospheric", "2020s"],
  ),
  g(
    "Soft Chaos",
    "Lifestyle / Vibe",
    "soft chaos, controlled glitch textures over gentle groove, playful instability, artistic experimental pop energy",
    "soft chaos, controlled glitch, gentle groove, artistic experimental",
    115,
    ["atmospheric", "2020s"],
  ),

  // ── Internet / Gen Z / Underground (2026) ──
  g(
    "Hyperpop 2.0",
    "Internet / Gen Z / Underground",
    "hyperpop 2.0, ultra-processed vocals, metallic synth chaos, maximalist digital pop, glitchy sidechain, Gen Z internet energy",
    "hyperpop 2.0, processed vocals, metallic synths, maximalist digital pop",
    165,
    ["energetic", "2020s"],
  ),
  g(
    "Krushclub",
    "Internet / Gen Z / Underground",
    "krushclub, blown-out digital bass, crushed drums, chaotic club energy, SoundCloud underground mosh vibe",
    "krushclub, blown-out bass, crushed drums, chaotic club energy",
    155,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Webcore",
    "Internet / Gen Z / Underground",
    "webcore, early-internet MIDI textures, nostalgic browser aesthetic, bitcrushed drums, surreal digital melancholy",
    "webcore, early internet MIDI, browser aesthetic, bitcrushed drums",
    120,
    ["lo-fi", "melancholic", "2010s"],
  ),
  g(
    "Cybercore",
    "Internet / Gen Z / Underground",
    "cybercore, aggressive digital synths, dystopian club drums, neon glitch stabs, hacker-matrix underground energy",
    "cybercore, digital synths, dystopian drums, neon glitch",
    150,
    ["aggressive", "dark", "2020s"],
  ),
  g(
    "Scene Revival",
    "Internet / Gen Z / Underground",
    "scene revival, 2010s emo-pop crossover energy, chugging guitars blended with modern trap drums, MySpace nostalgia",
    "scene revival, emo-pop crossover, chugging guitars, trap drums",
    140,
    ["energetic", "melodic", "2010s"],
  ),
  g(
    "Emo Electronic",
    "Internet / Gen Z / Underground",
    "emo electronic, heartbreak synth leads, sidechain pads, punchy drums, sad-but-danceable digital club mood",
    "emo electronic, heartbreak synths, sidechain pads, sad danceable",
    128,
    ["melancholic", "energetic", "2020s"],
  ),
  g(
    "Hypertrap",
    "Internet / Gen Z / Underground",
    "hypertrap, distorted 808s, rapid hi-hat rolls, metallic synth chaos, extreme modern trap intensity",
    "hypertrap, distorted 808s, rapid hats, metallic synth chaos",
    150,
    ["trap", "aggressive", "2020s"],
  ),
  g(
    "Hyperrage",
    "Internet / Gen Z / Underground",
    "hyperrage, rage synth leads on steroids, blown 808s, mosh-pit trap energy, aggressive Gen Z club sound",
    "hyperrage, rage synths, blown 808s, mosh-pit trap energy",
    155,
    ["trap", "aggressive", "2020s"],
  ),
  g(
    "Terror Plugg",
    "Internet / Gen Z / Underground",
    "terror plugg, dark plugg nb groove, eerie bell melodies, sliding 808s, sinister underground Memphis energy",
    "terror plugg, dark plugg, eerie bells, sliding 808s, sinister",
    145,
    ["dark", "trap", "2020s"],
  ),
  g(
    "Diary Plugg",
    "Internet / Gen Z / Underground",
    "diary plugg, intimate plugg nb beat, soft bell plucks, emotional sliding bass, lonely late-night SoundCloud vibe",
    "diary plugg, intimate plugg, soft bells, emotional sliding bass",
    130,
    ["melancholic", "trap", "2020s"],
  ),
  g(
    "Ambient Plugg",
    "Internet / Gen Z / Underground",
    "ambient plugg, spacious plugg nb groove, reverb-drenched bells, floating 808s, dreamy underground haze",
    "ambient plugg, spacious plugg, reverb bells, floating 808s",
    125,
    ["atmospheric", "trap", "2020s"],
  ),
  g(
    "Dark Plugg",
    "Internet / Gen Z / Underground",
    "dark plugg, minor-key plugg nb, ominous bell motif, heavy sub slides, shadowy underground trap mood",
    "dark plugg, minor plugg, ominous bells, heavy sub slides",
    138,
    ["dark", "trap", "2020s"],
  ),
  g(
    "Balloon Plugg",
    "Internet / Gen Z / Underground",
    "balloon plugg, bouncy plugg nb groove, playful bell bounce, rubbery 808 slides, colorful underground energy",
    "balloon plugg, bouncy plugg, playful bells, rubbery 808 slides",
    132,
    ["trap", "energetic", "2020s"],
  ),
  g(
    "Jerk",
    "Internet / Gen Z / Underground",
    "jerk, off-kilter bounce rhythm, minimal synth stabs, Memphis-influenced pocket, raw SoundCloud dance energy",
    "jerk, off-kilter bounce, minimal synth stabs, Memphis pocket",
    142,
    ["rhythmic", "energetic", "2020s"],
  ),
  g(
    "Glo",
    "Internet / Gen Z / Underground",
    "glo, ethereal cloud trap, shimmering synth pads, soft 808s, hazy Chicago drill-influenced atmosphere",
    "glo, ethereal cloud trap, shimmering pads, soft 808s, hazy",
    135,
    ["atmospheric", "trap", "2020s"],
  ),
  g(
    "Ragewave",
    "Internet / Gen Z / Underground",
    "ragewave, rage synth leads with wave-style pads, half-time drums, emotional aggressive internet trap hybrid",
    "ragewave, rage synths, wave pads, half-time drums, emotional aggressive",
    148,
    ["trap", "dark", "2020s"],
  ),
  g(
    "Hyperdrill",
    "Internet / Gen Z / Underground",
    "hyperdrill, drill hi-hats with rage synth chaos, dark sliding bass, UK-meets-Atlanta underground intensity",
    "hyperdrill, drill hats, rage synths, dark sliding bass",
    152,
    ["trap", "aggressive", "2020s"],
  ),
  g(
    "Trap Metal",
    "Internet / Gen Z / Underground",
    "trap metal, distorted guitar riffs over trap drums, scream-ready energy, mosh-pit hybrid aggression",
    "trap metal, distorted guitars, trap drums, mosh-pit aggression",
    145,
    ["aggressive", "rock", "2020s"],
  ),
  g(
    "Drainwave",
    "Internet / Gen Z / Underground",
    "drainwave, blown-out lo-fi trap, degraded textures, sad aggressive cloud energy, SoundCloud drain aesthetic",
    "drainwave, blown-out lo-fi trap, degraded textures, sad aggressive",
    130,
    ["dark", "melancholic", "2020s"],
  ),
  g(
    "Sadboy Aesthetic",
    "Internet / Gen Z / Underground",
    "sadboy aesthetic, melancholic trap, soft piano or guitar over 808s, Tumblr-era emotional internet mood",
    "sadboy aesthetic, melancholic trap, soft piano, emotional internet",
    128,
    ["melancholic", "trap", "2010s"],
  ),
  g(
    "Doomtrap",
    "Internet / Gen Z / Underground",
    "doomtrap, slow heavy 808s, ominous minor chords, apocalyptic trap atmosphere, dark end-times energy",
    "doomtrap, slow heavy 808s, ominous chords, apocalyptic trap",
    130,
    ["dark", "trap", "2020s"],
  ),
  g(
    "Digital Punk",
    "Internet / Gen Z / Underground",
    "digital punk, punk guitar energy fused with hyperpop synths, chaotic drums, anti-corporate internet rebellion",
    "digital punk, punk guitars, hyperpop synths, chaotic rebellion",
    160,
    ["aggressive", "energetic", "2020s"],
  ),

  // ── TikTok / Viral / Edit Culture ──
  g(
    "Drift Phonk",
    "TikTok / Viral / Edit",
    "drift phonk, cowbell melody, distorted Memphis bass, aggressive drift edit energy, car-video soundtrack vibe",
    "drift phonk, cowbell melody, distorted bass, drift edit energy",
    130,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Edit Audio",
    "TikTok / Viral / Edit",
    "edit audio, punchy hook designed for short-form edits, dramatic transitions, loud clean mix, clip-ready energy",
    "edit audio, punchy hook, dramatic transitions, clip-ready energy",
    132,
    ["energetic", "2020s"],
  ),
  g(
    "TikTok Sad Edit",
    "TikTok / Viral / Edit",
    "TikTok sad edit, emotional piano or guitar over soft trap pulse, slow cinematic build, heartbreak montage energy",
    "TikTok sad edit, emotional piano, soft trap pulse, heartbreak montage",
    85,
    ["melancholic", "2020s"],
  ),
  g(
    "Viral Speed Up",
    "TikTok / Viral / Edit",
    "viral speed up, bright pitched-up pop-trap crossover, catchy hook, sped-up TikTok trend energy, glossy mix",
    "viral speed up, pitched-up pop-trap, catchy hook, TikTok trend",
    145,
    ["energetic", "melodic", "2020s"],
  ),
  g(
    "Slowed + Reverb",
    "TikTok / Viral / Edit",
    "slowed and reverb, time-stretched emotional texture, deep reverb wash, dreamy melancholic TikTok edit vibe",
    "slowed and reverb, time-stretched, deep reverb wash, dreamy melancholic",
    70,
    ["melancholic", "atmospheric", "2020s"],
  ),
  g(
    "Nightcore",
    "TikTok / Viral / Edit",
    "nightcore, sped-up trance-pop energy, bright supersaw leads, euphoric fast BPM, anime-edit adrenaline",
    "nightcore, sped-up trance-pop, supersaw leads, euphoric fast BPM",
    175,
    ["energetic", "melodic", "2010s"],
  ),
  g(
    "Atmospheric Trap",
    "TikTok / Viral / Edit",
    "atmospheric trap, wide reverb 808s, ethereal pads, spacious modern trap, cinematic emotional depth",
    "atmospheric trap, wide reverb 808s, ethereal pads, cinematic depth",
    130,
    ["atmospheric", "trap", "2020s"],
  ),
  g(
    "Sigma Edit Music",
    "TikTok / Viral / Edit",
    "sigma edit music, hard phonk or trap with motivational energy, gym montage drums, alpha edit soundtrack vibe",
    "sigma edit music, hard phonk trap, gym montage drums, motivational",
    135,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Drift House",
    "TikTok / Viral / Edit",
    "drift house, four-on-the-floor kick with phonk cowbell layers, car drift edit groove, bass-heavy club hybrid",
    "drift house, four-on-the-floor, phonk cowbell, drift edit groove",
    128,
    ["dance", "aggressive", "2020s"],
  ),
  g(
    "Aggressive Bass",
    "TikTok / Viral / Edit",
    "aggressive bass, distorted sub-heavy drop energy, hard drums, edit-friendly impact hits, loud modern mix",
    "aggressive bass, distorted sub drops, hard drums, edit impact hits",
    140,
    ["aggressive", "energetic", "2020s"],
  ),
  g(
    "Moshpit Rage",
    "TikTok / Viral / Edit",
    "moshpit rage, rage synth chaos with mosh-pit drum intensity, crowd-surf trap energy, live-feel aggression",
    "moshpit rage, rage synth chaos, mosh-pit drums, crowd-surf energy",
    150,
    ["aggressive", "trap", "2020s"],
  ),
  g(
    "Midnight Drive",
    "TikTok / Viral / Edit",
    "midnight drive, dark synthwave trap hybrid, neon highway bass, late-night edit montage atmosphere",
    "midnight drive, dark synthwave trap, neon highway bass, late-night edit",
    105,
    ["atmospheric", "dark", "2020s"],
  ),
  g(
    "Anime Edit Core",
    "TikTok / Viral / Edit",
    "anime edit core, emotional J-anime inspired chords, dramatic build, AMV soundtrack energy, cinematic drops",
    "anime edit core, J-anime chords, dramatic build, AMV soundtrack energy",
    140,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Cinematic Edit Audio",
    "TikTok / Viral / Edit",
    "cinematic edit audio, orchestral hits blended with modern drums, epic short-form edit transitions, trailer energy",
    "cinematic edit audio, orchestral hits, modern drums, trailer edit energy",
    110,
    ["dark", "energetic", "2020s"],
  ),
  g(
    "Bass Boosted",
    "TikTok / Viral / Edit",
    "bass boosted, extreme sub emphasis, distorted low-end, meme-edit loudness energy, club-rattling mix",
    "bass boosted, extreme sub emphasis, distorted low-end, loud mix",
    128,
    ["aggressive", "2020s"],
  ),
  g(
    "VHS Nostalgia",
    "TikTok / Viral / Edit",
    "VHS nostalgia, tape-saturated drums, warm lo-fi chords, home-video memory aesthetic, retro edit vibe",
    "VHS nostalgia, tape-saturated drums, warm lo-fi chords, retro edit",
    95,
    ["lo-fi", "melancholic", "1990s"],
  ),
  g(
    "2000s Internet",
    "TikTok / Viral / Edit",
    "2000s internet, early web pop-trap crossover, glossy synths, MySpace-era emotional digital nostalgia",
    "2000s internet, early web pop-trap, glossy synths, MySpace nostalgia",
    108,
    ["melodic", "2000s"],
  ),

  // ── Global / Rising ──
  g(
    "Drum & Bass Revival",
    "Global / Rising",
    "drum and bass revival, modern rolling breaks, heavy sub, melodic DnB energy, 2020s festival polish",
    "drum and bass revival, rolling breaks, heavy sub, festival polish",
    174,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Jungle Revival",
    "Global / Rising",
    "jungle revival, chopped amen breaks, ragga-influenced bass, raw UK rave comeback energy, modern mix",
    "jungle revival, amen breaks, ragga bass, UK rave comeback",
    172,
    ["dance", "aggressive", "2020s"],
  ),
  g(
    "Melodic Techno",
    "Global / Rising",
    "melodic techno, hypnotic four-on-the-floor, emotional arpeggios, festival afterhours atmosphere, wide mix",
    "melodic techno, hypnotic kick, emotional arpeggios, afterhours",
    124,
    ["dance", "melodic", "2020s"],
  ),
  g(
    "Hard Groove",
    "Global / Rising",
    "hard groove techno, funky percussive drive, pounding kick, warehouse sweat energy, relentless club groove",
    "hard groove, funky percussive drive, pounding kick, warehouse energy",
    135,
    ["dance", "aggressive", "2020s"],
  ),
  g(
    "Trance Revival",
    "Global / Rising",
    "trance revival, modern supersaw leads, euphoric build-ups, festival mainstage nostalgia with 2026 polish",
    "trance revival, supersaw leads, euphoric builds, festival mainstage",
    140,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Future Garage",
    "Global / Rising",
    "future garage, shuffled 2-step drums, emotive vocal chops, UK bass weight, late-night urban atmosphere",
    "future garage, shuffled 2-step, vocal chops, UK bass weight",
    130,
    ["dance", "melancholic", "2020s"],
  ),
  g(
    "Latin Trap",
    "Global / Rising",
    "latin trap, dembow-influenced rhythm, reggaeton-trap hybrid, Spanish-market club energy, modern 808s",
    "latin trap, dembow rhythm, reggaeton-trap hybrid, modern 808s",
    95,
    ["latin", "trap", "2020s"],
  ),
  g(
    "Corridos Tumbados",
    "Global / Rising",
    "corridos tumbados, Mexican regional guitar with trap 808s, sad melodic storytelling, modern corrido fusion",
    "corridos tumbados, regional guitar, trap 808s, sad melodic storytelling",
    88,
    ["latin", "melancholic", "2020s"],
  ),
  g(
    "City Pop Revival",
    "Global / Rising",
    "city pop revival, 80s Japanese funk groove reborn, bright chords, slick bass, sunset Tokyo nostalgia",
    "city pop revival, 80s Japanese funk, bright chords, sunset Tokyo",
    110,
    ["smooth", "melodic", "1980s"],
  ),

  // ── Aesthetic / Mood ──
  g(
    "Nostalgic Future",
    "Aesthetic / Mood",
    "nostalgic future, retro synths meeting modern trap production, bittersweet futuristic memory, emotional hybrid",
    "nostalgic future, retro synths, modern trap, bittersweet futuristic",
    115,
    ["melodic", "atmospheric", "2020s"],
  ),
  g(
    "Dreamwave",
    "Aesthetic / Mood",
    "dreamwave, hazy synth pads, slow-motion groove, surreal pastel atmosphere, floating emotional textures",
    "dreamwave, hazy synth pads, slow groove, surreal pastel atmosphere",
    90,
    ["atmospheric", "melodic", "2020s"],
  ),
  g(
    "Ocean Ambient",
    "Aesthetic / Mood",
    "ocean ambient, liquid pads, gentle tidal motion, deep blue reverb, serene underwater calm",
    "ocean ambient, liquid pads, tidal motion, underwater calm",
    68,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Underground Tunnel",
    "Aesthetic / Mood",
    "underground tunnel, echoing concrete ambience, distant bass pulse, liminal transit space atmosphere",
    "underground tunnel, echoing concrete, distant bass, liminal transit",
    80,
    ["dark", "atmospheric", "2020s"],
  ),
  g(
    "Neon City",
    "Aesthetic / Mood",
    "neon city, bright synth stabs, cyberpunk bass pulse, rain-soaked metropolis nightlife energy",
    "neon city, bright synth stabs, cyberpunk bass, metropolis nightlife",
    118,
    ["dance", "atmospheric", "2020s"],
  ),
  g(
    "Seoul Nightlife",
    "Aesthetic / Mood",
    "Seoul nightlife, sleek K-club groove, glossy synths, tight modern drums, Gangnam after-dark energy",
    "Seoul nightlife, K-club groove, glossy synths, after-dark energy",
    120,
    ["dance", "smooth", "2020s"],
  ),
  g(
    "Fashion Week Soundtrack",
    "Aesthetic / Mood",
    "fashion week soundtrack, minimal chic groove, confident bass, runway-ready percussion, high-fashion polish",
    "fashion week soundtrack, minimal chic groove, runway percussion",
    122,
    ["rhythmic", "smooth", "2020s"],
  ),
  g(
    "Cyber Y2K",
    "Aesthetic / Mood",
    "cyber Y2K, chrome synths, futuristic 2000s pop-trap sheen, glossy digital nostalgia, neon optimism",
    "cyber Y2K, chrome synths, futuristic 2000s sheen, neon optimism",
    112,
    ["melodic", "2000s"],
  ),
  g(
    "VHS Dream",
    "Aesthetic / Mood",
    "VHS dream, warbled tape pitch, soft hazy chords, dreamlike home-video nostalgia, faded memory glow",
    "VHS dream, warbled tape, hazy chords, dreamlike home-video nostalgia",
    88,
    ["lo-fi", "melancholic", "1990s"],
  ),
  g(
    "Digital Nostalgia",
    "Aesthetic / Mood",
    "digital nostalgia, early social-media era textures, bitcrushed warmth, emotional internet memory atmosphere",
    "digital nostalgia, early social media textures, bitcrushed warmth",
    102,
    ["lo-fi", "melancholic", "2010s"],
  ),
  g(
    "Artificial Nostalgia",
    "Aesthetic / Mood",
    "artificial nostalgia, AI-era synthetic memory feel, uncanny warm synths, simulated vintage emotional haze",
    "artificial nostalgia, synthetic memory, uncanny warm synths, simulated vintage",
    100,
    ["atmospheric", "melancholic", "2020s"],
  ),
  g(
    "Internet Dreamscape",
    "Aesthetic / Mood",
    "internet dreamscape, surreal digital pads, floating rhythm, hyper-real online fantasy atmosphere",
    "internet dreamscape, surreal digital pads, floating rhythm, online fantasy",
    105,
    ["atmospheric", "melodic", "2020s"],
  ),

  // ── Creator / Playlist ──
  g(
    "Sleep Ambient",
    "Creator / Playlist",
    "sleep ambient, ultra-soft drones, no percussion, warm low textures, deeply calming nocturnal atmosphere",
    "sleep ambient, ultra-soft drones, warm textures, calming nocturnal",
    50,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Meditation Soundscape",
    "Creator / Playlist",
    "meditation soundscape, healing pads, gentle bells, slow harmonic bloom, mindful peaceful atmosphere",
    "meditation soundscape, healing pads, gentle bells, mindful peaceful",
    55,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Piano Atmosphere",
    "Creator / Playlist",
    "piano atmosphere, sparse expressive piano, long reverb tail, minimal soft pulse, intimate focus mood",
    "piano atmosphere, sparse piano, long reverb, intimate focus",
    72,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "Coffee Shop Lo-Fi",
    "Creator / Playlist",
    "coffee shop lo-fi, warm jazz chords, mellow dusty drums, vinyl crackle, cozy café study atmosphere",
    "coffee shop lo-fi, warm jazz chords, dusty drums, cozy café",
    80,
    ["lo-fi", "jazz", "smooth", "2020s"],
  ),
  g(
    "Focus Music",
    "Creator / Playlist",
    "focus music, minimal repetitive groove, non-distracting textures, steady productive concentration mood",
    "focus music, minimal groove, non-distracting textures, productive concentration",
    85,
    ["smooth", "2020s"],
  ),
  g(
    "Deep Focus",
    "Creator / Playlist",
    "deep focus, ambient electronic pulse, no hooks, long-form concentration atmosphere, subtle evolution",
    "deep focus, ambient pulse, no hooks, long-form concentration",
    78,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Spa Ambient",
    "Creator / Playlist",
    "spa ambient, soft water-like pads, gentle harmonic drift, luxury wellness relaxation atmosphere",
    "spa ambient, soft pads, gentle drift, wellness relaxation",
    60,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Cozy Rain",
    "Creator / Playlist",
    "cozy rain, soft lo-fi drums with rain ambience, warm chords, blanket-and-window melancholic comfort",
    "cozy rain, lo-fi drums, rain ambience, warm chords, comfort",
    75,
    ["lo-fi", "melancholic", "2020s"],
  ),
  g(
    "Fireplace Lo-Fi",
    "Creator / Playlist",
    "fireplace lo-fi, crackling warmth texture, mellow jazz chords, slow cozy winter evening groove",
    "fireplace lo-fi, crackling warmth, mellow jazz chords, cozy winter",
    78,
    ["lo-fi", "smooth", "2020s"],
  ),
  g(
    "Reading Music",
    "Creator / Playlist",
    "reading music, gentle acoustic or piano motif, soft pulse, unobtrusive literary atmosphere",
    "reading music, gentle piano motif, soft pulse, unobtrusive literary",
    70,
    ["smooth", "melodic", "2020s"],
  ),
  g(
    "Coding Music",
    "Creator / Playlist",
    "coding music, steady electronic groove, subtle synth arps, developer flow-state concentration vibe",
    "coding music, steady electronic groove, subtle arps, flow-state",
    88,
    ["smooth", "2020s"],
  ),
  g(
    "Chill Gaming",
    "Creator / Playlist",
    "chill gaming, relaxed electronic groove, loop-friendly motif, casual stream background energy",
    "chill gaming, relaxed electronic groove, loop-friendly motif, stream background",
    95,
    ["smooth", "2020s"],
  ),

  // ── Underground Artist 2026 ──
  g(
    "Opium",
    "Underground Artist 2026",
    "opium sound, dark avant-garde trap, distorted synths, underground fashion rap energy, raw experimental mix",
    "opium sound, dark avant-garde trap, distorted synths, underground fashion",
    145,
    ["dark", "trap", "2020s"],
  ),
  g(
    "Underground Rage",
    "Underground Artist 2026",
    "underground rage, raw rage synths, unpolished aggressive 808s, SoundCloud mosh energy, anti-mainstream trap",
    "underground rage, raw rage synths, aggressive 808s, SoundCloud mosh",
    152,
    ["trap", "aggressive", "2020s"],
  ),
  g(
    "Fashion Trap",
    "Underground Artist 2026",
    "fashion trap, minimal dark trap, runway-ready bass, designer-brand underground energy, sleek aggression",
    "fashion trap, minimal dark trap, runway bass, designer underground",
    140,
    ["trap", "dark", "2020s"],
  ),
  g(
    "Dark Fashion",
    "Underground Artist 2026",
    "dark fashion, gothic trap aesthetics, ominous synth stabs, luxury noir club energy, high-end darkness",
    "dark fashion, gothic trap, ominous synth stabs, luxury noir",
    135,
    ["dark", "trap", "2020s"],
  ),
  g(
    "Avant Pop",
    "Underground Artist 2026",
    "avant pop, experimental pop structure, unconventional hooks, art-forward production, bold harmonic choices",
    "avant pop, experimental structure, unconventional hooks, art-forward",
    118,
    ["melodic", "2020s"],
  ),
  g(
    "Experimental Pop",
    "Underground Artist 2026",
    "experimental pop, genre-bending textures, unexpected sound design, artistic pop deconstruction, modern edge",
    "experimental pop, genre-bending, unexpected sound design, artistic",
    120,
    ["melodic", "2020s"],
  ),
  g(
    "Indie Sleaze Revival",
    "Underground Artist 2026",
    "indie sleaze revival, 2010s bloghouse-meets-indie energy, dirty synths, party-rock groove, nostalgic chaos",
    "indie sleaze revival, bloghouse indie, dirty synths, party-rock chaos",
    128,
    ["energetic", "rock", "2010s"],
  ),
  g(
    "Neo Soul Future",
    "Underground Artist 2026",
    "neo soul future, warm Rhodes chords, modern trap-influenced drums, futuristic soul vocal space, smooth groove",
    "neo soul future, warm Rhodes, modern drums, futuristic soul groove",
    92,
    ["r&b/soul", "smooth", "2020s"],
  ),
  g(
    "Sad R&B",
    "Underground Artist 2026",
    "sad R&B, heartbreak chord progression, soft trap-influenced drums, intimate late-night emotional vocal space",
    "sad R&B, heartbreak chords, soft trap drums, intimate late-night",
    85,
    ["r&b/soul", "melancholic", "2020s"],
  ),
  g(
    "Atmospheric R&B",
    "Underground Artist 2026",
    "atmospheric R&B, wide reverb chords, spacious slow groove, ethereal modern soul production, dreamy depth",
    "atmospheric R&B, wide reverb chords, spacious groove, ethereal soul",
    88,
    ["r&b/soul", "atmospheric", "2020s"],
  ),
  g(
    "Futuristic Soul",
    "Underground Artist 2026",
    "futuristic soul, analog warmth meets sci-fi synth design, emotional groove, forward-looking R&B atmosphere",
    "futuristic soul, analog warmth, sci-fi synths, emotional groove",
    95,
    ["r&b/soul", "melodic", "2020s"],
  ),
  g(
    "Shoegaze Revival",
    "Underground Artist 2026",
    "shoegaze revival, dense reverb guitars, modern drum production, dreamy blurred 2020s alternative haze",
    "shoegaze revival, dense reverb guitars, modern drums, dreamy haze",
    112,
    ["atmospheric", "rock", "2020s"],
  ),
  g(
    "Alternative Indie",
    "Underground Artist 2026",
    "alternative indie, off-center song structure, raw emotional guitars or synths, DIY bedroom authenticity",
    "alternative indie, off-center structure, raw emotional, DIY bedroom",
    120,
    ["melodic", "2020s"],
  ),
  g(
    "Psychedelic Trap",
    "Underground Artist 2026",
    "psychedelic trap, trippy synth textures over trap drums, mind-bending sound design, hazy underground mood",
    "psychedelic trap, trippy synths, trap drums, mind-bending haze",
    135,
    ["trap", "atmospheric", "2020s"],
  ),
  ...HIP_HOP_SOUL_GENRES,
];

export const EXTENDED_GENRE_VALUES = new Set(EXTENDED_GENRES.map((x) => x.value));

export function extendedGenrePromptMap(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const item of EXTENDED_GENRES) out[item.value] = item.prompt;
  return out;
}

export function extendedGenreAceTagMap(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const item of EXTENDED_GENRES) out[item.value] = item.aceTags;
  return out;
}

export function extendedGenreBpmMap(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const item of EXTENDED_GENRES) out[item.value] = item.bpm;
  return out;
}

export function extendedGenreSonautoMap(): Record<string, string[]> {
  const out: Record<string, string[]> = {};
  for (const item of EXTENDED_GENRES) out[item.value] = item.sonautoTags;
  return out;
}

export function extendedGenreDropdownOptions(): { group: string; value: string; label: string }[] {
  return EXTENDED_GENRES.map((item) => ({
    group: item.group,
    value: item.value,
    label: item.label ?? item.value,
  }));
}
