/** Hip-hop, trap, drill, and R&B/soul microgenres — ACE-Step XL 1.5 prompts (musicological). */
import type { ExtendedGenreDef } from "@/lib/genres/extendedCatalog";

function g(
  value: string,
  group: string,
  prompt: string,
  aceTags: string,
  bpm: number,
  sonautoTags: string[] = ["2020s"],
): ExtendedGenreDef {
  return { value, group, prompt, aceTags, bpm, sonautoTags };
}

export const HIP_HOP_SOUL_GENRES: ExtendedGenreDef[] = [

  g(
    "Rage Trap",
    "Trap / Modern",
    "rage trap, distorted supersaw leads over blown sliding 808s, frantic triplet hi-hat rolls, hard snare claps with sidechain pump, mosh-pit aggression and screamed ad-lib vocal shouts",
    "rage trap, distorted 808s, supersaw leads, triplet hats, sidechain pump, screamed ad-libs, high intensity",
    130,
    ["2020s","trap","aggressive"],
  ),
  g(
    "Emo Trap",
    "Trap / Modern",
    "emo trap, palm-muted clean guitar arpeggios under crying minor synth pads, soft rubbery 808 slides, sparse trap hats, melancholic melodic rap hook with strained emotional vocal tone",
    "emo trap, guitar arpeggios, minor synth pads, rubbery 808, sparse hats, melodic rap hook, strained vocals",
    130,
    ["2020s","trap"],
  ),
  g(
    "Cloud Trap",
    "Trap / Modern",
    "cloud trap, washed-out reverb on airy bell plucks and hazy stacked synth pads, sparse kick pattern, soft detuned 808 sub, slow swung hats, dreamy muted vocal layers floating in haze",
    "cloud trap, washed reverb, bell plucks, hazy pads, soft 808 sub, slow swung hats, dreamy vocals, ethereal",
    130,
    ["2020s","trap"],
  ),
  g(
    "Drill Trap",
    "Trap / Modern",
    "drill trap, dark sliding chromatic 808 bass glides over trap snare claps, rapid drill hi-hat skippy rolls, eerie minor bell synth stabs, cold menacing energy in half-time trap feel",
    "drill trap, sliding 808, chromatic bass, skippy hats, minor bells, trap snare claps, half-time, menacing",
    142,
    ["2020s","trap","aggressive"],
  ),
  g(
    "Space Trap",
    "Trap / Modern",
    "space trap, cosmic arpeggiated synth leads and granular pad swells through long reverb tails, deep sub 808 with pitch-drop glides, metallic percussion clicks, sci-fi laser FX, zero-gravity floating atmosphere",
    "space trap, cosmic arps, granular pads, long reverb, pitch-drop 808, metallic percussion, sci-fi FX, floating",
    130,
    ["2020s","trap","atmospheric"],
  ),
  g(
    "Gothic Trap",
    "Trap / Modern",
    "gothic trap, pipe-organ chord stabs and cathedral hall reverb over hammering 808 kicks, harmonic minor harpsichord plucks, dark romantic velvet atmosphere, whispered haunting vocal ad-libs",
    "gothic trap, pipe organ stabs, cathedral reverb, 808 kicks, harmonic minor, harpsichord plucks, whispered ad-libs, dark romantic",
    130,
    ["2020s","trap"],
  ),
  g(
    "Sad Trap",
    "Trap / Modern",
    "sad trap, detuned minor piano melodies with tearful string pad swells, slow long-decay 808 slides, minimal brushed trap hats, hollow snare ghosts, heavy lonely midnight melancholy without bright highs",
    "sad trap, detuned piano, string pads, long-decay 808, brushed hats, hollow snare, midnight melancholy, minor key",
    130,
    ["2020s","trap","melancholic"],
  ),
  g(
    "Horror Trap",
    "Trap / Modern",
    "horror trap, dissonant string stabs and detuned music-box melodies through bitcrushed horror FX, pounding distorted 808 hits, abrupt silence gaps, whispered menacing vocal breaths, cinematic nightmare tension and dread",
    "horror trap, dissonant strings, music-box melody, bitcrush FX, distorted 808, silence gaps, whispered breaths, dread",
    130,
    ["2020s","trap","aggressive"],
  ),
  g(
    "Glitch Trap",
    "Trap / Modern",
    "glitch trap, stuttered vocal chops and granular glitch edits on trap drums, rubber-band pitch-warped 808 bass, broken sequencer hi-hat skips, digital artifact bursts, unstable futuristic chaos with abrasive transient spikes",
    "glitch trap, stuttered vocals, granular edits, pitch-warped 808, broken hats, digital artifacts, abrasive transients, chaotic",
    130,
    ["2020s","trap"],
  ),
  g(
    "Neo Trap",
    "Trap / Modern",
    "neo trap, lush neo-soul chord voicings on Rhodes keys under crisp tuned 808 patterns, syncopated rimshot grooves, airy flute or synth lead hooks, warm melodic rap cadence, smooth confident evening-drive energy",
    "neo trap, neo-soul chords, Rhodes keys, tuned 808, rimshot groove, flute lead, melodic rap, evening energy",
    130,
    ["2020s","trap"],
  ),
  g(
    "Lo-Fi Trap",
    "Trap / Modern",
    "lo-fi trap, vinyl crackle and tape wow on dusty swung 808 kicks, muffled low-pass sub slides, muted rimshot groove, mellow Rhodes or guitar sample chops, sleepy nostalgic basement-room warmth at relaxed tempo",
    "lo-fi trap, vinyl crackle, tape wow, dusty 808, low-pass sub, rimshot groove, Rhodes samples, relaxed tempo",
    82,
    ["2020s","trap","lo-fi"],
  ),
  g(
    "Jazz Trap",
    "Trap / Modern",
    "jazz trap, extended jazz chord voicings on upright-bass-like 808 slides, brushed cymbal textures merged with trap snare rolls, muted trumpet or sax sample phrases, improvisational harmonic movement, late-night smoky lounge sophistication",
    "jazz trap, jazz chords, 808 slides, brushed cymbals, trap snare rolls, trumpet samples, harmonic movement, smoky lounge",
    130,
    ["2020s","trap"],
  ),
  g(
    "Hyper Trap",
    "Trap / Modern",
    "hyper trap, hyperpop-speed distorted 808 barrage, machine-gun 32nd-note hi-hat rolls, screaming detuned lead synth arpeggios, hard clipping on every transient, maximal frantic adrenaline rush above 150 BPM intensity",
    "hyper trap, distorted 808 barrage, 32nd hats, detuned arps, hard clipping, frantic energy, 150+ BPM, maximal",
    155,
    ["2020s","trap"],
  ),
  g(
    "Underground Trap",
    "Trap / Modern",
    "underground trap, raw distorted 808 thumps with unquantized swung hat grooves, minimal eerie one-note bell loops, basement tape saturation on drums, confrontational street energy, gritty unpolished vocal delivery with heavy attitude",
    "underground trap, raw 808, unquantized hats, eerie bells, tape saturation, confrontational energy, gritty vocals, minimal",
    130,
    ["2020s","trap"],
  ),
  g(
    "Alien Trap",
    "Trap / Modern",
    "alien trap, microtonal bent synth leads and alien vocoder textures, phase-shifted 808 wobbles, inverse-reverb impacts, bizarre atonal harmonic clusters, extraterrestrial sound design, otherworldly cold isolation with robotic processed vocal drips",
    "alien trap, microtonal synths, vocoder textures, phase-shifted 808, inverse reverb, atonal clusters, robotic vocals, otherworldly",
    130,
    ["2020s","trap"],
  ),
  g(
    "Trap&B",
    "Trap / Modern",
    "trap&b, trap kick and rolling 808 pattern under silky R&B chord progressions on electric piano, intimate falsetto hook space, finger-snaps with soft shaker layers, sensual slow-grind late-night romantic vocal presence",
    "trap&b, trap kick, rolling 808, R&B chords, electric piano, falsetto hooks, finger snaps, sensual vocals",
    130,
    ["2020s","trap"],
  ),
  g(
    "Orchestral Trap",
    "Trap / Modern",
    "orchestral trap hip hop, staccato string section runs and brass stab hits layered over hard trap 808 and snare rolls, timpani-like low hits, dramatic minor-key cinematic swells, epic confrontation energy with orchestral tension building",
    "orchestral trap hip hop, staccato strings, brass stabs, trap 808, snare rolls, timpani hits, minor swells, epic tension",
    130,
    ["2020s","trap"],
  ),
  g(
    "SoundCloud Rap",
    "SoundCloud / Underground",
    "soundcloud rap, lo-fi blown-out drums, warped sample chops, pitched ad-libs, bedroom vocal texture over thin distorted 808s and tape-saturated hi-hats, muted synth pads, late-night scrolling haze",
    "soundcloud rap, lo-fi drums, warped samples, tape 808s, bedroom vocal",
    130,
    ["2020s"],
  ),
  g(
    "Plugg",
    "SoundCloud / Underground",
    "plugg, bouncy sliding 808 sub, bright bell plucks on root-fifth patterns, sparse claps, Memphis plugg bounce at mellow tempo, rubber bass glides between chords while airy digital pads fill negative space",
    "plugg, sliding 808, bell plucks, memphis bounce, sparse claps",
    130,
    ["2020s"],
  ),
  g(
    "Vaportrap",
    "SoundCloud / Underground",
    "vaportrap, vaporwave-slowed trap pocket, chopped soul loops pitched down, drowned reverb snares, washed saw leads over sub-heavy 808, hazy mall-atrium nostalgia bleeding into trap drums",
    "vaportrap, slowed soul chops, washed synths, reverb snares, sub 808",
    130,
    ["2020s","trap"],
  ),
  g(
    "Internet Rap",
    "SoundCloud / Underground",
    "internet rap, hyper-digital beat, meme-sample stabs, pixelated synth bleeps, tight trap hats over rubber 808, ironic bounce, short loop hooks, bright mids, dry vocal pocket, chronically online energy",
    "internet rap, meme samples, digital bleeps, ironic bounce, tight hats",
    130,
    ["2020s"],
  ),
  g(
    "Tumblr Rap",
    "SoundCloud / Underground",
    "tumblr rap, indie-trap crossover, jangly guitar fragments, soft piano chords, emotional minor melodies over muted 808, reverb-heavy snare, whispered hook space, pastel synth pads, intimate bedroom confession vibe",
    "tumblr rap, jangly guitar, soft piano, emotional minor, reverb snare",
    130,
    ["2020s"],
  ),
  g(
    "Blog Era Rap",
    "SoundCloud / Underground",
    "blog era rap, early-2010s bloghouse rap fusion, sidechained synth stabs, four-on-the-floor kick undertow, chopped vocal hooks, festival-ready chords meet trap hats, euphoric pre-streaming hype",
    "blog era rap, sidechain synths, four-on-floor, chopped hooks, supersaw",
    130,
    ["2020s"],
  ),
  g(
    "Alternative Hip Hop",
    "SoundCloud / Underground",
    "alternative hip hop, live drum break textures, odd-meter hi-hat patterns, fuzz bass and analog keys, unconventional song form, art-school rhythm, indie rock guitar undertones, organic swing, cerebral pocket",
    "alternative hip hop, live breaks, odd hats, fuzz bass, analog keys",
    130,
    ["2020s"],
  ),
  g(
    "Abstract Hip Hop",
    "SoundCloud / Underground",
    "abstract hip hop, dissonant jazz chords, spoken-word pocket, found-sound percussion layers, unpredictable bar lengths, free-form bass drones, minimal 808 only for anchor, intellectual texture, collage sampling",
    "abstract hip hop, jazz dissonance, found percussion, free bass, collage samples",
    130,
    ["2020s","experimental"],
  ),
  g(
    "Experimental Rap",
    "SoundCloud / Underground",
    "experimental rap, granular vocal chops, atonal synth clusters, time-stretched drums, sub-bass earthquakes, rule-breaking arrangement, noise bursts, silence gaps, harsh transients meet whispered ambience, laboratory sound design",
    "experimental rap, granular chops, atonal synths, noise bursts, sub earthquakes",
    130,
    ["2020s","experimental"],
  ),
  g(
    "Industrial Hip Hop",
    "SoundCloud / Underground",
    "industrial hip hop, metallic percussion hits, distorted drum machine, grinding synth drones, militant march snare, factory-floor aggression, clangorous stabs, compressed screaming lead, cold mechanical groove, post-punk bass weight",
    "industrial hip hop, metallic hits, drum machine grind, militant snare, cold drones",
    130,
    ["2020s"],
  ),
  g(
    "Art Rap",
    "SoundCloud / Underground",
    "art rap, gallery-installation ambience, minimal piano motif, tape hiss, conceptual silence between hits, sparse 808 for gravity only, spoken cadence pocket, highbrow restraint, museum reverb, intellectual cool",
    "art rap, minimal piano, tape hiss, sparse 808, conceptual silence",
    130,
    ["2020s"],
  ),
  g(
    "Dream Rap",
    "SoundCloud / Underground",
    "dream rap, submerged pads, reverse reverb tails, floating 808 like underwater pressure, soft music-box melody, distant vocal chops, sleep-paralysis tempo, hazy stereo width, gentle kick thump, surreal clouded groove",
    "dream rap, submerged pads, reverse reverb, floating 808, music-box melody",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Psychedelic Rap",
    "SoundCloud / Underground",
    "psychedelic rap, phasing guitar, swirling stereo delays, trippy wah-filtered keys, tabla-adjacent percussion layers, modulated 808 wobble, kaleidoscopic chord movement, mind-bending panning, incense-haze atmosphere",
    "psychedelic rap, phasing guitar, stereo delays, wah keys, modulated 808",
    130,
    ["2020s"],
  ),
  g(
    "Witch Rap",
    "SoundCloud / Underground",
    "witch rap, occult folk samples, detuned harp plucks, ritualistic hand percussion, cauldron-low sub drone, haunted forest ambience, minor pentatonic spells, crackling fire texture, dark feminine energy, ethereal whisper space",
    "witch rap, occult samples, detuned harp, ritual percussion, haunted ambience",
    130,
    ["2020s"],
  ),
  g(
    "Sigilkore Rap",
    "SoundCloud / Underground",
    "sigilkore rap, blown-out distorted 808, occult bell motifs, demonic choir stabs, bitcrushed drum collapse, chaos magic energy, hyper-compressed transients, underground ritual bounce, dark digital sigils in the stereo field",
    "sigilkore rap, distorted 808, occult bells, choir stabs, bitcrushed drums",
    130,
    ["2020s"],
  ),
  g(
    "Hyperpop Rap",
    "SoundCloud / Underground",
    "hyperpop rap, pitched-up chipmunk hooks, maximalist synth stacks, distortion-saturated 808, glittering arp runs, breakcore-adjacent drum fills, emotional screamo melody over candy-coated chaos, extreme brightness, ADHD tempo bursts",
    "hyperpop rap, pitched hooks, maximal synths, distorted 808, breakcore fills",
    155,
    ["2020s"],
  ),
  g(
    "Digicore Rap",
    "SoundCloud / Underground",
    "digicore rap, NES-style square waves, 8-bit drum blips, Game Boy bass lines, anime sample stabs, frantic energy, kawaii melody over crushing 808, internet café nostalgia, pixelated chaos, digital-native bounce",
    "digicore rap, 8-bit waves, gameboy bass, anime stabs, pixel drums",
    130,
    ["2020s"],
  ),
  g(
    "Glitchcore Rap",
    "SoundCloud / Underground",
    "glitchcore rap, buffer-stutter vocal cuts, databent drum glitches, CPU-overload white noise, fractured MIDI melodies, unstable grid, intentional digital errors, seizure-speed hat rolls, cyberpunk breakdown energy, corrupted file aesthetic",
    "glitchcore rap, buffer stutter, databent drums, fractured midi, hat seizures",
    130,
    ["2020s"],
  ),
  g(
    "HexD Rap",
    "SoundCloud / Underground",
    "hexd rap, bitcrushed kick cannon, demonic pitched vocals, chaotic synth squeals, 160 BPM aggression, Frenchcore-adjacent intensity, distorted everything, moshpit-ready low end, cursed internet velocity, pure digital violence",
    "hexd rap, bitcrushed kick, pitched demons, chaotic squeals, 160 bpm",
    130,
    ["2020s"],
  ),
  g(
    "Drain Gang Style",
    "SoundCloud / Underground",
    "drain gang style, blown-out lo-fi trap, sad cloud synths, autotune-ready space, degraded tape compression, melancholic minor chords, sparse hats, emotional emptiness in the mix, icy reverb, lonely 808 glide",
    "drain gang, blown-out trap, sad cloud synths, tape compression, icy reverb",
    130,
    ["2020s","melancholic"],
  ),
  g(
    "Opium Style",
    "SoundCloud / Underground",
    "opium style, dark avant-garde trap, detuned synth leads, distorted rage textures, underground fashion rap energy, raw experimental drums, punk-trap crossover aggression, black leather atmosphere, mosh pit 808, chaotic high-end shards",
    "opium style, avant-garde trap, detuned leads, rage textures, punk-trap drums",
    130,
    ["2020s"],
  ),
  g(
    "Boom Bap",
    "Old School / Classic",
    "boom bap, mpc swung kick on two and four, dusty jazz sample chops, crisp snare crack, vinyl crackle, head-nod swing pocket, sparse upright bass, dj scratch breakdown lane, golden-era crate-digger drum science",
    "boom bap, mpc swing, jazz chops, vinyl dust, scratches",
    92,
    ["2020s","1990s"],
  ),
  g(
    "Jazz Rap",
    "Old School / Classic",
    "jazz rap, upright bass walking loop, brushed snare shuffle, rhodes chord voicings, flute and horn sample collage, poetic cadence pocket, tribe-era warmth, live kit swing over chopped soul breaks",
    "jazz rap, upright bass, rhodes, horn samples, live swing",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Conscious Rap",
    "Old School / Classic",
    "conscious rap, gospel organ stabs, uplifting soul horn section, thoughtful boom-bap groove, call-and-response hook space, message-driven cadence room, warm analog keys, restrained drum break for lyrical clarity",
    "conscious rap, gospel keys, soul horns, boom bap, uplifting",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Political Hip Hop",
    "Old School / Classic",
    "political hip hop, militant breakbeat density, siren and noise-layer stabs, public enemy-style collage samples, protest chant hook lane, hard snare on two, tense minor keys, spoken-word urgency in the pocket",
    "political hip hop, breakbeats, sirens, collage samples, militant",
    130,
    ["2020s","1990s"],
  ),
  g(
    "G-Funk",
    "Old School / Classic",
    "g-funk, sine moog bass glide, portamento synth leads, talk-box melody lane, laid-back west coast shuffle, p-funk whistle motifs, gangsta narrative swing, sunny minor-seven keys, low-rider tempo glide",
    "g-funk, moog bass, talk box, west coast, p-funk",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Mafioso Rap",
    "Old School / Classic",
    "mafioso rap, cinematic string swells, minor piano crime-drama chords, dark boom-bap drums, luxury tension atmosphere, italian film-score influence, narrative villain cadence space, brooding bass movement",
    "mafioso rap, strings, minor piano, dark boom bap, cinematic",
    130,
    ["2020s","1990s"],
  ),
  g(
    "East Coast Rap",
    "Old School / Classic",
    "east coast rap, crispy sp-1200 snare crack, subway-grit sample flips, lyrical punchline pocket, nyc boom-bap density, jazz-soul chop collage, head-nod two-and-four kick science, competitive cipher energy",
    "east coast rap, sp-1200, sample flips, boom bap, nyc grit",
    130,
    ["2020s","1990s"],
  ),
  g(
    "West Coast Rap",
    "Old School / Classic",
    "west coast rap, funky key gliss lines, bounce clap pattern, sunny synth pad layers, low-rider tempo, melodic gangsta narrative space, west-side shuffle hats, smooth bass glide under talk-ready hooks",
    "west coast rap, funk keys, bounce clap, synth pads, low-rider",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Southern Hip Hop",
    "Old School / Classic",
    "southern hip hop, trunk-rattling 808 sub pressure, bounced double hi-hats, porch-party chant hooks, drawled cadence pocket, soul-clap swing, regional storytelling room, humid night-drive bass movement",
    "southern hip hop, 808 sub, bounced hats, chants, soul clap",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Dirty South",
    "Old School / Classic",
    "dirty south, earthquake 808 slides, whistle lead riffs, strip-club bounce cadence, trunk-knock kick pattern, chant hook repeats, sweaty club sub pressure, atlanta lean pocket with sparse melodic stabs",
    "dirty south, 808 slides, whistle lead, bounce, trunk knock",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Memphis Rap",
    "Old School / Classic",
    "memphis rap, foggy horror synth pads, lo-fi drum machine grit, menacing half-time chants, phonk-precursor darkness, distorted bass murk, cassette-warble texture, intimidation cadence lane, minimal melody tension",
    "memphis rap, horror synths, lo-fi drums, half-time, phonk dark",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Crunk",
    "Old School / Classic",
    "crunk, shouting call-response hooks, distorted 808 stomps, squeal synth riffs, sweaty club mosh tempo, hype chant density, kick-driven energy bursts, mosh-pit drum aggression, atlanta party-war cadence space",
    "crunk, call-response, distorted 808, squeal synth, club mosh",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Snap Music",
    "Old School / Classic",
    "snap music, finger-snap clap grid, minimalist 808 tick pattern, atlanta lean bounce, chant hook repeats, skeletal melody stabs, dancefloor snap cadence, stripped kick-hat pocket, instant hook memorability lane",
    "snap music, finger snaps, minimal 808, lean bounce, chants",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Hyphy",
    "Old School / Classic",
    "hyphy, high-bpm slap groove, siren synth stabs, fuzzy bass drops, bay area sideline energy, whistle and clap hype layers, trunk-rattle sub bursts, party-go cadence space, frenetic hat rolls",
    "hyphy, slap groove, siren synths, fuzzy bass, bay area",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Horrorcore",
    "Old School / Classic",
    "horrorcore, demonic minor-key pads, reversed cymbal sweeps, whisper ad-lib lanes, slasher-film tension drums, eerie choir stabs, nightmare narrative cadence, dissonant bell motifs, graveyard half-time pocket",
    "horrorcore, minor pads, reversed cymbals, dissonant, half-time",
    130,
    ["2020s","1990s","aggressive"],
  ),
  g(
    "Hardcore Rap",
    "Old School / Classic",
    "hardcore rap, aggressive breakbeat density, shouted delivery pocket, punk-crossover guitar stabs optional, rapid-fire lyrical lane, hard snare attack, street battle intensity, no-frills drum violence, confrontational hook space",
    "hardcore rap, breakbeats, shouted flow, punk guitar, aggressive",
    130,
    ["2020s","1990s","aggressive"],
  ),
  g(
    "Backpack Rap",
    "Old School / Classic",
    "backpack rap, raw mpc grit drums, literary wordplay cadence room, indie jazz sample layers, anti-commercial diy warmth, obscure crate-digger chops, cipher-friendly sparse hooks, basement boom-bap science",
    "backpack rap, mpc grit, jazz samples, crate digger, cipher",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Golden Era Hip Hop",
    "Old School / Classic",
    "golden era hip hop, 1993 sp-1200 swing, parliament funk sample flips, crate-digger chop collage, lyrical posse-cut vibe, head-nod break science, classic two-and-four snare, era-defining drum warmth",
    "golden era, sp-1200, funk samples, chop collage, posse cut",
    92,
    ["2020s","1990s"],
  ),
  g(
    "Freestyle Rap",
    "Old School / Classic",
    "freestyle rap, sparse boom drum breaks, battle cypher pocket, instant lyrical flip cadence, park-jam atmosphere, minimal melody for mc focus, raw snare crack, open instrumental space, competitive flow lane",
    "freestyle rap, boom breaks, cypher, battle flow, park jam",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Old School Party Rap",
    "Old School / Classic",
    "old school party rap, sugarhill drum machine bounce, disco funk bassline drive, crowd chant hook space, block-party celebration energy, early hip-hop break flavor, call-and-response party cadence, vintage drumbox swing",
    "old school party, drum machine, disco funk, crowd chants, block party",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Turntablism",
    "Old School / Classic",
    "turntablism, scratch-friendly breakbeat loops, transformer cut showcase space, solo dj rhythm architecture, minimal vocal dominance, battle-break drum science, crossfader choreography lane, classic b-boy break selection energy",
    "turntablism, breaks, scratches, transformer cuts, b-boy",
    92,
    ["2020s","1990s"],
  ),
  g(
    "Gangsta Rap",
    "Old School / Classic",
    "gangsta rap, menacing moog bass movement, crime narrative tension drums, street realism cadence pocket, west or east regional drum dialect, talk-ready melodic space, hard snare authority, narrative villain atmosphere",
    "gangsta rap, moog bass, crime narrative, street drums, menacing",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Underground Boom Bap",
    "Old School / Classic",
    "underground boom bap, gritty basement drum texture, obscure sample flips, cipher lyrical density, indie-label rawness, anti-mainstream chop science, dusty snare crack, head-nod swing, minimal hook interference",
    "underground boom bap, gritty drums, obscure samples, cipher, raw",
    92,
    ["2020s","1990s"],
  ),
  g(
    "Lo-Fi Boom Bap",
    "Old School / Classic",
    "lo-fi boom bap, tape-saturated kick thump, muffled snare warmth, rainy-day jazz chord loops, bedroom study-beat texture, wobble wow flutter, soft vinyl hiss, introspective cadence pocket, gentle swing",
    "lo-fi boom bap, tape saturation, jazz chords, vinyl hiss, bedroom",
    92,
    ["2020s","1990s","lo-fi"],
  ),
  g(
    "Neo Boom Bap",
    "Old School / Classic",
    "neo boom bap, contemporary crisp drums referencing golden-era chops, updated mpc swing, modern soul sample sensibility, clean head-nod pocket without losing grit, lyrical space priority, tasteful horn stabs",
    "neo boom bap, crisp drums, soul samples, mpc swing, head-nod",
    92,
    ["2020s","1990s"],
  ),
  g(
    "UK Drill",
    "Drill / Aggressive",
    "uk drill, sliding 808 glide bass on minor-two dark melodies, offbeat syncopated hi-hat skanks with mute rolls, sparse clap snare, shaker textures, cold London head-top energy, deadpan drill vocal cadence and ad-libs",
    "uk drill, sliding 808, minor-two melody, offbeat hats, mute rolls, sparse clap, shaker, deadpan vocals, cold energy",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "NY Drill",
    "Drill / Aggressive",
    "ny drill, bouncy NYC drill 808 patterns with sharp snare cracks, playful manic synth squeaks, sliding bass hits on Brooklyn bounce, aggressive staccato delivery space, party confrontational energy hotter than UK coldness",
    "ny drill, bouncy 808, sharp snare, manic synth squeaks, sliding bass, Brooklyn bounce, staccato vocals, party energy",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Dark Drill",
    "Drill / Aggressive",
    "dark drill, even deeper detuned sliding 808s on tritone-heavy minor loops, minimal haunted bell samples, tombstone-slow half-time hats, oppressive sub pressure, sinister paranoid street atmosphere with barely-there vocal breath",
    "dark drill, detuned 808 slides, tritone minor, haunted bells, half-time hats, oppressive sub, paranoid atmosphere, vocal breath",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Cinematic Drill",
    "Drill / Aggressive",
    "cinematic drill, film-score string sustains and brass hits under drill sliding bass and rapid hats, sweeping risers and impact FX, tense chase-scene narrative arc, dramatic pauses then bass drops, epic urban crime thriller mood",
    "cinematic drill, string sustains, brass hits, sliding bass, rapid hats, risers, impact FX, bass drops, thriller mood",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Rage Drill",
    "Drill / Aggressive",
    "rage drill, blown distortion on sliding drill 808s, chaotic triplet hat bursts, screeching synth lead chaos over dark drill melody, mosh intensity meeting drill syncopation, furious shouted vocal energy with crowd-chant ad-lib space",
    "rage drill, blown 808 distortion, triplet hats, screeching synths, drill syncopation, shouted vocals, crowd chants, mosh intensity",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Horror Drill",
    "Drill / Aggressive",
    "horror drill, chromatic horror piano stabs against drill slide bass and skippy hats, reversed cymbal whooshes, creepy whisper FX, sudden sub shock drops, night-terror stalking atmosphere with menacing monotone drill delivery",
    "horror drill, chromatic piano, slide bass, skippy hats, reversed cymbals, whisper FX, sub shocks, monotone delivery",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Melo Drill",
    "Drill / Aggressive",
    "melo drill, bittersweet minor-key arpeggiated guitar or pluck melodies over classic drill slide bass and hat patterns, R&B-influenced chord pads, emotional sung hook pockets, reflective sorrowful energy softer than pure aggression",
    "melo drill, minor arpeggios, guitar plucks, slide bass, drill hats, R&B chord pads, sung hooks, sorrowful energy",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Hyper Drill",
    "Drill / Aggressive",
    "hyper drill, drill sliding 808s pushed to extreme tempos with dense 32nd hi-hat barrages, stuttering vocal chops, maximal drum density, sprinting aggression, breathless energy beyond standard drill BPM with relentless forward drive",
    "hyper drill, sliding 808, 32nd hat barrage, stuttered vocals, maximal drums, extreme tempo, breathless energy, relentless drive",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Trap Drill",
    "Drill / Aggressive",
    "trap drill, trap triplet hi-hat rolls fused with drill slide-bass glides and skippy offbeats, hybrid snare clap layering, dark bell synth motifs from both worlds, menacing half-time to double-time switch energy",
    "trap drill, triplet hats, slide-bass glides, skippy offbeats, hybrid snare, dark bells, half-time switch, menacing energy",
    142,
    ["2020s","trap","aggressive"],
  ),
  g(
    "Orchestral Drill",
    "Drill / Aggressive",
    "orchestral drill, low brass stabs and tremolo string ostinatos riding drill sliding 808 bass and skippy hat patterns, timpani rolls into bass drops, epic gothic-urban confrontation, war-march intensity with drill cadence pockets",
    "orchestral drill, brass stabs, tremolo strings, sliding 808, skippy hats, timpani rolls, bass drops, war-march intensity",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Experimental Drill",
    "Drill / Aggressive",
    "experimental drill, unconventional time-feel shifts and polyrhythmic hat phasing over mutated slide-bass textures, prepared-piano hits, aleatoric noise bursts, deconstructed drill form, intellectual abrasive avant energy with spoken abstract vocal fragments",
    "experimental drill, time-feel shifts, polyrhythmic hats, mutated 808, prepared piano, aleatoric noise, deconstructed form, abstract vocals",
    142,
    ["2020s","aggressive","experimental"],
  ),
  g(
    "Detroit Rap",
    "Regional / Internet",
    "detroit rap, fast punchy drums, energetic 808 bass, quirky piano melodies, off-beat rhythmic flows, minimal production, street atmosphere, modern Michigan rap sound around 140 bpm",
    "detroit rap, punchy drums, 808 bass, quirky piano, off-beat flows, 140 bpm",
    130,
    ["2020s"],
  ),
  g(
    "Flint Rap",
    "Regional / Internet",
    "flint rap, speaker-rattling 808 sequences, skeletal two-note melody, bare-room intimidation tempo, minimal harmonic movement, aggressive cadence lane, midwest trap precursor darkness, trunk-knock sub science, cold empty-space reverb",
    "flint rap, 808 sequences, skeletal melody, intimidation, minimal",
    130,
    ["2020s"],
  ),
  g(
    "Michigan Trap",
    "Regional / Internet",
    "michigan trap, arpeggiated bell synth riffs, sliding 808 patterns, cold midwest winter ambiance, icy minor keys, rapid hat rolls, sparse melodic intimidation, detroit-area dark club energy, sub glide movement",
    "michigan trap, bell arps, sliding 808, icy minor, hat rolls",
    130,
    ["2020s","trap"],
  ),
  g(
    "Jersey Club Rap",
    "Regional / Internet",
    "jersey club rap, bed squeak kick pattern, four-on-floor club bounce fused with rap cadence, rapid kick rolls, ballroom-influenced energy, high-bpm chant hooks, east coast club-rap hybrid pocket, percussive bounce science",
    "jersey club rap, bed squeak, kick rolls, four-on-floor, chants",
    138,
    ["2020s"],
  ),
  g(
    "Philly Club Rap",
    "Regional / Internet",
    "philly club rap, ballroom kick pattern influence, soul clap sample layers, high-energy east coast club-rap fusion, rapid percussive bounce, chant hook density, regional party cadence, sweaty dancefloor sub drive",
    "philly club rap, ballroom kicks, soul claps, bounce, party energy",
    138,
    ["2020s"],
  ),
  g(
    "Bay Area Rap",
    "Regional / Internet",
    "bay area rap, talk-box melodic hints, hyphy-influenced slap groove, west coast funk bounce, regional slang hook space, siren synth accents, trunk-rattle sub bursts, sideline party cadence, northern california shuffle",
    "bay area rap, talk box, slap groove, funk bounce, hyphy",
    130,
    ["2020s"],
  ),
  g(
    "Chopped & Screwed",
    "Regional / Internet",
    "chopped & screwed, half-tempo syrup drag, pitch-shifted vocal lane space, houston purple lean atmosphere, syrupy reverb wash, trunk-rumble sub, slow-motion hat ticks, cassette-deck warp texture, hypnotic repetition hooks",
    "chopped screwed, half tempo, pitch shift, syrupy reverb, houston",
    68,
    ["2020s"],
  ),
  g(
    "Houston Slowed",
    "Regional / Internet",
    "houston slowed, screwed tape warp texture, sub-heavy trunk rumble, candy-paint shimmer synths, lean-paced cadence pocket, slow 808 glide, chopped vocal fragment space, humid night-drive atmosphere, hypnotic loop hypnosis",
    "houston slowed, tape warp, trunk sub, shimmer synths, lean pace",
    72,
    ["2020s"],
  ),
  g(
    "Memphis Revival",
    "Regional / Internet",
    "memphis revival, phonk cowbell stabs, memphis sample loop resurrection, distorted 808 murk, modern dark trap-boom hybrid, cassette grit revival, menacing half-time chants, horror-synth nostalgia updated for streaming era",
    "memphis revival, phonk cowbell, sample loops, distorted 808, dark",
    130,
    ["2020s"],
  ),
  g(
    "Cali Bounce",
    "Regional / Internet",
    "cali bounce, g-funk melodic bounce meets modern slap drums, sunny chord stacks, dancefloor west coast glide, low-rider tempo feel, talk-ready hook lane, coastal party energy, smooth bass glide under regional cadence",
    "cali bounce, g-funk melody, slap drums, sunny chords, low-rider",
    130,
    ["2020s"],
  ),
  g(
    "DMV Flow",
    "Regional / Internet",
    "dmv flow, go-go percussion pocket inspiration, mid-atlantic rhythmic bounce, local chant energy, live drum break flavor, regional slang cadence lane, clap-driven party science, baltimore-dc hybrid groove tension",
    "dmv flow, go-go percussion, mid-atlantic bounce, chants, clap groove",
    130,
    ["2020s"],
  ),
  g(
    "UK Rap",
    "Regional / Internet",
    "uk rap, grime-influenced sub bass weight, sparse 140-drop pockets, london road narrative cadence, icy minor synths, rapid lyrical lane, uk garage hat influence optional, metropolitan tension atmosphere",
    "uk rap, grime sub, 140 drops, icy synths, london narrative",
    130,
    ["2020s"],
  ),
  g(
    "Grime Rap",
    "Regional / Internet",
    "grime rap, square-wave synth bass stabs, 140 bpm stop-start rhythm, mc clash energy, eskibeat darkness optional, rapid reload drum pattern, london estate narrative cadence, aggressive minimal melody lane",
    "grime rap, square-wave bass, 140 bpm, mc clash, eskibeat",
    140,
    ["2020s"],
  ),
  g(
    "Afro Trap",
    "Regional / Internet",
    "afro trap, diaspora log drum fusion, melodic minor arabic-scale flute lines, 808 with afrobeats swing, percolating shaker layers, cross-continental hook cadence, tropical percussion meets trap hat science",
    "afro trap, log drums, arabic flute, afrobeats swing, shakers",
    130,
    ["2020s","trap"],
  ),
  g(
    "French Trap",
    "Regional / Internet",
    "french trap, ouf autotune aesthetic space, european minor melody leads, sleek paris-banlieue urban cadence, trap 808 with continental synth stacks, french lyrical flow pocket, night-drive neon minor keys",
    "french trap, autotune, european minor, paris urban, trap 808",
    130,
    ["2020s","trap"],
  ),
  g(
    "Brazilian Trap",
    "Regional / Internet",
    "brazilian trap, baile funk tamborzão rhythm influence, portuguese hook cadence space, tropical percussion with 808 sub, favela-party energy, melodic minor brass optional, rapid bounce hat pattern, carioca club heat",
    "brazilian trap, tamborzao, portuguese hooks, tropical perc, 808",
    130,
    ["2020s","trap"],
  ),
  g(
    "Japanese Trap",
    "Regional / Internet",
    "japanese trap, crisp hi-hat roll science, tokyo club synth stacks, kawaii minor melody optional, shibuya night energy, sparse intimidating 808 pocket, japanese lyrical cadence lane, electronic city-pop chord hints",
    "japanese trap, hat rolls, tokyo synths, kawaii minor, shibuya",
    130,
    ["2020s","trap"],
  ),
  g(
    "Korean Hip Hop",
    "Regional / Internet",
    "korean hip hop, r&b-influenced chord stacks, korean lyrical flow pocket, seoul urban night atmosphere, boom-trap hybrid drums, melodic hook sensibility, k-hip-hop session energy, subtle 808 sub without trap cliché overload",
    "korean hip hop, rnb chords, seoul urban, boom-trap, melodic hooks",
    130,
    ["2020s"],
  ),
  g(
    "Sadboy Rap",
    "Emotional / Atmospheric",
    "sadboy rap, crying piano loops, soft trap snare, gentle 808 heartbeat, autotune-ready melancholy space, lonely bedroom tears, rain-on-window pad, minor key confession, fragile vocal pocket, understated drums",
    "sadboy rap, crying piano, soft snare, gentle 808, rain pads",
    130,
    ["2020s","melancholic"],
  ),
  g(
    "Emotional Rap",
    "Emotional / Atmospheric",
    "emotional rap, soaring string swells, vulnerable chord progression, dynamic trap drums from whisper to impact, cathartic build-ups, raw feeling in melody, sincere major-minor shifts, human voice space, cinematic rise, tearful release",
    "emotional rap, string swells, vulnerable chords, dynamic trap, cathartic builds",
    130,
    ["2020s"],
  ),
  g(
    "Melancholic Hip Hop",
    "Emotional / Atmospheric",
    "melancholic hip hop, gray-scale piano, slow swung drums, heavy reverb snare, descending bass line, autumn-leaf sadness, overcast sky pads, unresolved harmonic tension, contemplative pace, beautiful sorrow without rage",
    "melancholic hip hop, gray piano, slow drums, heavy reverb, descending bass",
    130,
    ["2020s","melancholic"],
  ),
  g(
    "Dreamy Hip Hop",
    "Emotional / Atmospheric",
    "dreamy hip hop, cotton-candy synth clouds, slow-motion hats, velvety 808, lullaby chord movement, half-asleep groove, pastel harmonies, floating stereo delay, soft focus melody, pillow-soft kick, sunlight haze",
    "dreamy hip hop, cotton synths, slow hats, velvety 808, lullaby chords",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Rainy Night Rap",
    "Emotional / Atmospheric",
    "rainy night rap, rainstick percussion layers, distant thunder sub, neon-reflection synth pads, wet pavement reverb, umbrella-walk tempo, jazz-influenced chords, cozy isolation, window-glass melody, 2 AM streetlight glow",
    "rainy night rap, rain percussion, thunder sub, neon pads, jazz chords",
    130,
    ["2020s","melancholic"],
  ),
  g(
    "Midnight Rap",
    "Emotional / Atmospheric",
    "midnight rap, deep blue minor keys, clock-tick percussion, low-pass filtered melody, city-after-hours silence, moonlit 808, sparse arrangement, insomniac thoughts in the pocket, dark room ambience, 3 AM clarity",
    "midnight rap, deep minor keys, clock percussion, low-pass melody, moonlit 808",
    130,
    ["2020s"],
  ),
  g(
    "Liminal Hip Hop",
    "Emotional / Atmospheric",
    "liminal hip hop, empty hallway reverb, fluorescent hum drone, uncanny calm drums, backrooms unease, transitional space melody, neither scary nor safe, suspended chord pads, familiar yet wrong, infinite corridor bounce",
    "liminal hip hop, hallway reverb, fluorescent hum, uncanny drums, backrooms unease",
    130,
    ["2020s"],
  ),
  g(
    "Ethereal Rap",
    "Emotional / Atmospheric",
    "ethereal rap, angelic choir pads, harp glissandi, gossamer hi-hats, heaven-sent 808 below clouds, weightless stereo field, sacred minor lift, translucent vocal space, otherworldly brightness, cathedral reverb tail",
    "ethereal rap, choir pads, harp gliss, gossamer hats, heaven 808",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Space Rap",
    "Emotional / Atmospheric",
    "space rap, cosmic synth pads, satellite beep motifs, zero-gravity 808, orbital hat patterns, nebula chord swells, black-hole sub pressure, astronaut loneliness, deep space reverb, starfield arpeggios, interstellar drift tempo",
    "space rap, cosmic pads, satellite beeps, zero-g 808, nebula chords",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Spiritual Hip Hop",
    "Emotional / Atmospheric",
    "spiritual hip hop, gospel organ stabs, choir hum samples, conscious chord movement, uplifting 808 foundation, meditation bell accents, incense-smoke pads, soul-searching melody, inner peace groove, temple reverb, higher-self energy",
    "spiritual hip hop, gospel organ, choir hum, meditation bells, uplifting 808",
    130,
    ["2020s"],
  ),
  g(
    "Luxury Melancholy",
    "Emotional / Atmospheric",
    "luxury melancholy, silk-string samples, champagne-room piano, expensive reverb, sad eyes behind designer shades, velvet 808, gold-chain minor chords, penthouse loneliness, high-end sorrow, marble-floor echo, wealth cannot heal ache",
    "luxury melancholy, silk strings, champagne piano, velvet 808, penthouse sadness",
    130,
    ["2020s","melancholic","smooth"],
  ),
  g(
    "Nostalgic Rap",
    "Emotional / Atmospheric",
    "nostalgic rap, faded photograph melody, vinyl crackle layer, old-school sample flip, memory-lane chord loop, bittersweet reminiscence, childhood summer keys, dusty drum break, looking backward with love, warm tape saturation",
    "nostalgic rap, faded melody, vinyl crackle, sample flip, memory chords",
    130,
    ["2020s"],
  ),
  g(
    "VHS Rap",
    "Emotional / Atmospheric",
    "vhs rap, tracking-error wobble, CRT hum undertone, degraded 90s sample chops, magnetic tape wow, home-video grain, camcorder-datestamp energy, fuzzy low-pass highs, analog warmth, rewind-button nostalgia, fuzzy childhood footage",
    "vhs rap, tracking wobble, crt hum, tape wow, degraded 90s chops",
    82,
    ["2020s"],
  ),
  g(
    "Y2K Rap",
    "Emotional / Atmospheric",
    "y2k rap, glossy 2000s synths, flip-phone melody, TRL-era chord stabs, early-digital optimism, shiny production sheen, butterfly-clip nostalgia, pre-smartphone innocence, bright major lift, chunky 808, millennium-party flash",
    "y2k rap, glossy 2000s synths, flip-phone melody, trl chords, bright 808",
    130,
    ["2020s","2000s"],
  ),
  g(
    "Digital Nostalgia Rap",
    "Emotional / Atmospheric",
    "digital nostalgia rap, Windows XP startup tones, dial-up texture, MySpace-era synth leads, pixel-heart sadness, early-internet emotional residue, CRT-blue chord palette, deleted-profile longing, cached memory melody, soft glitch tears",
    "digital nostalgia rap, xp tones, dial-up texture, myspace synths, soft glitch",
    130,
    ["2020s"],
  ),
  g(
    "Edit Audio Rap",
    "TikTok / Viral Era",
    "edit audio rap, razor-sharp hook stabs over tight trap claps, dramatic half-bar stops for meme edits, impact risers, punchy 808 drops built for fifteen-second clip cuts",
    "edit audio rap, hook stabs, trap claps, clip cuts",
    130,
    ["2020s"],
  ),
  g(
    "Sigma Rap",
    "TikTok / Viral Era",
    "sigma rap, distorted cowbell lead, Memphis sub slides, military snare rolls, motivational hard-trap drums, gym montage swagger, alpha-edit phonk undertones and aggressive chant-ready hook pockets",
    "sigma rap, cowbell, Memphis sub, gym montage phonk",
    130,
    ["2020s"],
  ),
  g(
    "Drift Rap",
    "TikTok / Viral Era",
    "drift rap, drifting cowbell melody over sliding 808 glide, tire-screech FX layers, night highway trap groove, Brazilian phonk swing, car edit energy, smoky bass weight",
    "drift rap, cowbell glide, 808 slides, car edit phonk",
    135,
    ["2020s"],
  ),
  g(
    "Gym Rap",
    "TikTok / Viral Era",
    "gym rap, pounding kick-forward trap drums, brass stab lifts, gritty 808 chest hits, pre-drop silence gaps, pump-up vocal chant space, high-energy resistance-training montage drive",
    "gym rap, trap drums, brass stabs, pump-up 808s",
    135,
    ["2020s"],
  ),
  g(
    "Anime Trap",
    "TikTok / Viral Era",
    "anime trap, emotional minor piano chords, orchestral string swells over trap hats, J-rock guitar flick accents, dramatic anime AMV build, supersaw drop release, bittersweet melody lead",
    "anime trap, piano strings, trap hats, AMV build",
    130,
    ["2020s","trap"],
  ),
  g(
    "Viral Trap",
    "TikTok / Viral Era",
    "viral trap, catchy whistle lead hook, bright detuned synth plucks, bounce-house 808 pattern, TikTok loop-friendly two-bar repetition, finger-snap pocket groove, instant recall melody",
    "viral trap, whistle hook, synth plucks, loop-friendly 808",
    130,
    ["2020s","trap"],
  ),
  g(
    "Bass Boosted Rap",
    "TikTok / Viral Era",
    "bass boosted rap, sub-destroyer sine 808 tail, clipped low-end saturation, meme-edit loud kick thump, distorted bass wobble, ear-rattling sub octaves, minimal midrange pocket",
    "bass boosted rap, saturated 808, sub wobble, loud kick",
    130,
    ["2020s"],
  ),
  g(
    "Nightcore Rap",
    "TikTok / Viral Era",
    "nightcore rap, sped-up pitched vocal feel, bright supersaw chords, fast hi-hat rolls at rave tempo, trance-pop trap fusion, anime adrenaline rush, euphoric chip-tune arp layer",
    "nightcore rap, supersaw, fast hats, trance-pop trap",
    155,
    ["2020s"],
  ),
  g(
    "Slowed + Reverb Rap",
    "TikTok / Viral Era",
    "slowed + reverb rap, time-stretched vocal texture, cathedral reverb wash over deep 808 pulse, vinyl crackle bed, mournful piano droplets, dreamy half-speed heartbreak edit groove",
    "slowed reverb rap, stretched vocals, deep 808, vinyl piano",
    72,
    ["2020s"],
  ),
  g(
    "Hyper Edit Rap",
    "TikTok / Viral Era",
    "hyper edit rap, chopped vocal stutter edits, glitch hop percussion bursts, sidechain pump drops every bar, sped trap chaos, datamosh SFX hits, ADHD short-form montage frenzy",
    "hyper edit rap, vocal chops, glitch drums, sidechain pump",
    155,
    ["2020s"],
  ),
  g(
    "Cinematic Edit Rap",
    "TikTok / Viral Era",
    "cinematic edit rap, taiko drum hits blended with trap 808, brass fanfare stabs, trailer whoosh transitions, epic strings under mumbled rap pocket, movie recap edit crescendo energy",
    "cinematic edit rap, taiko brass, strings, trailer whoosh",
    130,
    ["2020s"],
  ),
  g(
    "AMV Rap",
    "TikTok / Viral Era",
    "amv rap, syncopated battle-scene drum pattern, emotional anime chord loop, sword-clash percussion layers, soaring lead at chorus, shonen fight montage intensity, bittersweet drop turnaround",
    "AMV rap, anime chords, battle drums, shonen energy",
    130,
    ["2020s"],
  ),
  g(
    "Phonk Rap",
    "TikTok / Viral Era",
    "phonk rap, Memphis sample chop, cowbell hook loop, dusty vinyl crackle, distorted 808 boom-bap hybrid, drift tape warble, underground Memphis phonk rap pocket groove",
    "phonk rap, Memphis chop, cowbell, dusty 808",
    135,
    ["2020s"],
  ),
  g(
    "Rage Edit Music",
    "TikTok / Viral Era",
    "rage edit music, squealing rage synth lead, moshing trap drums, crowd noise layers, distorted 808 chaos, mosh-pit edit aggression, machine-gun hi-hat bursts, ear-splitting drop impact",
    "rage edit, rage synth, mosh drums, distorted 808",
    130,
    ["2020s","aggressive"],
  ),
  g(
    "Runway Rap",
    "Luxury / Fashion / Aesthetic",
    "runway rap, minimalist Roland drum machine click, catwalk four-on-the-floor under luxury 808, glossy synth pads, model walk tempo swagger, fashion show bass runway strut groove",
    "runway rap, drum machine, catwalk bass, glossy pads",
    130,
    ["2020s"],
  ),
  g(
    "Fashion Week Rap",
    "Luxury / Fashion / Aesthetic",
    "fashion week rap, couture harp plucks over slick trap hats, champagne bubble FX, velvet bass glide, Paris show front-row energy, elegant minor-key melody, curator-approved pocket",
    "fashion week rap, harp plucks, velvet 808, couture trap",
    130,
    ["2020s","smooth"],
  ),
  g(
    "Designer Trap",
    "Luxury / Fashion / Aesthetic",
    "designer trap, cash-register coin FX, silk-string sample loop, crisp hi-end 808 sparkle, boutique luxury chord voicings, branded-logo synth blips, exclusive velvet night-club groove",
    "designer trap, silk strings, coin FX, boutique chords",
    130,
    ["2020s","trap","smooth"],
  ),
  g(
    "Luxury Rap",
    "Luxury / Fashion / Aesthetic",
    "luxury rap, Rhodes electric piano jazz chords, champagne-room sub warmth, smooth syncopated snare pattern, gold-chain shaker percussion, penthouse sunset melody, understated wealth swagger pocket",
    "luxury rap, Rhodes piano, warm sub, penthouse groove",
    130,
    ["2020s","smooth"],
  ),
  g(
    "Avant-Garde Hip Hop",
    "Luxury / Fashion / Aesthetic",
    "avant-garde hip hop, prepared piano clangs, aleatoric percussion clusters, dissonant harp clusters over sub pulse, gallery-installation spatial delays, unconventional bar lengths, experimental art-world rhythmic fractures",
    "avant-garde hip hop, prepared piano, dissonant harp, experimental bars",
    130,
    ["2020s","experimental"],
  ),
  g(
    "Art Gallery Rap",
    "Luxury / Fashion / Aesthetic",
    "art gallery rap, muted upright bass pizzicato, white-cube reverb tails, sparse brush snare, contemplative Rhodes loops, museum whisper vocal space, abstract painting chord colors, restrained intellectual groove",
    "art gallery rap, pizzicato bass, Rhodes loops, white-cube space",
    130,
    ["2020s"],
  ),
  g(
    "Cyber Luxury Trap",
    "Luxury / Fashion / Aesthetic",
    "cyber luxury trap, chrome-dipped synth arps, gated luxury 808, holographic pad sheen, neon boutique bass slides, high-fashion tech runway cyberpulse, diamond-cut digital hi-hats",
    "cyber luxury trap, chrome arps, holographic pads, neon 808",
    130,
    ["2020s","trap","smooth"],
  ),
  g(
    "Chrome Trap",
    "Luxury / Fashion / Aesthetic",
    "chrome trap, metallic FM bell lead, mirror-polish synth reflections, liquid chrome bass wobbles, robotic trap hats, futuristic jewelry shine timbre, reflective Y2K chrome groove",
    "chrome trap, FM bells, chrome bass wobble, robotic hats",
    130,
    ["2020s","trap"],
  ),
  g(
    "Neo Fashion Rap",
    "Luxury / Fashion / Aesthetic",
    "neo fashion rap, underground runway hats, minimalist couture 808 slides, editorial camera-shutter FX, high-fashion mag cover bass, sleek monochrome melody, 2020s street-luxe crossover pocket",
    "neo fashion rap, couture 808, shutter FX, street-luxe melody",
    130,
    ["2020s","smooth"],
  ),
  g(
    "Futuristic Hip Hop",
    "Luxury / Fashion / Aesthetic",
    "futuristic hip hop, laser-grid synth bass, orbital pad atmospheres, robotic vocoder chant pockets, ion-drive kick pattern, space-station corridor reverb, tomorrow-city hi-tech percussion grid",
    "futuristic hip hop, laser bass, orbital pads, vocoder chant",
    130,
    ["2020s"],
  ),
  g(
    "Editorial Rap",
    "Luxury / Fashion / Aesthetic",
    "editorial rap, magazine-page turn percussion, Vogue-cover string stabs, black-and-white film noir bass, photographic shutter trap hats, high-gloss stylistic minimal pocket, fashion-editor melody restraint",
    "editorial rap, string stabs, noir bass, shutter hats",
    130,
    ["2020s"],
  ),
  g(
    "Minimal Trap",
    "Luxury / Fashion / Aesthetic",
    "minimal trap, sparse kick-only pocket, single-note marimba motif, negative space between hits, refined one-oscillator sub tone, whisper hi-hats, less-is-more boutique restraint groove",
    "minimal trap, sparse kick, marimba motif, restrained sub",
    130,
    ["2020s","trap"],
  ),
  g(
    "Opulent Trap",
    "Luxury / Fashion / Aesthetic",
    "opulent trap, orchestral harp glissandos, gold-leaf brass stabs, velour 808 sustain, chandelier sparkle hi-hat rolls, ballroom chandelier reverb, baroque-meets-trap aristocratic swagger groove",
    "opulent trap, harp gliss, brass stabs, ballroom 808",
    130,
    ["2020s","trap"],
  ),
  g(
    "Dark Luxury Trap",
    "Luxury / Fashion / Aesthetic",
    "dark luxury trap, mahogany Rhodes minor chords, noir saxophone breath samples, shadowed velvet sub, late-night penthouse rain FX, black-tie ominous trap pocket, candlelit wealth melancholy",
    "dark luxury trap, minor Rhodes, noir sax, velvet sub",
    130,
    ["2020s","trap","smooth"],
  ),
  g(
    "Frutiger Aero Rap",
    "Internet Aesthetics Rap",
    "frutiger aero rap, bubbly kalimba plucks, glassy aqua synth pads, breezy tropical marimba over soft 808, glossy Windows-XP optimism chords, shimmering water-drop percussion, serene digital meadow groove",
    "frutiger aero rap, kalimba plucks, aqua pads, bubbly 808",
    130,
    ["2020s"],
  ),
  g(
    "Dreamcore Hip Hop",
    "Internet Aesthetics Rap",
    "dreamcore hip hop, surreal detuned music-box melody, foggy reverb hall pianos, liminal corridor 808 pulse, uncanny soft trap hats, hazy memory-loop chord haze, dissociative dream-walk pocket",
    "dreamcore hip hop, music-box, fog piano, liminal 808",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Weirdcore Rap",
    "Internet Aesthetics Rap",
    "weirdcore rap, detuned circus organ stabs, broken JPEG static hiss, wrong-speed tape wobble, unsettling nursery-rhyme hook loop, disorienting ping-pong delay drums, surreal uncanny valley pocket",
    "weirdcore rap, circus organ, tape wobble, uncanny hook",
    130,
    ["2020s"],
  ),
  g(
    "Webcore Rap",
    "Internet Aesthetics Rap",
    "webcore rap, dial-up modem scrape texture, GeoCities MIDI chord stab, early GIF-era synth blips, homepage guestbook 808 bounce, hyperlinked percussion clicks, hypertext nostalgia pocket groove",
    "webcore rap, modem scrape, MIDI stab, homepage 808",
    130,
    ["2020s"],
  ),
  g(
    "Mallsoft Hip Hop",
    "Internet Aesthetics Rap",
    "mallsoft hip hop, distant mall PA reverb, soft muzak Rhodes loop, empty food-court 808 echo, fluorescent-light hum pad, late-2000s retail nostalgia chord, wandering escalator pocket",
    "mallsoft hip hop, mall PA, muzak Rhodes, food-court 808",
    130,
    ["2020s"],
  ),
  g(
    "Analog Horror Rap",
    "Internet Aesthetics Rap",
    "analog horror rap, VCR tracking-error warble, emergency broadcast tone drone, CCTV static snare, found-footage tape hiss, unsettling liminal basement 808, analog creepypasta dread pocket",
    "analog horror rap, VCR warble, broadcast drone, CCTV static",
    130,
    ["2020s","aggressive"],
  ),
  g(
    "VHS Trap",
    "Internet Aesthetics Rap",
    "vhs trap, magnetic tape wow-flutter drums, warm CRT hiss layer, tracking-line wobble bass, Blockbuster-era chord sample, degraded tracking-head 808, home-video nostalgic trap pocket",
    "VHS trap, tape wow-flutter, CRT hiss, tracking wobble 808",
    82,
    ["2020s","trap"],
  ),
  g(
    "MP3 Era Rap",
    "Internet Aesthetics Rap",
    "mp3 era rap, 128kbps artifact crunch, limewire-era synth stab, buffering-skips percussion, burnt-CD skipping hi-hat, compressed mid-focused 808, early-2000s download culture pocket groove",
    "MP3 era rap, bitrate crunch, limewire stab, skipping hats",
    130,
    ["2020s"],
  ),
  g(
    "Browsercore Rap",
    "Internet Aesthetics Rap",
    "browsercore rap, tab-loading click percussion, scrollbar scrape hi-hats, Incognito-window minor chords, bookmark-notification bell blips, midnight Chromium trap pulse, endless-scroll insomnia pocket",
    "browsercore rap, tab clicks, scrollbar hats, Chromium pulse",
    130,
    ["2020s"],
  ),
  g(
    "Retro Internet Trap",
    "Internet Aesthetics Rap",
    "retro internet trap, AIM doorbell sample hook, dial-up handshake intro texture, MySpace glitter synth arp, LAN-party 808 bounce, pixel-art melody lead, 2005 forum nostalgia pocket",
    "retro internet trap, AIM bell, dial-up, MySpace arp",
    130,
    ["2020s","trap"],
  ),
  g(
    "Neo Y2K Rap",
    "Internet Aesthetics Rap",
    "neo Y2K rap, translucent plastic synth chords, frosted-glass digital bell lead, flip-phone notification blips, frosted chrome 808, futuristic 2000s revival pocket, glossy cyber sparkle hats",
    "neo Y2K rap, plastic synth, flip-phone FX, chrome 808",
    130,
    ["2020s","2000s"],
  ),
  g(
    "Playstation 2 Rap",
    "Internet Aesthetics Rap",
    "playstation 2 rap, PS2 menu ambient pad loop, controller-button click hats, loading-screen orchestral stab, memory-card save chime melody, retro console startup bass, gaming-lounge 808 pocket",
    "PS2 rap, menu pads, controller clicks, save chime melody",
    130,
    ["2020s"],
  ),
  g(
    "Midnight Browser Rap",
    "Internet Aesthetics Rap",
    "midnight browser rap, blue-screen glow pad wash, insomnia tab-switch percussion, 3AM caffeine shaker groove, dim keyboard-type hi-hats, lonely screensaver chord loop, nocturnal scroll trap pocket",
    "midnight browser rap, glow pads, tab percussion, screensaver chords",
    130,
    ["2020s"],
  ),
  g(
    "Digital Dream Rap",
    "Internet Aesthetics Rap",
    "digital dream rap, cloud-render synth choir, sleep-mode soft 808 pulse, screensaver fractal arp layers, lucid pixel-dream melody, floating notification chime accents, reverie internet trap pocket",
    "digital dream rap, synth choir, fractal arp, lucid melody",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Artificial Nostalgia Rap",
    "Internet Aesthetics Rap",
    "artificial nostalgia rap, AI-smoothed tape hiss, synthetic memory-loop piano, fake-vintage vinyl crackle bed, algorithmic sunset chord progression, simulated childhood 808 warmth, fabricated yesterday pocket",
    "artificial nostalgia rap, AI tape hiss, memory piano, sunset chords",
    130,
    ["2020s"],
  ),
  g(
    "Ambient R&B",
    "R&B / Soul",
    "ambient r&b, washed pad drones over muted fingertip snares, sub-heavy 808 swells, breathy stacked harmonies, cathedral reverb tails, nocturnal floating melancholy drift",
    "ambient r&b, pad drones, muted snares, sub 808, breathy harmonies, cathedral reverb",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Contemporary Soul",
    "R&B / Soul",
    "contemporary soul, tight neo-disco pocket drums, syncopated electric bass, Rhodes voicings with jazz extensions, falsetto lead hooks, polished urban warmth and forward groove",
    "contemporary soul, neo-disco drums, syncopated bass, Rhodes jazz chords, falsetto lead",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Psychedelic Soul",
    "R&B / Soul",
    "psychedelic soul, fuzz-wah guitar layers, swung live kit, Hammond B3 stabs, phase-shifted vocal stacks, Sly Stone funk breakdowns, kaleidoscopic head-nod groove",
    "psychedelic soul, fuzz-wah guitar, Hammond B3, phase vocals, funk breakdowns",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Bedroom R&B",
    "R&B / Soul",
    "bedroom r&b, laptop-close vocal takes, dry finger snaps, soft sine sub, detuned micro-synth chords, whispered ad-libs, intimate headphone-night confession mood",
    "bedroom r&b, close vocals, finger snaps, sine sub, micro-synth, whisper ad-libs",
    88,
    ["2020s","r&b/soul","lo-fi"],
  ),
  g(
    "Indie R&B",
    "R&B / Soul",
    "indie r&b, off-grid programmed drums, chorus guitar licks, muted bass plucks, vulnerable tenor vocals, DIY tape warmth, left-field harmony twists and raw honesty",
    "indie r&b, off-grid drums, chorus guitar, muted bass, vulnerable tenor, DIY tape",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Emotional R&B",
    "R&B / Soul",
    "emotional r&b, slow six-eight sway, tear-streaked piano, round sub bass, stacked cry vocals, minor sevenths resolving late, heart-on-sleeve ache and trembling delivery",
    "emotional r&b, 6/8 sway, tear piano, round sub, cry vocals, minor sevenths",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Dreamy R&B",
    "R&B / Soul",
    "dreamy r&b, chorus-laden guitars, floating half-time trap hats, glassy bell plucks, reverb-drenched falsetto, hazy narcotic night-drive glow and narcoleptic sway",
    "dreamy r&b, chorus guitar, half-time hats, bell plucks, reverb falsetto",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Midnight R&B",
    "R&B / Soul",
    "midnight r&b, deep pocket four-on-floor kick, muted claps, minor ninth Rhodes, smoky alto vocals, neon city loneliness after last-call stillness",
    "midnight r&b, four-on-floor kick, muted claps, minor ninth Rhodes, smoky alto",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Late Night Soul",
    "R&B / Soul",
    "late night soul, brushed snare backbeat, upright electric bass walk, dim lamp Rhodes, bourbon-rough tenor ad-libs, smoke-filled booth intimacy and unhurried swing",
    "late night soul, brushed snare, upright bass walk, dim Rhodes, bourbon tenor",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Rainy Night R&B",
    "R&B / Soul",
    "rainy night r&b, pattering percussion layers, distant thunder sub drops, pluvial pad washes, lonely falsetto, rain-on-glass tears, grey-window introspective mood",
    "rainy night r&b, pattering percussion, thunder sub, pluvial pads, lonely falsetto",
    88,
    ["2020s","r&b/soul","melancholic"],
  ),
  g(
    "Ethereal R&B",
    "R&B / Soul",
    "ethereal r&b, angelic choir pads, sparse crystal hats, bowed bass harmonics, airborne soprano runs, shimmer delay trails, weightless celestial drift and halo glow",
    "ethereal r&b, choir pads, crystal hats, bowed bass, soprano runs, shimmer delay",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Experimental R&B",
    "R&B / Soul",
    "experimental r&b, asymmetrical drum edits, granular vocal chops, dissonant cluster chords, glitch transients, collage song-form turns, unpredictable harmonic left-field movement",
    "experimental r&b, asymmetrical drums, granular vocals, cluster chords, glitch transients",
    88,
    ["2020s","r&b/soul","experimental"],
  ),
  g(
    "Chill R&B",
    "R&B / Soul",
    "chill r&b, lazy syncopated rimshots, warm round bass, nylon guitar touches, buttery mid-range vocals, sunset patio breeze, unhurried head-nod pocket and ease",
    "chill r&b, syncopated rimshots, round bass, nylon guitar, mid-range vocals",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Velvet Soul",
    "R&B / Soul",
    "velvet soul, brushed hi-hat swish, velvety round bass, muted trumpet pads, silk tenor croon, plush chord cushions, old-Hollywood ballroom glide and satin sway",
    "velvet soul, brushed hats, round bass, muted trumpet, silk tenor croon",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Smooth Soul",
    "R&B / Soul",
    "smooth soul, Linn-style programmed groove, buttery finger bass, polished horn stabs, velvet lead vocals, satin major-seventh resolutions, silk-sheet sway and glide",
    "smooth soul, Linn groove, finger bass, horn stabs, major-seventh chords",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Soft Soul",
    "R&B / Soul",
    "soft soul, pillowy kick thumps, feather-light shakers, tender piano arpeggios, hushed stacked harmonies, quilted major chords, gentle morning-after tenderness and cotton warmth",
    "soft soul, pillowy kick, light shakers, piano arpeggios, hushed harmonies",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Minimal Soul",
    "R&B / Soul",
    "minimal soul, kick-and-rim skeleton groove, single-note bass pulses, sparse Rhodes stabs, naked lead vocal center, negative space, less-is-more hypnotic pulse and restraint",
    "minimal soul, kick-rim skeleton, single-note bass, sparse Rhodes, naked vocal",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Luxury Soul",
    "R&B / Soul",
    "luxury soul, crisp boutique drums, champagne-bright brass, expensive slap bass, couture falsetto runs, marble-club sophistication, gold-chain swagger and uptown sheen",
    "luxury soul, boutique drums, bright brass, slap bass, couture falsetto",
    88,
    ["2020s","r&b/soul","smooth"],
  ),
  g(
    "Fashion R&B",
    "R&B / Soul",
    "fashion r&b, runway four-on-floor pulse, staccato synth bass, glossy talk-box accents, model-cool detached vocals, flashbulb runway energy, high-gloss attitude and strut",
    "fashion r&b, runway four-on-floor, staccato synth bass, talk-box, detached vocals",
    88,
    ["2020s","r&b/soul","smooth"],
  ),
  g(
    "Cinematic R&B",
    "R&B / Soul",
    "cinematic r&b, timpani swells, orchestral string lifts, blockbuster sub drops, narrative alto belt, dramatic key changes, film-score emotional arc and widescreen tension",
    "cinematic r&b, timpani swells, orchestral strings, blockbuster sub, narrative alto",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Jazzy R&B",
    "R&B / Soul",
    "jazzy r&b, ride-cymbal swing feel, walking electric bass, II-V-I Rhodes comping, scat-adjacent vocal runs, smoky jazz-club flirtation, live-session looseness and swing",
    "jazzy r&b, ride cymbal swing, walking bass, II-V-I Rhodes, scat vocals",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Acoustic R&B",
    "R&B / Soul",
    "acoustic r&b, live strummed guitar pocket, cajón or brush kit, organic fingerstyle bass, unprocessed soul vocals, wooden-room honesty, unplugged heart and human breath",
    "acoustic r&b, strummed guitar, brush kit, fingerstyle bass, unprocessed vocals",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Piano Soul",
    "R&B / Soul",
    "piano soul, grand piano lead voicings, brushed snare waltz feel, upright bass thumps, gospel-tinged melismas, pew-bench resonance, sanctified groove and testify lift",
    "piano soul, grand piano, brushed snare waltz, upright bass, gospel melismas",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Vinyl Soul",
    "R&B / Soul",
    "vinyl soul, crackle-warm drums, dusty trumpet samples, tube-compressed bass, vintage tenor grit, needle-drop nostalgia, seventies hi-fi soul crate-dig warmth",
    "vinyl soul, crackle drums, dusty trumpet, tube bass, vintage tenor grit",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Retro Soul",
    "R&B / Soul",
    "retro soul, Motown four-on-floor kick, tambourine shake, Stax horn section hits, call-response vocals, analog tape slapback, sixties soul revue energy and swing",
    "retro soul, Motown kick, tambourine, Stax horns, call-response, tape slapback",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Y2K R&B",
    "R&B / Soul",
    "y2k r&b, crispy Timbaland bounce, syncopated synth stabs, chunky two-step sub, processed nasal tenor, millennium chrome-pop sheen, flip-phone flirt and digital gloss",
    "y2k r&b, Timbaland bounce, synth stabs, two-step sub, nasal tenor",
    88,
    ["2020s","2000s","r&b/soul"],
  ),
  g(
    "2000s R&B",
    "R&B / Soul",
    "2000s r&b, Neptunes-style pocket claps, talk-box bass filigree, layered harmony stacks, ringtone-era hook cadence, oversized polo-soul swagger and club-ready bounce",
    "2000s r&b, Neptunes claps, talk-box bass, harmony stacks, ringtone hooks",
    88,
    ["2020s","2000s","r&b/soul"],
  ),
  g(
    "90s Slow Jam",
    "R&B / Soul",
    "90s slow jam, drum-machine ballad swing, deep 808 sub pillow, talk-singing tenor, candlelit key changes, Teddy Riley slow-grind romance and bedroom heat",
    "90s slow jam, drum-machine swing, 808 sub, talk-singing tenor, key changes",
    72,
    ["2020s","2000s"],
  ),
  g(
    "Slow Jamz",
    "R&B / Soul",
    "slow jamz, syrupy seventy-two bpm sway, rimshot-and-shaker glue, plush sub sustain, ad-lib-heavy croon, bedroom confession booth heat, body-press slow dance",
    "slow jamz, 72 bpm sway, rimshot shaker, plush sub, ad-lib croon",
    72,
    ["2020s"],
  ),
  g(
    "Quiet Storm",
    "R&B / Soul",
    "quiet storm, silk-sheet Rhodes, gentle shaker three-two clave, pillow bass, smokey radio whisper vocals, late-night FM seduction, Smokey Robinson tenderness and hush",
    "quiet storm, silk Rhodes, shaker clave, pillow bass, whisper vocals",
    72,
    ["2020s"],
  ),
  g(
    "Alternative Soul",
    "R&B / Soul",
    "alternative soul, off-kilter drum patterns, distortion-kissed guitars, gritty bass drive, raw breakup alto, indie-soul angst, non-radio song structure freedom and edge",
    "alternative soul, off-kilter drums, distorted guitar, gritty bass, raw alto",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Cloud R&B",
    "R&B / Soul",
    "cloud r&b, syrup-slow trap hats, foggy pad stacks, muffled 808 tails, autotuned distant vocals, smoked-out zen haze, spaced-out ride-out groove and float",
    "cloud r&b, slow trap hats, foggy pads, muffled 808, distant autotune",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Space Soul",
    "R&B / Soul",
    "space soul, cosmic synth arpeggios, orbital delay drums, alien talk-box bass, astronaut falsetto echoes, zero-gravity funk orbit, Sun Ra celestial drift and wonder",
    "space soul, cosmic arps, orbital delay drums, talk-box bass, falsetto echoes",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Cosmic R&B",
    "R&B / Soul",
    "cosmic r&b, phased synth galaxies, neutron-star kick thumps, wormhole reverb vocals, astral jazz-funk bass, interstellar love transmission, star-chart harmony and glow",
    "cosmic r&b, phased synths, neutron kick, wormhole reverb, jazz-funk bass",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Dream Soul",
    "R&B / Soul",
    "dream soul, narcoleptic half-time pulse, lullaby music-box plucks, fogged sub dreams, sleepwalking vocal layers, pillow-talk subconscious, REM-cycle sway and soft blur",
    "dream soul, half-time pulse, music-box plucks, fogged sub, sleepwalking vocals",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Melancholic Soul",
    "R&B / Soul",
    "melancholic soul, minor-key Rhodes weep, heavy-hearted rim clicks, descending bass sighs, tear-choked tenor, grey-sky introspection, unresolved emotional cadence and ache",
    "melancholic soul, minor Rhodes, rim clicks, descending bass, tear-choked tenor",
    88,
    ["2020s","r&b/soul","melancholic"],
  ),
  g(
    "Spiritual Soul",
    "R&B / Soul",
    "spiritual soul, gospel clap stacks, Hammond shout chords, testify melismas, church pew bass rumble, sanctified call-response, transcendental uplift cadence and holy rise",
    "spiritual soul, gospel claps, Hammond shout, testify melismas, church bass",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Vulnerable R&B",
    "R&B / Soul",
    "vulnerable r&b, bare vocal upfront, shaky breath takes, sparse piano confessional, quivering lower register, diary-page honesty, no armor left and trembling truth",
    "vulnerable r&b, bare vocal, shaky breath, sparse piano, quivering lower register",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Romantic R&B",
    "R&B / Soul",
    "romantic r&b, rose-petal chord voicings, heartbeat kick pattern, serenade tenor glide, swooning string pads, love-letter lyric tenderness, candlelight slow whine and blush",
    "romantic r&b, rose-petal chords, heartbeat kick, serenade tenor, string pads",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Intimate R&B",
    "R&B / Soul",
    "intimate r&b, close-mic lip friction, fingerpicked guitar whispers, heartbeat sub pulses, breath-count ad-libs, one-inch-apart headphone confession, skin-contact proximity and hush",
    "intimate r&b, close-mic vocals, fingerpicked guitar, heartbeat sub, breath ad-libs",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Seductive R&B",
    "R&B / Soul",
    "seductive r&b, snake-charmer minor groove, humid rim-snap swagger, slippery talk-singing, honey-drip falsetto tease, dim red-room tension, slow body-roll heat and pull",
    "seductive r&b, minor groove, rim-snap swagger, talk-singing, honey falsetto",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Soft Girl R&B",
    "R&B / Soul",
    "soft girl r&b, pastel synth bells, cotton-candy vocal layers, bunny-hop trap hats, heart-shaped major chords, tender self-care glow, blush-pink daydream and sweetness",
    "soft girl r&b, pastel bells, cotton-candy vocals, trap hats, major chords",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Digital Soul",
    "R&B / Soul",
    "digital soul, bit-crushed drum hits, quantize-tight grid bass, FM synthesis bells, pixelated vocal chops, internet-age soul glitch, screen-lit midnight scroll and neon ache",
    "digital soul, bit-crushed drums, grid bass, FM bells, pixelated vocals",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Internet Soul",
    "R&B / Soul",
    "internet soul, hyperpop-adjacent synth blips, distorted meme-bass, parasocial vocal breath, DM-slide chord stabs, URL heartbreak, bandwidth emotional spill and scroll grief",
    "internet soul, hyperpop blips, distorted bass, parasocial vocals, DM-slide chords",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Tumblr Era R&B",
    "R&B / Soul",
    "tumblr era r&b, reverb-soaked Frank Ocean chords, nostalgic sample chops, sad-boy falsetto layers, gradient-purple melancholy, 2012 dashboard heartbreak aesthetic and diary posts",
    "tumblr era r&b, Frank Ocean chords, sample chops, sad falsetto, purple melancholy",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Blog Era Soul",
    "R&B / Soul",
    "blog era soul, chopped soul samples, dusty MPC swing, Pitchfork-adjacent Rhodes, earnest indie tenor, pre-streaming bloghouse innocence, DIY neo-soul pocket and warmth",
    "blog era soul, chopped samples, MPC swing, Rhodes, indie tenor, neo-soul",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Cassette Soul",
    "R&B / Soul",
    "cassette soul, tape-wow flutter drums, hiss-layered bass, thrift-store Wurlitzer, demo-tape vocal crackle, dub analog warmth, four-track bedroom confession and thrift glow",
    "cassette soul, tape-wow drums, hiss bass, Wurlitzer, demo-tape vocals",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "VHS Soul",
    "R&B / Soul",
    "vhs soul, VCR-tracking synth warble, eighties boogie bass slap, chromatic VHS hue pads, retro-future alto, mall-rat nostalgia glow, tracking-line haze and rewind",
    "vhs soul, VCR synth warble, boogie bass slap, VHS pads, retro alto",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Chrome Soul",
    "R&B / Soul",
    "chrome soul, futuristic neo-soul Rhodes, glossy synthesizers, silky electric piano, smooth bass groove, spacious reverb, modern R&B drums, luxurious digital soul textures",
    "chrome soul, neo-soul Rhodes, glossy synths, electric piano, smooth bass, spacious reverb",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Holographic Soul",
    "R&B / Soul",
    "holographic soul, prismatic arp sweeps, iridescent pad shifts, prism-vocal doubles, liquid light bass, futuristic soul hologram dance, refracted rainbow groove and shimmer",
    "holographic soul, prismatic arps, iridescent pads, prism vocals, liquid bass",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Synthetic Soul",
    "R&B / Soul",
    "synthetic soul, all-digital drum machine, vocoder harmony stacks, silicon bass pulses, android soul tenor, programmed humanity glitch, cybernetic church revival and neon pulse",
    "synthetic soul, digital drums, vocoder stacks, silicon bass, android tenor",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Analog Soul",
    "R&B / Soul",
    "analog soul, tape-saturated kick thump, warm Moog bass, live-room Rhodes bleed, unquantized human pocket, wood-panel studio breathe, pre-digital soul truth and grit",
    "analog soul, tape kick, Moog bass, Rhodes bleed, unquantized pocket",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Neo Lounge Soul",
    "R&B / Soul",
    "neo lounge soul, cocktail jazz brushes, upright bass stroll, martini-hour Rhodes, baritone croon, smoky hotel lobby sophistication, after-hours penthouse ease and satin night",
    "neo lounge soul, jazz brushes, upright bass stroll, Rhodes, baritone croon",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Chillwave R&B",
    "R&B / Soul",
    "chillwave r&b, pitched-down soul samples, washed-out sidechain pads, nostalgic eighties synth ghosts, vapor-haze vocals, sun-faded boombox romance, cassette-memory drift and fade",
    "chillwave r&b, pitched soul samples, sidechain pads, 80s synth ghosts, vapor vocals",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Vapor Soul",
    "R&B / Soul",
    "vapor soul, hazy detuned synth pads, sidechain-warped minor chords, soft 707 drums, tape-saturated Rhodes, slow swung groove, muted sub, breathy vocal space",
    "vapor soul, hazy pads, sidechain chords, tape Rhodes, soft drums, muted sub",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Future Soul",
    "R&B / Soul",
    "future soul, glossy FM bell chords, tight electronic drums, warm sine sub bass, shimmering arp layers, minor ninth voicings, neon pulse bounce, vocal-forward hooks",
    "future soul, FM bells, electronic drums, sine sub, shimmer arps, minor ninths",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Afro Soul",
    "R&B / Soul",
    "afro soul, talking drum patterns, warm nylon guitar licks, soulful seventh chords, deep round bass, shakers and congas, call-response melody space, sunset groove",
    "afro soul, talking drums, nylon guitar, seventh chords, congas, call-response",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "UK Soul",
    "R&B / Soul",
    "uk soul, skippy two-step drums, fat sub bass slides, minor Rhodes stabs, chopped vocal accents, syncopated hi-hat swings, London night pulse, garage-soul bounce",
    "uk soul, two-step drums, sub slides, Rhodes stabs, vocal chops, syncopated hats",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Soul Pop",
    "R&B / Soul",
    "soul pop, major-seven hook chords, bright clap-snare pocket, melodic bass line, brass stab accents, upbeat soul bounce, catchy topline space, hook-forward energy",
    "soul pop, major sevenths, clap snare, melodic bass, brass stabs, upbeat bounce",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Soulwave",
    "R&B / Soul",
    "soulwave, analog synth wave chords, slow four-four groove, chorus Rhodes, liquid bass glide, retro drum machine ticks, dreamy pad layers, intimate late-night sway",
    "soulwave, synth wave, chorus Rhodes, liquid bass, drum machine, dreamy pads",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Dreamwave R&B",
    "R&B / Soul",
    "dreamwave r&b, wide reverb synth washes, airy choir pads, soft rimshot groove, suspended minor chords, slow tempo drift, floating topline halo, sleepwalk bounce",
    "dreamwave r&b, reverb washes, choir pads, rimshots, suspended chords, slow drift",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Soultronica",
    "R&B / Soul",
    "soultronica, broken beat drums, filtered soul sample chops, warm Moog bass, bitcrushed Rhodes, glitch percussion hits, hypnotic chord loop, electronic soul pocket",
    "soultronica, broken beat, sample chops, Moog bass, bitcrush Rhodes, glitch percussion",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Electro Soul",
    "R&B / Soul",
    "electro soul, punchy four-on-four kick, acid-tinged synth bass, disco clap pattern, soul chord stabs, vocoder topline space, neon club pulse, dancefloor soul bounce",
    "electro soul, four-on-four kick, acid bass, disco claps, chord stabs, vocoder space",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Deep Soul",
    "R&B / Soul",
    "deep soul, low-register Rhodes voicings, round upright bass, brushed snare swing, gospel organ swells, minor seventh progressions, slow sensual pocket, heartfelt vocal room",
    "deep soul, low Rhodes, upright bass, brushed snare, organ swells, minor sevenths",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Velvet Nights",
    "R&B / Soul",
    "velvet nights, dark plush Rhodes chords, muted trumpet phrases, brushed ride cymbal sway, midnight minor groove, smokey bass warmth, candlelit lounge soul atmosphere",
    "velvet nights, plush Rhodes, muted trumpet, brushed ride, midnight minor, smokey bass",
    88,
    ["2020s"],
  ),
  g(
    "Sunset Soul",
    "R&B / Soul",
    "sunset soul, golden-hour nylon guitar arps, warm Rhodes sevenths, lazy boom-bap kick, shaker rhythm, amber pad glow, west-coast slow bounce, fading light groove",
    "sunset soul, nylon arps, Rhodes sevenths, boom-bap kick, shakers, amber pads",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Ocean Soul",
    "R&B / Soul",
    "ocean soul, wide chorus-pad tides, gentle surf percussion, rolling sub bass waves, suspended chord swells, breezy nylon picking, tranquil tidal groove, coastal drift",
    "ocean soul, chorus pads, surf percussion, rolling sub, suspended chords, nylon picking",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Moonlight R&B",
    "R&B / Soul",
    "moonlight r&b, soft piano arpeggios, sparse rimclick drums, deep round sub, silver synth pad glow, whispered minor romance, nocturnal slow sway, lunar vocal space",
    "moonlight r&b, piano arps, rimclicks, round sub, silver pads, minor romance",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Neon Soul",
    "R&B / Soul",
    "neon soul, bright synth brass stabs, gated reverb snare, purple neon chord glow, funky slap bass pops, city-night pulse, eighties-future soul bounce, electric avenue energy",
    "neon soul, synth brass, gated snare, neon chords, slap bass, city pulse",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Liquid Soul",
    "R&B / Soul",
    "liquid soul, cascading Rhodes runs, fluid 808 glide bass, watery chorus pads, triplet hi-hat rolls, seamless seventh voicings, pouring groove, melt-flow soul bounce",
    "liquid soul, Rhodes runs, 808 glide, chorus pads, triplet hats, seventh voicings",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Floating Soul",
    "R&B / Soul",
    "floating soul, ethereal string pad lift, weightless kickless pulse, soft cloud snare taps, drifting suspended chords, zero-gravity melody space, ambient soul drift, airy bounce",
    "floating soul, string pads, kickless pulse, cloud snares, suspended chords, ambient drift",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Digital Romance",
    "R&B / Soul",
    "digital romance, pixel-soft synth plucks, chat-notification percussion ticks, warm DM chord buzz, modem-crunch texture, smartphone glow pads, intimate online heart pulse, screen-lit sway",
    "digital romance, synth plucks, notification ticks, DM chords, modem crunch, glow pads",
    88,
    ["2020s"],
  ),
  g(
    "Heartbreak Soul",
    "R&B / Soul",
    "heartbreak soul, tearful minor piano, cracking vocal reverb tail, sparse kick and rim, descending chord sighs, lonely Rhodes cry, slow ache pocket, wounded soul sway",
    "heartbreak soul, minor piano, vocal reverb, sparse kick, descending chords, lonely Rhodes",
    88,
    ["2020s","r&b/soul","melancholic"],
  ),
  g(
    "After Hours R&B",
    "R&B / Soul",
    "after hours r&b, dim bar Rhodes chords, soft hi-hat shuffle, upright bass walk, brushed snare hush, whiskey-glass reverb, 2am closing-time soul sway, last-call groove",
    "after hours r&b, bar Rhodes, hi-hat shuffle, upright bass, brushed snare, 2am sway",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Lounge R&B",
    "R&B / Soul",
    "lounge r&b, cocktail piano comping, upright bass thump, brushed ride swing, muted trumpet grace notes, plush velvet chord voicings, sophisticated late-lounge groove, martini sway",
    "lounge r&b, cocktail piano, upright bass, brushed ride, muted trumpet, velvet chords",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Late Drive Soul",
    "R&B / Soul",
    "late drive soul, highway synth pad sweep, steady cruise kick, dashboard Rhodes glow, passing-car hi-hat flicker, open-road minor chords, midnight windshield bounce, freeway sway",
    "late drive soul, highway pads, cruise kick, dashboard Rhodes, open-road minor, freeway bounce",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Motel Soul",
    "R&B / Soul",
    "motel soul, cheap-TV static hum, neon-sign buzz bass, worn Rhodes keys, slow door-slam kick, roadside minor sevenths, lonely highway night groove, vacancy-sign sway",
    "motel soul, TV static, neon buzz bass, worn Rhodes, door-slam kick, roadside minor",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Luxury Hotel R&B",
    "R&B / Soul",
    "luxury hotel r&b, marble-hall Rhodes sparkle, champagne-cork snare pops, silk-string overlays, gold-major chord plush, concierge bass glide, penthouse midnight elegance, five-star sway",
    "luxury hotel r&b, marble Rhodes, champagne snare, silk strings, gold major, concierge bass",
    88,
    ["2020s","r&b/soul","smooth"],
  ),
  g(
    "Paris Night Soul",
    "R&B / Soul",
    "paris night soul, accordion-flavored chord color, café upright bass, soft brush waltz sway, streetlamp synth glow, Left Bank minor romance, cobblestone late stroll, Seine-night bounce",
    "paris night soul, accordion chords, café bass, brush waltz, streetlamp synth, Left Bank minor",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Tokyo Soul",
    "R&B / Soul",
    "tokyo soul, crisp electronic hi-hats, city-pop synth sparkle, tight four-on-floor pocket, kawaii chord brightness, neon Shibuya bounce, polished urban night pulse, Shinjuku sway",
    "tokyo soul, electronic hats, city-pop synth, four-on-floor, kawaii chords, Shibuya bounce",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Seoul Midnight R&B",
    "R&B / Soul",
    "seoul midnight r&b, K-R&B glossy synth layers, trap-soft drums, emotional minor topline space, glassy chord stacks, han river night sway, soft 808 sub, midnight city glow",
    "seoul midnight r&b, glossy synths, trap-soft drums, glassy chords, 808 sub, han river sway",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Miami Sunset Soul",
    "R&B / Soul",
    "miami sunset soul, pastel synth chords, disco-funk bass slap, Latin shaker groove, ocean-breeze pad wash, Art Deco major bounce, palm-tree twilight sway, South Beach glow",
    "miami sunset soul, pastel synths, funk bass slap, Latin shakers, ocean pads, Art Deco bounce",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Cigarette Break Soul",
    "R&B / Soul",
    "cigarette break soul, solo Rhodes exhale chords, lazy rimshot inhale, smoky pad haze, porch-light minor glow, unhurried pause groove, ash-tray silence space, balcony sway",
    "cigarette break soul, Rhodes exhale, lazy rimshot, smoky pads, porch-light minor, pause groove",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Bedroom Confession R&B",
    "R&B / Soul",
    "bedroom confession r&b, close-mic piano whispers, pillow-soft kick thump, tape-saturated warmth, intimate headphone chords, diary-page melody space, late-night whisper groove, secret sway",
    "bedroom confession r&b, close piano, pillow kick, tape warmth, headphone chords, whisper groove",
    88,
    ["2020s","r&b/soul","lo-fi"],
  ),
  g(
    "Slow Motion Soul",
    "R&B / Soul",
    "slow motion soul, half-time dragged drums, stretched Rhodes chords, floating time-stretch pads, heavy legato bass, cinematic slow sway, suspended moment groove, time-dilated bounce",
    "slow motion soul, half-time drums, stretched Rhodes, time-stretch pads, legato bass, cinematic sway",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Emotional Luxury",
    "R&B / Soul",
    "emotional luxury, plush string orchestra swells, designer-brand minor chords, crystal hi-hat shimmer, silk bass contour, couture sadness bounce, high-end tear sparkle, runway grief sway",
    "emotional luxury, string swells, designer minor, crystal hats, silk bass, couture sadness",
    88,
    ["2020s","smooth"],
  ),
  g(
    "Soft Chaos Soul",
    "R&B / Soul",
    "soft chaos soul, gentle dissonant chord clusters, unpredictable hi-hat accents, cozy Rhodes warmth underneath, controlled noise texture, tender turmoil bounce, organized beautiful mess, gentle storm sway",
    "soft chaos soul, dissonant clusters, unpredictable hats, cozy Rhodes, controlled noise, tender turmoil",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Introspective R&B",
    "R&B / Soul",
    "introspective r&b, journal-page piano motifs, minimal kick pulse, thoughtful minor progressions, inward melody holes, quiet snare brushes, reflective late-night sway, inner monologue groove",
    "introspective r&b, journal piano, minimal kick, minor progressions, quiet brushes, reflective sway",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Vulnerable Nights",
    "R&B / Soul",
    "vulnerable nights, fragile piano single notes, exposed vocal reverb, thin kick heartbeat, quivering string pad, open wound minor chords, tender midnight confessional groove, raw night sway",
    "vulnerable nights, fragile piano, exposed reverb, thin kick, quivering strings, open wound minor",
    88,
    ["2020s"],
  ),
  g(
    "Crying in Designer Clothes",
    "R&B / Soul",
    "crying in designer clothes, glossy synth tears, couture minor progressions, expensive reverb sobs, runway drum march, luxury sadness sparkle, high-fashion heartbreak pulse, boutique ache sway",
    "crying in designer clothes, glossy synths, couture minor, expensive reverb, runway drums, fashion heartbreak",
    88,
    ["2020s","smooth"],
  ),
  g(
    "Nostalgic Romance",
    "R&B / Soul",
    "nostalgic romance, VHS-warm tape hiss, retro chorus Rhodes, old-love melody fragments, analog drum machine sway, faded-photo chord glow, bittersweet memory drift, rewind romance bounce",
    "nostalgic romance, VHS hiss, retro Rhodes, analog drums, faded-photo chords, memory drift",
    88,
    ["2020s"],
  ),
  g(
    "Rain on Windows R&B",
    "R&B / Soul",
    "rain on windows r&b, rainstick percussion texture, gray pad wash, melancholic piano drops, windshield-wiper hi-hats, stormy minor chords, indoor cozy ache groove, stormglass sway",
    "rain on windows r&b, rainstick, gray pads, melancholic piano, wiper hats, stormy minor",
    88,
    ["2020s","r&b/soul","melancholic"],
  ),
  g(
    "Floating Memories Soul",
    "R&B / Soul",
    "floating memories soul, reversed piano echoes, memory-flash synth stabs, soft cloud drums, déjà-vu chord cycles, nostalgic pad drift, dream-recall soul sway, echo-chamber bounce",
    "floating memories soul, reversed piano, memory stabs, cloud drums, déjà-vu chords, nostalgic pads",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Dream Apartment R&B",
    "R&B / Soul",
    "dream apartment r&b, loft-reverb Rhodes, skyline synth view, cozy kick cushion, sun-through-blinds pad glow, aspirational major chords, penthouse daydream bounce, lease-to-love sway",
    "dream apartment r&b, loft Rhodes, skyline synth, cozy kick, blinds pads, aspirational major",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Silk Soul",
    "R&B / Soul",
    "silk soul, smooth legato Rhodes glide, satin-string pad sheen, feather-light snare brush, flowing bass ribbon, seamless seventh voicings, luxury fabric groove, whisper-soft bounce",
    "silk soul, legato Rhodes, satin strings, feather snare, flowing bass, seventh voicings",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Satin R&B",
    "R&B / Soul",
    "satin r&b, slippery synth glide chords, soft glossy snare sheen, lingerie-mood minor warmth, brushed hi-hat whisper, sensual slow body sway, bedroom silk pulse, skin-close groove",
    "satin r&b, slippery synths, glossy snare, lingerie minor, brushed hats, sensual sway",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Velvet Rain",
    "R&B / Soul",
    "velvet rain, plush pad rainfall, deep suede Rhodes, muffled kick through raincoat, stormy minor romance, soaked reverb tail, rainy velvet night groove, downpour soul sway",
    "velvet rain, plush pads, suede Rhodes, muffled kick, stormy minor, soaked reverb",
    88,
    ["2020s","melancholic"],
  ),
  g(
    "Chrome Tears",
    "R&B / Soul",
    "chrome tears, metallic synth cry leads, mirror-shine hi-hats, chrome-plated minor chords, robotic emotion bass, futuristic sadness glare, polished digital weep pulse, reflective ache bounce",
    "chrome tears, metallic synths, mirror hats, chrome minor, robotic bass, digital weep",
    88,
    ["2020s"],
  ),
  g(
    "Neon Heartbreak",
    "R&B / Soul",
    "neon heartbreak, pink-blue synth sign flicker, crying LED pad glow, broken-neon bass buzz, strobe snare ache, city-night tear bounce, luminous sadness pulse, sign-out soul sway",
    "neon heartbreak, pink-blue synth, LED pads, broken-neon bass, strobe snare, luminous sadness",
    88,
    ["2020s","melancholic"],
  ),
  g(
    "Emotional Futurism",
    "R&B / Soul",
    "emotional futurism, AI-era synth chord stacks, holographic pad shimmer, deep sub emotion weight, glitch-accent soul drums, tomorrow-tear melody space, sci-fi feeling groove, future-grief bounce",
    "emotional futurism, AI synth stacks, holographic pads, deep sub, glitch drums, sci-fi feeling",
    88,
    ["2020s"],
  ),
  g(
    "Artificial Romance",
    "R&B / Soul",
    "artificial romance, synthetic voice-pad romance, algorithmic chord patterns, plastic heart bass throb, chatbot affection arps, fake-intimacy groove pulse, digital love simulation sway, bot-heart bounce",
    "artificial romance, synthetic pads, algorithmic chords, plastic bass, chatbot arps, fake intimacy",
    88,
    ["2020s"],
  ),
  g(
    "Digital Heartbreak",
    "R&B / Soul",
    "digital heartbreak, pixel-crushed Rhodes sob, error-message percussion, disconnected sub bass, notification ping sadness, corrupted file chord ache, online breakup pulse, buffer-overflow sway",
    "digital heartbreak, pixel Rhodes, error percussion, disconnected sub, notification pings, corrupted chords",
    88,
    ["2020s","melancholic"],
  ),
  g(
    "Midnight Confessions",
    "R&B / Soul",
    "midnight confessions, whisper Rhodes in darkness, confessional snare rim, secret minor chords, candle-flicker pad, 3am truth-telling groove, intimate shadow bounce, confession-booth sway",
    "midnight confessions, whisper Rhodes, confessional rim, secret minor, candle pads, 3am truth",
    88,
    ["2020s"],
  ),
  g(
    "Purple Lights R&B",
    "R&B / Soul",
    "purple lights r&b, violet synth pad wash, indigo Rhodes glow, nightclub purple haze, moody minor chord mist, slow body-sway pulse, late-party soul shimmer, ultraviolet bounce",
    "purple lights r&b, violet pads, indigo Rhodes, purple haze, minor mist, body-sway pulse",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Soft Neon Soul",
    "R&B / Soul",
    "soft neon soul, gentle pastel synth chords, diffused neon pad glow, tender trap-soft drums, muted sub warmth, blush-colored night bounce, understated city sparkle, low-watt soul sway",
    "soft neon soul, pastel synths, diffused neon, trap-soft drums, muted sub, blush bounce",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Late Text Message Soul",
    "R&B / Soul",
    "late text message soul, phone-screen glow pads, typing-indicator percussion ticks, unanswered minor chords, notification anxiety bass, 2am draft melody space, read-receipt soul sway, unsent bounce",
    "late text message soul, screen glow pads, typing ticks, unanswered minor, notification bass, 2am draft",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Emotional Trap Soul",
    "Trap Soul / Hybrid",
    "emotional trap soul, cinematic minor Rhodes, melodic 808 glides, crisp trap hi-hats, soulful chord swells, Bryson Tiller pocket, heartfelt late-night bounce, vulnerable trap-soul sway",
    "emotional trap soul, minor Rhodes, 808 glides, trap hats, chord swells, Bryson pocket",
    88,
    ["2020s","trap","r&b/soul"],
  ),
  g(
    "Ambient Trap Soul",
    "Trap Soul / Hybrid",
    "ambient trap soul, wide reverb soul pads, sparse trap kick punch, deep 808 sub drones, airy vocal space, hypnotic slow pulse, cloud-heavy emotional sway, fogged trap-soul drift",
    "ambient trap soul, wide pads, sparse kick, 808 drones, airy vocals, hypnotic pulse",
    88,
    ["2020s","trap","r&b/soul","atmospheric"],
  ),
  g(
    "Dark Trap Soul",
    "Trap Soul / Hybrid",
    "dark trap soul, menacing minor synth stabs, hard distorted 808, trap snare crack, moody Rhodes underneath, nocturnal danger chords, sinister soul-trap pulse, shadowed late-night sway",
    "dark trap soul, minor stabs, distorted 808, trap snare, moody Rhodes, sinister pulse",
    88,
    ["2020s","trap","r&b/soul"],
  ),
  g(
    "Neo Trap Soul",
    "Trap Soul / Hybrid",
    "neo trap soul, jazzy seventh chord stacks, modern trap drum bounce, warm 808 sine glide, fresh R&B melody holes, contemporary soul-trap hybrid sway, new-wave emotional pocket",
    "neo trap soul, jazzy sevenths, trap bounce, 808 glide, R&B melody, hybrid sway",
    88,
    ["2020s","trap","r&b/soul"],
  ),
  g(
    "Atmospheric Trap Soul",
    "Trap Soul / Hybrid",
    "atmospheric trap soul, foggy pad atmosphere, rolling 808 bass waves, spaced trap percussion, emotional chord haze, wide stereo drift, cinematic trap-soul depth, clouded heart sway",
    "atmospheric trap soul, foggy pads, rolling 808, spaced percussion, chord haze, wide stereo",
    88,
    ["2020s","trap","r&b/soul"],
  ),
  g(
    "Sad Trap Soul",
    "Trap Soul / Hybrid",
    "sad trap soul, weeping Rhodes minor keys, tearful 808 slides, damp trap snare thuds, lonely pad rainfall, heartbroken pocket sway, melancholic soul-trap ache, rainy-night bounce",
    "sad trap soul, weeping Rhodes, 808 slides, damp snare, lonely pads, heartbroken sway",
    88,
    ["2020s","trap","r&b/soul","melancholic"],
  ),
  g(
    "Luxury Trap Soul",
    "Trap Soul / Hybrid",
    "luxury trap soul, champagne synth sparkle, plush soul chord stacks, clean trap hi-hat rolls, smooth deep 808, designer-night bounce, upscale emotional trap pulse, penthouse ache sway",
    "luxury trap soul, champagne synth, plush chords, clean hats, deep 808, designer bounce",
    88,
    ["2020s","trap","r&b/soul","smooth"],
  ),
  g(
    "Lo-Fi Trap Soul",
    "Trap Soul / Hybrid",
    "lo-fi trap soul, dusty vinyl crackle layer, muffled trap kick thump, warm tape Rhodes, crunchy 808 sub, nostalgic headphone groove, bedroom soul-trap haze, cassette-night sway",
    "lo-fi trap soul, vinyl crackle, muffled kick, tape Rhodes, crunchy 808, bedroom haze",
    88,
    ["2020s","trap","r&b/soul","lo-fi"],
  ),
  g(
    "Midnight Trap Soul",
    "Trap Soul / Hybrid",
    "midnight trap soul, moonlit soul chord glow, hard-soft trap drums, rolling 808 under stars, nocturnal hi-hat shimmer, dark hour emotional bounce, witching-hour trap-soul sway",
    "midnight trap soul, moonlit chords, trap drums, rolling 808, nocturnal hats, dark hour bounce",
    88,
    ["2020s","trap","r&b/soul"],
  ),
  g(
    "Rainy Trap Soul",
    "Trap Soul / Hybrid",
    "rainy trap soul, rain percussion on trap hats, gloomy soul Rhodes drip, wet 808 sub puddles, storm-window pad wash, melancholic soul-trap storm groove, thunderheart sway",
    "rainy trap soul, rain hats, gloomy Rhodes, wet 808, storm pads, melancholic storm",
    88,
    ["2020s","trap","r&b/soul","melancholic"],
  ),
];
