/** Hip-hop, trap, drill, and R&B/soul microgenres — auto-expanded catalog batch. */
import type { ExtendedGenreDef } from "@/lib/genres/extendedCatalog";

function g(
  value: string,
  group: string,
  prompt: string,
  aceTags: string,
  bpm: number,
  sonautoTags: string[] = ["2020s"],
): ExtendedGenreDef {
  return { value, group, prompt, aceTags, bpm, sonautoTags };
}

export const HIP_HOP_SOUL_GENRES: ExtendedGenreDef[] = [
  g(
    "Rage Trap",
    "Trap / Modern",
    "rage trap, aggressive high-intensity energy, authentic trap / modern production, radio-ready polish",
    "rage trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap","aggressive"],
  ),
  g(
    "Emo Trap",
    "Trap / Modern",
    "emo trap, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "emo trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Cloud Trap",
    "Trap / Modern",
    "cloud trap, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "cloud trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Drill Trap",
    "Trap / Modern",
    "drill trap, dark sliding bass and rapid hi-hats, authentic trap / modern production, radio-ready polish",
    "drill trap, trap / modern, modern production, polished mix",
    142,
    ["2020s","trap","aggressive"],
  ),
  g(
    "Space Trap",
    "Trap / Modern",
    "space trap, spacious atmospheric depth, authentic trap / modern production, radio-ready polish",
    "space trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap","atmospheric"],
  ),
  g(
    "Gothic Trap",
    "Trap / Modern",
    "gothic trap, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "gothic trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Sad Trap",
    "Trap / Modern",
    "sad trap, melancholic emotional atmosphere, authentic trap / modern production, radio-ready polish",
    "sad trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap","melancholic"],
  ),
  g(
    "Horror Trap",
    "Trap / Modern",
    "horror trap, aggressive high-intensity energy, authentic trap / modern production, radio-ready polish",
    "horror trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap","aggressive"],
  ),
  g(
    "Glitch Trap",
    "Trap / Modern",
    "glitch trap, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "glitch trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Neo Trap",
    "Trap / Modern",
    "neo trap, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "neo trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Lo-Fi Trap",
    "Trap / Modern",
    "lo-fi trap, warm nostalgic texture, authentic trap / modern production, radio-ready polish",
    "lo-fi trap, trap / modern, modern production, polished mix",
    82,
    ["2020s","trap","lo-fi"],
  ),
  g(
    "Jazz Trap",
    "Trap / Modern",
    "jazz trap, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "jazz trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Hyper Trap",
    "Trap / Modern",
    "hyper trap, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "hyper trap, trap / modern, modern production, polished mix",
    155,
    ["2020s","trap"],
  ),
  g(
    "Underground Trap",
    "Trap / Modern",
    "underground trap, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "underground trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Alien Trap",
    "Trap / Modern",
    "alien trap, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "alien trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Trap&B",
    "Trap / Modern",
    "trap&b, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "trap&b, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Orchestral Trap",
    "Trap / Modern",
    "orchestral trap, modern underground pocket and clean mix, authentic trap / modern production, radio-ready polish",
    "orchestral trap, trap / modern, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "SoundCloud Rap",
    "SoundCloud / Underground",
    "soundcloud rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "soundcloud rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Plugg",
    "SoundCloud / Underground",
    "plugg, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "plugg, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Vaportrap",
    "SoundCloud / Underground",
    "vaportrap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "vaportrap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Internet Rap",
    "SoundCloud / Underground",
    "internet rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "internet rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Tumblr Rap",
    "SoundCloud / Underground",
    "tumblr rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "tumblr rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Blog Era Rap",
    "SoundCloud / Underground",
    "blog era rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "blog era rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Alternative Hip Hop",
    "SoundCloud / Underground",
    "alternative hip hop, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "alternative hip hop, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Abstract Hip Hop",
    "SoundCloud / Underground",
    "abstract hip hop, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "abstract hip hop, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s","experimental"],
  ),
  g(
    "Experimental Rap",
    "SoundCloud / Underground",
    "experimental rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "experimental rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s","experimental"],
  ),
  g(
    "Industrial Hip Hop",
    "SoundCloud / Underground",
    "industrial hip hop, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "industrial hip hop, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Art Rap",
    "SoundCloud / Underground",
    "art rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "art rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Dream Rap",
    "SoundCloud / Underground",
    "dream rap, spacious atmospheric depth, authentic soundcloud / underground production, radio-ready polish",
    "dream rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Psychedelic Rap",
    "SoundCloud / Underground",
    "psychedelic rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "psychedelic rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Witch Rap",
    "SoundCloud / Underground",
    "witch rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "witch rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Sigilkore Rap",
    "SoundCloud / Underground",
    "sigilkore rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "sigilkore rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Hyperpop Rap",
    "SoundCloud / Underground",
    "hyperpop rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "hyperpop rap, soundcloud / underground, modern production, polished mix",
    155,
    ["2020s"],
  ),
  g(
    "Digicore Rap",
    "SoundCloud / Underground",
    "digicore rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "digicore rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Glitchcore Rap",
    "SoundCloud / Underground",
    "glitchcore rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "glitchcore rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "HexD Rap",
    "SoundCloud / Underground",
    "hexd rap, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "hexd rap, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Drain Gang Style",
    "SoundCloud / Underground",
    "drain gang style, melancholic emotional atmosphere, authentic soundcloud / underground production, radio-ready polish",
    "drain gang style, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s","melancholic"],
  ),
  g(
    "Opium Style",
    "SoundCloud / Underground",
    "opium style, modern underground pocket and clean mix, authentic soundcloud / underground production, radio-ready polish",
    "opium style, soundcloud / underground, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Boom Bap",
    "Old School / Classic",
    "boom bap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "boom bap, old school / classic, modern production, polished mix",
    92,
    ["2020s","1990s"],
  ),
  g(
    "Jazz Rap",
    "Old School / Classic",
    "jazz rap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "jazz rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Conscious Rap",
    "Old School / Classic",
    "conscious rap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "conscious rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Political Hip Hop",
    "Old School / Classic",
    "political hip hop, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "political hip hop, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "G-Funk",
    "Old School / Classic",
    "g-funk, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "g-funk, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Mafioso Rap",
    "Old School / Classic",
    "mafioso rap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "mafioso rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "East Coast Rap",
    "Old School / Classic",
    "east coast rap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "east coast rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "West Coast Rap",
    "Old School / Classic",
    "west coast rap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "west coast rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Southern Hip Hop",
    "Old School / Classic",
    "southern hip hop, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "southern hip hop, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Dirty South",
    "Old School / Classic",
    "dirty south, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "dirty south, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Memphis Rap",
    "Old School / Classic",
    "memphis rap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "memphis rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Crunk",
    "Old School / Classic",
    "crunk, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "crunk, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Snap Music",
    "Old School / Classic",
    "snap music, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "snap music, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Hyphy",
    "Old School / Classic",
    "hyphy, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "hyphy, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Horrorcore",
    "Old School / Classic",
    "horrorcore, aggressive high-intensity energy, authentic old school / classic production, radio-ready polish",
    "horrorcore, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s","aggressive"],
  ),
  g(
    "Hardcore Rap",
    "Old School / Classic",
    "hardcore rap, aggressive high-intensity energy, authentic old school / classic production, radio-ready polish",
    "hardcore rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s","aggressive"],
  ),
  g(
    "Backpack Rap",
    "Old School / Classic",
    "backpack rap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "backpack rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Golden Era Hip Hop",
    "Old School / Classic",
    "golden era hip hop, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "golden era hip hop, old school / classic, modern production, polished mix",
    92,
    ["2020s","1990s"],
  ),
  g(
    "Freestyle Rap",
    "Old School / Classic",
    "freestyle rap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "freestyle rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Old School Party Rap",
    "Old School / Classic",
    "old school party rap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "old school party rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Turntablism",
    "Old School / Classic",
    "turntablism, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "turntablism, old school / classic, modern production, polished mix",
    92,
    ["2020s","1990s"],
  ),
  g(
    "Gangsta Rap",
    "Old School / Classic",
    "gangsta rap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "gangsta rap, old school / classic, modern production, polished mix",
    130,
    ["2020s","1990s"],
  ),
  g(
    "Underground Boom Bap",
    "Old School / Classic",
    "underground boom bap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "underground boom bap, old school / classic, modern production, polished mix",
    92,
    ["2020s","1990s"],
  ),
  g(
    "Lo-Fi Boom Bap",
    "Old School / Classic",
    "lo-fi boom bap, warm nostalgic texture, authentic old school / classic production, radio-ready polish",
    "lo-fi boom bap, old school / classic, modern production, polished mix",
    92,
    ["2020s","1990s","lo-fi"],
  ),
  g(
    "Neo Boom Bap",
    "Old School / Classic",
    "neo boom bap, modern underground pocket and clean mix, authentic old school / classic production, radio-ready polish",
    "neo boom bap, old school / classic, modern production, polished mix",
    92,
    ["2020s","1990s"],
  ),
  g(
    "UK Drill",
    "Drill / Aggressive",
    "uk drill, dark sliding bass and rapid hi-hats, authentic drill / aggressive production, radio-ready polish",
    "uk drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "NY Drill",
    "Drill / Aggressive",
    "ny drill, dark sliding bass and rapid hi-hats, authentic drill / aggressive production, radio-ready polish",
    "ny drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Dark Drill",
    "Drill / Aggressive",
    "dark drill, dark sliding bass and rapid hi-hats, authentic drill / aggressive production, radio-ready polish",
    "dark drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Cinematic Drill",
    "Drill / Aggressive",
    "cinematic drill, dark sliding bass and rapid hi-hats, authentic drill / aggressive production, radio-ready polish",
    "cinematic drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Rage Drill",
    "Drill / Aggressive",
    "rage drill, aggressive high-intensity energy, authentic drill / aggressive production, radio-ready polish",
    "rage drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Horror Drill",
    "Drill / Aggressive",
    "horror drill, aggressive high-intensity energy, authentic drill / aggressive production, radio-ready polish",
    "horror drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Melo Drill",
    "Drill / Aggressive",
    "melo drill, dark sliding bass and rapid hi-hats, authentic drill / aggressive production, radio-ready polish",
    "melo drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Hyper Drill",
    "Drill / Aggressive",
    "hyper drill, dark sliding bass and rapid hi-hats, authentic drill / aggressive production, radio-ready polish",
    "hyper drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Trap Drill",
    "Drill / Aggressive",
    "trap drill, dark sliding bass and rapid hi-hats, authentic drill / aggressive production, radio-ready polish",
    "trap drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","trap","aggressive"],
  ),
  g(
    "Orchestral Drill",
    "Drill / Aggressive",
    "orchestral drill, dark sliding bass and rapid hi-hats, authentic drill / aggressive production, radio-ready polish",
    "orchestral drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","aggressive"],
  ),
  g(
    "Experimental Drill",
    "Drill / Aggressive",
    "experimental drill, dark sliding bass and rapid hi-hats, authentic drill / aggressive production, radio-ready polish",
    "experimental drill, drill / aggressive, modern production, polished mix",
    142,
    ["2020s","aggressive","experimental"],
  ),
  g(
    "Detroit Rap",
    "Regional / Internet",
    "detroit rap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "detroit rap, regional / internet, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Flint Rap",
    "Regional / Internet",
    "flint rap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "flint rap, regional / internet, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Michigan Trap",
    "Regional / Internet",
    "michigan trap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "michigan trap, regional / internet, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Jersey Club Rap",
    "Regional / Internet",
    "jersey club rap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "jersey club rap, regional / internet, modern production, polished mix",
    138,
    ["2020s"],
  ),
  g(
    "Philly Club Rap",
    "Regional / Internet",
    "philly club rap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "philly club rap, regional / internet, modern production, polished mix",
    138,
    ["2020s"],
  ),
  g(
    "Bay Area Rap",
    "Regional / Internet",
    "bay area rap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "bay area rap, regional / internet, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Chopped & Screwed",
    "Regional / Internet",
    "chopped & screwed, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "chopped & screwed, regional / internet, modern production, polished mix",
    68,
    ["2020s"],
  ),
  g(
    "Houston Slowed",
    "Regional / Internet",
    "houston slowed, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "houston slowed, regional / internet, modern production, polished mix",
    72,
    ["2020s"],
  ),
  g(
    "Memphis Revival",
    "Regional / Internet",
    "memphis revival, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "memphis revival, regional / internet, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Cali Bounce",
    "Regional / Internet",
    "cali bounce, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "cali bounce, regional / internet, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "DMV Flow",
    "Regional / Internet",
    "dmv flow, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "dmv flow, regional / internet, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "UK Rap",
    "Regional / Internet",
    "uk rap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "uk rap, regional / internet, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Grime Rap",
    "Regional / Internet",
    "grime rap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "grime rap, regional / internet, modern production, polished mix",
    140,
    ["2020s"],
  ),
  g(
    "Afro Trap",
    "Regional / Internet",
    "afro trap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "afro trap, regional / internet, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "French Trap",
    "Regional / Internet",
    "french trap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "french trap, regional / internet, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Brazilian Trap",
    "Regional / Internet",
    "brazilian trap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "brazilian trap, regional / internet, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Japanese Trap",
    "Regional / Internet",
    "japanese trap, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "japanese trap, regional / internet, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Korean Hip Hop",
    "Regional / Internet",
    "korean hip hop, modern underground pocket and clean mix, authentic regional / internet production, radio-ready polish",
    "korean hip hop, regional / internet, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Sadboy Rap",
    "Emotional / Atmospheric",
    "sadboy rap, melancholic emotional atmosphere, authentic emotional / atmospheric production, radio-ready polish",
    "sadboy rap, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s","melancholic"],
  ),
  g(
    "Emotional Rap",
    "Emotional / Atmospheric",
    "emotional rap, modern underground pocket and clean mix, authentic emotional / atmospheric production, radio-ready polish",
    "emotional rap, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Melancholic Hip Hop",
    "Emotional / Atmospheric",
    "melancholic hip hop, melancholic emotional atmosphere, authentic emotional / atmospheric production, radio-ready polish",
    "melancholic hip hop, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s","melancholic"],
  ),
  g(
    "Dreamy Hip Hop",
    "Emotional / Atmospheric",
    "dreamy hip hop, spacious atmospheric depth, authentic emotional / atmospheric production, radio-ready polish",
    "dreamy hip hop, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Rainy Night Rap",
    "Emotional / Atmospheric",
    "rainy night rap, melancholic emotional atmosphere, authentic emotional / atmospheric production, radio-ready polish",
    "rainy night rap, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s","melancholic"],
  ),
  g(
    "Midnight Rap",
    "Emotional / Atmospheric",
    "midnight rap, modern underground pocket and clean mix, authentic emotional / atmospheric production, radio-ready polish",
    "midnight rap, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Liminal Hip Hop",
    "Emotional / Atmospheric",
    "liminal hip hop, modern underground pocket and clean mix, authentic emotional / atmospheric production, radio-ready polish",
    "liminal hip hop, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Ethereal Rap",
    "Emotional / Atmospheric",
    "ethereal rap, spacious atmospheric depth, authentic emotional / atmospheric production, radio-ready polish",
    "ethereal rap, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Space Rap",
    "Emotional / Atmospheric",
    "space rap, spacious atmospheric depth, authentic emotional / atmospheric production, radio-ready polish",
    "space rap, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Spiritual Hip Hop",
    "Emotional / Atmospheric",
    "spiritual hip hop, modern underground pocket and clean mix, authentic emotional / atmospheric production, radio-ready polish",
    "spiritual hip hop, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Luxury Melancholy",
    "Emotional / Atmospheric",
    "luxury melancholy, melancholic emotional atmosphere, authentic emotional / atmospheric production, radio-ready polish",
    "luxury melancholy, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s","melancholic","smooth"],
  ),
  g(
    "Nostalgic Rap",
    "Emotional / Atmospheric",
    "nostalgic rap, modern underground pocket and clean mix, authentic emotional / atmospheric production, radio-ready polish",
    "nostalgic rap, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "VHS Rap",
    "Emotional / Atmospheric",
    "vhs rap, warm nostalgic texture, authentic emotional / atmospheric production, radio-ready polish",
    "vhs rap, emotional / atmospheric, modern production, polished mix",
    82,
    ["2020s"],
  ),
  g(
    "Y2K Rap",
    "Emotional / Atmospheric",
    "y2k rap, modern underground pocket and clean mix, authentic emotional / atmospheric production, radio-ready polish",
    "y2k rap, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s","2000s"],
  ),
  g(
    "Digital Nostalgia Rap",
    "Emotional / Atmospheric",
    "digital nostalgia rap, modern underground pocket and clean mix, authentic emotional / atmospheric production, radio-ready polish",
    "digital nostalgia rap, emotional / atmospheric, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Edit Audio Rap",
    "TikTok / Viral Era",
    "edit audio rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "edit audio rap, tiktok / viral era, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Sigma Rap",
    "TikTok / Viral Era",
    "sigma rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "sigma rap, tiktok / viral era, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Drift Rap",
    "TikTok / Viral Era",
    "drift rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "drift rap, tiktok / viral era, modern production, polished mix",
    135,
    ["2020s"],
  ),
  g(
    "Gym Rap",
    "TikTok / Viral Era",
    "gym rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "gym rap, tiktok / viral era, modern production, polished mix",
    135,
    ["2020s"],
  ),
  g(
    "Anime Trap",
    "TikTok / Viral Era",
    "anime trap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "anime trap, tiktok / viral era, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Viral Trap",
    "TikTok / Viral Era",
    "viral trap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "viral trap, tiktok / viral era, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Bass Boosted Rap",
    "TikTok / Viral Era",
    "bass boosted rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "bass boosted rap, tiktok / viral era, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Nightcore Rap",
    "TikTok / Viral Era",
    "nightcore rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "nightcore rap, tiktok / viral era, modern production, polished mix",
    155,
    ["2020s"],
  ),
  g(
    "Slowed + Reverb Rap",
    "TikTok / Viral Era",
    "slowed + reverb rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "slowed + reverb rap, tiktok / viral era, modern production, polished mix",
    72,
    ["2020s"],
  ),
  g(
    "Hyper Edit Rap",
    "TikTok / Viral Era",
    "hyper edit rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "hyper edit rap, tiktok / viral era, modern production, polished mix",
    155,
    ["2020s"],
  ),
  g(
    "Cinematic Edit Rap",
    "TikTok / Viral Era",
    "cinematic edit rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "cinematic edit rap, tiktok / viral era, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "AMV Rap",
    "TikTok / Viral Era",
    "amv rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "amv rap, tiktok / viral era, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Phonk Rap",
    "TikTok / Viral Era",
    "phonk rap, modern underground pocket and clean mix, authentic tiktok / viral era production, radio-ready polish",
    "phonk rap, tiktok / viral era, modern production, polished mix",
    135,
    ["2020s"],
  ),
  g(
    "Rage Edit Music",
    "TikTok / Viral Era",
    "rage edit music, aggressive high-intensity energy, authentic tiktok / viral era production, radio-ready polish",
    "rage edit music, tiktok / viral era, modern production, polished mix",
    130,
    ["2020s","aggressive"],
  ),
  g(
    "Runway Rap",
    "Luxury / Fashion / Aesthetic",
    "runway rap, polished upscale nightlife energy, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "runway rap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Fashion Week Rap",
    "Luxury / Fashion / Aesthetic",
    "fashion week rap, polished upscale nightlife energy, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "fashion week rap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s","smooth"],
  ),
  g(
    "Designer Trap",
    "Luxury / Fashion / Aesthetic",
    "designer trap, polished upscale nightlife energy, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "designer trap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s","trap","smooth"],
  ),
  g(
    "Luxury Rap",
    "Luxury / Fashion / Aesthetic",
    "luxury rap, polished upscale nightlife energy, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "luxury rap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s","smooth"],
  ),
  g(
    "Avant-Garde Hip Hop",
    "Luxury / Fashion / Aesthetic",
    "avant-garde hip hop, modern underground pocket and clean mix, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "avant-garde hip hop, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s","experimental"],
  ),
  g(
    "Art Gallery Rap",
    "Luxury / Fashion / Aesthetic",
    "art gallery rap, modern underground pocket and clean mix, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "art gallery rap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Cyber Luxury Trap",
    "Luxury / Fashion / Aesthetic",
    "cyber luxury trap, polished upscale nightlife energy, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "cyber luxury trap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s","trap","smooth"],
  ),
  g(
    "Chrome Trap",
    "Luxury / Fashion / Aesthetic",
    "chrome trap, modern underground pocket and clean mix, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "chrome trap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Neo Fashion Rap",
    "Luxury / Fashion / Aesthetic",
    "neo fashion rap, polished upscale nightlife energy, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "neo fashion rap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s","smooth"],
  ),
  g(
    "Futuristic Hip Hop",
    "Luxury / Fashion / Aesthetic",
    "futuristic hip hop, modern underground pocket and clean mix, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "futuristic hip hop, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Editorial Rap",
    "Luxury / Fashion / Aesthetic",
    "editorial rap, modern underground pocket and clean mix, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "editorial rap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Minimal Trap",
    "Luxury / Fashion / Aesthetic",
    "minimal trap, modern underground pocket and clean mix, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "minimal trap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Opulent Trap",
    "Luxury / Fashion / Aesthetic",
    "opulent trap, modern underground pocket and clean mix, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "opulent trap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Dark Luxury Trap",
    "Luxury / Fashion / Aesthetic",
    "dark luxury trap, polished upscale nightlife energy, authentic luxury / fashion / aesthetic production, radio-ready polish",
    "dark luxury trap, luxury / fashion / aesthetic, modern production, polished mix",
    130,
    ["2020s","trap","smooth"],
  ),
  g(
    "Frutiger Aero Rap",
    "Internet Aesthetics Rap",
    "frutiger aero rap, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "frutiger aero rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Dreamcore Hip Hop",
    "Internet Aesthetics Rap",
    "dreamcore hip hop, spacious atmospheric depth, authentic internet aesthetics rap production, radio-ready polish",
    "dreamcore hip hop, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Weirdcore Rap",
    "Internet Aesthetics Rap",
    "weirdcore rap, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "weirdcore rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Webcore Rap",
    "Internet Aesthetics Rap",
    "webcore rap, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "webcore rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Mallsoft Hip Hop",
    "Internet Aesthetics Rap",
    "mallsoft hip hop, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "mallsoft hip hop, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Analog Horror Rap",
    "Internet Aesthetics Rap",
    "analog horror rap, aggressive high-intensity energy, authentic internet aesthetics rap production, radio-ready polish",
    "analog horror rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s","aggressive"],
  ),
  g(
    "VHS Trap",
    "Internet Aesthetics Rap",
    "vhs trap, warm nostalgic texture, authentic internet aesthetics rap production, radio-ready polish",
    "vhs trap, internet aesthetics rap, modern production, polished mix",
    82,
    ["2020s","trap"],
  ),
  g(
    "MP3 Era Rap",
    "Internet Aesthetics Rap",
    "mp3 era rap, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "mp3 era rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Browsercore Rap",
    "Internet Aesthetics Rap",
    "browsercore rap, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "browsercore rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Retro Internet Trap",
    "Internet Aesthetics Rap",
    "retro internet trap, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "retro internet trap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s","trap"],
  ),
  g(
    "Neo Y2K Rap",
    "Internet Aesthetics Rap",
    "neo y2k rap, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "neo y2k rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s","2000s"],
  ),
  g(
    "Playstation 2 Rap",
    "Internet Aesthetics Rap",
    "playstation 2 rap, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "playstation 2 rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Midnight Browser Rap",
    "Internet Aesthetics Rap",
    "midnight browser rap, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "midnight browser rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Digital Dream Rap",
    "Internet Aesthetics Rap",
    "digital dream rap, spacious atmospheric depth, authentic internet aesthetics rap production, radio-ready polish",
    "digital dream rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s","atmospheric"],
  ),
  g(
    "Artificial Nostalgia Rap",
    "Internet Aesthetics Rap",
    "artificial nostalgia rap, modern underground pocket and clean mix, authentic internet aesthetics rap production, radio-ready polish",
    "artificial nostalgia rap, internet aesthetics rap, modern production, polished mix",
    130,
    ["2020s"],
  ),
  g(
    "Ambient R&B",
    "R&B / Soul",
    "ambient r&b, spacious atmospheric depth, authentic r&b / soul production, radio-ready polish",
    "ambient r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Contemporary Soul",
    "R&B / Soul",
    "contemporary soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "contemporary soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Psychedelic Soul",
    "R&B / Soul",
    "psychedelic soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "psychedelic soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Bedroom R&B",
    "R&B / Soul",
    "bedroom r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "bedroom r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","lo-fi"],
  ),
  g(
    "Indie R&B",
    "R&B / Soul",
    "indie r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "indie r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Emotional R&B",
    "R&B / Soul",
    "emotional r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "emotional r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Dreamy R&B",
    "R&B / Soul",
    "dreamy r&b, spacious atmospheric depth, authentic r&b / soul production, radio-ready polish",
    "dreamy r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Midnight R&B",
    "R&B / Soul",
    "midnight r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "midnight r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Late Night Soul",
    "R&B / Soul",
    "late night soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "late night soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Rainy Night R&B",
    "R&B / Soul",
    "rainy night r&b, melancholic emotional atmosphere, authentic r&b / soul production, radio-ready polish",
    "rainy night r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","melancholic"],
  ),
  g(
    "Ethereal R&B",
    "R&B / Soul",
    "ethereal r&b, spacious atmospheric depth, authentic r&b / soul production, radio-ready polish",
    "ethereal r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Experimental R&B",
    "R&B / Soul",
    "experimental r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "experimental r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","experimental"],
  ),
  g(
    "Chill R&B",
    "R&B / Soul",
    "chill r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "chill r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Velvet Soul",
    "R&B / Soul",
    "velvet soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "velvet soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Smooth Soul",
    "R&B / Soul",
    "smooth soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "smooth soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Soft Soul",
    "R&B / Soul",
    "soft soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "soft soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Minimal Soul",
    "R&B / Soul",
    "minimal soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "minimal soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Luxury Soul",
    "R&B / Soul",
    "luxury soul, polished upscale nightlife energy, authentic r&b / soul production, radio-ready polish",
    "luxury soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","smooth"],
  ),
  g(
    "Fashion R&B",
    "R&B / Soul",
    "fashion r&b, polished upscale nightlife energy, authentic r&b / soul production, radio-ready polish",
    "fashion r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","smooth"],
  ),
  g(
    "Cinematic R&B",
    "R&B / Soul",
    "cinematic r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "cinematic r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Jazzy R&B",
    "R&B / Soul",
    "jazzy r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "jazzy r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Acoustic R&B",
    "R&B / Soul",
    "acoustic r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "acoustic r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Piano Soul",
    "R&B / Soul",
    "piano soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "piano soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Vinyl Soul",
    "R&B / Soul",
    "vinyl soul, warm nostalgic texture, authentic r&b / soul production, radio-ready polish",
    "vinyl soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Retro Soul",
    "R&B / Soul",
    "retro soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "retro soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Y2K R&B",
    "R&B / Soul",
    "y2k r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "y2k r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","2000s","r&b/soul"],
  ),
  g(
    "2000s R&B",
    "R&B / Soul",
    "2000s r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "2000s r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","2000s","r&b/soul"],
  ),
  g(
    "90s Slow Jam",
    "R&B / Soul",
    "90s slow jam, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "90s slow jam, r&b / soul, modern production, polished mix",
    72,
    ["2020s","2000s"],
  ),
  g(
    "Slow Jamz",
    "R&B / Soul",
    "slow jamz, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "slow jamz, r&b / soul, modern production, polished mix",
    72,
    ["2020s"],
  ),
  g(
    "Quiet Storm",
    "R&B / Soul",
    "quiet storm, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "quiet storm, r&b / soul, modern production, polished mix",
    72,
    ["2020s"],
  ),
  g(
    "Alternative Soul",
    "R&B / Soul",
    "alternative soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "alternative soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Cloud R&B",
    "R&B / Soul",
    "cloud r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "cloud r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Space Soul",
    "R&B / Soul",
    "space soul, spacious atmospheric depth, authentic r&b / soul production, radio-ready polish",
    "space soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Cosmic R&B",
    "R&B / Soul",
    "cosmic r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "cosmic r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Dream Soul",
    "R&B / Soul",
    "dream soul, spacious atmospheric depth, authentic r&b / soul production, radio-ready polish",
    "dream soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Melancholic Soul",
    "R&B / Soul",
    "melancholic soul, melancholic emotional atmosphere, authentic r&b / soul production, radio-ready polish",
    "melancholic soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","melancholic"],
  ),
  g(
    "Spiritual Soul",
    "R&B / Soul",
    "spiritual soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "spiritual soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Vulnerable R&B",
    "R&B / Soul",
    "vulnerable r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "vulnerable r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Romantic R&B",
    "R&B / Soul",
    "romantic r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "romantic r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Intimate R&B",
    "R&B / Soul",
    "intimate r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "intimate r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Seductive R&B",
    "R&B / Soul",
    "seductive r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "seductive r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Soft Girl R&B",
    "R&B / Soul",
    "soft girl r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "soft girl r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Digital Soul",
    "R&B / Soul",
    "digital soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "digital soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Internet Soul",
    "R&B / Soul",
    "internet soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "internet soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Tumblr Era R&B",
    "R&B / Soul",
    "tumblr era r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "tumblr era r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Blog Era Soul",
    "R&B / Soul",
    "blog era soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "blog era soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Cassette Soul",
    "R&B / Soul",
    "cassette soul, warm nostalgic texture, authentic r&b / soul production, radio-ready polish",
    "cassette soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "VHS Soul",
    "R&B / Soul",
    "vhs soul, warm nostalgic texture, authentic r&b / soul production, radio-ready polish",
    "vhs soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Chrome Soul",
    "R&B / Soul",
    "chrome soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "chrome soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Holographic Soul",
    "R&B / Soul",
    "holographic soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "holographic soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Synthetic Soul",
    "R&B / Soul",
    "synthetic soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "synthetic soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Analog Soul",
    "R&B / Soul",
    "analog soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "analog soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Neo Lounge Soul",
    "R&B / Soul",
    "neo lounge soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "neo lounge soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Chillwave R&B",
    "R&B / Soul",
    "chillwave r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "chillwave r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Vapor Soul",
    "R&B / Soul",
    "vapor soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "vapor soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Future Soul",
    "R&B / Soul",
    "future soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "future soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Afro Soul",
    "R&B / Soul",
    "afro soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "afro soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "UK Soul",
    "R&B / Soul",
    "uk soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "uk soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Soul Pop",
    "R&B / Soul",
    "soul pop, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "soul pop, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Soulwave",
    "R&B / Soul",
    "soulwave, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "soulwave, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Dreamwave R&B",
    "R&B / Soul",
    "dreamwave r&b, spacious atmospheric depth, authentic r&b / soul production, radio-ready polish",
    "dreamwave r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Soultronica",
    "R&B / Soul",
    "soultronica, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "soultronica, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Electro Soul",
    "R&B / Soul",
    "electro soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "electro soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Deep Soul",
    "R&B / Soul",
    "deep soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "deep soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Velvet Nights",
    "R&B / Soul",
    "velvet nights, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "velvet nights, r&b / soul, modern production, polished mix",
    88,
    ["2020s"],
  ),
  g(
    "Sunset Soul",
    "R&B / Soul",
    "sunset soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "sunset soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Ocean Soul",
    "R&B / Soul",
    "ocean soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "ocean soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Moonlight R&B",
    "R&B / Soul",
    "moonlight r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "moonlight r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Neon Soul",
    "R&B / Soul",
    "neon soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "neon soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Liquid Soul",
    "R&B / Soul",
    "liquid soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "liquid soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Floating Soul",
    "R&B / Soul",
    "floating soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "floating soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Digital Romance",
    "R&B / Soul",
    "digital romance, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "digital romance, r&b / soul, modern production, polished mix",
    88,
    ["2020s"],
  ),
  g(
    "Heartbreak Soul",
    "R&B / Soul",
    "heartbreak soul, melancholic emotional atmosphere, authentic r&b / soul production, radio-ready polish",
    "heartbreak soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","melancholic"],
  ),
  g(
    "After Hours R&B",
    "R&B / Soul",
    "after hours r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "after hours r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Lounge R&B",
    "R&B / Soul",
    "lounge r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "lounge r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Late Drive Soul",
    "R&B / Soul",
    "late drive soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "late drive soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Motel Soul",
    "R&B / Soul",
    "motel soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "motel soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Luxury Hotel R&B",
    "R&B / Soul",
    "luxury hotel r&b, polished upscale nightlife energy, authentic r&b / soul production, radio-ready polish",
    "luxury hotel r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","smooth"],
  ),
  g(
    "Paris Night Soul",
    "R&B / Soul",
    "paris night soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "paris night soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Tokyo Soul",
    "R&B / Soul",
    "tokyo soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "tokyo soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Seoul Midnight R&B",
    "R&B / Soul",
    "seoul midnight r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "seoul midnight r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Miami Sunset Soul",
    "R&B / Soul",
    "miami sunset soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "miami sunset soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Cigarette Break Soul",
    "R&B / Soul",
    "cigarette break soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "cigarette break soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Bedroom Confession R&B",
    "R&B / Soul",
    "bedroom confession r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "bedroom confession r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","lo-fi"],
  ),
  g(
    "Slow Motion Soul",
    "R&B / Soul",
    "slow motion soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "slow motion soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Emotional Luxury",
    "R&B / Soul",
    "emotional luxury, polished upscale nightlife energy, authentic r&b / soul production, radio-ready polish",
    "emotional luxury, r&b / soul, modern production, polished mix",
    88,
    ["2020s","smooth"],
  ),
  g(
    "Soft Chaos Soul",
    "R&B / Soul",
    "soft chaos soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "soft chaos soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Introspective R&B",
    "R&B / Soul",
    "introspective r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "introspective r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Vulnerable Nights",
    "R&B / Soul",
    "vulnerable nights, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "vulnerable nights, r&b / soul, modern production, polished mix",
    88,
    ["2020s"],
  ),
  g(
    "Crying in Designer Clothes",
    "R&B / Soul",
    "crying in designer clothes, melancholic emotional atmosphere, authentic r&b / soul production, radio-ready polish",
    "crying in designer clothes, r&b / soul, modern production, polished mix",
    88,
    ["2020s","smooth"],
  ),
  g(
    "Nostalgic Romance",
    "R&B / Soul",
    "nostalgic romance, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "nostalgic romance, r&b / soul, modern production, polished mix",
    88,
    ["2020s"],
  ),
  g(
    "Rain on Windows R&B",
    "R&B / Soul",
    "rain on windows r&b, melancholic emotional atmosphere, authentic r&b / soul production, radio-ready polish",
    "rain on windows r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","melancholic"],
  ),
  g(
    "Floating Memories Soul",
    "R&B / Soul",
    "floating memories soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "floating memories soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Dream Apartment R&B",
    "R&B / Soul",
    "dream apartment r&b, spacious atmospheric depth, authentic r&b / soul production, radio-ready polish",
    "dream apartment r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul","atmospheric"],
  ),
  g(
    "Silk Soul",
    "R&B / Soul",
    "silk soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "silk soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Satin R&B",
    "R&B / Soul",
    "satin r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "satin r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Velvet Rain",
    "R&B / Soul",
    "velvet rain, melancholic emotional atmosphere, authentic r&b / soul production, radio-ready polish",
    "velvet rain, r&b / soul, modern production, polished mix",
    88,
    ["2020s","melancholic"],
  ),
  g(
    "Chrome Tears",
    "R&B / Soul",
    "chrome tears, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "chrome tears, r&b / soul, modern production, polished mix",
    88,
    ["2020s"],
  ),
  g(
    "Neon Heartbreak",
    "R&B / Soul",
    "neon heartbreak, melancholic emotional atmosphere, authentic r&b / soul production, radio-ready polish",
    "neon heartbreak, r&b / soul, modern production, polished mix",
    88,
    ["2020s","melancholic"],
  ),
  g(
    "Emotional Futurism",
    "R&B / Soul",
    "emotional futurism, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "emotional futurism, r&b / soul, modern production, polished mix",
    88,
    ["2020s"],
  ),
  g(
    "Artificial Romance",
    "R&B / Soul",
    "artificial romance, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "artificial romance, r&b / soul, modern production, polished mix",
    88,
    ["2020s"],
  ),
  g(
    "Digital Heartbreak",
    "R&B / Soul",
    "digital heartbreak, melancholic emotional atmosphere, authentic r&b / soul production, radio-ready polish",
    "digital heartbreak, r&b / soul, modern production, polished mix",
    88,
    ["2020s","melancholic"],
  ),
  g(
    "Midnight Confessions",
    "R&B / Soul",
    "midnight confessions, modern underground pocket and clean mix, authentic r&b / soul production, radio-ready polish",
    "midnight confessions, r&b / soul, modern production, polished mix",
    88,
    ["2020s"],
  ),
  g(
    "Purple Lights R&B",
    "R&B / Soul",
    "purple lights r&b, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "purple lights r&b, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Soft Neon Soul",
    "R&B / Soul",
    "soft neon soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "soft neon soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Late Text Message Soul",
    "R&B / Soul",
    "late text message soul, smooth heartfelt chord movement and intimate groove, authentic r&b / soul production, radio-ready polish",
    "late text message soul, r&b / soul, modern production, polished mix",
    88,
    ["2020s","r&b/soul"],
  ),
  g(
    "Emotional Trap Soul",
    "Trap Soul / Hybrid",
    "emotional trap soul, smooth heartfelt chord movement and intimate groove, authentic trap soul / hybrid production, radio-ready polish",
    "emotional trap soul, trap soul / hybrid, modern production, polished mix",
    88,
    ["2020s","trap","r&b/soul"],
  ),
  g(
    "Ambient Trap Soul",
    "Trap Soul / Hybrid",
    "ambient trap soul, spacious atmospheric depth, authentic trap soul / hybrid production, radio-ready polish",
    "ambient trap soul, trap soul / hybrid, modern production, polished mix",
    88,
    ["2020s","trap","r&b/soul","atmospheric"],
  ),
  g(
    "Dark Trap Soul",
    "Trap Soul / Hybrid",
    "dark trap soul, smooth heartfelt chord movement and intimate groove, authentic trap soul / hybrid production, radio-ready polish",
    "dark trap soul, trap soul / hybrid, modern production, polished mix",
    88,
    ["2020s","trap","r&b/soul"],
  ),
  g(
    "Neo Trap Soul",
    "Trap Soul / Hybrid",
    "neo trap soul, smooth heartfelt chord movement and intimate groove, authentic trap soul / hybrid production, radio-ready polish",
    "neo trap soul, trap soul / hybrid, modern production, polished mix",
    88,
    ["2020s","trap","r&b/soul"],
  ),
  g(
    "Atmospheric Trap Soul",
    "Trap Soul / Hybrid",
    "atmospheric trap soul, smooth heartfelt chord movement and intimate groove, authentic trap soul / hybrid production, radio-ready polish",
    "atmospheric trap soul, trap soul / hybrid, modern production, polished mix",
    88,
    ["2020s","trap","r&b/soul"],
  ),
  g(
    "Sad Trap Soul",
    "Trap Soul / Hybrid",
    "sad trap soul, melancholic emotional atmosphere, authentic trap soul / hybrid production, radio-ready polish",
    "sad trap soul, trap soul / hybrid, modern production, polished mix",
    88,
    ["2020s","trap","r&b/soul","melancholic"],
  ),
  g(
    "Luxury Trap Soul",
    "Trap Soul / Hybrid",
    "luxury trap soul, polished upscale nightlife energy, authentic trap soul / hybrid production, radio-ready polish",
    "luxury trap soul, trap soul / hybrid, modern production, polished mix",
    88,
    ["2020s","trap","r&b/soul","smooth"],
  ),
  g(
    "Lo-Fi Trap Soul",
    "Trap Soul / Hybrid",
    "lo-fi trap soul, warm nostalgic texture, authentic trap soul / hybrid production, radio-ready polish",
    "lo-fi trap soul, trap soul / hybrid, modern production, polished mix",
    88,
    ["2020s","trap","r&b/soul","lo-fi"],
  ),
  g(
    "Midnight Trap Soul",
    "Trap Soul / Hybrid",
    "midnight trap soul, smooth heartfelt chord movement and intimate groove, authentic trap soul / hybrid production, radio-ready polish",
    "midnight trap soul, trap soul / hybrid, modern production, polished mix",
    88,
    ["2020s","trap","r&b/soul"],
  ),
  g(
    "Rainy Trap Soul",
    "Trap Soul / Hybrid",
    "rainy trap soul, melancholic emotional atmosphere, authentic trap soul / hybrid production, radio-ready polish",
    "rainy trap soul, trap soul / hybrid, modern production, polished mix",
    88,
    ["2020s","trap","r&b/soul","melancholic"],
  ),
];
