import type { DropdownOption } from "@/components/ui/Dropdown";
import { extendedGenreDropdownOptions } from "@/lib/genres/extendedCatalog";

/** Core genres already in the app before the extended catalog expansion. */
export const CORE_GENRE_OPTIONS: DropdownOption[] = [
  { value: "Auto", label: "Auto" },
  { group: "Trap / Hip-Hop", value: "Contemporary Rap", label: "Contemporary Rap" },
  { group: "Trap / Hip-Hop", value: "Dark Trap", label: "Dark Trap" },
  { group: "Trap / Hip-Hop", value: "Melodic Trap", label: "Melodic Trap" },
  { group: "Trap / Hip-Hop", value: "PluggnB", label: "PluggnB" },
  { group: "Trap / Hip-Hop", value: "Rage", label: "Rage" },
  { group: "Trap / Hip-Hop", value: "Cloud Rap", label: "Cloud Rap" },
  { group: "Trap / Hip-Hop", value: "Emo Rap", label: "Emo Rap" },
  { group: "Trap / Hip-Hop", value: "Sad Rap", label: "Sad Rap" },
  { group: "Trap / Hip-Hop", value: "Atmospheric Rap", label: "Atmospheric Rap" },
  { group: "Trap / Hip-Hop", value: "Emotional Trap", label: "Emotional Trap" },
  { group: "Trap / Hip-Hop", value: "Ambient Trap", label: "Ambient Trap" },
  { group: "Trap / Hip-Hop", value: "Cinematic Trap", label: "Cinematic Trap" },
  { group: "Trap / Hip-Hop", value: "Experimental Trap", label: "Experimental Trap" },
  { group: "Trap / Hip-Hop", value: "Old School Hip-Hop", label: "Old School (Boom Bap)" },
  { group: "Trap / Hip-Hop", value: "Drill", label: "Drill" },
  { group: "Trap / Hip-Hop", value: "Jersey Drill", label: "Jersey Drill" },
  { group: "Trap / Hip-Hop", value: "Afrotrap", label: "Afrotrap" },
  { group: "Trap / Hip-Hop", value: "Sample Drill", label: "Sample Drill" },
  { group: "Trap / Hip-Hop", value: "Melodic Drill", label: "Melodic Drill" },
  { group: "Trap / Hip-Hop", value: "Lo-Fi Hip-Hop", label: "Lo‑Fi (Hip Hop)" },
  { group: "R&B / Soul", value: "Trapsoul", label: "Trap Soul" },
  { group: "R&B / Soul", value: "90s R&B", label: "90s R&B" },
  { group: "R&B / Soul", value: "Contemporary R&B", label: "Contemporary R&B" },
  { group: "R&B / Soul", value: "R&B Alternative", label: "R&B Alternative" },
  { group: "R&B / Soul", value: "Dark R&B", label: "Dark R&B" },
  { group: "R&B / Soul", value: "Future R&B", label: "Future R&B" },
  { group: "R&B / Soul", value: "Afro R&B", label: "Afro R&B" },
  { group: "R&B / Soul", value: "Toxic R&B", label: "Toxic R&B" },
  { group: "R&B / Soul", value: "Neo Soul", label: "Neo Soul" },
  { group: "R&B / Soul", value: "Soul", label: "Soul" },
  { group: "R&B / Soul", value: "Funk", label: "Funk" },
  { group: "R&B / Soul", value: "Lo-fi R&B", label: "Lo‑Fi R&B" },
  { group: "Afro / Latin / Island", value: "Afrobeats", label: "Afrobeats" },
  { group: "Afro / Latin / Island", value: "Amapiano", label: "Amapiano" },
  { group: "Afro / Latin / Island", value: "Afro House", label: "Afro House" },
  { group: "Afro / Latin / Island", value: "Latin", label: "Latin" },
  { group: "Afro / Latin / Island", value: "Reggaeton", label: "Reggaeton" },
  { group: "Afro / Latin / Island", value: "Baile Funk", label: "Baile Funk" },
  { group: "Afro / Latin / Island", value: "Dancehall", label: "Dancehall" },
  { group: "Afro / Latin / Island", value: "Reggae", label: "Reggae" },
  { group: "Electronic / Pop", value: "House", label: "House" },
  { group: "Electronic / Pop", value: "Pop", label: "Pop" },
  { group: "Electronic / Pop", value: "K-Pop", label: "K‑Pop" },
  { group: "Electronic / Pop", value: "Indie Pop", label: "Indie Pop" },
  { group: "Electronic / Pop", value: "Dream Pop", label: "Dream Pop" },
  { group: "Electronic / Pop", value: "Dance Pop", label: "Dance Pop" },
  { group: "Electronic / Pop", value: "Viral TikTok", label: "Viral TikTok" },
  { group: "Electronic / Pop", value: "Viral TikTok Pop", label: "Viral TikTok Pop" },
  { group: "Electronic / Pop", value: "French Pop", label: "French Pop" },
  { group: "Electronic / Pop", value: "UK Garage", label: "UK Garage" },
  { group: "Electronic / Pop", value: "Speed Garage", label: "Speed Garage" },
  { group: "Electronic / Pop", value: "Drum and Bass", label: "Drum & Bass" },
  { group: "Electronic / Pop", value: "Jersey Club", label: "Jersey Club" },
  { group: "Electronic / Pop", value: "Electro", label: "Electro" },
  { group: "Electronic / Pop", value: "Video Game", label: "Video Game" },
  { group: "Electronic / Pop", value: "Hyperpop", label: "Hyperpop" },
  { group: "Electronic / Pop", value: "Hyperpop (Hip-Hop/R&B)", label: "Hyperpop (Hip-Hop/R&B)" },
  { group: "Electronic / Pop", value: "EDM", label: "EDM" },
  { group: "Electronic / Pop", value: "Chillstep", label: "Chillstep" },
  { group: "Electronic / Pop", value: "Dubstep", label: "Dubstep" },
  { group: "Electronic / Pop", value: "Vaporwave", label: "Vaporwave" },
  { group: "Electronic / Pop", value: "Synthwave", label: "SynthWave" },
  { group: "Electronic / Pop", value: "Witch House", label: "Witch House" },
  { group: "Electronic / Pop", value: "Glitchcore", label: "Glitchcore" },
  { group: "Electronic / Pop", value: "Digicore", label: "Digicore" },
  { group: "Electronic / Pop", value: "Brazilian Phonk", label: "Brazilian Phonk" },
  { group: "Electronic / Pop", value: "VinaHouse", label: "VinaHouse (VN House)" },
  { group: "Electronic / Pop", value: "Study Beats", label: "Study Beats" },
  { group: "Rock", value: "Pop Rock", label: "Pop Rock" },
  { group: "Rock", value: "Rock", label: "Rock" },
  { group: "Other", value: "Jazz", label: "Jazz" },
  { group: "Other", value: "New Jazz", label: "New Jazz" },
  { group: "Other", value: "Classical", label: "Musique Classique" },
  { group: "Other", value: "Opera", label: "Opera" },
  { group: "Other", value: "Oriental", label: "Oriental" },
  { group: "Other", value: "Guitar Acoustic Live", label: "Guitar Acoustic Live" },
  { group: "Other", value: "Piano Acoustic Live", label: "Piano Acoustic Live" },
  { group: "Other", value: "Country", label: "Country" },
  { group: "LAB (Futur)", value: "Rage + Ambient", label: "Rage + Ambient" },
  { group: "LAB (Futur)", value: "Holographic R&B", label: "Holographic R&B" },
  { group: "LAB (Futur)", value: "Futuristic Trap Soul", label: "Futuristic Trap Soul" },
  { group: "LAB (Futur)", value: "Ambient Drill", label: "Ambient Drill" },
  { group: "LAB (Futur)", value: "Cinematic Afro Trap", label: "Cinematic Afro Trap" },
  { group: "LAB (Futur)", value: "AI-assisted Pop", label: "AI‑assisted Pop" },
  { group: "LAB (Futur)", value: "Experimental Afro House", label: "Experimental Afro House" },
  { group: "LAB (Futur)", value: "Hyper Melodic Rap", label: "Hyper Melodic Rap" },
  { group: "LAB (Futur)", value: "Dark Atmospheric Pop", label: "Dark Atmospheric Pop" },
  { group: "LAB (Futur)", value: "Y2K Futuristic Pop", label: "Y2K Futuristic Pop" },
  { group: "LAB (Futur)", value: "Hybrid Electronic Rap", label: "Hybrid Electronic Rap" },
  { group: "LAB (Futur)", value: "Sci-Fi R&B", label: "Sci‑Fi R&B" },
  { group: "LAB (Futur)", value: "Ethereal Trap", label: "Ethereal Trap" },
  { group: "LAB (Futur)", value: "Nostalgic Future Beats", label: "Nostalgic Future Beats" },
];

const extendedOptions: DropdownOption[] = extendedGenreDropdownOptions().map((item) => ({
  group: item.group,
  value: item.value,
  label: item.label,
}));

/** Full genre list for Dashboard dropdowns — core + extended catalog. */
export const ALL_GENRE_OPTIONS: DropdownOption[] = [...CORE_GENRE_OPTIONS, ...extendedOptions];

export const GENRE_COUNT = ALL_GENRE_OPTIONS.filter((o) => o.value !== "Auto").length;
