/** Wave 3 — Middle East / Gulf, extended K-Pop & Asia niche, Maghreb crossover. */
import type { ExtendedGenreDef } from "@/lib/genres/extendedCatalog";

function g(
  value: string,
  group: string,
  prompt: string,
  aceTags: string,
  bpm: number,
  sonautoTags: string[] = ["2020s"],
): ExtendedGenreDef {
  return { value, group, prompt, aceTags, bpm, sonautoTags };
}

export const WORLD_WAVE3_GENRES: ExtendedGenreDef[] = [

  // ── Middle East / Gulf (Tier 1 SEO) ──
  g(
    "Khaleeji",
    "Middle East / Gulf",
    "khaleeji, Gulf Arabic pop groove, oud or synth tarab melody lead, darbuka and riq percussion pocket, warm sub bass heartbeat, romantic khaleeji vocal melisma space, Dubai-Riyadh radio polish, majlis party bounce optional",
    "khaleeji, Gulf Arabic pop, oud melody, darbuka riq, khaleeji vocal melisma",
    98,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "Arabic Pop",
    "Middle East / Gulf",
    "arabic pop, modern Levant-Egypt pop production, catchy quarter-tone melodic hook, layered synth brass stabs, four-on-the-floor or khaleeji-trap hybrid drums, Arabic vocal topline with melismatic ad-libs, Cairo-Beirut crossover sheen",
    "arabic pop, quarter-tone hooks, synth brass, Arabic vocal melisma, Cairo-Beirut pop",
    102,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Mahraganat",
    "Middle East / Gulf",
    "mahraganat, Egyptian electro-shaabi, distorted synth lead stabs, heavy kick and snare machine groove, auto-tuned Arabic vocal chant hooks, street-festival energy, Cairo shaabi party bounce, aggressive low-end drive",
    "mahraganat, electro-shaabi, distorted synth, auto-tune Arabic vocals, Cairo street party",
    128,
    ["dance", "aggressive", "2020s"],
  ),
  g(
    "Shaabi",
    "Middle East / Gulf",
    "shaabi, Egyptian folk-pop groove, accordion or keyboard lead, tabla and darbuka percussion, working-class party pulse, call-response vocal shouts, raw Cairo street authenticity, festive wedding energy",
    "shaabi, Egyptian folk-pop, accordion lead, tabla darbuka, call-response vocals",
    115,
    ["rhythmic", "energetic", "2020s"],
  ),
  g(
    "Dabke",
    "Middle East / Gulf",
    "dabke, Levantine dabke line-dance groove, mijwiz or synth reed lead, darbuka tumbao with stomp-clap accents, fast 120 BPM circle-dance pulse, Arabic wedding celebration energy, group chant vocal space",
    "dabke, mijwiz reed, darbuka stomp-clap, Levant wedding dance, Arabic chant vocals",
    120,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Gulf Trap",
    "Middle East / Gulf",
    "gulf trap, Khaleeji trap crossover, sliding 808 sub under Arabic scale synth lead, crisp trap hi-hats, auto-tuned Gulf Arabic rap flow space, luxury night-drive Dubai energy, dark minor-key hook",
    "gulf trap, Khaleeji trap, 808 slides, Arabic scale synth, Gulf rap flow",
    130,
    ["hip-hop/rap", "dark", "2020s"],
  ),
  g(
    "Persian Pop",
    "Middle East / Gulf",
    "persian pop, Iranian pop ballad chord stacks, santur or tar pluck accents, daf frame drum groove, emotional Farsi vocal melody space, Tehran studio polish, nostalgic tarab lift in chorus",
    "persian pop, santur tar pluck, daf groove, Farsi vocal melody, Tehran ballad",
    92,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "Turkish Pop",
    "Middle East / Gulf",
    "turkish pop, Anatolian pop-rock crossover, bağlama or electric guitar arpeggios, darbuka and drum kit blend, major-key catchy chorus hook, Istanbul radio production sheen, Turkish vocal belt space",
    "turkish pop, baglama arpeggios, darbuka drums, Istanbul radio chorus, Turkish vocals",
    108,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Mizrahi Pop",
    "Middle East / Gulf",
    "mizrahi pop, Israeli Mizrahi wedding groove, darbuka and electronic percussion stack, Mediterranean scale melody lead, festive party energy, Hebrew-Arabic crossover vocal hooks, Tel Aviv club-night bounce",
    "mizrahi pop, darbuka stack, Mediterranean melody, Mizrahi wedding party, Hebrew-Arabic hooks",
    112,
    ["dance", "rhythmic", "2020s"],
  ),
  g(
    "Afro-Arab",
    "Middle East / Gulf",
    "afro-arab, West African percussion fused with Arabic scale synth leads, talking drum accents over khaleeji sub bass, bilingual Afro-Arab vocal hook space, diaspora club crossover energy, Dubai-Lagos pulse",
    "afro-arab, talking drum, Arabic scale synth, khaleeji sub, diaspora crossover",
    105,
    ["african", "dance", "2020s"],
  ),
  g(
    "Maghreb Pop",
    "Middle East / Gulf",
    "maghreb pop, North African pop crossover, gnawa bass synth pulse, darbuka and bendir layers, French-Arabic bilingual chorus hooks, Casablanca-Algiers radio energy, raï-adjacent melodic ornaments",
    "maghreb pop, gnawa bass pulse, darbuka bendir, French-Arabic chorus, raï ornaments",
    110,
    ["melodic", "rhythmic", "2020s"],
  ),
  g(
    "Levant Pop",
    "Middle East / Gulf",
    "levant pop, modern Syrian-Lebanese pop ballad, piano and string pad stacks, soft darbuka brush groove, emotional Arabic vocal storytelling space, Beirut studio intimacy, diaspora nostalgia lift",
    "levant pop, piano string pads, soft darbuka, Arabic storytelling vocals, Beirut ballad",
    88,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "Qawwali Fusion",
    "Middle East / Gulf",
    "qawwali fusion, harmonium drone bed with tabla rhythmic drive, Sufi-inspired vocal chant layers, handclap congregation pulse, spiritual ecstatic build arc, modern production polish optional, Urdu or Punjabi vocal space",
    "qawwali fusion, harmonium drone, tabla drive, Sufi vocal chants, handclap pulse",
    95,
    ["atmospheric", "melodic", "2020s"],
  ),

  // ── K-Pop & East Asia niche ──
  g(
    "K-Pop Idol",
    "K-Pop & East Asia",
    "K-pop idol, polished Seoul production, stacked vocal harmony hooks, punchy four-on-the-floor or trap-pop hybrid drums, bright supersaw chord drops, rap verse and sung chorus contrast, English-Korean code-switch hooks, music-show choreography energy",
    "K-pop idol, stacked harmonies, trap-pop drums, supersaw drops, rap-sung contrast",
    124,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "K-Pop Ballad",
    "K-Pop & East Asia",
    "K-pop ballad, emotional piano-led chord progression, soft string pad swells, restrained kick-snare groove, soaring Korean vocal belt space in chorus, OST drama intimacy, Seoul winter-night mood",
    "K-pop ballad, piano chords, string swells, Korean vocal belt, OST drama mood",
    72,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "K-Indie",
    "K-Pop & East Asia",
    "K-indie, Hongdae indie band aesthetic, jangly clean guitar arpeggios, lo-fi room drums, warm bass groove, bittersweet Korean vocal storytelling space, bedroom-studio sincerity, cafe playlist mood",
    "K-indie, jangly guitar, lo-fi drums, Korean storytelling vocals, Hongdae indie",
    118,
    ["melodic", "2020s"],
  ),
  g(
    "K-Rock",
    "K-Pop & East Asia",
    "K-rock, Korean alt-rock power chords, driving live drum pocket, melodic bass line, anthemic chorus lift, post-BTS band energy, Korean or English vocal shout space, festival-ready distortion",
    "K-rock, power chords, live drums, anthemic chorus, Korean alt-rock",
    138,
    ["rock", "energetic", "2020s"],
  ),
  g(
    "City Pop",
    "K-Pop & East Asia",
    "city pop, 1980s Japanese city pop revival, funky bass groove, glossy synth brass and electric piano, tight disco-influenced drums, neon Tokyo night-drive nostalgia, smooth Japanese or English vocal hooks",
    "city pop, funky bass, synth brass, disco drums, Tokyo night-drive nostalgia",
    115,
    ["dance", "smooth", "1980s"],
  ),
  g(
    "Anison",
    "K-Pop & East Asia",
    "anison, anime opening song energy, fast melodic guitar or synth lead, driving double-time drum feel, major-key heroic chorus lift, Japanese vocal belt space, orchestral hit accents on chorus drop",
    "anison, anime opening, heroic chorus, fast drums, Japanese vocal belt",
    160,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Trot",
    "K-Pop & East Asia",
    "trot, Korean trot rhythm shuffle, accordion or synth reed lead, four-four danceable groove, nostalgic elder-audience singalong hooks, bright major-key melody, retro Seoul noraebang party energy",
    "trot, Korean shuffle groove, accordion reed lead, noraebang singalong, retro Seoul",
    128,
    ["melodic", "rhythmic", "2020s"],
  ),
  g(
    "Enka",
    "K-Pop & East Asia",
    "enka, Japanese enka ballad, melancholic pentatonic melody line, shamisen or synth koto pluck accents, orchestral string swells, dramatic vocal vibrato space, Showa-era emotional storytelling arc",
    "enka, pentatonic melody, shamisen pluck, string swells, Japanese vocal vibrato",
    78,
    ["melodic", "melancholic", "2020s"],
  ),
  g(
    "J-Indie",
    "K-Pop & East Asia",
    "J-indie, Japanese indie rock, clean tremolo guitar layers, mid-tempo live drum pocket, melodic bass counterlines, introspective Japanese vocal space, Shibuya-kei adjacent sparkle optional",
    "J-indie, tremolo guitar, live drums, introspective Japanese vocals, Shibuya sparkle",
    122,
    ["rock", "melodic", "2020s"],
  ),
  g(
    "Hyperpop K",
    "K-Pop & East Asia",
    "hyperpop K, Korean hyperpop crossover, glitchy synth stabs, pitched vocal chops, maximalist sidechain pump, trap-influenced 808 hits, TikTok challenge hook energy, Seoul digicore aesthetic",
    "hyperpop K, glitch synths, pitched vocal chops, sidechain pump, Seoul digicore",
    145,
    ["dance", "experimental", "2020s"],
  ),

  // ── Maghreb & diaspora wave 3 ──
  g(
    "Amazigh Pop",
    "Maghreb & Diaspora",
    "amazigh pop, Berber-Amazigh melodic ornaments over modern pop drums, bendir and darbuka percussion, Tamazight vocal phrase space, Atlas mountains folk-modern crossover, festive wedding pulse",
    "amazigh pop, Berber ornaments, bendir darbuka, Tamazight vocals, Atlas crossover",
    108,
    ["melodic", "rhythmic", "2020s"],
  ),
  g(
    "Chaabi Marocain",
    "Maghreb & Diaspora",
    "chaabi marocain, Moroccan chaabi party groove, sintir or keyboard lead, darbuka and taarija percussion stack, call-response crowd vocal shouts, Casablanca wedding celebration energy, raw street-festival bounce",
    "chaabi marocain, sintir lead, darbuka taarija, Casablanca wedding party, crowd shouts",
    118,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "Gnawa Fusion",
    "Maghreb & Diaspora",
    "gnawa fusion, gnawa guembri bass pulse, krakebs metal castanet accents, trance-inducing repetitive groove cycles, psychedelic rock or electronic fusion layers optional, spiritual ritual-to-club arc",
    "gnawa fusion, guembri pulse, krakebs castanets, trance groove, ritual-to-club",
    100,
    ["atmospheric", "rhythmic", "2020s"],
  ),
  g(
    "Somali Pop",
    "Maghreb & Diaspora",
    "somali pop, Somali pop ballad chord stacks, oud or synth melody lead, East African percussion bounce, Mogadishu diaspora nostalgia mood, Somali vocal melisma space, warm major-key chorus lift",
    "somali pop, oud melody, East African percussion, Somali vocal melisma, diaspora ballad",
    95,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "Ethiopian Jazz Pop",
    "Maghreb & Diaspora",
    "ethiopian jazz pop, Ethio-jazz pentatonic melody over funk-influenced bass groove, brass section stabs, Addis Ababa vintage-modern crossover, Amharic vocal phrase space, hypnotic polyrhythmic pocket",
    "ethiopian jazz pop, pentatonic melody, funk bass, brass stabs, Amharic vocals",
    105,
    ["jazz", "melodic", "2020s"],
  ),
  g(
    "Desi Hip-Hop",
    "Maghreb & Diaspora",
    "desi hip-hop, South Asian hip-hop groove, tabla or dhol accent hits over trap drums, Bollywood sample chop optional, Punjabi-Hindi-English code-switch rap flow space, diaspora club energy",
    "desi hip-hop, tabla dhol accents, trap drums, Punjabi-Hindi rap flow, diaspora club",
    92,
    ["hip-hop/rap", "rhythmic", "2020s"],
  ),
  g(
    "Tamil Pop",
    "Maghreb & Diaspora",
    "tamil pop, Kollywood-adjacent pop production without full filmi orchestra, catchy synth hook, mridangam-accented drum groove, Tamil vocal melody space, Chennai radio crossover polish",
    "tamil pop, synth hooks, mridangam accents, Tamil vocal melody, Chennai radio",
    110,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Filipino Pop",
    "Maghreb & Diaspora",
    "filipino pop, OPM ballad-pop crossover, acoustic guitar and piano blend, emotional Tagalog vocal belt space, Manila radio chorus lift, karaoke-friendly hook contour, warm string pad swells",
    "filipino pop, OPM ballad, acoustic piano, Tagalog vocal belt, Manila radio chorus",
    98,
    ["melodic", "smooth", "2020s"],
  ),
];
