/** Wave 2 — Asia, Africa, rock, country, Latin niche, wellness & cinematic genres. */
import type { ExtendedGenreDef } from "@/lib/genres/extendedCatalog";

function g(
  value: string,
  group: string,
  prompt: string,
  aceTags: string,
  bpm: number,
  sonautoTags: string[] = ["2020s"],
): ExtendedGenreDef {
  return { value, group, prompt, aceTags, bpm, sonautoTags };
}

export const WORLD_WAVE2_GENRES: ExtendedGenreDef[] = [

  // ── Asia / Pacific ──
  g(
    "Bollywood",
    "Asia / Pacific",
    "bollywood, Hindi filmi orchestration with sitar and tabla layers, lush string section swells, harmonium drone bed, cinematic percussion hits, melodic vocal hook space for Hindi lyrics, Mumbai masala drama lift",
    "bollywood, sitar, tabla, harmonium, Hindi filmi orchestration, cinematic strings",
    105,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Mandopop",
    "Asia / Pacific",
    "mandopop, Mandarin pop ballad chord stacks, glossy synth pads, steady four-four drum groove, emotional topline melody space, Taipei-Shanghai radio crossover sheen, Mandarin vocal hook lift",
    "mandopop, Mandarin pop, glossy synths, emotional topline, ballad chords",
    92,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "C-Pop",
    "Asia / Pacific",
    "C-pop, modern Chinese pop production, bright layered synth hooks, punchy kick-snare groove, major-key chorus lift, mandarin or cantonese vocal space, idol-group energy optional",
    "C-pop, Chinese pop, bright synth hooks, punchy drums, chorus lift",
    118,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Thai Pop",
    "Asia / Pacific",
    "thai pop, luk thung-influenced melodic ornaments, bright keyboard hooks, steady pop drum pocket, warm bass groove, Bangkok radio crossover energy, Thai vocal phrase space",
    "thai pop, luk thung ornaments, keyboard hooks, Bangkok radio groove",
    110,
    ["melodic", "2020s"],
  ),
  g(
    "J-Rock",
    "Asia / Pacific",
    "J-rock, driving distorted guitar power chords, tight live drum pocket, melodic bass line, anthemic major-key chorus lift, Tokyo band-energy vocal shout space, anime-adjacent hook optional",
    "J-rock, distorted guitars, live drums, anthemic chorus, Tokyo band energy",
    140,
    ["rock", "energetic", "2020s"],
  ),
  g(
    "V-Pop",
    "Asia / Pacific",
    "V-pop, Vietnamese pop crossover, bright synth lead hooks, four-on-the-floor or trap-pop drums, warm bass glide, Ho Chi Minh City night-drive energy, Vietnamese vocal melody space",
    "V-pop, Vietnamese pop, bright synth hooks, warm bass, night-drive energy",
    112,
    ["melodic", "2020s"],
  ),
  g(
    "Indo Pop",
    "Asia / Pacific",
    "indo pop, Indonesian dangdut-influenced tabla or kendang percussion accents, catchy pop chorus hook, modern Jakarta production layers, warm bass groove, Bahasa vocal space",
    "indo pop, dangdut percussion, Jakarta pop hooks, Bahasa vocal space",
    108,
    ["melodic", "rhythmic", "2020s"],
  ),
  g(
    "Bhangra",
    "Asia / Pacific",
    "bhangra, Punjabi dhol drum drive, tumbi pluck accents, energetic handclap patterns, bright major-key melody, wedding-party bounce energy, Punjabi vocal shout hooks",
    "bhangra, dhol drums, tumbi pluck, handclaps, Punjabi wedding bounce",
    125,
    ["dance", "energetic", "2020s"],
  ),
  g(
    "K-Hip-Hop",
    "Asia / Pacific",
    "K-hip-hop, Seoul trap-influenced drums, crisp hi-hat rolls, minor-key synth stab loop, sliding 808 sub, Korean rap flow vocal space, street-luxury night energy",
    "K-hip-hop, Seoul trap drums, 808 slides, minor synth stabs, Korean rap flow",
    130,
    ["hip-hop/rap", "2020s"],
  ),
  g(
    "Kollywood",
    "Asia / Pacific",
    "kollywood, Tamil film music orchestration, mridangam and tabla percussion layers, Carnatic-influenced melodic ornaments, cinematic string swells, hero-entry brass hits, Tamil vocal melody space",
    "kollywood, Tamil filmi, mridangam, Carnatic ornaments, cinematic brass",
    100,
    ["melodic", "energetic", "2020s"],
  ),

  // ── Africa / Diaspora ──
  g(
    "Highlife",
    "Africa / Diaspora",
    "highlife, Ghanaian highlife guitar pick pattern, horn section call-response stabs, light shuffle drum groove, warm bass tumbao, palm-wine party swing, English or Twi vocal hooks",
    "highlife, Ghana guitar pick, horn stabs, shuffle groove, palm-wine swing",
    105,
    ["african", "rhythmic", "2020s"],
  ),
  g(
    "Bongo Flava",
    "Africa / Diaspora",
    "bongo flava, Tanzanian hip-hop groove, Swahili rap flow pocket, East African percussion layers, melodic synth hook, warm sub bass, Dar es Salaam street-party energy",
    "bongo flava, Tanzanian hip-hop, Swahili rap, East African percussion",
    95,
    ["african", "hip-hop/rap", "2020s"],
  ),
  g(
    "Afropiano",
    "Africa / Diaspora",
    "afropiano, amapiano log drum fused with afrobeats percussion bounce, shaker and conga layers, jazzy chord stabs, deep sub bass, Lagos-Johannesburg crossover dance pulse",
    "afropiano, log drum, afrobeats percussion, jazzy stabs, crossover dance",
    112,
    ["african", "dance", "2020s"],
  ),
  g(
    "Classic Afrobeat",
    "Africa / Diaspora",
    "classic afrobeat, Fela-style polyrhythmic percussion stacks, tenor guitar interlock pattern, horn section unison riffs, long hypnotic groove cycles, call-response vocal chant space",
    "classic afrobeat, polyrhythmic percussion, tenor guitar, horn riffs, Fela groove",
    108,
    ["african", "rhythmic", "1970s"],
  ),
  g(
    "Soukous",
    "Africa / Diaspora",
    "soukous, Congolese soukous cascading electric guitar lines, rumba clave feel, bright percussion drive, dancefloor sebene breakdown section, Lingala vocal call space",
    "soukous, Congolese guitar cascade, rumba clave, sebene breakdown, Lingala vocal",
    120,
    ["african", "dance", "2020s"],
  ),
  g(
    "Ndombolo",
    "Africa / Diaspora",
    "ndombolo, Congolese ndombolo four-on-the-floor kick with soukous guitar licks, hip-sway dance groove, bright synth brass optional, Kinshasa club bounce energy",
    "ndombolo, soukous guitar, four-on-floor kick, Kinshasa club bounce",
    118,
    ["african", "dance", "2020s"],
  ),
  g(
    "Maskandi",
    "Africa / Diaspora",
    "maskandi, Zulu maskandi acoustic guitar fingerpicking, concertina accordion accents, traditional isigubhu drum patterns, storytelling vocal narrative space, rural South African folk pulse",
    "maskandi, Zulu guitar picking, concertina, isigubhu drums, folk narrative",
    115,
    ["african", "melodic", "2020s"],
  ),
  g(
    "Afrobeats Gospel",
    "Africa / Diaspora",
    "afrobeats gospel, West African percussion bounce under uplifting major-key chords, choir stack harmony space, talking drum accents, praise-breakdown lift, English or Yoruba vocal hooks",
    "afrobeats gospel, percussion bounce, choir stacks, praise breakdown, uplifting chords",
    105,
    ["african", "energetic", "2020s"],
  ),

  // ── Rock / Metal ──
  g(
    "Metalcore",
    "Rock / Metal",
    "metalcore, downtuned chugging guitar palm mutes, double-kick blast sections, screamed verse and melodic chorus vocal contrast, breakdown half-time drop, mosh-pit aggression layers",
    "metalcore, chugging guitars, double-kick, scream chorus contrast, breakdown drop",
    140,
    ["rock", "aggressive", "2020s"],
  ),
  g(
    "Post-Punk Revival",
    "Rock / Metal",
    "post-punk revival, angular clean guitar stabs, driving motorik bass line, tight dry snare groove, chorus-heavy bass tone, cold dance-punk tension, baritone vocal space",
    "post-punk revival, angular guitar, motorik bass, dry snare, cold dance-punk",
    128,
    ["rock", "dark", "2020s"],
  ),
  g(
    "Grunge Revival",
    "Rock / Metal",
    "grunge revival, detuned power-chord guitar riffs, loose room-sound drums, fuzzy bass drive, 90s Seattle raw distortion texture, angst-filled vocal shout space",
    "grunge revival, detuned power chords, fuzzy bass, 90s Seattle distortion",
    115,
    ["rock", "aggressive", "1990s"],
  ),
  g(
    "Hard Rock",
    "Rock / Metal",
    "hard rock, crunchy distorted guitar riffs, punchy live kick-snare groove, driving bass line, anthemic chorus chord lift, stadium-ready guitar solo space, powerful vocal belt",
    "hard rock, crunchy riffs, punchy live drums, anthemic chorus, guitar solo",
    130,
    ["rock", "energetic", "2020s"],
  ),
  g(
    "Punk Rock",
    "Rock / Metal",
    "punk rock, fast downstroke guitar chugs, driving eighth-note drum assault, raw shouted vocal delivery, simple three-chord progression, garage rebellion energy, short burst song arc",
    "punk rock, downstroke chugs, fast drums, shouted vocals, three-chord rebellion",
    165,
    ["rock", "aggressive", "2020s"],
  ),
  g(
    "Blues Rock",
    "Rock / Metal",
    "blues rock, blues pentatonic guitar licks, shuffle or straight rock drum pocket, tube-amp crunch tone, walking bass groove, expressive bend-heavy lead space, gritty vocal growl",
    "blues rock, pentatonic licks, shuffle drums, tube-amp crunch, bend leads",
    105,
    ["rock", "rhythmic", "2020s"],
  ),
  g(
    "Southern Rock",
    "Rock / Metal",
    "southern rock, dual guitar harmony lines, shuffle rock drum groove, organ swells optional, gritty bar-band energy, slide guitar accent hooks, outlaw storytelling vocal space",
    "southern rock, dual guitar harmonies, shuffle groove, slide guitar, bar-band energy",
    110,
    ["rock", "rhythmic", "2020s"],
  ),
  g(
    "Post-Rock",
    "Rock / Metal",
    "post-rock, slow-building guitar crescendo layers, tremolo-picked arpeggios, dynamic soft-loud arc, minimal vocal absence, cinematic drum swells, emotional instrumental climax peaks",
    "post-rock, tremolo arpeggios, crescendo layers, cinematic swells, instrumental climax",
    95,
    ["rock", "atmospheric", "2020s"],
  ),
  g(
    "Alternative Metal",
    "Rock / Metal",
    "alternative metal, syncopated heavy guitar riffs, hip-hop influenced drum pocket, melodic vocal hook over aggressive texture, electronic sample accents optional, nu-metal adjacent groove",
    "alternative metal, syncopated heavy riffs, hip-hop drums, melodic vocal hooks",
    125,
    ["rock", "aggressive", "2020s"],
  ),
  g(
    "Emo Rock",
    "Rock / Metal",
    "emo rock, palm-muted clean-then-crunch guitar arpeggios, emotional minor-key progression, driving pop-punk drum pocket, confessional vocal belt space, cathartic chorus lift",
    "emo rock, palm-muted arpeggios, minor progression, pop-punk drums, confessional vocals",
    140,
    ["rock", "melancholic", "2000s"],
  ),
  g(
    "Garage Rock",
    "Rock / Metal",
    "garage rock, lo-fi distorted guitar fuzz, minimal two-piece drum thump, raw energetic chord stabs, basement rehearsal room tone, rebellious shout vocal space",
    "garage rock, lo-fi fuzz guitar, minimal drums, raw chord stabs, basement tone",
    135,
    ["rock", "aggressive", "2020s"],
  ),
  g(
    "Stoner Rock",
    "Rock / Metal",
    "stoner rock, slow heavy fuzz guitar riffs, thick bass drone, laid-back half-time drum groove, desert amplifier sustain, hypnotic repetitive riff cycles, gritty low vocal space",
    "stoner rock, slow fuzz riffs, bass drone, half-time groove, desert sustain",
    90,
    ["rock", "dark", "2020s"],
  ),

  // ── Country / Folk ──
  g(
    "Bluegrass",
    "Country / Folk",
    "bluegrass, banjo roll picking patterns, mandolin chop accents, upright bass walk, acoustic guitar rhythm strum, fiddle melody breaks, fast Appalachian ensemble drive",
    "bluegrass, banjo rolls, mandolin chop, fiddle breaks, Appalachian drive",
    140,
    ["melodic", "energetic", "2020s"],
  ),
  g(
    "Americana",
    "Country / Folk",
    "americana, acoustic guitar and pedal steel blend, roots-rock drum pocket, warm bass groove, storytelling verse-chorus arc, heartland narrative vocal space, dusty road-trip mood",
    "americana, acoustic guitar, pedal steel, roots-rock drums, storytelling vocals",
    100,
    ["melodic", "2020s"],
  ),
  g(
    "Contemporary Country",
    "Country / Folk",
    "contemporary country, Nashville pop-country production, acoustic and electric guitar blend, steady kick-snare groove, polished chorus lift hooks, modern radio storytelling vocal space",
    "contemporary country, Nashville production, acoustic-electric blend, radio chorus hooks",
    108,
    ["melodic", "2020s"],
  ),
  g(
    "Honky Tonk",
    "Country / Folk",
    "honky tonk, twangy telecaster guitar licks, shuffle bar-room drum groove, walking bass line, piano barrel-house accents, beer-hall dance energy, classic country vocal drawl",
    "honky tonk, twangy telecaster, shuffle groove, piano accents, bar-room drawl",
    120,
    ["rhythmic", "2020s"],
  ),
  g(
    "Folk Country",
    "Country / Folk",
    "folk country, fingerpicked acoustic guitar, soft brushed percussion, harmonica accent optional, warm intimate room tone, campfire storytelling vocal space, Appalachian folk melody",
    "folk country, fingerpick guitar, brushed percussion, harmonica, campfire storytelling",
    88,
    ["melodic", "smooth", "2020s"],
  ),
  g(
    "Appalachian Folk",
    "Country / Folk",
    "appalachian folk, modal fiddle melody lines, clawhammer banjo pattern, sparse foot-stomp percussion, mountain ballad harmonic color, oral-tradition narrative vocal space",
    "appalachian folk, modal fiddle, clawhammer banjo, foot-stomp, mountain ballad",
    85,
    ["melodic", "melancholic", "2020s"],
  ),

  // ── Latin Wave 2 ──
  g(
    "Ranchera",
    "Latin Wave 2",
    "ranchera, mariachi trumpet fanfare with nylon guitar strum, waltz or bolero-ranchera pulse, guitarrón bass foundation, emotional Mexican serenade vocal cry, cantina storytelling mood",
    "ranchera, mariachi trumpet, nylon guitar, guitarrón, Mexican serenade vocal",
    95,
    ["latin", "melodic", "2020s"],
  ),
  g(
    "Norteño",
    "Latin Wave 2",
    "norteño, bajo sexto twelve-string arpeggios, polka-influenced snare pattern, accordion lead melody, tuba bass octaves, norteño waltz bounce, Spanish corrido vocal narrative",
    "norteño, bajo sexto, accordion lead, tuba bass, polka snare, corrido vocal",
    115,
    ["latin", "rhythmic", "2020s"],
  ),
  g(
    "Timba",
    "Latin Wave 2",
    "timba, Cuban timba piano montuno tumbao, aggressive horn section hits, conga and timbale drive at high tempo, clave backbone, Havana dancefloor explosion energy, Spanish coro hooks",
    "timba, Cuban montuno, horn hits, congas timbales, clave, Havana dance energy",
    190,
    ["latin", "dance", "energetic", "2020s"],
  ),
  g(
    "Lambada",
    "Latin Wave 2",
    "lambada, Brazilian lambada four-on-the-floor kick with Caribbean zouk-influenced synth leads, sensual hip-sway groove, bright digital accordion or synth hook, Portuguese romantic vocal space",
    "lambada, zouk synth leads, four-on-floor kick, hip-sway groove, Portuguese vocal",
    120,
    ["latin", "dance", "smooth", "2020s"],
  ),
  g(
    "MPB",
    "Latin Wave 2",
    "MPB, Brazilian música popular brasileira, acoustic guitar and light percussion pocket, bossa-influenced chord voicings, melodic storytelling vocal space, Rio-São Paulo intimate art-pop warmth",
    "MPB, Brazilian popular music, acoustic guitar, bossa chords, storytelling vocal",
    100,
    ["latin", "melodic", "smooth", "2020s"],
  ),

  // ── Wellness / Creator ──
  g(
    "Yoga Flow",
    "Wellness / Creator",
    "yoga flow, slow breath-paced pad swells, gentle acoustic guitar or kora-like plucks, soft frame drum pulse, major-seventh chord warmth, mindful movement synchronization space, studio calm",
    "yoga flow, breath-paced pads, soft plucks, frame drum, mindful calm",
    60,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Sound Bath",
    "Wellness / Creator",
    "sound bath, crystal singing bowl resonance tones, gong wash swells, harmonic overtone layers, no percussion, sustained drone evolution, deep relaxation theta-state atmosphere",
    "sound bath, singing bowls, gong swells, overtone drones, deep relaxation",
    50,
    ["atmospheric", "smooth", "2020s"],
  ),
  g(
    "Pilates Beat",
    "Wellness / Creator",
    "pilates beat, steady mid-tempo four-four pulse, neutral major chord bed, soft marimba or pluck motif, controlled energy without distraction, clean minimal groove for movement repetition",
    "pilates beat, mid-tempo pulse, major chord bed, marimba motif, movement groove",
    118,
    ["smooth", "rhythmic", "2020s"],
  ),
  g(
    "Workout Pop",
    "Wellness / Creator",
    "workout pop, high-energy four-on-the-floor kick, bright supersaw chord stabs, motivational chorus hook space, punchy clap pattern, treadmill-interval tempo drive, English vocal chant hooks",
    "workout pop, four-on-floor kick, supersaw stabs, motivational chorus, interval tempo",
    128,
    ["energetic", "dance", "2020s"],
  ),
  g(
    "Healing Ambient",
    "Wellness / Creator",
    "healing ambient, soft sine-wave pad layers, gentle nature texture bed, slow harmonic drift, no sharp transients, restorative breath-length phrasing, spa-studio stillness atmosphere",
    "healing ambient, sine pads, nature texture, slow harmonic drift, spa stillness",
    55,
    ["atmospheric", "smooth", "2020s"],
  ),

  // ── Cinematic / Classical ──
  g(
    "Horror Cinematic",
    "Cinematic / Classical",
    "horror cinematic, dissonant string cluster stabs, low brass drone undertones, prepared piano knock accents, sudden silence gaps, creeping atonal tension build, nightmare underscore atmosphere",
    "horror cinematic, dissonant strings, low brass drone, prepared piano, tension build",
    70,
    ["atmospheric", "dark", "2020s"],
  ),
  g(
    "Action Cinematic",
    "Cinematic / Classical",
    "action cinematic, driving orchestral ostinato strings, taiko or epic percussion hits, brass fanfare stabs, rising harmonic tension arcs, chase-scene pulse acceleration, blockbuster adrenaline lift",
    "action cinematic, ostinato strings, taiko hits, brass stabs, chase-scene pulse",
    130,
    ["atmospheric", "energetic", "2020s"],
  ),
  g(
    "Dark Orchestral",
    "Cinematic / Classical",
    "dark orchestral, minor-key string section tremolo, low choir pad drones, timpani roll crescendos, gothic harmonic movement, villain-theme brass motifs, gothic hall reverb space",
    "dark orchestral, minor tremolo strings, choir drones, timpani rolls, gothic brass",
    85,
    ["atmospheric", "dark", "2020s"],
  ),
  g(
    "Neo-Classical Piano",
    "Cinematic / Classical",
    "neo-classical piano, sparse felt piano arpeggios, minimal string pad accompaniment, emotional rubato phrasing, concert-hall reverb tail, intimate classical-crossover melody drift",
    "neo-classical piano, felt arpeggios, string pads, rubato phrasing, concert hall",
    72,
    ["melodic", "smooth", "2020s"],
  ),

  // ── Phonk / Club niche ──
  g(
    "House Phonk",
    "Phonk / Club",
    "house phonk, four-on-the-floor kick with phonk cowbell hook, distorted Memphis sample chops, club-house bass groove, pitched vocal stab accents, late-night warehouse bounce energy",
    "house phonk, four-on-floor kick, cowbell hook, Memphis chops, warehouse bounce",
    128,
    ["dance", "aggressive", "2020s"],
  ),
  g(
    "Atmospheric Phonk",
    "Phonk / Club",
    "atmospheric phonk, washed reverb cowbell melody, slow half-time trap drums, deep sub drone, tape-saturated Memphis vocal ghost samples, foggy night-drive melancholy groove",
    "atmospheric phonk, reverb cowbell, half-time drums, sub drone, night-drive mood",
    75,
    ["atmospheric", "melancholic", "2020s"],
  ),
  g(
    "Aggressive Phonk",
    "Phonk / Club",
    "aggressive phonk, hard distorted cowbell lead, blown 808 sub hits, rapid snare rolls, bitcrushed Memphis sample bursts, mosh-pit phonk drop tension, maximum trunk-rattle weight",
    "aggressive phonk, distorted cowbell, blown 808, snare rolls, phonk drop weight",
    145,
    ["aggressive", "energetic", "2020s"],
  ),
];

export function worldWave2GenrePromptMap(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const item of WORLD_WAVE2_GENRES) out[item.value] = item.prompt;
  return out;
}
