import type { CategorizedLocalePools, PromptCategory } from "./types";
import { buildGenreMenuCategory } from "@/lib/randomPromptIdeas/genreMenuPrompts";
import { getAceProseCuratedPool } from "@producerhit/shared";

const SONG_NATURAL: PromptCategory = {
  id: "natural",
  label: "Like a real user message",
  mode: "song",
  prompts: [
    "Make me a song about summer vacation in Italy with my family",
    "I need a romantic song for a proposal, modern not cheesy",
    "Can you do a birthday party anthem for my friends",
    "A sad song about a friend moving overseas",
    "Motivational song to survive Monday morning",
    "Make something about my cat destroying the house at 3am",
    "Song about falling in love for the first time in high school",
    "A song for my mom, gentle gospel touches, saying thank you",
    "A track about burnout at work but hope at the end",
    "Road trip song in a van along the coast",
    "Funny song about subway delays and commuter chaos",
    "Feel-good beach summer song, easy singalong chorus",
    "Song about my ex who ghosted me, slightly petty",
    "Wedding ceremony song, elegant and bright",
    "Song about growing up in the suburbs, pride and nostalgia",
    "Car-cry breakup song for late night drives",
    "Song about my first tiny apartment, big dreams",
    "Team anthem before the football match",
    "Warm Christmas family song with a little magic",
    "Song about real guy-girl friendship that lasts",
    "Song about morning coffee and quiet moments",
    "Lullaby-ish song for my newborn, tender and light",
    "Exam all-nighter song, lo-fi soul",
    "Song about finding love again after a long pause",
    "Song about the sea, wind and freedom",
    "Kitchen dance song at midnight",
    "Song about quitting a toxic job with courage",
    "Summer at grandma's village memories",
    "Long-distance soulmates song",
    "Graduation celebration song, euphoric",
    "Melancholic rain and broken umbrellas song",
    "Night city wandering under neon lights",
    "Respectful song for my dad",
    "Italy song, pasta, scooter and sunset",
    "Erasmus departure, excitement and fear",
    "First day of college, shy but determined",
    "Sports defeat that makes you stronger",
    "Autumn leaves folk song",
    "Girls night empowerment song",
    "Missing someone you don't see anymore",
    "Bachelorette party fun song",
    "Stars and kept promises song",
    "Anger then forgiveness in a couple",
    "Loyal slightly crazy dog song",
    "Mountain silence song",
    "Apology song without being heavy",
    "Coming home after years abroad",
    "Dance song, body free, living room or club",
    "Childhood playground recess song",
    "Crush who doesn't know yet song",
    "Euphoric anthem to celebrate your country winning the 2026 World Cup",
    "Funny song about your Spotify algorithm not getting you anymore",
    "Track for a TikTok reel: POV you finished a beat at 4am",
    "Song about your first BeatStars sale at $29",
    "Melodic trap about anxiety before sending an important DM",
    "Corridos tumbados about a family business comeback",
    "Glossy K-pop song for a dance challenge",
    "Ironic pop about Zoom meetings that should've been an email",
    "Song about scoring a penalty and making the whole bar cry",
    "Afro-house for sunrise after a long club night",
    "Song about your cat walking on the MIDI keyboard",
    "Slow jam for a rooftop civil wedding in Marrakech",
    "Anthem for indie creators finally shipping their EP",
    "Phonk song for a night-drive car edit",
    "Neo-soul about a crush met in a concert queue",
    "Cinematic song for an indie trailer",
    "Pop punk about burnout — I quit on Monday",
    "Track about hearing your own song in public for the first time",
    "Electro-pop about a European festival summer",
    "Gospel-pop for a Sunday after the block party",
    "Reggaeton song for a Barcelona bachelor party without cringe",
    "Funny song about a collaborator who uses the same hi-hat everywhere",
    "Folk song about grandma and kitchen radio",
    "Jersey club song for a confident New York night",
    "Song about discovering AI music at midnight",
  ],
};

const SONG_CINEMATIC: PromptCategory = {
  id: "cinematic",
  label: "Film & trailer",
  mode: "song",
  prompts: [
    "epic trailer, orchestral strings, taiko drums, heroic rise, powerful choir, IMAX mix",
    "suspense film score, dissonant strings, minimal piano, rising tension, sub drones, brutal climax",
    "fantasy soundtrack, celtic flute, harp, wide strings, bright adventure theme, rich orchestration",
    "emotional neoclassical, concert grand piano, legato strings, breakup theme, cathartic crescendo",
    "modern western, dry acoustic guitar, harmonica, wood percussion, sunset duel mood",
    "horror cinematic, piano clusters, bowed metal, heartbeat sub, jump scare stinger, anxious mix",
    "sci-fi orchestral, hybrid synth brass, icy arps, space exploration, immense pads",
    "historical drama, plaintive solo violin, chamber orchestra, memory and war theme",
    "feel-good comedy film, ukulele, claps, upright bass bounce, light optimistic theme",
    "action chase, staccato strings, brass hits, ethnic percussion, nervous 7/8 rhythm",
    "nature documentary, contemplative piano, airy strings, wind field-recording feel",
    "political thriller, dark bassoon, discreet synth pulses, urban paranoia, tight mix",
    "epic anime opening, orchestral J-rock, double kick drums, Japanese choir, melodic guitar lead",
    "bollywood drama, sitar, tabla, eastern strings, melismatic melody, festive climax",
    "modern war, military snare, low brass, grave synth, sacrifice and honor",
    "pixar emotion, naive piano, soft strings, family theme, controlled tearful rise",
    "film noir jazz, smoky tenor sax, walking bass, brushes, rain on glass",
    "post-apocalyptic, desolate synth pad, detuned piano, long strings, fragile final hope",
    "sports epic race, orchestra percussion, brass fanfare, BPM rise, stadium victory",
    "90s romance film, piano ballad, satin strings, chance meeting theme, soft mix",
    "AAA game music, hybrid orchestral, choir chants, boss fight energy, syncopated drops",
    "inspiring biopic, nylon guitar, warm strings, resilience theme, final crescendo",
    "chic spy lounge, jazz vibraphone, upright bass, ride cymbal, elegant tension",
    "natural disaster score, low drones, orchestral hits, silence then impact, dramatic mix",
    "ghost memory song, ethereal female vocal, long piano reverb, spectral strings",
  ],
};

const SONG_ACOUSTIC: PromptCategory = {
  id: "acoustic",
  label: "Unplugged & acoustic",
  mode: "song",
  prompts: [
    "MTV unplugged, steel-string acoustic, raw male vocal, harmonics, live room, intimate mix",
    "folk fingerstyle, nylon guitar, picking melody, soft female vocal, campfire mood",
    "French chanson acoustic, deep male vocal, light accordion, exile theme, warm mix",
    "indie acoustic, capo guitar, open strumming, fragile female vocal, distant brush drums",
    "modern country acoustic, twang guitar, light pedal steel, male vocal, road regrets",
    "bossa acoustic, bossa nylon guitar, whispered female vocal, hand percussion, soft evening",
    "delta blues acoustic, slide guitar, gravel vocal, stomp board, organic saturation",
    "singer-songwriter piano-voice, dry Steinway, confessional male vocal, recovery theme",
    "unplugged R&B, electro-acoustic jazz chords, male vocal runs, light upright bass",
    "flamenco pop fusion, palmas, nylon rasgueado, passionate vocal, percussive claps",
    "modern bluegrass, banjo, mandolin, upright bass, trio harmonies, porch energy",
    "lo-fi acoustic, room nylon guitar, whisper vocal, light crackle, rainy night",
    "acoustic duo, two guitars, third harmonies, mature love theme",
    "unplugged rock ballad, clean arpeggio guitar, soft drums, male power chorus",
    "celtic acoustic, tin whistle, dreadnought guitar, bodhran, sea legends theme",
    "afro acoustic, kora, rhythm guitar, male vocal, light hand groove",
    "modern chanson, spoken-sung female vocal, folk guitar, society theme",
    "unplugged soul, jazz guitar voicings, female gospel touches vocal, hand claps",
    "cinematic acoustic instrumental, 12-string guitar, hall reverb, inner journey",
    "TikTok acoustic pop, ukulele, Gen Z vocal, whistle hook, minimal production",
  ],
};

const SONG_URBAN: PromptCategory = {
  id: "urban",
  label: "Rap, trap & drill",
  mode: "song",
  prompts: [
    "hyperpop, glitchy synth lead, distorted 808, bright female vocal, catchy hook, punchy drums",
    "UK drill, cold male rap delivery, sliding 808, sparse piano, dark cinematic strings, 140 BPM",
    "melodic rap, emotional male vocal, minor guitar, airy pads, sliding 808, hook space",
    "melodic trap, introspective male vocal, rainy night, minor piano, sliding 808",
    "boom bap, chopped soul sample, conscious theme, spoken-word vocal, MPC swing, vinyl texture",
    "Travis Scott melodic trap, spacey plucks, psychedelic 808, heavy reverb, autotuned hook",
    "jersey club, chopped vocal hooks, punchy kicks, bounce energy, hype vocal, club edit",
    "cloud rap, dreamy pads, soft 808, floating male vocal, minimal drums, ethereal mix",
    "melancholic French rap, introspective verses, dark piano, heavy 808, suburban night",
    "melodic drill, storytelling male vocal, chromatic piano, 808 slide, cold tension",
    "rage rap, aggressive male vocal, distorted synth lead, saturated 808, moshpit energy",
    "trap soul, vulnerable male vocal, rhodes, smooth 808, atmospheric pads, late night",
    "pluggnb, airy female vocal, bright plucks, soft 808 bounce, light drums, dreamy mood",
    "emo rap, clean palm mute guitar, cracked male vocal, heavy 808, anxiety theme",
    "afrotrap, male vocal, afro percussion, trap 808, minor melody, street energy",
    "latin trap, Spanish male vocal, dembow hints, 808, dark plucks, nocturnal mood",
    "UK grime, fast male flow, wobble bass, minimal synth lead, cold energy",
    "phonk rap, grave male vocal, cowbell, distorted 808, Memphis saturation, night drive",
    "conscious rap, old spoken sample, boom bap drums, upright bass, social message",
    "hyperpop trap, glitch female vocal, distorted 808, arcade leads, maximal compressed mix",
    "French drill, cold male vocal, staccato piano, sliding 808, Paris 3am mood",
    "French melodic rap, light autotune, nylon guitar loop, 808, ambition theme",
    "cinematic trap vocal, epic male vocal, string hits, 808, trailer rise, heroic hook",
    "jersey drill, kick clusters, vocal chops, drill 808, aggressive NY bounce",
    "sample drill storytelling, grave male vocal, soul loop, 808 slide, urban film mood",
  ],
};

const SONG_POP_RNB: PromptCategory = {
  id: "pop_rnb",
  label: "Pop, R&B & soul",
  mode: "song",
  prompts: [
    "dark alt-pop, moody pads, minor progression, breathy female vocal, cinematic tension, radio mix",
    "TikTok pop, short catchy chorus, glossy synths, Gen Z female vocal, punchy drums, wide stereo",
    "modern pop, stacked female harmonies, supersaw chorus, auto-tuned lead, stadium energy",
    "contemporary R&B, silky male vocal runs, rhodes chords, warm sub, heartbreak mood",
    "neo soul, smooth female vocal, jazzy rhodes, live bass pocket, futuristic synths, intimate mix",
    "contemporary R&B, breathy female vocal, rhodes piano, ghosted ex theme, soft drums, warm mix",
    "lo-fi R&B, dusty drums, vinyl crackle, study night, mellow male vocal, tape saturation",
    "house pop, four-on-the-floor kick, uplifting female vocal, bright plucks, summer energy",
    "neo soul, confident female vocal, funky bass, rhodes, cathartic chorus, new chapter",
    "dance pop, catchy topline, resilience theme, bright female vocal, punchy kick, radio polish",
    "French pop chanson, soft female vocal, piano, strings, melancholic chorus, ex returns",
    "90s R&B, smooth male vocal, new jack swing, synth brass, slow dance theme",
    "future R&B, processed female vocal, glitch pads, sub bass, cyber romance mood",
    "gospel pop, female choir, soprano lead, light organ, claps, spiritual rise",
    "retro 80s synthpop, female vocal, synth arp, gated reverb drums, neon nostalgia",
    "bedroom pop, whisper female vocal, clean guitar, lo-fi drums, introversion theme",
    "K-pop ballad, female vocal, orchestra strings, piano, dramatic chorus rise",
    "modern disco pop, funky bass, strings, female vocal, four-on-floor, glitter night",
    "indie pop, soft male vocal, synth arp, live drums, small town theme",
    "latin pop, bilingual female vocal, light reggaeton, nylon guitar, romantic summer",
    "dark R&B, grave male vocal, minor pads, soft 808, toxic love theme",
    "afro R&B, male vocal, shaker percussion, warm chords, sensual groove",
    "female pop rock, drive guitar, power vocal, arena drums, freedom theme",
    "vapor soul, reverbed female vocal, rhodes, slow jam, neon rainy night",
    "French touch pop, female vocal, filter house chords, talkbox, chic Parisian",
  ],
};

const SONG_WORLD: PromptCategory = {
  id: "world",
  label: "Afro, latin & global",
  mode: "song",
  prompts: [
    "amapiano, log drum bass, jazzy piano stabs, shaker groove, male vocal, summer club",
    "reggaeton, dembow rhythm, bright pluck, Latin male vocal, perreo bounce, heavy sub",
    "afrobeats, male vocal, talking drum, highlife guitar, danceable groove, festival sunset",
    "dancehall, patois male vocal, riddim bounce, heavy bass, summer street party",
    "romantic bachata, nylon arpeggio guitar, bongo, Spanish male vocal, slow dance",
    "modern salsa, montuno piano, brass, male vocal, social dance energy",
    "electro cumbia, synth accordion, guiro, female vocal, Latin club bounce",
    "rai pop, male vocal, oriental synth, darbuka, Maghreb melody, Oran night",
    "kizomba, male vocal, sensual pads, slow groove, intimate slow dance theme",
    "samba pop, cuica, Brazilian violin, female vocal, carnival joy",
    "highlife pop, African guitar, male vocal, horn section, Accra groove",
    "arabic pop, melismatic male vocal, oud, synth pads, quarter-tone hooks",
    "bhangra pop, dhol drums, Punjabi male vocal, synth lead, wedding energy",
    "raw dembow, male vocal, heavy 808, perreo, hot street",
    "modern zouk, female vocal, synth brass, Caribbean groove, island romance",
    "afro house vocal, female vocal, log drum, piano chords, Ibiza sunrise",
    "latin trap soul, male vocal, flamenco guitar touches, 808, Madrid night",
    "amapiano vocal, female vocal, log bass, jazz piano, deep Pretoria club",
    "kompa pop, male vocal, clean guitar, synth brass, couple dance",
    "afro drill fusion, UK male vocal, west africa percussion, 808 slide, hybrid",
  ],
};

const SONG_ROCK: PromptCategory = {
  id: "rock",
  label: "Rock, punk & metal",
  mode: "song",
  prompts: [
    "indie sleaze, gritty electric guitar, live drums, raspy female vocal, downtown night",
    "pop-punk, distorted guitars, burnout theme, shouted vocals, fast drums, raw mix",
    "alternative rock, male vocal, delay guitar, drive bass, suburban angst theme",
    "post-punk revival, melodic bass, chorus guitar, detached male vocal, cold wave",
    "modern hard rock, palm mute riffs, gravel male vocal, double kick, arena energy",
    "emo pop rock, cracked male vocal, clean/distort guitar, explosive chorus drums",
    "90s grunge revival, fuzz guitar, lazy male vocal, loose drums, apathy theme",
    "melodic metalcore, scream verse, female clean chorus, breakdown drop, djent guitar",
    "stoner rock, slow fuzz riff, grave male vocal, hypnotic groove, wah lead",
    "garage rock, male vocal, crunchy guitar, one-mic drums, cave energy",
    "shoegaze pop, buried female vocal, guitar wall, distant drums, dense dream",
    "French punk rock, male vocal, power chords, fast drums, daily revolt theme",
    "short prog rock, 7/8 signatures, synth lead, male vocal, virtuoso guitar solo",
    "blues rock, overdrive lead guitar, male vocal, shuffle drums, long solo",
    "stadium rock, mass choir, anthem guitar, male vocal, final rise",
  ],
};

const SONG_ELECTRONIC: PromptCategory = {
  id: "electronic",
  label: "Electronic & club",
  mode: "song",
  prompts: [
    "vocal house, four-on-floor kick, female vocal, piano chords, summer terrace",
    "UK garage, chopped female vocal, skippy drums, bouncy bass, 2-step feel",
    "vocal drum and bass, male vocal, breakbeats, rolling sub, euphoric rush",
    "techno pop, female vocal, acid arp, hard kick, warehouse night",
    "vocal trance, female vocal, supersaw, long build, uplifting drop",
    "electro swing, male vocal, brass samples, swing drums, modern charleston",
    "synthwave, male vocal, neon arp, gated snare, retro 80s drive",
    "future bass, female vocal, chord stabs, wobble drop, emotional lift",
    "hyperpop club, female vocal, 808, glitch leads, fast BPM, colorful chaos",
    "deep house, spoken male vocal, warm pads, bass groove, afterhours",
    "vocal jersey x house, chopped vocal, bounce kick, stabs, NY club",
    "eurodance revival, female vocal, synth lead, pounding kick, 2000s festival",
    "ambient electronic pop, whisper female vocal, immense pads, soft beat, floating",
    "breakbeat pop, male vocal, chopped breaks, reese bass, big beat energy",
    "French touch vocal, female vocal, filter disco sample, vocoder, chic electro",
  ],
};

const SONG_IMPRESSIVE: PromptCategory = {
  id: "impressive",
  label: "Impressive & niche",
  mode: "song",
  prompts: [
    "hybrid orchestral trap, Latin choir, 808 under strings, epic rise, heroic male vocal",
    "vocal jazz fusion, tenor sax solo, fretless bass, scat vocal, complex impro",
    "opera pop crossover, soprano lead, synth pads, trap chorus drop, dramatic contrast",
    "epic celtic music, bodhran, fiddle, male vocal, Gaelic choir, mist battle",
    "middle eastern trap, oud plucks, darbuka, 808, melismatic male vocal, desert night",
    "baroque pop, harp, chamber strings, female vocal, upright bass, rich ornamentation",
    "vocal psytrance, shamanic male vocal, acid arp, rolling kick, desert festival",
    "art noise pop, female vocal, controlled distortion, chaos drums, abrasive beauty",
    "electro tango, synth bandoneon, male vocal, double bass, Buenos Aires passion",
    "gamelan fusion, metallophones, female vocal, sub bass, modern Bali trance",
    "choral drill, gospel choir, 808 slide, rap lead vocal, sacred-street contrast",
    "unplugged orchestral, acoustic guitar, live strings, male vocal, intimate-epic bridge",
    "microtonal ambient song, female vocal, Turkish saz, pads, off-key emotion",
    "marching band hip-hop, brass fanfare, snare line, male vocal, halftime show",
    "horror cute pop, female vocal, piano, trap bass drop, creepy meets sweet",
    "cinematic slide blues, male vocal, western strings, orchestral sunset duel",
    "throat singing electronic, harmonic male vocal, synth drone, slow tribal beat",
    "glass harmonica dream pop, female vocal, crystal pads, bells, surreal beauty",
    "classical harp x 808, female vocal, trap drums, baroque arps, luxury clash",
    "vocoder symphony, processed vocal, orchestra hits, disco bass, grand retro future",
  ],
};

const SONG_FUN_URBAN: PromptCategory = {
  id: "fun_urban",
  label: "Fun urban vibes",
  mode: "song",
  prompts: [
    "melodic trap about your cat walking on the MIDI keyboard at 3am, purrs included",
    "hip-hop track celebrating your first $29 BeatStars sale, champagne on a budget",
    "trap anthem for when the group chat goes silent and you know they're plotting",
    "drill beat about your roommate eating your leftovers, diss track energy",
    "melodic rap about finally deleting that toxic ex's number, clean slate energy",
    "jersey club track for when you nail the TikTok transition on the first try",
    "pluggnb song about your Spotify Wrapped exposing your guilty pleasures",
    "afrobeats anthem for surviving Monday morning with coffee and delusion",
    "latin trap about your abuela's cooking being better than any Michelin star",
    "UK drill track about your neighbor's WiFi name being 'FBI Surveillance Van'",
    "cloud rap vibes for when you're too cozy to get up but the beat is fire",
    "rage rap about your code finally compiling after 47 errors, pure victory",
    "trap soul song for that 3am realization that you're actually doing okay",
    "phonk track for the 4am night drive where every streetlight hits different",
    "melodic drill about your plants growing better than your side hustle",
    "jersey drill for when you walk into the club and the DJ plays YOUR track",
  ],
};

const SONG_FUN_RNB: PromptCategory = {
  id: "fun_rnb",
  label: "Feel-good R&B & soul",
  mode: "song",
  prompts: [
    "neo-soul track about your skincare routine finally working, glow up anthem",
    "R&B slow jam for when your crush actually texts back, no mixed signals",
    "contemporary R&B about treating yourself to brunch alone and loving it",
    "soulful song about your grandma's advice hitting different now that you're older",
    "lo-fi R&B for Sunday morning pancakes, zero obligations, pure vibes",
    "afro R&B about dancing in your kitchen while the plantain fries perfectly",
    "90s R&B throwback for when you and your bestie communicate in pure vibes",
    "future R&B about manifesting your dream life and watching it unfold",
    "bedroom pop R&B about your cat choosing your lap over the expensive bed",
    "gospel-pop for when the group chat sends a prayer request and everyone shows up",
    "dark R&B but make it funny — toxic trait: falling for potential, not reality",
    "French touch R&B about a Parisian summer romance that lives in your head rent-free",
    "vapor soul for late night drives where the city lights understand you",
    "K-R&B inspired track about your skincare routine having more steps than your love life",
    "contemporary R&B about finally setting boundaries and it feeling like a weight lifted",
  ],
};

const SONG_FUN_LATINO: PromptCategory = {
  id: "fun_latino",
  label: "Latino party vibes",
  mode: "song",
  prompts: [
    "reggaeton perreo for when the tacos hit different at 2am, zero regrets",
    "bachata about your dance partner having two left feet but you love them anyway",
    "merengue so fast your abuela would be proud, pure energia Dominicana",
    "cumbia about the family WhatsApp group blowing up with 200 voice notes",
    "salsa track for when you nail the turn pattern in class, reina de la pista",
    "dembow dominicano for the block party where everyone knows the lyrics",
    "afrobeats x reggaeton fusion for that Barcelona summer that changed everything",
    "pop latino about your mom's chancla having better aim than a sniper",
    "ranchera moderna about your tía's chisme being the original social network",
    "corridos tumbados about your cousin's quinceañera going harder than Coachella",
    "bachata sensual for when the DJ plays your song and you lock eyes across the room",
    "reggaeton viejo escuela for the nostalgia trip when 'Gasolina' drops",
    "merengue de calle about your cafecito being stronger than your will to work",
    "cumbia villera for the after-party where the karaoke mic never stops",
    "latin trap about your playlist being 90% Bad Bunny and you're not even mad",
  ],
};

const SONG_FUN_ELECTRONIC: PromptCategory = {
  id: "fun_electronic",
  label: "Electronic fun & festival",
  mode: "song",
  prompts: [
    "house track for when the drop hits and your shoulders do that involuntary thing",
    "techno banger for the warehouse rave where strangers become family by 6am",
    "trance anthem for the mainstage moment when 50,000 hands go up in unison",
    "drum & bass roller for the liquid DnB set that heals your soul",
    "UK garage shuffle for when the 2-step groove makes you forget your name",
    "future bass drop so emotional you cry happy tears in the crowd",
    "french touch filter house for that chic Parisian rooftop sunset session",
    "synthwave night drive where the neon reflections match your playlist perfectly",
    "electro swing for the vintage soul who was born in the wrong decade",
    "ambient electronic for the comedown where the sky turns pink and you're grateful",
    "hardstyle kick so hard it rearranges your DNA in the best way",
    "psytrance portal for the forest festival where the trees dance with you",
    "melodic techno journey where the arp tells your life story in 8 minutes",
    "breakbeat roller for the illegal rave that becomes a core memory",
    "deep house groove for the boat party where the sunset never ends",
  ],
};

const SONG_FUN_POP: PromptCategory = {
  id: "fun_pop",
  label: "Pop anthems & good vibes",
  mode: "song",
  prompts: [
    "pop anthem for when you get the promotion and do the happy dance in the elevator",
    "K-pop style track for your main character moment walking down the street",
    "y2k pop about your flip phone era being cooler than your smartphone life",
    "dance pop for the girls' night where the playlist is 100% no skips",
    "indie pop about your weird hobby that makes you uniquely you, own it",
    "hyperpop glitter explosion for when you need a dopamine IV drip",
    "bedroom pop about your plants being your most reliable emotional support",
    "eurodance revival for when the pre-drinks hit harder than the club",
    "j-pop anime opening energy for when you're the protagonist today",
    "synthpop about your morning coffee tasting like liquid motivation",
    "power pop for the karaoke night where you absolutely crush the high note",
    "dream pop for the nap that hits different on a rainy Sunday afternoon",
    "art pop about your messy room being a curated aesthetic, actually",
    "bubblegum pop so sweet it fixes a bad mood in 3 seconds flat",
    "stadium pop for singing in the shower like you're headlining Wembley",
  ],
};

const SONG_CONTENT_CREATOR: PromptCategory = {
  id: "content_creator",
  label: "Content creator & social",
  mode: "song",
  prompts: [
    "TikTok viral audio for a 15-second transition reveal, catchy hook, female vocal",
    "YouTube vlog outro song, upbeat acoustic pop, feel-good, subscribe-worthy energy",
    "Instagram reel audio, short dance challenge, punchy drums, memorable hook",
    "podcast intro jingle, lo-fi hip-hop, mellow, branded but not annoying",
    "Twitch streamer victory fanfare, electronic, 10 seconds, hype energy",
    "sponsorship ad jingle, 30 seconds, catchy, product-friendly, no explicit lyrics",
    "YouTube commentary background music, subtle electronic, doesn't overpower voice",
    "TikTok trend song, danceable, simple lyrics, repeatable chorus, algorithm-friendly",
    "thumbnail-worthy epic trailer music for your next viral video, 30 seconds",
    "collaboration announcement track, glossy pop, two-part harmony, hype build",
  ],
};

const SONG_GAMING: PromptCategory = {
  id: "gaming",
  label: "Gaming & esports",
  mode: "song",
  prompts: [
    "victory royale anthem, electronic, orchestral hybrid, 30 seconds, winner energy",
    "loading screen lofi, chillhop, study beats, gaming session vibe",
    "esports hype track, aggressive EDM, build and drop, crowd energy, 2 minutes",
    "RPG quest theme, fantasy acoustic guitar, soft strings, adventure mood",
    "battle royale drop mix, trap, dark synth, ticking tension, explosive chorus",
    "retro 8-bit chiptune, NES nostalgia, catchy melody, speedrun energy",
    "MMO guild anthem, orchestral choir, heroic brass, community pride",
    "speedrun music, high BPM, electronic, precise, focused energy",
    "streamer intro theme, hyperpop, colorful, 15 seconds, attention-grabbing",
    "co-op victory song, indie folk, celebratory, friendship themes",
  ],
};

const SONG_FITNESS_SPORTS: PromptCategory = {
  id: "fitness_sports",
  label: "Fitness, sports & motivation",
  mode: "song",
  prompts: [
    "gym PR anthem, hard rock, driving drums, weightlifting energy, aggressive",
    "morning run playlist song, EDM, 128 BPM, sunrise energy, lungs open",
    "comeback sports ballad, piano, strings, emotional, slow burn victory",
    "boxing entrance music, trap, dark 808, intimidating, champion walk",
    "yoga flow soundtrack, ambient, soft pads, breath-paced, grounding",
    "marathon finish line song, euphoric pop, stadium energy, tears of joy",
    "extreme sports edit track, rock, fast drums, adrenaline junkie mood",
    "pre-game motivation, hip-hop, confident bars, locker room energy",
    "post-workout cool down, neo-soul, slow groove, body appreciation",
    "sports documentary theme, orchestral hybrid, cinematic, human spirit",
  ],
};

const SONG_FOOD_CULINARY: PromptCategory = {
  id: "food_culinary",
  label: "Food, cooking & culinary",
  mode: "song",
  prompts: [
    "cooking channel theme, upbeat acoustic, kitchen vibes, warm and inviting",
    "baking show intro, whimsical piano, sweet, flour-dusted nostalgia",
    "street food market song, latin percussion, festive, hungry energy",
    "wine tasting evening, smooth jazz, intimate, sophisticated but relaxed",
    "brunch with friends, indie pop, sunny, mimosa energy, zero rush",
    "late night food run, R&B, sensual, drive-thru romance, neon kitchen",
    "farm to table anthem, folk, organic instruments, earthy, honest",
    "spicy food challenge, reggaeton, hot, sweating, fire energy",
    "coffee shop aesthetic, lo-fi jazzhop, rainy window, steam and vinyl",
    "family recipe song, soul, grandma's kitchen, generations of love",
  ],
};

const SONG_TRAVEL_ADVENTURE: PromptCategory = {
  id: "travel_adventure",
  label: "Travel, road trips & exploration",
  mode: "song",
  prompts: [
    "road trip highway song, indie rock, open windows, nowhere to be",
    "backpacker hostel jam, acoustic guitar, travelers singalong, cheap wine",
    "sunrise at the beach, tropical house, soft kick, salt air, new day",
    "mountain hiking summit, cinematic ambient, wide reverb, elevation",
    "city break exploration, jazzy hip-hop, urban wanderlust, getting lost",
    "campfire night in the woods, folk, crackling fire, stars and stories",
    "desert road trip, psychedelic rock, heat waves, isolated beauty",
    "island hopping summer, reggaeton, boat speakers, island time",
    "train journey through Europe, synthpop, window reflections, somewhere new",
    "adventure documentary theme, orchestral, vast landscapes, human curiosity",
  ],
};

const SONG_MENTAL_HEALTH_SELFCARE: PromptCategory = {
  id: "mental_health_selfcare",
  label: "Mental health, self-care & growth",
  mode: "song",
  prompts: [
    "therapy session reflection, soft piano, vulnerable, breakthrough moment",
    "anxiety calming track, ambient, breathing-paced, safe space",
    "self-love anthem, pop, empowering, mirror affirmations, glow up",
    "grief healing song, cello, slow strings, tears and release, gentle",
    "mindfulness meditation, Tibetan bowls, soft drones, present moment",
    "depression hope track, slow build, light at the end, resilience",
    "boundaries empowerment, R&B, confident, toxic trait detox, strong",
    "introvert recharge song, lo-fi, cozy, alone is okay, blanket fort",
    "trauma recovery ballad, acoustic, raw, safe and sound, healing",
    "self-care Sunday, bedroom pop, PJs all day, no guilt, rest is productive",
  ],
};

const SONG_FAMILY_PARENTING: PromptCategory = {
  id: "family_parenting",
  label: "Family, parenting & loved ones",
  mode: "song",
  prompts: [
    "thank you mom song, heartfelt pop, mother's day, grew from your heart",
    "dad and daughter dance, country, wedding moment, growing up too fast",
    "sibling road trip anthem, pop rock, inside jokes, forever bond",
    "new parents lullaby, soft piano, newborn, tiny fingers, infinite love",
    "family reunion song, gospel-pop, multi-generational, same roots",
    "empty nest blues, country, house feels too quiet, proud but missing",
    "grandparent wisdom, folk, kitchen table stories, heritage and values",
    "adopted child belonging, orchestral, found family, you are home",
    "blended family love, indie pop, new chapters, redefining family",
    "pet as family member, silly pop, dog is my kid, fur baby anthem",
  ],
};

const SONG_CAREER_BUSINESS: PromptCategory = {
  id: "career_business",
  label: "Career, hustle & business",
  mode: "song",
  prompts: [
    "side hustle startup anthem, hip-hop, grind mode, 5pm to 5am",
    "corporate fatigue, art pop, Zoom calls, Monday meetings, golden handcuffs",
    "freelancer freedom, indie folk, no boss, chaotic but mine",
    "promotion celebration, disco pop, corner office, champagne toast",
    "burnout recovery, slow R&B, unplugging, woods and no signal",
    "creator economy hustle, trap, views and revenue, algorithm life",
    "small business owner, country rock, local shop, community first",
    "job interview confidence, pop, elevator pitch, fake it till you make it",
    "remote work lifestyle, chill electronic, home office, sweatpants CEO",
    "retirement dream, yacht rock, 30 years paid off, island cocktail",
  ],
};

const SONG_PETS_ANIMALS: PromptCategory = {
  id: "pets_animals",
  label: "Pets, animals & funny creatures",
  mode: "song",
  prompts: [
    "dog greeting you at the door, hyperpop, tail wag energy, pure joy",
    "cat judging you, Lounge jazz, superiority complex, hairball elegance",
    "pet parrot talking over you, reggae, squawking chorus, pirate vibe",
    "hamster wheel existential crisis, indie rock, tiny wheels, big dreams",
    "goldfish memory joke, bubblegum pop, 3 seconds, forgetful but happy",
    "rabbit chaos mode, ska, zoomies at 3am, carrot obsession",
    "rescue dog transformation, soul, underdog story, tail wags prove it",
    "cat knocking things off table, phonk, destruction with purpose",
    "turtle racing confidence, slow jam, shell, steady wins the race",
    "guinea pig wheek chorus, children's music, adorable squeaks, cuteness overload",
  ],
};

const SONG_MEMES_INTERNET: PromptCategory = {
  id: "memes_internet",
  label: "Memes, internet culture & viral",
  mode: "song",
  prompts: [
    "Skibidi Toilet theme, absurdist electronic, meme energy, brain rot",
    "NPC trend audio, glitchy vocal, jarring, TikTok algorithm bait",
    "rizz song, R&B, smooth one-liners, chat GPT wrote this",
    "sigma male soundtrack, phonk, dark gym, lone wolf aesthetic",
    "gyatt song, Jersey club, booty bass, internet slang explained",
    "Ohio final boss music, hyperpop, chaotic, why is everything so weird",
    "AI generated this song, electronic, uncanny valley, meta commentary",
    "fanum tax song, trap, stealing your fries, loyalty test",
    "cooking with the Gas compartido, reggaeton, chaotic kitchen, spicy",
    "touch grass anthem, acoustic, go outside, nature is free",
  ],
};

const SONG_NOSTALGIA_THROWBACKS: PromptCategory = {
  id: "nostalgia_throwbacks",
  label: "Nostalgia, throwbacks & retro",
  mode: "song",
  prompts: [
    "Windows XP startup sound but full song, nostalgic electronic, 2000s PC era",
    "Disney Channel theme vibe, pop rock, Saturday morning, childhood hero",
    "Tamagotchi memory, chiptune, pixelated love, virtual pet grief",
    "2000s school dance, teen pop, awkward slow song, back to middle school",
    "Neo Geo arcade theme, 90s fighting game, continue screen, quarter drop",
    "Flip phone text message tone, bubblegum pop, T9 texting, missed calls",
    "Lego building soundtrack, orchestral, childhood creation, plastic bricks",
    "Saturday morning cartoon, power pop, good vs evil, sugar cereal energy",
    "Mixtape nostalgia, R&B, burned CD, pencil label, 2003 summer",
    "Dial-up internet song, industrial, screeching connection, AOL friends",
  ],
};

const SONG_SEASONAL_HOLIDAYS: PromptCategory = {
  id: "seasonal_holidays",
  label: "Seasonal, holidays & celebrations",
  mode: "song",
  prompts: [
    "summer night breeze, tropical pop, beach fire, salty skin, freedom",
    "Halloween spooky party, dark pop, costume chaos, candy cravings",
    "Thanksgiving dinner, folk, family drama, pumpkin pie, gratitude",
    "New Year Eve countdown, electronic, fireworks, new beginnings, champagne",
    "Valentine breakup anthem, indie rock, single awareness, chocolate therapy",
    "Easter spring renewal, indie pop, pastel colors, egg hunts, rebirth",
    "back to school, hip-hop, new shoes, fresh start, September anxiety",
    "Christmas morning, gospel-pop, family chaos, gifts, childhood wonder",
    "wedding first dance, R&B, slow jam, forever starts tonight",
    "graduation ceremony, orchestral pop, cap toss, next chapter begins",
  ],
};

const SONG_URBAN_RAW: PromptCategory = {
  id: "urban_raw",
  label: "Urban raw: trap, drill, rap, R&B",
  mode: "song",
  prompts: [
    "melodic trap, rainy city night, sliding 808, minor piano, emotional male vocal, late-night thoughts",
    "UK drill, cold aggressive rap, sparse piano, sliding 808, drill hats, 140 BPM, street tension",
    "melodic rap, introspective bars, minor guitar loop, airy pads, 808 glides, hook space",
    "trap soul, vulnerable vocal, warm rhodes, smooth 808, atmospheric pads, 3am confessions",
    "phonk rap, grave distorted vocal, cowbell, Memphis 808, night drive, aggressive energy",
    "dancehall, patois vocal, riddim bounce, heavy bass, summer street, club energy",
    "UK garage, chopped female vocal, skippy drums, bouncy bass, 2-step shuffle, late night",
    "baile funk, Brazilian party energy, pounding tamborzao, MC vocal, dancefloor chaos",
    "trapsoul, breathy female vocal, rhodes chords, soft 808, late-night vulnerability, warm mix",
    "drill, cold male vocal, staccato piano, sliding 808, crisp hats, cinematic street mood",
    "melodic drill, storytelling bars, chromatic piano, 808 slide, cold tension, UK vibe",
    "cloud rap, dreamy washed pads, soft 808, floating vocal, minimal drums, ethereal mix",
    "rage rap, aggressive vocal, distorted 808, chaotic synth, moshpit energy, loud mix",
    "emo rap, cracked vocal, palm mute guitar, heavy 808, anxiety theme, emotional",
    "conscious rap, chopped soul sample, boom bap drums, upright bass, social message",
    "French drill, cold rap, staccato piano, sliding 808, Paris 3am mood, cinematic",
    "French melodic rap, light autotune, nylon guitar loop, 808, ambition theme,banlieue",
    "sample drill, grave vocal, soul loop, 808 slide, gritty texture, urban film mood",
    "jersey club, chopped vocal hooks, punchy kicks, bounce energy, hype vocal, club edit",
    "jersey drill, kick clusters, vocal chops, drill 808, aggressive NY bounce, energetic",
  ],
};

const SONG_URBAN_BEATS: PromptCategory = {
  id: "urban_beats",
  label: "Urban instrumental beats",
  mode: "song",
  prompts: [
    "Travis Scott style melodic trap, spacey plucks, psychedelic 808, heavy reverb, autotuned hook",
    "Metro Boomin dark trap, cinematic strings, sliding 808, crisp snare, minor piano, menacing",
    "Future x Southside melodic trap, toxic minor melody, hard bounce 808, punchy drums, dark",
    "Drake x PARTYNEXTDOOR trap soul, moody rhodes, smooth 808, tight hats, late-night R&B",
    "Playboi Carti rage trap, distorted 808, chaotic synth lead, aggressive hats, moshpit",
    "21 Savage dark trap, sinister piano stabs, 808 slides, hard drums, menacing low end",
    "Central Cee UK drill, cold sparse piano, sliding 808, syncopated hats, minimal 140 BPM",
    "J Dilla boom bap, chopped soul sample, dusty drums, MPC swing, warm vinyl texture",
    "Skread French trap, icy minor melody, hard 808 slides, crisp hats, cold Paris mood",
    "Kore melodic trap, sunny guitar pluck, bouncy 808, warm polished mix, optimistic",
    "DJ Weedim cloud trap, dreamy washed pads, soft 808, minimal drums, floating vibe",
    "Le Motif French drill, cold piano, sliding 808, drill hats, cinematic tension, Paris",
    "M1OnTheBeat UK drill, cold piano motif, sliding 808, sharp snare, 140 BPM, gritty",
    "Memphis phonk, distorted 808, cowbell hook, dark synth lead, aggressive raw mix",
    "baile funk, Brazilian tamborzao kick, MC vocal chop, party energy, raw Rio groove",
  ],
};

const SONG_RB_SOUL_SPECIFIC: PromptCategory = {
  id: "rb_soul_specific",
  label: "R&B, soul & neo-soul specifics",
  mode: "song",
  prompts: [
    "neo soul, smooth female vocal, jazzy rhodes, live bass pocket, futuristic synths, intimate",
    "contemporary R&B, silky male vocal runs, rhodes chords, warm sub, heartbreak mood",
    "90s R&B, smooth male vocal, new jack swing, synth brass, slow dance, nostalgic",
    "future R&B, processed female vocal, glitch pads, sub bass, cyber romance mood",
    "lo-fi R&B, dusty drums, vinyl crackle, study night, mellow male vocal, tape saturation",
    "gospel trap soul, organ chords, 808, claps, spiritual uplift, Sunday morning vibe",
    "dark R&B, grave male vocal, minor pads, soft 808, sparse piano, toxic love theme",
    "afro R&B, male vocal, shaker percussion, warm chords, sensual groove, danceable",
    "vapor soul, reverbed female vocal, rhodes, slow jam, neon rainy night, nostalgic",
    "French touch R&B, female vocal, filter house chords, talkbox, chic Parisian night",
    "K-R&B, sleek modern chords, tight trap drums, glossy synths, Seoul night vibe",
    "trap soul, vulnerable male vocal, rhodes, smooth 808, atmospheric pads, late night",
    "quiet storm R&B, silky vocal, soft drums, warm bass, romantic late-night mood",
    "new jack swing, drum machine swing, synth brass, male vocal, 90s dancefloor",
    "soul ballad, raw vocal, piano, strings, emotional, tears and release, timeless",
  ],
};

const BEAT_URBAN_RAW: PromptCategory = {
  id: "urban_raw",
  label: "Urban raw beats: trap, drill, phonk",
  mode: "beat",
  prompts: [
    "melodic trap, sliding 808, minor piano, airy pads, hard drums, rainy night vibe",
    "UK drill, cold sparse piano, sliding 808, syncopated hats, 140 BPM, minimal tension",
    "phonk, distorted 808, cowbell pattern, dark synth lead, aggressive raw energy",
    "dark trap, cinematic strings, sliding 808 bass, crisp snare, minor piano, menacing",
    "rage trap, distorted 808, chaotic synth lead, saturated bass, aggressive hats",
    "sample drill, chopped soul loop, drill 808 slides, hard snare, gritty texture",
    "jersey drill, kick clusters, vocal chops, drill 808, aggressive NY bounce",
    "French drill, cold piano, sliding 808, drill hats, cinematic tension, Paris 3am",
    "cloud rap, washed reverb pads, soft 808, minimal trap drums, dreamy plucks",
    "emo rap, palm mute guitar, heavy 808, dark pads, minor melody, anxiety mood",
    "afrotrap, afro percussion, trap 808, pentatonic melody, hot street groove",
    "latin trap, dembow hints, minor plucks, 808, heavy bass, Latino night",
    "grime instrumental, wobble bass, minimal synth, skippy drums, cold London",
    "Memphis phonk, cowbell hook, dark trap drums, distorted bass, tape saturation",
    "cinematic trap, short viral loop hook, hard 808, crisp hats, tension build, TikTok",
  ],
};

const BEAT_UK_GARAGE_DANCEHALL: PromptCategory = {
  id: "uk_garage_dancehall",
  label: "UK garage, dancehall & baile",
  mode: "beat",
  prompts: [
    "UK garage, skippy drums, bouncy bass, chord stabs, 2-step shuffle, vocal chops",
    "jersey club, bed-squeak sample, punchy kick clusters, chopped vocal one-shots, bounce",
    "dancehall riddim, heavy bass, skank guitar, claps, summer street party energy",
    "baile funk, Brazilian tamborzao kick, MC vocal chop, party energy, raw Rio groove",
    "dembow dominicano, raw dembow kick, 808, minimal perreo, hot street energy",
    "afrobeats, burna boy style, log drum groove, rhythmic guitar, warm chords, danceable",
    "amapiano, log drum bass, jazzy piano stabs, shaker groove, deep house groove",
    "afro house vocal, female vocal, log drum, piano chords, Ibiza sunrise vibe",
    "reggaeton, Bad Bunny style, dembow kick, bright pluck, warm sub, summer club",
    "dancehall, patois vocal, riddim bounce, heavy bass, summer street, club energy",
  ],
};

const BEAT_RB_SOUL_BEATS: PromptCategory = {
  id: "rb_soul_beats",
  label: "R&B, soul & trap soul beats",
  mode: "beat",
  prompts: [
    "trap soul, Drake style, moody rhodes, smooth 808, tight hi-hats, late-night R&B",
    "contemporary R&B beat, rhodes, 808 glide, tight hats, hook chord lift, vocal-ready",
    "neo soul beat, rhodes chords, live bass pocket, brushed drums, warm analog feel",
    "future R&B beat, glitch pads, deep sub, sparse pluck, cyber soul, atmospheric",
    "90s R&B instrumental, juno pads, drum machine swing, synth bass, slow jam",
    "dark R&B instrumental, minor pads, soft 808, sparse piano, toxic mood",
    "gospel trap soul beat, organ chords, 808, claps, spiritual uplift, warm",
    "lo-fi R&B beat, dusty drums, vinyl crackle, mellow chords, study night vibe",
    "bedroom pop beat, clean guitar, lo-fi drums, synth arp, intimate, quiet",
    "pluggnb, bright plucks, soft 808 bounce, light drums, airy pads, dreamy mood",
  ],
};

const BEAT_URBAN: PromptCategory = {
  id: "urban",
  label: "Trap, drill & rap",
  mode: "beat",
  prompts: [
    "melodic trap, Travis Scott style, spacey synth plucks, psychedelic 808 glides, hard trap drums",
    "trap soul, Drake x PARTYNEXTDOOR style, moody rhodes, smooth 808, tight hi-hats, late-night R&B trap",
    "rage trap, Playboi Carti style, distorted 808, chaotic synth lead, aggressive hats, moshpit energy",
    "dark trap, Metro Boomin style, cinematic strings, sliding 808 bass, crisp snare, minor piano",
    "UK drill, Central Cee style, cold sparse piano, sliding 808, syncopated hats, 140 BPM feel",
    "melodic trap, Future x Southside style, toxic minor melody, hard bounce 808, punchy drums",
    "dark trap, 21 Savage style, sinister piano stabs, 808 slides, hard drums, menacing low end",
    "melodic trap, Lil Uzi style, spacey bell plucks, emotional minor chords, bouncy 808, airy pads",
    "French trap, Skread style, icy minor melody, hard 808 slides, crisp hats, cold Paris mood",
    "melodic trap, Kore style, sunny guitar pluck, bouncy 808, warm polished mix",
    "cloud trap, DJ Weedim style, dreamy washed pads, soft 808, minimal drums, floating vibe",
    "French drill, Le Motif style, cold piano, sliding 808, drill hats, cinematic tension",
    "boom bap, J Dilla style, chopped soul sample, dusty drums, MPC swing, warm vinyl texture",
    "UK drill, M1OnTheBeat style, cold piano motif, sliding 808, sharp snare, 140 BPM feel",
    "phonk, distorted 808, cowbell pattern, dark synth lead, aggressive energy, raw compressed mix",
    "jersey club, bed-squeak sample, punchy kick clusters, chopped vocal one-shots, bounce groove",
    "sample drill, chopped soul loop, drill 808 slides, hard snare, gritty texture, dark mood",
    "cloud rap, washed reverb pads, soft 808, minimal trap drums, dreamy plucks, wide stereo",
    "cinematic trap, short viral loop hook, hard 808, crisp hats, tension build, TikTok edit",
    "pluggnb, bright plucks, soft 808 bounce, light drums, airy pads, hook space",
    "emo trap, palm mute guitar, heavy 808, dark pads, minor melody, anxiety mood",
    "afrotrap, afro percussion, trap 808, pentatonic melody, hot street groove",
    "latin trap, dembow hints, minor plucks, 808, heavy bass, Latino night",
    "grime instrumental, wobble bass, minimal synth, skippy drums, cold London",
    "Memphis phonk, cowbell hook, dark trap drums, distorted bass, gritty tape saturation",
  ],
};

const BEAT_CINEMATIC: PromptCategory = {
  id: "cinematic",
  label: "Film & epic",
  mode: "beat",
  prompts: [
    "cinematic trap, tension riser, orchestral hit, hard drop 808, sync-ready arrangement, trailer energy",
    "cinematic trap, short viral loop hook, hard 808, crisp hats, tension build, TikTok edit",
    "orchestral hybrid trap, brass stabs, taiko hits, 808 sub, epic montage energy",
    "horror trap, dissonant strings, sub drone, sudden silence drop, 808 impact, jump scare",
    "western trap, dry acoustic guitar, harmonica, 808 under strings, sunset duel",
    "sci-fi trap, icy arp, synth choir, 808, immense pads, space exploration",
    "epic piano trap, repetitive minor motif, string rise, 808 drop, hero theme",
    "cinematic drill, staccato piano, legato strings, 808 slide, crime film mood",
    "anime type beat, J-rock guitars, double kick drums, synth lead, opening energy",
    "bollywood trap fusion, sitar pluck, tabla, 808, brass hits, festive drama",
    "war drums trap, military snare, low brass, 808, battlefield tension",
    "fantasy orchestral loop, flute, harp arp, soft 808, quest adventure",
    "noir jazz trap, sax sample, upright bass, lazy 808, neon rain",
    "disaster movie pulse, heartbeat kick, rising strings, impact drop, survival tension",
    "video game boss, chip arp, orchestral hit, 808, intense fight phase",
  ],
};

const BEAT_ACOUSTIC: PromptCategory = {
  id: "acoustic",
  label: "Guitar & unplugged",
  mode: "beat",
  prompts: [
    "unplugged guitar loop, fingerstyle steel-string, hand percussion, room reverb, melodic hook",
    "acoustic trap, nylon arp guitar, soft 808, light hats, warm organic fusion",
    "folk trap, open tuning guitar, banjo pluck, 808 sub, stomp clap, modern country",
    "flamenco trap, palmas, nylon rasgueado, 808, castanets, Spanish passion",
    "bossa trap, bossa guitar chords, shakers, smooth 808, Rio night",
    "acoustic blues loop, slide guitar, minimal kick, harmonica, smoky bar",
    "celtic guitar, tin whistle layer, soft bodhran, light 808 sub, Irish mist",
    "neoclassical guitar, arpeggios, synth strings, 808, baroque trap bridge",
    "ukulele pop beat, joyful strum, soft kick, claps, summer tiktok",
    "12-string ambient, harmonics, pads, distant 808, introspective journey",
    "acoustic drill, piano-guitar hybrid, 808 slide, drill hats, soft-hard contrast",
    "kora afro loop, rhythm guitar, 808, percussion, west African groove",
  ],
};

const BEAT_ELECTRONIC: PromptCategory = {
  id: "electronic",
  label: "House, DnB & electro",
  mode: "beat",
  prompts: [
    "jersey club x house, four-on-the-floor kick, chopped stabs, club bounce, edit-ready energy",
    "amapiano, log drum bass, percussive shakers, jazzy piano stabs, deep house groove, summer dancefloor",
    "hyperpop trap, glitchy synth stabs, distorted 808, colorful leads, internet-native sound design",
    "ambient drill, reverb-heavy pads, sparse drill drums, emotional minor melody, streaming polish",
    "lo-fi hip-hop, dusty drums, jazz sample chop, vinyl crackle, mellow chords, study beat groove",
    "UK garage instrumental, skippy drums, bouncy bass, chord stabs, 2-step shuffle",
    "drum and bass, rolling breakbeats, reese sub, arp lead, 174 rave energy",
    "techno trap hybrid, hard kick, acid arp, 808 overlay, dark warehouse",
    "future bass, emotional chord stabs, wobble drop, bright arp, festival lift",
    "deep house, warm pads, bass groove, conga percussion, hypnotic afterhours",
    "electro swing, brass samples, swing drums, synth upright bass, charleston",
    "synthwave trap, neon arp, gated snare, 808, retro night drive",
    "French touch house, filter disco loop, talkbox lead, four kick, chic Paris",
    "breakbeat hybrid, chopped breaks, reese bass, stabs, big beat energy",
    "ambient club, immense pads, soft kick, granular texture, floating dancefloor",
  ],
};

const BEAT_WORLD: PromptCategory = {
  id: "world",
  label: "Afro, latin & global",
  mode: "beat",
  prompts: [
    "reggaeton, Bad Bunny style, dembow kick pattern, bright pluck lead, warm sub, summer club bounce",
    "afrobeats, Burna Boy style, log drum groove, rhythmic guitar, warm chords, danceable percussion",
    "pop-trap, Nyda style, dembow-influenced bounce, bright plucks, French urban pop energy, glossy mix",
    "afrobeats, bright guitar licks, talking drum percussion, warm sub, uplifting bounce, festival energy",
    "dancehall riddim, heavy bass, skank guitar, claps, summer street",
    "bachata loop, nylon arp, bongo, guiro, romantic mid-tempo",
    "electro cumbia, synth accordion, guiro, Latin bounce, club",
    "rai trap, oriental synth, darbuka, 808, Maghreb groove",
    "samba break, cuica, surdo, whistle, carnival bounce",
    "highlife guitar, horn stabs, Accra groove, shakers, sunny",
    "raw dembow, dembow kick, 808, minimal perreo, hot street",
    "zouk instrumental, synth brass, slow groove, round bass, Caribbean",
    "afro house, log drum, piano chords, shekere percussion, Ibiza sunrise",
    "latin jazz trap, montuno piano, 808, congas, Havana night",
    "middle eastern trap, oud pluck, darbuka, 808, desert pulse",
  ],
};

const BEAT_POP_RNB: PromptCategory = {
  id: "pop_rnb",
  label: "R&B & pop instrumental",
  mode: "beat",
  prompts: [
    "neo soul, rhodes chords, live bass pocket, brushed drums, laid-back swing, warm analog feel",
    "R&B slow jam, silky rhodes, soft kick, warm bass, late-night mood, smooth polished mix",
    "contemporary R&B instrumental, open verse space, big chorus lift chords, smooth 808, vocal-ready",
    "modern pop-trap, radio-ready polish, unique signature synth, tight drums, catchy motif, wide clean mix",
    "contemporary R&B beat, rhodes, 808 glide, tight hats, hook chord lift",
    "90s R&B instrumental, juno pads, drum machine swing, synth bass, slow jam",
    "future R&B, glitch pads, deep sub, sparse pluck, cyber soul",
    "bedroom pop beat, clean guitar, lo-fi drums, synth arp, intimate",
    "gospel trap soul, organ chords, 808, claps, spiritual uplift",
    "dark R&B instrumental, minor pads, soft 808, sparse piano, toxic mood",
  ],
};

const BEAT_ROCK: PromptCategory = {
  id: "rock",
  label: "Rock & punk",
  mode: "beat",
  prompts: [
    "pop punk type beat, power chords, fast drums, picked bass, skatepark energy",
    "indie rock loop, delay arp guitar, live drums, melodic bass, dream drive",
    "hard rock riff, palm mute, double kick, overdrive lead, arena stomp",
    "emo guitar beat, clean/distort switch, explosive drums, sad pads, heartbreak",
    "garage rock one mic, crunchy guitar, loose drums, raw cave energy",
    "post-punk bass, chorus guitar, dry drums, cold atmosphere, 80s revival",
    "slow stoner riff, fuzz wall, hypnotic groove, sparse wah lead",
    "metalcore breakdown, djent palm mute, drop tuning, double kick, pit energy",
    "blues rock shuffle, overdrive lead guitar, swing drums, faint organ",
    "shoegaze wall, dense guitars, distant drums, pads, heavy float",
  ],
};

const BEAT_IMPRESSIVE: PromptCategory = {
  id: "impressive",
  label: "Niche & fusion",
  mode: "beat",
  prompts: [
    "g-funk, talk box lead, funky synth bass, crisp drums, west coast sunny haze, polished mix",
    "orchestral drill, staccato strings, 808 slide, choir hit, classical-street clash",
    "jazz fusion trap, sax sample solo, rhodes, 808, synth walking bass, impro loop",
    "baroque trap, harp arp, chamber strings, 808, upright bass, ornamented",
    "tango trap, synth bandoneon, double bass, 808, Argentine passion",
    "gamelan electronic, metallophone, sub bass, soft kick, Bali trance",
    "microtonal beat, saz pluck, drone pad, sparse 808, off-scale",
    "marching band trap, snare line, brass fanfare, 808, halftime epic",
    "horror cute beat, clusters, sub drop, 808, creepy sweet",
    "classical harp x 808, baroque arp, trap drums, luxury clash",
    "throat singing drone, tribal percussion, minimal 808, vast steppe",
    "glass harmonica ambient, bells, crystal pads, soft kick, surreal",
    "vocoder disco trap, orchestra hit, filter bass, four kick, retro future",
    "western slide guitar trap, harmonica, 808, strings, cinematic duel",
    "type beat intro, memorable motif hook, clean punchy drums, YouTube-ready polish",
  ],
};

const SONG_ACE_PROSE: PromptCategory = {
  id: "ace_prose",
  label: "ACE prose (optimized)",
  mode: "song",
  prompts: getAceProseCuratedPool("song", "en"),
};

const BEAT_ACE_PROSE: PromptCategory = {
  id: "ace_prose",
  label: "ACE prose (optimized)",
  mode: "beat",
  prompts: getAceProseCuratedPool("beat", "en"),
};

const HERO = [
  "Euphoric anthem to celebrate your country winning the 2026 World Cup",
  "Funny song about your Spotify algorithm not getting you anymore",
  "Track for a TikTok reel: POV you finished a beat at 4am",
  "R&B ballad for a rooftop proposal, modern not cheesy",
  "Song about your first BeatStars sale at $29",
  "Melodic trap about anxiety before sending an important DM",
  "Corridos tumbados about a family business comeback",
  "Glossy K-pop song for a dance challenge",
  "Ironic pop about Zoom meetings that should've been an email",
  "Song about scoring a penalty and making the whole bar cry",
  "Afro-house for sunrise after a long club night",
  "Song about your cat walking on the MIDI keyboard",
  "Slow jam for a rooftop civil wedding in Marrakech",
  "Anthem for indie creators finally shipping their EP",
  "Phonk song for a night-drive car edit",
  "Neo-soul about a crush met in a concert queue",
  "Cinematic song for an indie trailer",
  "Pop punk about burnout — I quit on Monday",
  "Track about hearing your own song in public for the first time",
  "Electro-pop about a European festival summer",
  "Gospel-pop for a Sunday after the block party",
  "Reggaeton song for a Barcelona bachelor party without cringe",
  "Funny song about the same hi-hat on every beat",
  "Folk song about grandma and kitchen radio",
  "Jersey club song for a confident New York night",
  "Song about discovering AI music at midnight",
] as const;

export const CATEGORIZED_EN: CategorizedLocalePools = {
  song: [
    SONG_NATURAL,
    SONG_CINEMATIC,
    SONG_ACOUSTIC,
    SONG_URBAN,
    SONG_POP_RNB,
    SONG_WORLD,
    SONG_ROCK,
    SONG_ELECTRONIC,
    SONG_IMPRESSIVE,
    SONG_FUN_URBAN,
    SONG_FUN_RNB,
    SONG_FUN_LATINO,
    SONG_FUN_ELECTRONIC,
    SONG_FUN_POP,
    SONG_CONTENT_CREATOR,
    SONG_GAMING,
    SONG_FITNESS_SPORTS,
    SONG_FOOD_CULINARY,
    SONG_TRAVEL_ADVENTURE,
    SONG_MENTAL_HEALTH_SELFCARE,
    SONG_FAMILY_PARENTING,
    SONG_CAREER_BUSINESS,
    SONG_PETS_ANIMALS,
    SONG_MEMES_INTERNET,
    SONG_NOSTALGIA_THROWBACKS,
    SONG_SEASONAL_HOLIDAYS,
    SONG_URBAN_RAW,
    SONG_URBAN_BEATS,
    SONG_RB_SOUL_SPECIFIC,
    SONG_ACE_PROSE,
    buildGenreMenuCategory("song", "Full genre catalog", "en"),
  ],
  beat: [
    BEAT_URBAN,
    BEAT_CINEMATIC,
    BEAT_ACOUSTIC,
    BEAT_ELECTRONIC,
    BEAT_WORLD,
    BEAT_POP_RNB,
    BEAT_ROCK,
    BEAT_IMPRESSIVE,
    BEAT_URBAN_RAW,
    BEAT_UK_GARAGE_DANCEHALL,
    BEAT_RB_SOUL_BEATS,
    BEAT_ACE_PROSE,
    buildGenreMenuCategory("beat", "Full genre catalog", "en"),
  ],
  hero: HERO,
};
