import type { CategorizedLocalePools, PromptCategory } from "./types";
import { buildGenreMenuCategory } from "@/lib/randomPromptIdeas/genreMenuPrompts";
import { getAceProseCuratedPool } from "@producerhit/shared";

/** Formulations naturelles — comme un vrai utilisateur qui ne maîtrise pas les tags ACE. */
const SONG_NATURAL: PromptCategory = {
  id: "natural",
  label: "Comme un vrai message",
  mode: "song",
  prompts: [
    "Fais-moi une chanson sur les vacances d'été en Italie avec ma famille",
    "Une chanson romantique pour demander en mariage, moderne pas cucul",
    "J'ai besoin d'un son pour mon anniversaire, ambiance fête entre potes",
    "Tu peux me faire une chanson triste sur un ami qui part à l'étranger",
    "Une chanson motivante pour survivre au lundi matin",
    "Fais-moi un truc sur mon chat qui démonte la maison à 3h du matin",
    "Chanson sur la première fois qu'on tombe amoureux au lycée",
    "Une chanson pour ma mère, douce, un peu gospel, pour lui dire merci",
    "Un son sur le burn-out au travail mais avec de l'espoir à la fin",
    "Fais-moi une chanson sur un road trip en van sur la côte atlantique",
    "Une chanson drôle sur les galères du métro et les retards",
    "Chanson d'été pour la plage, feel-good, facile à chanter en chorus",
    "Tu peux faire un son sur mon ex qui m'a ghosté, un peu vengeur",
    "Une chanson pour mon mariage civil, élégante et lumineuse",
    "Fais-moi une chanson sur grandir en banlieue, fierté et nostalgie",
    "Un son pour pleurer dans la voiture après une rupture",
    "Chanson sur mon premier appart, petit budget mais grand rêve",
    "Une chanson pour mon équipe de foot, hymne avant le match",
    "Fais-moi un truc sur Noël en famille, chaleureux et un peu magique",
    "Chanson sur l'amitié fille-garçon qui dure vraiment",
    "Tu peux me faire une chanson sur le café du matin et le silence",
    "Une chanson pour mon bébé qui vient de naître, tendre",
    "Fais-moi un son sur les nuits blanches d'examens, lo-fi dans l'âme",
    "Chanson sur retrouver l'amour après une longue pause",
    "Une chanson sur la mer en Bretagne, vent et liberté",
    "Fais-moi une chanson pour danser dans la cuisine à minuit",
    "Un son sur le courage de quitter un job toxique",
    "Chanson sur l'été au village chez grand-mère",
    "Tu peux faire une chanson sur deux âmes sœurs à distance",
    "Une chanson pour fêter mon diplôme, euphorique",
    "Fais-moi un truc sur la pluie et les parapluies cassés",
    "Chanson sur errer en ville la nuit sous les néons",
    "Une chanson pour mon père, sobre et respectueuse",
    "Fais-moi une chanson sur l'Italie, pasta, scooter et coucher de soleil",
    "Un son pour un départ en Erasmus, excitation et peur",
    "Chanson sur le premier jour de fac, timide mais déterminée",
    "Tu peux me faire une chanson sur la défaite qui forge au sport",
    "Une chanson sur l'automne et les feuilles, folk doux",
    "Fais-moi un son pour une soirée entre filles, empowerment",
    "Chanson sur le manque de quelqu'un qu'on ne voit plus",
    "Une chanson pour un EVJF, fun et un peu folle",
    "Fais-moi une chanson sur les étoiles et les promesses tenues",
    "Un son sur la colère puis le pardon dans un couple",
    "Chanson sur mon chien, loyal et un peu fou",
    "Tu peux faire une chanson sur la montagne et le silence",
    "Une chanson pour dire désolé sans être lourd",
    "Fais-moi un truc sur le retour au pays après des années loin",
    "Chanson sur danser, corps libéré, salon ou club",
    "Une chanson sur l'enfance et la cour de récré",
    "Peux-tu me faire une chanson sur un crush qui ne sait pas",
    "Hymne pour célébrer la victoire du pays à la Coupe du monde 2026",
    "Chanson drôle sur ton algorithme Spotify qui ne te comprend plus",
    "Son pour un reel TikTok « POV : beat terminé à 4h du mat »",
    "Chanson sur la première vente BeatStars — fierté et incrédulité",
    "Pop ironique sur les réunions Zoom qui auraient pu être un mail",
    "Chanson sur scorer en penalty et faire pleurer tout le bar",
    "Slow R&B sur un ghosting après trois dates parfaites",
    "Chanson pour une pub sneakers Gen Z, urbaine sans être agressive",
    "Trap mélodique sur l'angoisse avant d'envoyer un DM important",
    "Chanson sur ton chat qui marche sur le clavier MIDI",
    "Anthem pour créateurs indés qui sortent enfin leur premier EP",
    "Corridos tumbados sur une family business qui se relève",
    "Chanson gospel pop pour un dimanche après la fête de quartier",
    "Electro-pop sur un été européen de festivals",
    "Chanson sur entendre ton morceau en public pour la première fois",
    "Drôle : une chanson sur un collègue qui met le même hi-hat partout",
    "Ballade pour une demande en mariage rooftop, moderne pas cucul",
    "Chanson afrobeat pour un after mariage qui part en danse totale",
    "Son sur découvrir l'IA musicale à minuit et ne plus dormir",
  ],
};

const SONG_CINEMATIC: PromptCategory = {
  id: "cinematic",
  label: "Ciné & bande-annonce",
  mode: "song",
  prompts: [
    "bande-annonce épique, cordes orchestrales, percussions taiko, montée héroïque, chœur puissant, mix IMAX",
    "musique de film suspense, cordes dissonantes, piano minimal, tension croissante, drones sourds, climax brutal",
    "soundtrack fantasy, flûte celtique, harpe, cordes larges, thème aventure lumineux, orchestration riche",
    "néo-classique émotionnel, piano concert grand, cordes legato, thème rupture, crescendo cathartique",
    "western moderne, guitare acoustique séche, harmonica, percussion bois, duel au soleil couchant",
    "horror cinématique, clusters piano, bowed metal, heartbeat sub, jump scare stinger, mix angoissant",
    "sci-fi orchestral, synth brass hybrid, arpèges glacés, exploration spatiale, pads immenses",
    "drame historique, violon solo plaintif, orchestre chambre, thème mémoire et guerre",
    "comédie feel-good ciné, ukulele, claquements, contrebasse bounce, thème optimiste léger",
    "action pursuit, staccato strings, brass hits, percussion ethnique, rythme 7/8 nerveux",
    "musique de documentaire nature, piano contemplatif, cordes aériennes, field-recording vents",
    "thriller politique, basson sombre, pulses synth discrets, paranoïa urbaine, mix serré",
    "anime opening épique, J-rock orchestral, batterie double kick, chœur japonais, lead guitare mélodique",
    "bollywood drama, sitar, tabla, cordes orientales, mélodie melismatic, climax festif",
    "guerre moderne, snare militaire, cuivres graves, synth grave, sacrifice et honneur",
    "pixar émotion, piano naïf, cordes douces, thème famille, montée larmoyante contrôlée",
    "film noir jazz, sax ténor smoky, contrebasse walking, brushes, pluie sur vitre",
    "post-apocalyptique, synth pad désolé, piano détuné, cordes longues, espoir fragile final",
    "course épique sport, percussion orchestre, brass fanfare, montée BPM, victoire stade",
    "romance ciné 90s, piano ballad, cordes satin, thème rencontre hasard, mix doux",
    "musique de jeu AAA, hybrid orchestral, choir chants, boss fight energy, drops syncopés",
    "biopic inspirant, guitare nylon, cordes chaleureuses, thème résilience, crescendo final",
    "espionnage chic, jazz lounge, vibraphone, contrebasse, cymbales ride, tension élégante",
    "catastrophe naturelle, drones graves, hits orchestraux, silence puis impact, mix dramatique",
    "fantômes et mémoire, voix féminine éthérée, piano reverb long, cordes spectrale",
  ],
};

const SONG_ACOUSTIC: PromptCategory = {
  id: "acoustic",
  label: "Unplugged & acoustique",
  mode: "song",
  prompts: [
    "unplugged MTV, guitare acoustique steel-string, voix masculine raw, harmoniques, room live, mix intime",
    "folk fingerstyle, guitare nylon, mélodie picking, voix douce féminine, ambiance feu de camp",
    "chanson acoustique française, voix masculine grave, accordéon léger, thème exil, mix chaleureux",
    "indie acoustique, guitare capo, strumming ouvert, voix féminine fragile, batterie brushes lointaine",
    "country acoustique moderne, guitare twang, pedal steel léger, voix masculine, thème route et regrets",
    "bossa nova acoustique, guitare nylon bossa, voix féminine chuchotée, percussions main, soirée douce",
    "blues acoustique delta, slide guitare, voix grave, stomp board, saturation organique",
    "singer-songwriter piano-voix, Steinway sec, voix masculine confessional, thème addiction guérie",
    "unplugged R&B, guitare électro-acoustique jazz chords, voix masculine runs, basse upright légère",
    "flamenco pop fusion, palmas, guitare nylon rasgueado, voix passionnée, claps percussifs",
    "bluegrass moderne, banjo, mandoline, contrebasse, harmonies trio, énergie porch",
    "acoustique lo-fi, guitare nylon enreg room, voix whisper, crackle léger, nuit pluvieuse",
    "duo acoustique homme-femme, deux guitares, harmonies tierces, thème amour mature",
    "unplugged rock ballad, guitare clean arpégée, batterie soft, voix masculine power chorus",
    "celtic acoustique, tin whistle, guitare dreadnought, bodhran, thème mer et légendes",
    "afro-acoustique, kora, guitare rythmique, voix masculine, groove léger mains",
    "chanson à texte moderne, voix féminine parlée-chantée, guitare folk, thème société",
    "unplugged soul, guitare jazz voicings, voix féminine gospel touches, claps main",
    "instrumental acoustique ciné, guitare 12 cordes, reverb hall, thème voyage intérieur",
    "pop acoustique TikTok, guitare ukulele, voix Gen Z, hook whistle, production minimal",
  ],
};

const SONG_URBAN: PromptCategory = {
  id: "urban",
  label: "Rap, trap & drill",
  mode: "song",
  prompts: [
    "hyperpop, lead synth glitché, 808 distordue, voix féminine brillante, refrain accrocheur, drums punchy",
    "UK drill, flow rap masculin froid, 808 glissante, piano sparse, strings ciné sombres, 140 BPM",
    "rap mélodique, voix masculine émotionnelle, guitare mineure, pads aériens, 808 glissante, hook space",
    "trap mélodique, voix masculine introspective, nuit pluvieuse, piano mineur, 808 glissante",
    "boom bap, sample soul coupé, thème conscient, voix spoken-word, swing MPC, texture vinyle",
    "trap mélodique style Travis Scott, plucks spacey, 808 psychédélique, reverb lourde, hook auto-tuné",
    "jersey club, hooks vocaux chopped, kicks punchy, énergie bounce, voix hype, edit club",
    "cloud rap, pads dreamy, 808 soft, voix masculine flottante, drums minimales, mix éthéré",
    "rap français mélancolique, couplets introspectifs, piano sombre, 808 lourde, banlieue nuit",
    "drill mélodique, voix masculine storytelling, piano chromatique, 808 slide, tension froide",
    "rage rap, voix masculine agressive, synth lead distordu, 808 saturée, énergie moshpit",
    "trap soul, voix masculine vulnérable, rhodes, 808 smooth, pads atmos, fin de nuit",
    "pluggnb, voix féminine airy, plucks brillants, 808 bounce soft, drums légers, mood rêveur",
    "emo rap, guitare clean palm mute, voix masculine cracked, 808 lourde, thème anxiété",
    "afrotrap, voix masculine, percussions afro, 808 trap, mélodie mineure, énergie rue",
    "latin trap, voix masculine espagnole, dembow hints, 808, plucks sombres, mood nocturne",
    "grime UK, flow rap rapide masculin, bass wobble, synth lead minimal, énergie froide",
    "phonk rap, voix masculine grave, cowbell, 808 distordue, saturation Memphis, drive nocturne",
    "rap conscience, sample spoken old, batterie boom bap, basse upright, message société",
    "trap hyperpop, voix féminine glitch, 808 distordue, leads arcade, mix compressé maximal",
    "drill français, voix masculine froide, piano staccato, 808 glissante, ambiance paris 3h",
    "melodic rap français, autotune léger, guitare nylon loop, 808, thème ambition",
    "trap cinématique, voix masculine epic, strings hits, 808, montée trailer, hook heroïque",
    "jersey drill, kicks clusters, vocal chops, 808 drill, bounce agressif, club NY",
    "sample drill storytelling, voix masculine grave, loop soul, 808 slide, mood film urbain",
  ],
};

const SONG_POP_RNB: PromptCategory = {
  id: "pop_rnb",
  label: "Pop, R&B & soul",
  mode: "song",
  prompts: [
    "dark alt-pop, pads sombres, progression mineure, voix féminine breathy, tension ciné, mix radio",
    "pop TikTok, refrain court accrocheur, synthés glossy, voix Gen Z, drums punchy, stéréo large",
    "pop moderne, harmonies féminines empilées, chorus supersaw, lead auto-tuné, énergie stade",
    "R&B contemporain, runs vocaux masculins soyeux, accords rhodes, sub chaud, heartbreak",
    "neo soul, voix féminine smooth, rhodes jazzy, basse live pocket, synthés futuristes, mix intime",
    "R&B contemporain, voix féminine breathy, piano rhodes, thème ghost, drums doux, mix chaleureux",
    "lo-fi R&B, drums dusty, crackle vinyle, nuit d'étude, voix masculine mellow, tape saturation",
    "house pop, kick four-on-the-floor, voix féminine uplifting, plucks brillants, été",
    "neo soul, voix féminine confiante, basse funky, rhodes, chorus cathartique, nouveau départ",
    "dance pop, topline catchy, résilience, voix féminine brillante, kick punchy, mix radio",
    "chanson pop française, voix féminine douce, piano, cordes, refrain mélancolique, ex qui revient",
    "90s R&B, voix masculine smooth, nouvelle jack swing, synth brass, thème slow dance",
    "future R&B, voix féminine processed, pads glitch, basse sub, mood cyber romance",
    "gospel pop, chœur femmes, lead soprano, orgue léger, claps, montée spirituelle",
    "synthpop rétro 80s, voix féminine, arp synth, gated reverb drums, néon nostalgique",
    "bedroom pop, voix féminine whisper, guitare clean, lo-fi drums, thème introversion",
    "K-pop ballad, voix féminine, strings orchestra, piano, montée chorus dramatique",
    "disco pop moderne, basse funky, strings, voix féminine, four-on-floor, glitter night",
    "indie pop, voix masculine douce, synth arp, batterie live, thème petite ville",
    "latin pop, voix féminine bilingue, reggaeton léger, guitare nylon, été romantique",
    "dark R&B, voix masculine grave, pads mineurs, 808 soft, thème toxic love",
    "afro R&B, voix masculine, percussion shakers, chords warm, groove sensuel",
    "pop rock féminine, guitare drive, voix power, batterie arena, thème liberté",
    "vapor soul, voix féminine reverbed, rhodes, slow jam, nuit néon pluie",
    "French touch pop, voix féminine, filter house chords, talkbox, chic parisien",
  ],
};

const SONG_WORLD: PromptCategory = {
  id: "world",
  label: "Afro, latin & monde",
  mode: "song",
  prompts: [
    "amapiano, basse log drum, stabs piano jazzy, shaker groove, voix masculine, club été",
    "reggaeton, rythme dembow, pluck brillant, voix masculine latine, bounce perreo, sub lourd",
    "afrobeats, voix masculine, talking drum, guitare highlife, groove dansant, festival sunset",
    "dancehall, voix masculine patois, riddim bounce, basse lourde, summer street party",
    "bachata romantique, guitare nylon arpège, bongo, voix masculine espagnole, slow dance",
    "salsa moderne, piano montuno, cuivres, voix masculine, énergie danse sociale",
    "cumbia électro, accordéon synth, guiro, voix féminine, bounce latin club",
    "rai pop, voix masculine, synth oriental, darbuka, mélodie maghrébine, nuit Oran",
    "kizomba, voix masculine, pads sensuels, groove lent, thème slow dance intime",
    "samba pop, cuica, violon brésilien, voix féminine, carnaval joie",
    "highlife pop, guitare africaine, voix masculine, horns section, groove accra",
    "arabic pop, voix masculine melismatic, oud, synth pads, quarter tone hooks",
    "bhangra pop, dhol drums, voix masculine punjabi, synth lead, wedding energy",
    "dembow dominicain, voix masculine, 808 lourd, perreo raw, rue chaude",
    "zouk moderne, voix féminine, synth brass, groove antillais, romance caraïbe",
    "afro house vocal, voix féminine, log drum, piano chords, sunrise ibiza",
    "latin trap soul, voix masculine, guitare flamenco touches, 808, nuit madrid",
    "amapiano vocal, voix féminine, log bass, piano jazz, deep club pretoria",
    "kompa pop, voix masculine, guitare clean, synth brass, danse couple",
    "afro drill fusion, voix masculine UK, percussions west africa, 808 slide, hybrid",
  ],
};

const SONG_ROCK: PromptCategory = {
  id: "rock",
  label: "Rock, punk & metal",
  mode: "song",
  prompts: [
    "indie sleaze, guitare électrique crue, batterie live, voix féminine rauque, nuit downtown",
    "pop-punk, guitares distordues, burnout, vocals shoutés, drums rapides, mix raw",
    "alternative rock, voix masculine, guitare delay, basse drive, thème suburban angst",
    "post-punk revival, basse melodic, guitare chorus, voix masculine detached, cold wave",
    "hard rock moderne, riffs palm mute, voix masculine gravel, double kick, arena energy",
    "emo pop rock, voix masculine cracked, guitare arp clean/distort, drums explosive chorus",
    "grunge 90s revival, guitare fuzz, voix masculine lazy, batterie loose, thème apathie",
    "metalcore mélodique, scream verse, clean chorus féminin, breakdown drop, guitare djent",
    "stoner rock, riff lent fuzz, voix masculine grave, groove hypnotique, wah lead",
    "garage rock, voix masculine, guitare crunchy, batterie one mic, énergie cave",
    "shoegaze pop, voix féminine buried, guitares mur wall, drums distant, rêve dense",
    "punk rock français, voix masculine, power chords, batterie rapide, thème révolte quotidienne",
    "prog rock court, signatures 7/8, synth lead, voix masculine, solo guitare virtuose",
    "blues rock, lead guitare overdrive, voix masculine, shuffle drums, solo long",
    "stadium rock, chœur massif, guitare anthem, voix masculine, montée finale",
  ],
};

const SONG_ELECTRONIC: PromptCategory = {
  id: "electronic",
  label: "Électro & club",
  mode: "song",
  prompts: [
    "house vocale, kick four-on-floor, voix féminine, piano chords, summer terrace",
    "UK garage, voix féminine chopped, skippy drums, bass bouncy, 2-step feel",
    "drum and bass vocal, voix masculine, breakbeats, sub rolling, rush euphoric",
    "techno pop, voix féminine, arp acid, kick hard, warehouse night",
    "trance vocal, voix féminine, supersaw, build long, drop uplifting",
    "electro swing, voix masculine, brass samples, swing drums, charleston modern",
    "synthwave, voix masculine, arp neon, gated snare, retro 80s drive",
    "future bass, voix féminine, chord stabs, drop wobble, emotional lift",
    "hyperpop club, voix féminine, 808, leads glitch, BPM rapide, chaos coloré",
    "deep house, voix masculine spoken, pads warm, bass groove, afterhours",
    "vocal jersey x house, voix chopped, kick bounce, stabs, NY club",
    "eurodance revival, voix féminine, lead synth, kick pounding, festival 2000s",
    "ambient pop electronic, voix féminine whisper, pads immenses, beat soft, flottant",
    "breakbeat pop, voix masculine, breaks chopped, bass reese, énergie big beat",
    "French touch vocale, voix féminine, filter disco sample, vocoder, chic électro",
  ],
};

const SONG_IMPRESSIVE: PromptCategory = {
  id: "impressive",
  label: "Impressionnant & pointu",
  mode: "song",
  prompts: [
    "hybrid orchestral trap, chœur latin, 808 sous cordes, montée epic, voix masculine hero",
    "jazz fusion vocale, solo sax ténor, basse fretless, voix scat, impro complexe",
    "opéra pop crossover, soprano lead, synth pads, drop trap chorus, contrast dramatique",
    "musique celtique epic, bodhran, fiddle, voix masculine, chœur gaélique, bataille brume",
    "middle eastern trap, oud plucks, darbuka, 808, voix masculine melismatic, desert night",
    "baroque pop, harpe, cordes chambre, voix féminine, contrebasse, ornamentation riche",
    "psytrance vocal, voix masculine chamanique, arp acid, kick rolling, festival desert",
    "noise pop art, voix féminine, distorsion contrôlée, drums chaos, beauté abrasive",
    "tango électro, bandoneon synth, voix masculine, double bass, passion Buenos Aires",
    "gamelan fusion, metallophones, voix féminine, sub bass, trance bali moderne",
    "choral drill, chœur gospel, 808 slide, voix lead rap, contraste sacré-rue",
    "unplugged orchestral, guitare acoustique, cordes live, voix masculine, pont intime-epic",
    "microtonal ambient song, voix féminine, saz turc, pads, émotion hors tonalité",
    "marching band hip-hop, cuivres fanfare, snare line, voix masculine, halftime show",
    "waterphone horror pop, voix féminine, piano, drop bass trap, cute meets creepy",
    "slide guitar blues cinematic, voix masculine, cordes western, duel sunset orchestral",
    "throat singing electronic, voix masculine harmoniques, synth drone, beat tribal slow",
    "glass harmonica dream pop, voix féminine, pads cristallins, bells, surreal beauty",
    "808 x harpe classique, voix féminine, trap drums, arpèges baroques, clash luxe",
    "vocoder symphony, voix processed, orchestra hits, disco bass, futur rétro grandiose",
  ],
};

const BEAT_URBAN: PromptCategory = {
  id: "urban",
  label: "Trap, drill & rap",
  mode: "beat",
  prompts: [
    "trap mélodique style Travis Scott, plucks spacey, 808 psychédélique, drums trap durs, reverb large",
    "trap soul style Drake, rhodes moody, 808 smooth, hi-hats serrés, vibe trap R&B nocturne",
    "rage trap style Carti, 808 distordue, lead synth chaotique, hats agressifs, énergie moshpit",
    "dark trap style Metro, strings ciné, basse 808 glissante, snare crisp, piano mineur",
    "UK drill style Central Cee, piano froid sparse, 808 glissante, hats syncopés, mix minimal",
    "trap mélodique style Future, mélodie mineure toxique, 808 bounce dure, drums punchy, mood sombre",
    "dark trap style 21 Savage, stabs piano sinistres, slides 808, drums durs, basse menaçante",
    "trap mélodique style Lil Uzi, plucks cloche spacey, accords mineurs, 808 bounce, pads aériens",
    "trap français style Skread, mélodie mineure glaciale, slides 808 dures, hats crisp, paris froid",
    "trap mélodique style Kore, pluck guitare ensoleillé, 808 bounce, mix chaud poli",
    "cloud trap style Weedim, pads dreamy, 808 soft, drums minimales, vibe flottante",
    "drill français style Le Motif, piano froid, 808 glissante, hats drill, tension ciné",
    "boom bap style J Dilla, sample soul coupé, drums dusty, swing MPC, texture vinyle",
    "UK drill style M1OnTheBeat, motif piano froid, 808 glissante, snare sharp, 140 BPM",
    "phonk, 808 distordue, pattern cowbell, lead synth sombre, énergie agressive, mix raw",
    "jersey club, bed-squeak sample, kick clusters, one-shots vocaux, bounce groove, club",
    "sample drill, loop soul coupée, slides 808 drill, snare dure, texture gritty, mood sombre",
    "cloud rap, pads reverb, 808 soft, drums trap minimales, plucks dreamy, stéréo large",
    "trap ciné, hook viral court, 808 dure, hats crisp, montée tension, edit TikTok",
    "pluggnb, plucks brillants, 808 bounce soft, drums légers, pads airy, hook space",
    "emo trap, guitare palm mute, 808 lourde, pads sombres, mélodie mineure, mood anxiété",
    "afrotrap, percussions afro, 808 trap, mélodie pentatonique, groove rue chaude",
    "latin trap, dembow hints, plucks mineurs, 808, bass lourd, nuit latino",
    "grime instrumental, bass wobble, synth minimal, drums skippy, froid londonien",
    "Memphis phonk, cowbell hook, drums trap sombres, basse distordue, saturation tape gritty",
  ],
};

const BEAT_CINEMATIC: PromptCategory = {
  id: "cinematic",
  label: "Ciné & épique",
  mode: "beat",
  prompts: [
    "trap ciné, riser tension, hit orchestral, drop 808 dur, arrangement sync-ready, trailer",
    "cinematic trap, short viral loop hook, hard 808, crisp hats, tension build, TikTok edit",
    "orchestral hybrid trap, brass stabs, taiko hits, 808 sub, epic montage energy",
    "horror trap, dissonant strings, sub drone, sudden silence drop, 808 impact, jump scare",
    "western trap, guitare acoustique dry, harmonica, 808 sous cordes, duel sunset",
    "sci-fi trap, arp glacé, synth choir, 808, pads immenses, exploration spatiale",
    "piano trap épique, motif mineur répétitif, montée cordes, drop 808, hero theme",
    "drill cinématique, piano staccato, strings legato, 808 slide, mood film policier",
    "anime type beat, J-rock guitars, drums double kick, synth lead, opening energy",
    "bollywood trap fusion, sitar pluck, tabla, 808, brass hits, drama festif",
    "war drums trap, snare militaire, brass grave, 808, tension battlefield",
    "fantasy orchestral loop, flute, harp arp, soft 808, quest adventure",
    "noir jazz trap, sax sample, upright bass, 808 lazy, pluie neon",
    "disaster movie pulse, heartbeat kick, rising strings, drop impact, survival tension",
    "video game boss, chip arp, orchestral hit, 808, phase fight intense",
  ],
};

const BEAT_ACOUSTIC: PromptCategory = {
  id: "acoustic",
  label: "Guitare & acoustique",
  mode: "beat",
  prompts: [
    "unplugged guitar loop, fingerstyle steel-string, percussion main, room reverb, hook mélodique",
    "acoustic trap, guitare nylon arp, 808 soft, hats légers, fusion chaud organique",
    "folk trap, guitare open tuning, banjo pluck, 808 sub, stomp clap, country moderne",
    "flamenco trap, palmas, nylon rasgueado, 808, castanettes, passion espagnole",
    "bossa trap, guitare bossa chords, shakers, 808 smooth, nuit rio",
    "blues loop acoustique, slide guitar, kick minimal, harmonica, bar smoke",
    "celtic guitar, tin whistle layer, bodhran soft, 808 sub léger, brume irlandaise",
    "classical guitar neoclassical, arpèges, cordes synth, 808, pont baroque trap",
    "ukulele pop beat, strum joyeux, kick soft, claps, summer tiktok",
    "12-string ambient, harmoniques, pads, 808 distant, voyage introspectif",
    "acoustic drill, piano-guitare hybrid, 808 slide, hats drill, contraste doux-dur",
    "kora loop afro, guitare rythmique, 808, percussion, groove ouest-africain",
  ],
};

const BEAT_ELECTRONIC: PromptCategory = {
  id: "electronic",
  label: "House, DnB & électro",
  mode: "beat",
  prompts: [
    "jersey club x house, kick four-on-the-floor, stabs coupés, bounce club, edit-ready",
    "amapiano, basse log drum, shakers, stabs piano jazzy, groove deep house, été",
    "hyperpop trap, stabs synth glitchés, 808 distordue, leads colorés, sound design internet",
    "drill ambient, pads reverb lourds, drums drill sparse, mélodie mineure, polish streaming",
    "lo-fi hip-hop, drums dusty, chop jazz sample, crackle vinyle, accords mellow, study",
    "UK garage instrumental, skippy drums, bass bouncy, chord stabs, 2-step shuffle",
    "drum and bass, breakbeats rolling, sub reese, arp lead, rave energy 174",
    "techno trap hybrid, kick hard, acid arp, 808 overlay, warehouse dark",
    "future bass, chord stabs emotional, drop wobble, arp bright, festival lift",
    "deep house, pads warm, bass groove, percussions congas, afterhours hypnotic",
    "electro swing, brass samples, swing drums, bass upright synth, charleston",
    "synthwave trap, arp neon, gated snare, 808, retro drive night",
    "French touch house, filter disco loop, talkbox lead, kick four, chic paris",
    "breakbeat hybrid, breaks chopped, bass reese, stabs, big beat energy",
    "ambient club, pads immenses, kick soft, texture granular, float dancefloor",
  ],
};

const BEAT_WORLD: PromptCategory = {
  id: "world",
  label: "Afro, latin & global",
  mode: "beat",
  prompts: [
    "reggaeton style Bad Bunny, pattern dembow, lead pluck brillant, sub chaud, club été",
    "afrobeats style Burna Boy, log drum groove, guitare rythmique, accords chauds, percussion",
    "pop-trap style Nyda, bounce dembow, plucks brillants, pop urbaine française, mix glossy",
    "afrobeats, licks guitare brillants, talking drum, sub chaud, bounce uplifting, festival",
    "dancehall riddim, bass heavy, skank guitar, claps, summer street",
    "bachata loop, nylon arp, bongo, guira, romance mid-tempo",
    "cumbia electro, accordéon synth, guiro, bounce latin, club",
    "rai trap, synth oriental, darbuka, 808, groove maghrébin",
    "samba break, cuica, surdo, whistle, carnaval bounce",
    "highlife guitar, horns stabs, groove accra, shakers, sunny",
    "dembow raw, kick dembow, 808, perreo minimal, rue chaude",
    "zouk instrumental, synth brass, groove lent, basse round, caraïbe",
    "afro house, log drum, piano chords, percussion shekere, ibiza sunrise",
    "latin jazz trap, piano montuno, 808, congas, nuit havane",
    "middle eastern trap, oud pluck, darbuka, 808, desert pulse",
  ],
};

const BEAT_POP_RNB: PromptCategory = {
  id: "pop_rnb",
  label: "R&B & pop instrumentale",
  mode: "beat",
  prompts: [
    "neo soul, accords rhodes, basse live pocket, drums brossées, swing laid-back, analog chaud",
    "slow jam R&B, rhodes soyeux, kick soft, basse chaude, fin de nuit, mix smooth",
    "instrumental R&B contemporain, espace couplet ouvert, accords lift chorus, 808 smooth",
    "pop-trap moderne, polish radio-ready, synth signature, drums serrés, motif catchy",
    "contemporary R&B beat, rhodes, 808 glide, hats tight, hook chord lift",
    "90s R&B instrumental, juno pads, drum machine swing, bass synth, slow jam",
    "future R&B, pads glitch, sub deep, pluck sparse, cyber soul",
    "bedroom pop beat, guitare clean, lo-fi drums, synth arp, intime",
    "gospel trap soul, organ chords, 808, claps, uplift spirituel",
    "dark R&B instrumental, pads mineurs, 808 soft, piano sparse, toxic mood",
  ],
};

const BEAT_ROCK: PromptCategory = {
  id: "rock",
  label: "Rock & punk",
  mode: "beat",
  prompts: [
    "pop punk type beat, power chords, drums rapides, basse pick, énergie skatepark",
    "indie rock loop, guitare arp delay, batterie live, basse melodic, dream drive",
    "hard rock riff, palm mute, double kick, lead overdrive, arena stomp",
    "emo guitar beat, clean/distort switch, drums explosive, pads sad, heartbreak",
    "garage rock one mic, crunchy guitare, batterie loose, énergie cave raw",
    "post-punk bass, guitare chorus, drums dry, cold atmosphere, 80s revival",
    "stoner riff slow, fuzz wall, groove hypnotique, wah lead sparse",
    "metalcore breakdown, djent palm mute, drop tuning, double kick, pit energy",
    "blues rock shuffle, lead guitare overdrive, batterie swing, organ faint",
    "shoegaze wall, guitars dense, drums distant, pads, float heavy",
  ],
};

const BEAT_IMPRESSIVE: PromptCategory = {
  id: "impressive",
  label: "Pointu & fusion",
  mode: "beat",
  prompts: [
    "g-funk, lead talk box, basse synth funky, drums crisp, west coast sunny, mix poli",
    "orchestral drill, strings staccato, 808 slide, choir hit, clash classique-rue",
    "jazz fusion trap, solo sax sample, rhodes, 808, walking bass synth, impro loop",
    "baroque trap, harpe arp, cordes chambre, 808, contrebasse, ornamenté",
    "tango trap, bandoneon synth, double bass, 808, passion argentine",
    "gamelan electronic, metallophone, sub bass, kick soft, trance bali",
    "microtonal beat, saz pluck, drone pad, 808 sparse, hors gamme",
    "marching band trap, snare line, brass fanfare, 808, halftime epic",
    "waterphone horror beat, clusters, sub drop, 808, creepy cute",
    "808 x harpe classique, arp baroque, trap drums, luxe clash",
    "throat singing drone, tribal percussion, 808 minimal, steppe vast",
    "glass harmonica ambient, bells, pads cristal, kick soft, surreal",
    "vocoder disco trap, orchestra hit, filter bass, four kick, futur retro",
    "slide guitar western trap, harmonica, 808, cordes, duel ciné",
    "intro type beat, motif hook mémorable, drums punchy clean, YouTube-ready",
  ],
};

const HERO = [
  "Hymne euphorique pour célébrer la victoire à la Coupe du monde 2026",
  "Chanson drôle sur ton algorithme Spotify qui ne te comprend plus",
  "Son pour un reel TikTok « POV : beat fini à 4h du mat »",
  "Ballade R&B pour une demande en mariage rooftop, moderne pas cucul",
  "Chanson sur la première vente BeatStars à 29 $",
  "Trap mélodique sur l'angoisse avant un DM important",
  "Corridos tumbados sur une family business qui se relève",
  "Chanson K-pop glossy pour un challenge dance",
  "Pop ironique sur les réunions Zoom inutiles",
  "Chanson sur scorer en penalty et faire pleurer tout le bar",
  "Afro-house pour un lever de soleil après une nuit club",
  "Chanson sur ton chat qui marche sur le clavier MIDI",
  "Slow jam mariage civil rooftop Marrakech",
  "Anthem pour créateurs indés qui sortent enfin leur EP",
  "Chanson phonk pour un montage voiture nuit",
  "Neo-soul sur un crush rencontré dans une file de concert",
  "Chanson ciné pour une bande-annonce indie",
  "Pop punk sur un burnout — j'démissionne lundi",
  "Chanson sur entendre ton morceau en public pour la première fois",
  "Electro-pop sur un été européen de festivals",
  "Gospel pop pour un dimanche après la fête de quartier",
  "Chanson reggaeton pour un EVG à Barcelone sans cliché",
  "Drôle : collègue qui met le même hi-hat sur tous ses sons",
  "Chanson folk sur grand-mère et la radio en cuisine",
  "Jersey club pour une nuit New York confiante",
  "Chanson sur découvrir l'IA musicale à minuit",
] as const;

const SONG_FUN_URBAN: PromptCategory = {
  id: "fun_urban",
  label: "Fun vibes urbaines",
  mode: "song",
  prompts: [
    "trap mélodique sur ton chat qui marche sur le clavier MIDI à 3h du mat, ronrons inclus",
    "hip-hop pour fêter ta première vente BeatStars à 29$, champagne budget étudiant",
    "hymne trap pour quand le groupe de potes devient silencieux et tu sais qu'ils trament quelque chose",
    "drill beat sur ton algo Spotify qui te comprend plus, il te propose de la polka maintenant",
    "rap français mélancolique sur le café froid du matin, mais t'as le flow quand même",
    "trap soul sur le ghosting après trois dates parfaites, mais version drôle pas dépressive",
    "afrobeats pour l'after mariage qui part en danse totale, tonton Gérard en tête",
    "jersey club pour une nuit new-yorkaise confiante, même si t'es dans ta chambre à Lyon",
    "phonk pour le montage voiture de nuit, vitres baissées, basses qui font vibrer l'âme",
    "corridos tumbados sur le family business qui se relève, fierté et résilience",
  ],
};

const SONG_FUN_RNB: PromptCategory = {
  id: "fun_rnb",
  label: "R&B & soul feel-good",
  mode: "song",
  prompts: [
    "slow jam R&B pour une demande en mariage rooftop, moderne pas cucul, larmes de joie",
    "neo-soul sur un crush rencontré dans la file d'attente du concert, le destin fait bien les choses",
    "R&B contemporain sur le retour de l'ex... mais toi t'as glow up et tu t'en fous",
    "ballade pour ton meilleur ami qui se marie, fraternité pure, zéro cringe",
    "gospel pop pour le dimanche après la block party, âmes lavées, cœurs légers",
    "vapor soul sur une nuit néon pluvieuse, mais t'as ta playlist et ça va",
    "afro R&B sensuel pour un slow dance improvisé dans la cuisine à minuit",
    "French touch pop pour le chic parisien, filter house, talkbox, élégance",
    "90s R&B new jack swing pour danser comme dans les clips, shoulder roll obligatoire",
    "future R&B cyber romance, ton IA t'envoie des cœurs, c'est mignon quand même",
  ],
};

const SONG_FUN_LATINO: PromptCategory = {
  id: "fun_latino",
  label: "Latino & afro good vibes",
  mode: "song",
  prompts: [
    "reggaeton pour un EVG à Barcelone sans cliché, perreo respectueux, souvenirs pour la vie",
    "bachata romantique pour un slow dance sous les palmiers, guitare nylon, cœurs synchronisés",
    "amapiano vocal pour le sunrise à Ibiza, log drum, piano jazzy, vibes Pretoria deep club",
    "cumbia electro pour la fiesta en club, accordéon synth, guiro, bounce latin contagieux",
    "samba pop pour le carnaval, cuica, violon brésilien, joie pure, confettis dans l'âme",
    "dancehall riddim pour la summer street party, bass heavy, skank guitar, tout le quartier danse",
    "afro house pour l'after qui finit au lever du soleil, shekere, log drum, Pretoria vibes",
    "latin trap soul pour une nuit madrilène, guitare flamenco, 808, passion à l'état pur",
    "kompa pop pour danser en couple, guitare clean, synth brass, groove caribéen authentique",
    "kizomba sensuelle pour le slow dance intime, pads chauds, connexion sans mots nécessaires",
  ],
};

const SONG_FUN_ELECTRONIC: PromptCategory = {
  id: "fun_electronic",
  label: "Électro & club euphorique",
  mode: "song",
  prompts: [
    "house vocale pour la terrasse d'été, piano chords, kick four-on-the-floor, spritz à la main",
    "UK garage pour le 2-step dans le salon, vocal chopped, skippy drums, joie pure",
    "trance vocal pour l'ascenseur émotionnel, supersaw, long build, drop qui libère tout",
    "french touch pour le chic parisien, filter disco sample, vocoder, Daft Punk serait fier",
    "synthwave pour le night drive rétro, neon arp, gated snare, 80s nostalgia mode activé",
    "future bass pour le festival lift, chord stabs, wobble drop, mains en l'air, cœur ouvert",
    "electro swing pour le charleston modern, brass samples, swing drums, joie vintage",
    "deep house pour l'afterhours hypnotic, warm pads, bass groove, congas, 6am magic",
    "amapiano pour le summer dancefloor, log drum bass, jazzy piano stabs, groove deep house",
    "hyperpop club pour le chaos coloré, 808, glitch leads, fast BPM, internet aesthetic",
  ],
};

const SONG_FUN_POP: PromptCategory = {
  id: "fun_pop",
  label: "Pop fun & catchy",
  mode: "song",
  prompts: [
    "pop TikTok pour le hook qui reste en tête, glossy synths, Gen Z energy, viral ready",
    "K-pop ballad pour le dramatic chorus rise, orchestra strings, piano, main character energy",
    "disco pop moderne pour la glitter night, funky bass, strings, four-on-floor, Saturday fever",
    "indie pop pour le small town theme, soft male vocal, synth arp, live drums, authenticity",
    "Y2K pop pour la nostalgie futuriste, glossy 2000s synths, flip-phone era sparkle, catchy",
    "bedroom pop pour l'introversion assumée, whisper vocal, clean guitar, lo-fi drums, ton safe space",
    "gospel pop pour le spiritual rise, female choir, soprano lead, light organ, claps, amen",
    "French pop chanson pour l'ex qui revient, piano, strings, mélancolie mais tu t'en fous",
    "J-pop pour l'anime opening energy, bright layered synths, kawaii sparkle, determination",
    "viral pop ironique sur les réunions Zoom qui auraient dû être un mail, relatable AF",
  ],
};

const SONG_CONTENT_CREATOR: PromptCategory = {
  id: "content_creator",
  label: "Créateur de contenu & social",
  mode: "song",
  prompts: [
    "audio viral TikTok pour une transition de 15 secondes, hook accrocheur, voix féminine",
    "générique fin de vlog YouTube, pop acoustique upbeat, feel-good, énergie abo",
    "audio pour un Reel Instagram, défi danse court, drums punchy, hook mémorable",
    "jingle intro podcast, lo-fi hip-hop, doux, branding discret mais efficace",
    "fanfare victoire streamer Twitch, électronique, 10 secondes, énergie hype",
    "jingle pub sponsorisée, 30 secondes, catchy, produit-friendly, pas de lyrics explicites",
    "musique de fond YouTube commentary, électronique subtil, n'écrase pas la voix",
    "chanson tendance TikTok, dansable, paroles simples, refrain répétable, algorithm-friendly",
    "musique trailer épique pour ta prochaine vidéo virale, 30 secondes, thumbnail-ready",
    "track annonce collaboration, pop glossy, harmonie à deux voix, hype build",
  ],
};

const SONG_GAMING: PromptCategory = {
  id: "gaming",
  label: "Gaming & esports",
  mode: "song",
  prompts: [
    "hymne victoire royale, électronique, hybride orchestral, 30 secondes, énergie champion",
    "loading screen lofi, chillhop, study beats, vibe session gaming",
    "track hype esports, EDM agressif, build et drop, énergie foule, 2 minutes",
    "thème quête RPG, guitare acoustique fantasy, cordes douces, aventure",
    "mix drop battle royale, trap, synth sombre, tension tick-tock, chorus explosif",
    "chiptune rétro 8-bit, nostalgie NES, mélodie catchy, énergie speedrun",
    "hymne guilde MMO, chœur orchestral, cuivres héroïques, fierté communauté",
    "musique speedrun, BPM élevé, électronique, précis, énergie concentrée",
    "thème intro streamer, hyperpop, coloré, 15 secondes, capture l'attention",
    "chanson victoire co-op, indie folk, célébratoire, thème amitié",
  ],
};

const SONG_FITNESS_SPORTS: PromptCategory = {
  id: "fitness_sports",
  label: "Fitness, sports & motivation",
  mode: "song",
  prompts: [
    "hymne PR salle de sport, hard rock, drums entraînants, énergie musculation, agressif",
    "chanson matin run, EDM, 128 BPM, énergie sunrise, poumons ouverts",
    "ballade comeback sportif, piano, cordes, émotion, victoire à retardement",
    "musique entrée boxe, trap, 808 sombre, intimidant, marche champion",
    "soundtrack yoga flow, ambient, pads doux, rythme respiratoire, ancrage",
    "chanson ligne d'arrivée marathon, pop euphorique, énergie stade, larmes de joie",
    "track edit sports extrêmes, rock, drums rapides, mood adrénaline junkie",
    "motivation pré-match, hip-hop, bars confiants, énergie vestiaire",
    "cool down post-workout, neo-soul, groove lent, appreciation du corps",
    "thème documentaire sportif, hybride orchestral, cinématique, esprit humain",
  ],
};

const SONG_FOOD_CULINARY: PromptCategory = {
  id: "food_culinary",
  label: "Food, cuisine & culinaire",
  mode: "song",
  prompts: [
    "générique chaîne cuisine, acoustique upbeat, vibes cuisine, chaleureux et accueillant",
    "intro émission pâtisserie, piano whimsical, sucré, nostalgie farine",
    "chanson marché street food, percussions latines, festif, énergie faim",
    "soirée dégustation vin, smooth jazz, intime, sophistiqué mais décontracté",
    "brunch entre amis, indie pop, ensoleillé, énergie mimosa, zéro rush",
    "run food nocturne, R&B, sensuel, romance drive-thru, néon cuisine",
    "hymne farm to table, folk, instruments organiques, earthy, honnête",
    "défi nourriture épicée, reggaeton, hot, qui transpire, énergie feu",
    "esthétique coffee shop, lo-fi jazzhop, fenêtre pluvieuse, vapeur et vinyle",
    "chanson recette familiale, soul, cuisine grand-mère, générations d'amour",
  ],
};

const SONG_TRAVEL_ADVENTURE: PromptCategory = {
  id: "travel_adventure",
  label: "Voyage, road trips & exploration",
  mode: "song",
  prompts: [
    "chanson road trip highway, indie rock, fenêtres ouvertes, nulle part où aller",
    "jam auberge backpacker, guitare acoustique, chants voyageurs, vin pas cher",
    "sunrise à la plage, tropical house, kick doux, air salin, nouveau jour",
    "sommet randonnée montagne, ambient cinématique, reverb large, altitude",
    "exploration city break, jazzy hip-hop, flânerie urbaine, se perdre",
    "nuit feu de camp en forêt, folk, crépitement feu, étoiles et histoires",
    "road trip désert, rock psychédélique, vagues de chaleur, beauté isolée",
    "été island hopping, reggaeton, enceintes bateau, island time",
    "voyage train en Europe, synthpop, reflets fenêtre, somewhere new",
    "thème documentaire aventure, orchestral, paysages vastes, curiosité humaine",
  ],
};

const SONG_MENTAL_HEALTH_SELFCARE: PromptCategory = {
  id: "mental_health_selfcare",
  label: "Santé mentale, self-care & croissance",
  mode: "song",
  prompts: [
    "réflexion séance thérapie, piano doux, vulnérable, moment breakthrough",
    "track calming anxiété, ambient, rythme respiratoire, safe space",
    "hymne self-love, pop, empowerant, affirmations miroir, glow up",
    "chanson healing deuil, violoncelle, cordes lentes, larmes et libération",
    "méditation mindfulness, bols tibétains, drones doux, moment présent",
    "track espoir dépression, build lent, lumière au bout, résilience",
    "empowerment limites, R&B, confiant, detox toxic trait, fort",
    "chanson recharge introvert, lo-fi, cozy, alone is okay, forteresse couverture",
    "ballade recovery trauma, acoustique, raw, safe and sound, healing",
    "self-care dimanche, bedroom pop, pyjama toute la journée, pas de culpabilité",
  ],
};

const SONG_FAMILY_PARENTING: PromptCategory = {
  id: "family_parenting",
  label: "Famille, parentalité & êtres chers",
  mode: "song",
  prompts: [
    "chanson merci maman, pop heartfelt, fête des mères, grandi de ton cœur",
    "danse père-fille, country, moment mariage, grandit trop vite",
    "hymne road trip fratrie, pop rock, blagues inside, lien éternel",
    "berceuse nouveaux parents, piano doux, nouveau-né, petits doigts, amour infini",
    "chanson réunion familiale, gospel-pop, multi-générationnel, mêmes racines",
    "blues nid vide, country, maison trop silencieuse, fier mais le manque",
    "sagesse grands-parents, folk, histoires table cuisine, héritage et valeurs",
    "enfant adopté appartenance, orchestral, famille choisie, tu es chez toi",
    "amour famille recomposée, indie pop, nouveaux chapitres, redéfinir famille",
    "animal de compagnie membre famille, pop silly, chien est mon enfant, fur baby anthem",
  ],
};

const SONG_CAREER_BUSINESS: PromptCategory = {
  id: "career_business",
  label: "Carrière, hustle & business",
  mode: "song",
  prompts: [
    "hymne side hustle startup, hip-hop, grind mode, 17h à 5h du mat",
    "fatigue corporate, art pop, réunions Zoom, lundis, menottes dorées",
    "liberté freelance, indie folk, pas de boss, chaotique mais à toi",
    "célébration promotion, disco pop, bureau coin, toast champagne",
    "recovery burnout, R&B lent, déconnexion, forêts et pas de réseau",
    "hustle creator economy, trap, vues et revenus, vie algorithme",
    "petit business owner, country rock, shop local, communauté d'abord",
    "confiance entretien job, pop, elevator pitch, fake it till you make it",
    "lifestyle remote work, chill electronic, bureau maison, CEO en sweatpants",
    "rêve retraite, yacht rock, 30 ans payés, cocktail île",
  ],
};

const SONG_PETS_ANIMALS: PromptCategory = {
  id: "pets_animals",
  label: "Animaux, bêtes & créatures drôles",
  mode: "song",
  prompts: [
    "chien qui te accueille porte, hyperpop, énergie queue wag, joie pure",
    "chat qui te juge, Lounge jazz, complexe supériorité, élégance boule de poils",
    "perroquet qui parle par-dessus, reggae, chœur cacardement, vibe pirate",
    "hamster crise existentielle roue, indie rock, petites roues, grands rêves",
    "blague poisson rouge mémoire, bubblegum pop, 3 secondes, oublieux mais heureux",
    "lapin mode chaos, ska, zoomies 3h du mat, obsession carotte",
    "transformation chien adopté, soul, sous-dog story, tail wags prove it",
    "chat qui fait tomber objets, phonk, destruction avec purpose",
    "tortue course confiance, slow jam, shell, slow and steady wins",
    "cobra cochon d'Inde wheek chorus, musique enfants, cris adorables, cute overload",
  ],
};

const SONG_MEMES_INTERNET: PromptCategory = {
  id: "memes_internet",
  label: "Mèmes, culture internet & viral",
  mode: "song",
  prompts: [
    "thème Skibidi Toilet, électronique absurde, énergie meme, brain rot",
    "audio trend NPC, vocal glitchy, jarring, bait algorithme TikTok",
    "chanson rizz, R&B, one-liners smooth, ChatGPT wrote this",
    "soundtrack sigma male, phonk, gym sombre, aesthetic loup solitaire",
    "chanson gyatt, Jersey club, booty bass, internet slang expliqué",
    "musique Ohio final boss, hyperpop, chaotique, pourquoi tout est si weird",
    "IA a généré cette chanson, électronique, uncanny valley, meta commentary",
    "chanson fanum tax, trap, vole tes fries, loyalty test",
    "cuisine avec le Gas compartido, reggaeton, cuisine chaotique, épicé",
    "hymne touch grass, acoustique, sortez dehors, nature is free",
  ],
};

const SONG_NOSTALGIA_THROWBACKS: PromptCategory = {
  id: "nostalgia_throwbacks",
  label: "Nostalgie, rétro & throwbacks",
  mode: "song",
  prompts: [
    "son démarrage Windows XP mais chanson complète, électronique nostalgique, era PC 2000s",
    "vibe générique Disney Channel, pop rock, samedi matin, héros enfance",
    "mémoire Tamagotchi, chiptune, amour pixélisé, deuil animal virtuel",
    "bal de collège 2000s, teen pop, chanson lente awkward, retour collège",
    "thème arcade Neo Geo, jeu de combat 90s, écran continue, quarter drop",
    "ton SMS téléphone clapet, bubblegum pop, T9 texting, appels manqués",
    "soundtrack construction Lego, orchestral, création enfance, briques plastique",
    "dessin animé samedi matin, power pop, bien vs mal, énergie céréale sucrée",
    "nostalgie mixtape, R&B, CD gravé, étiquette crayon, été 2003",
    "chanson internet dial-up, industriel, connexion stridente, amis AOL",
  ],
};

const SONG_SEASONAL_HOLIDAYS: PromptCategory = {
  id: "seasonal_holidays",
  label: "Saisons, fêtes & célébrations",
  mode: "song",
  prompts: [
    "brise estivale nocturne, tropical pop, feu de plage, peau salée, liberté",
    "fête Halloween sombre, pop dark, chaos costumes, envie bonbons",
    "dîner Thanksgiving, folk, drame familial, tarte citrouille, gratitude",
    "compte à rebours nouvel an, électronique, feux d'artifice, nouveaux débuts, champagne",
    "anthem breakup Saint-Valentin, indie rock, single awareness, thérapie chocolat",
    "renouveau printemps Pâques, indie pop, couleurs pastel, chasse œufs, renaissance",
    "retour à l'école, hip-hop, nouvelles shoes, fresh start, anxiété septembre",
    "matin Noël, gospel-pop, chaos familial, cadeaux, wonder enfance",
    "première danse mariage, R&B, slow jam, forever commence ce soir",
    "cérémonie diplôme, orchestral pop, toss cap, prochain chapitre commence",
  ],
};

const SONG_URBAN_RAW: PromptCategory = {
  id: "urban_raw",
  label: "Urbain brut: trap, drill, rap, R&B",
  mode: "song",
  prompts: [
    "melodic trap, nuit de pluie en ville, 808 glissant, piano mineur, vocal masculin émotionnel",
    "UK drill, rap froid agressif, piano sparse, 808 glissant, hats drill, 140 BPM, tension rue",
    "melodic rap, bars introspectifs, loop guitare mineure, pads aériens, 808 glides, hook space",
    "trap soul, vocal vulnérable, rhodes chaud, 808 smooth, pads atmos, confessions 3am",
    "phonk rap, vocal grave distordu, cowbell, Memphis 808, night drive, énergie agressive",
    "dancehall, vocal patois, riddim bounce, basse lourde, summer street, énergie club",
    "UK garage, vocal féminin chopped, drums skippy, basse bouncy, 2-step shuffle, late night",
    "baile funk, énergie fête brésilienne, tamborzao pounding, vocal MC, chaos dancefloor",
    "trapsoul, vocal féminin breathy, accords rhodes, 808 soft, vulnérabilité nocturne, mix chaleureux",
    "drill, vocal masculin froid, piano staccato, 808 glissant, hats crisp, mood rue cinématique",
    "melodic drill, bars storytelling, piano chromatique, 808 slide, tension froide, UK vibe",
    "cloud rap, pads dreamy washed, 808 soft, vocal flottant, drums minimales, mix éthéré",
    "rage rap, vocal agressif, 808 distordu, synth chaotique, énergie moshpit, mix loud",
    "emo rap, vocal cracked, guitare palm mute, 808 lourde, thème anxiété, émotionnel",
    "conscious rap, sample soul coupé, drums boom bap, basse upright, message social",
    "French drill, rap froid, piano staccato, 808 glissant, mood Paris 3am, cinématique",
    "French melodic rap, autotune léger, loop guitare nylon, 808, thème ambition, banlieue",
    "sample drill, vocal grave, loop soul, 808 slide, texture gritty, mood film urbain",
    "jersey club, vocal hooks chopped, kicks punchy, énergie bounce, vocal hype, club edit",
    "jersey drill, kick clusters, vocal chops, drill 808, agressif NY bounce, énergique",
  ],
};

const SONG_URBAN_BEATS: PromptCategory = {
  id: "urban_beats",
  label: "Beats instrumentaux urbains",
  mode: "song",
  prompts: [
    "Travis Scott style melodic trap, plucks spacey, 808 psychédélique, reverb lourde, hook autotuné",
    "Metro Boomin dark trap, strings ciné, 808 glissante, snare crisp, piano mineur, menaçant",
    "Future x Southside melodic trap, mélodie mineure toxique, 808 bounce dure, drums punchy, dark",
    "Drake x PARTYNEXTDOOR trap soul, rhodes moody, 808 smooth, hats serrés, R&B nocturne",
    "Playboi Carti rage trap, 808 distordue, lead synth chaotique, hats agressifs, moshpit",
    "21 Savage dark trap, stabs piano sinistres, slides 808, drums durs, basse menaçante",
    "Central Cee UK drill, piano sparse froid, 808 glissante, hats syncopés, minimal 140 BPM",
    "J Dilla boom bap, sample soul coupé, drums dusty, swing MPC, texture vinyle chaleureuse",
    "Skread French trap, mélodie mineure glaciale, 808 slides durs, hats crisp, mood Paris froid",
    "Kore melodic trap, pluck guitare ensoleillé, 808 bounce, mix chaud poli, optimiste",
    "DJ Weedim cloud trap, pads dreamy washed, 808 soft, drums minimales, vibe flottante",
    "Le Motif French drill, piano froid, 808 glissante, hats drill, tension ciné, Paris",
    "M1OnTheBeat UK drill, motif piano froid, 808 glissante, snare sharp, 140 BPM, gritty",
    "Memphis phonk, 808 distordue, cowbell hook, lead synth sombre, agressif mix raw",
    "baile funk, tamborzao kick brésilien, vocal chop MC, énergie fête, groove Rio raw",
  ],
};

const SONG_RB_SOUL_SPECIFIC: PromptCategory = {
  id: "rb_soul_specific",
  label: "R&B, soul & neo-soul spécifiques",
  mode: "song",
  prompts: [
    "neo soul, vocal féminin smooth, rhodes jazzy, basse live pocket, synthés futuristes, mix intime",
    "R&B contemporain, vocal masculin soyeux, accords rhodes, sub chaud, thème heartbreak",
    "90s R&B, vocal masculin smooth, new jack swing, synth brass, slow dance, nostalgique",
    "future R&B, vocal féminin processed, pads glitch, basse sub, mood cyber romance",
    "lo-fi R&B, drums dusty, crackle vinyle, nuit étude, vocal masculin mellow, tape saturation",
    "gospel trap soul, accords orgue, 808, claps, uplift spirituel, vibe dimanche matin",
    "dark R&B, vocal masculin grave, pads mineurs, 808 soft, piano sparse, thème toxic love",
    "afro R&B, vocal masculin, shaker percussion, accords chauds, groove sensuel, dansant",
    "vapor soul, vocal féminin reverbed, rhodes, slow jam, nuit néon pluvieuse, nostalgique",
    "French touch R&B, vocal féminin, accords filter house, talkbox, chic Parisian night",
    "K-R&B, accords modernes sleek, drums trap serrés, synthés glossy, vibe Seoul night",
    "trap soul, vocal masculin vulnérable, rhodes, 808 smooth, pads atmos, late night",
    "quiet storm R&B, vocal soyeux, soft drums, basse chaude, mood romantique nocturne",
    "new jack swing, swing drum machine, synth brass, vocal masculin, dancefloor 90s",
    "soul ballad, vocal raw, piano, cordes, émotion, larmes et libération, intemporel",
  ],
};

const BEAT_URBAN_RAW: PromptCategory = {
  id: "urban_raw",
  label: "Beats urbains bruts: trap, drill, phonk",
  mode: "beat",
  prompts: [
    "melodic trap, 808 glissant, piano mineur, pads aériens, drums durs, vibe nuit pluvieuse",
    "UK drill, piano sparse froid, 808 glissante, hats syncopés, 140 BPM, tension minimal",
    "phonk, 808 distordu, pattern cowbell, lead synth sombre, énergie agressive raw",
    "dark trap, strings ciné, 808 bass glissante, snare crisp, piano mineur, menaçant",
    "rage trap, 808 distordu, lead synth chaotique, basse saturée, hats agressifs",
    "sample drill, loop soul coupée, drill 808 slides, snare dure, texture gritty",
    "jersey drill, kick clusters, vocal chops, drill 808, agressif NY bounce",
    "French drill, piano froid, 808 glissante, hats drill, tension ciné, Paris 3am",
    "cloud rap, pads reverb washed, 808 soft, trap drums minimales, plucks dreamy",
    "emo rap, guitare palm mute, 808 lourde, pads sombres, mélodie mineure, mood anxiété",
    "afrotrap, percussions afro, 808 trap, mélodie pentatonique, groove rue chaude",
    "latin trap, dembow hints, plucks mineurs, 808, basse lourde, nuit latino",
    "grime instrumental, wobble bass, synth minimal, drums skippy, froid londonien",
    "Memphis phonk, cowbell hook, drums trap sombres, basse distordue, saturation tape",
    "cinematic trap, short viral loop hook, 808 dure, hats crisp, tension build, TikTok",
  ],
};

const BEAT_UK_GARAGE_DANCEHALL: PromptCategory = {
  id: "uk_garage_dancehall",
  label: "UK garage, dancehall & baile",
  mode: "beat",
  prompts: [
    "UK garage, drums skippy, basse bouncy, chord stabs, 2-step shuffle, vocal chops",
    "jersey club, bed-squeak sample, punchy kick clusters, vocal one-shots chopped, bounce",
    "dancehall riddim, basse lourde, skank guitar, claps, énergie fête summer street",
    "baile funk, tamborzao kick brésilien, vocal chop MC, énergie fête, groove Rio raw",
    "dembow dominicano, raw dembow kick, 808, perreo minimal, énergie rue chaude",
    "afrobeats, style Burna Boy, log drum groove, guitare rythmique, accords chauds, dansant",
    "amapiano, basse log drum, stabs piano jazzy, shaker groove, deep house groove",
    "afro house vocal, vocal féminin, log drum, piano chords, vibe Ibiza sunrise",
    "reggaeton, style Bad Bunny, dembow kick, bright pluck, sub chaud, club summer",
    "dancehall, vocal patois, riddim bounce, basse lourde, summer street, énergie club",
  ],
};

const BEAT_RB_SOUL_BEATS: PromptCategory = {
  id: "rb_soul_beats",
  label: "Beats R&B, soul & trap soul",
  mode: "beat",
  prompts: [
    "trap soul, style Drake, rhodes moody, 808 smooth, hi-hats serrés, R&B nocturne",
    "contemporary R&B beat, rhodes, 808 glide, hats tight, hook chord lift, vocal-ready",
    "neo soul beat, accords rhodes, basse live pocket, drums brossées, warm analog feel",
    "future R&B beat, pads glitch, sub deep, pluck sparse, cyber soul, atmos",
    "90s R&B instrumental, juno pads, swing drum machine, synth bass, slow jam",
    "dark R&B instrumental, pads mineurs, 808 soft, piano sparse, toxic mood",
    "gospel trap soul beat, accords orgue, 808, claps, uplift spirituel, chaleureux",
    "lo-fi R&B beat, drums dusty, crackle vinyle, accords mellow, vibe nuit étude",
    "bedroom pop beat, guitare clean, lo-fi drums, synth arp, intime, quiet",
    "pluggnb, plucks brillants, 808 bounce soft, drums légers, pads airy, mood rêveur",
  ],
};

const SONG_ACE_PROSE: PromptCategory = {
  id: "ace_prose",
  label: "ACE prose (optimisé)",
  mode: "song",
  prompts: getAceProseCuratedPool("song", "fr"),
};

const BEAT_ACE_PROSE: PromptCategory = {
  id: "ace_prose",
  label: "ACE prose (optimisé)",
  mode: "beat",
  prompts: getAceProseCuratedPool("beat", "fr"),
};

export const CATEGORIZED_FR: CategorizedLocalePools = {
  song: [
    SONG_NATURAL,
    SONG_CINEMATIC,
    SONG_ACOUSTIC,
    SONG_URBAN,
    SONG_POP_RNB,
    SONG_WORLD,
    SONG_ROCK,
    SONG_ELECTRONIC,
    SONG_IMPRESSIVE,
    SONG_FUN_URBAN,
    SONG_FUN_RNB,
    SONG_FUN_LATINO,
    SONG_FUN_ELECTRONIC,
    SONG_FUN_POP,
    SONG_CONTENT_CREATOR,
    SONG_GAMING,
    SONG_FITNESS_SPORTS,
    SONG_FOOD_CULINARY,
    SONG_TRAVEL_ADVENTURE,
    SONG_MENTAL_HEALTH_SELFCARE,
    SONG_FAMILY_PARENTING,
    SONG_CAREER_BUSINESS,
    SONG_PETS_ANIMALS,
    SONG_MEMES_INTERNET,
    SONG_NOSTALGIA_THROWBACKS,
    SONG_SEASONAL_HOLIDAYS,
    SONG_URBAN_RAW,
    SONG_URBAN_BEATS,
    SONG_RB_SOUL_SPECIFIC,
    SONG_ACE_PROSE,
    buildGenreMenuCategory("song", "Tous les genres du menu", "fr"),
  ],
  beat: [
    BEAT_URBAN,
    BEAT_CINEMATIC,
    BEAT_ACOUSTIC,
    BEAT_ELECTRONIC,
    BEAT_WORLD,
    BEAT_POP_RNB,
    BEAT_ROCK,
    BEAT_IMPRESSIVE,
    BEAT_URBAN_RAW,
    BEAT_UK_GARAGE_DANCEHALL,
    BEAT_RB_SOUL_BEATS,
    BEAT_ACE_PROSE,
    buildGenreMenuCategory("beat", "Tous les genres du menu", "fr"),
  ],
  hero: HERO,
};
