import type { CategorizedLocalePools, PromptCategory } from "./types";
import { buildGenreMenuCategory } from "@/lib/randomPromptIdeas/genreMenuPrompts";

/** Formulations naturelles — comme un vrai utilisateur qui ne maîtrise pas les tags ACE. */
const SONG_NATURAL: PromptCategory = {
  id: "natural",
  label: "Comme un vrai message",
  mode: "song",
  prompts: [
    "Fais-moi une chanson sur les vacances d'été en Italie avec ma famille",
    "Une chanson romantique pour demander en mariage, moderne pas cucul",
    "J'ai besoin d'un son pour mon anniversaire, ambiance fête entre potes",
    "Tu peux me faire une chanson triste sur un ami qui part à l'étranger",
    "Une chanson motivante pour survivre au lundi matin",
    "Fais-moi un truc sur mon chat qui démonte la maison à 3h du matin",
    "Chanson sur la première fois qu'on tombe amoureux au lycée",
    "Une chanson pour ma mère, douce, un peu gospel, pour lui dire merci",
    "Un son sur le burn-out au travail mais avec de l'espoir à la fin",
    "Fais-moi une chanson sur un road trip en van sur la côte atlantique",
    "Une chanson drôle sur les galères du métro et les retards",
    "Chanson d'été pour la plage, feel-good, facile à chanter en chorus",
    "Tu peux faire un son sur mon ex qui m'a ghosté, un peu vengeur",
    "Une chanson pour mon mariage civil, élégante et lumineuse",
    "Fais-moi une chanson sur grandir en banlieue, fierté et nostalgie",
    "Un son pour pleurer dans la voiture après une rupture",
    "Chanson sur mon premier appart, petit budget mais grand rêve",
    "Une chanson pour mon équipe de foot, hymne avant le match",
    "Fais-moi un truc sur Noël en famille, chaleureux et un peu magique",
    "Chanson sur l'amitié fille-garçon qui dure vraiment",
    "Tu peux me faire une chanson sur le café du matin et le silence",
    "Une chanson pour mon bébé qui vient de naître, tendre",
    "Fais-moi un son sur les nuits blanches d'examens, lo-fi dans l'âme",
    "Chanson sur retrouver l'amour après une longue pause",
    "Une chanson sur la mer en Bretagne, vent et liberté",
    "Fais-moi une chanson pour danser dans la cuisine à minuit",
    "Un son sur le courage de quitter un job toxique",
    "Chanson sur l'été au village chez grand-mère",
    "Tu peux faire une chanson sur deux âmes sœurs à distance",
    "Une chanson pour fêter mon diplôme, euphorique",
    "Fais-moi un truc sur la pluie et les parapluies cassés",
    "Chanson sur errer en ville la nuit sous les néons",
    "Une chanson pour mon père, sobre et respectueuse",
    "Fais-moi une chanson sur l'Italie, pasta, scooter et coucher de soleil",
    "Un son pour un départ en Erasmus, excitation et peur",
    "Chanson sur le premier jour de fac, timide mais déterminée",
    "Tu peux me faire une chanson sur la défaite qui forge au sport",
    "Une chanson sur l'automne et les feuilles, folk doux",
    "Fais-moi un son pour une soirée entre filles, empowerment",
    "Chanson sur le manque de quelqu'un qu'on ne voit plus",
    "Une chanson pour un EVJF, fun et un peu folle",
    "Fais-moi une chanson sur les étoiles et les promesses tenues",
    "Un son sur la colère puis le pardon dans un couple",
    "Chanson sur mon chien, loyal et un peu fou",
    "Tu peux faire une chanson sur la montagne et le silence",
    "Une chanson pour dire désolé sans être lourd",
    "Fais-moi un truc sur le retour au pays après des années loin",
    "Chanson sur danser, corps libéré, salon ou club",
    "Une chanson sur l'enfance et la cour de récré",
    "Peux-tu me faire une chanson sur un crush qui ne sait pas",
  ],
};

const SONG_CINEMATIC: PromptCategory = {
  id: "cinematic",
  label: "Ciné & bande-annonce",
  mode: "song",
  prompts: [
    "bande-annonce épique, cordes orchestrales, percussions taiko, montée héroïque, chœur puissant, mix IMAX",
    "musique de film suspense, cordes dissonantes, piano minimal, tension croissante, drones sourds, climax brutal",
    "soundtrack fantasy, flûte celtique, harpe, cordes larges, thème aventure lumineux, orchestration riche",
    "néo-classique émotionnel, piano concert grand, cordes legato, thème rupture, crescendo cathartique",
    "western moderne, guitare acoustique séche, harmonica, percussion bois, duel au soleil couchant",
    "horror cinématique, clusters piano, bowed metal, heartbeat sub, jump scare stinger, mix angoissant",
    "sci-fi orchestral, synth brass hybrid, arpèges glacés, exploration spatiale, pads immenses",
    "drame historique, violon solo plaintif, orchestre chambre, thème mémoire et guerre",
    "comédie feel-good ciné, ukulele, claquements, contrebasse bounce, thème optimiste léger",
    "action pursuit, staccato strings, brass hits, percussion ethnique, rythme 7/8 nerveux",
    "musique de documentaire nature, piano contemplatif, cordes aériennes, field-recording vents",
    "thriller politique, basson sombre, pulses synth discrets, paranoïa urbaine, mix serré",
    "anime opening épique, J-rock orchestral, batterie double kick, chœur japonais, lead guitare mélodique",
    "bollywood drama, sitar, tabla, cordes orientales, mélodie melismatic, climax festif",
    "guerre moderne, snare militaire, cuivres graves, synth grave, sacrifice et honneur",
    "pixar émotion, piano naïf, cordes douces, thème famille, montée larmoyante contrôlée",
    "film noir jazz, sax ténor smoky, contrebasse walking, brushes, pluie sur vitre",
    "post-apocalyptique, synth pad désolé, piano détuné, cordes longues, espoir fragile final",
    "course épique sport, percussion orchestre, brass fanfare, montée BPM, victoire stade",
    "romance ciné 90s, piano ballad, cordes satin, thème rencontre hasard, mix doux",
    "musique de jeu AAA, hybrid orchestral, choir chants, boss fight energy, drops syncopés",
    "biopic inspirant, guitare nylon, cordes chaleureuses, thème résilience, crescendo final",
    "espionnage chic, jazz lounge, vibraphone, contrebasse, cymbales ride, tension élégante",
    "catastrophe naturelle, drones graves, hits orchestraux, silence puis impact, mix dramatique",
    "fantômes et mémoire, voix féminine éthérée, piano reverb long, cordes spectrale",
  ],
};

const SONG_ACOUSTIC: PromptCategory = {
  id: "acoustic",
  label: "Unplugged & acoustique",
  mode: "song",
  prompts: [
    "unplugged MTV, guitare acoustique steel-string, voix masculine raw, harmoniques, room live, mix intime",
    "folk fingerstyle, guitare nylon, mélodie picking, voix douce féminine, ambiance feu de camp",
    "chanson acoustique française, voix masculine grave, accordéon léger, thème exil, mix chaleureux",
    "indie acoustique, guitare capo, strumming ouvert, voix féminine fragile, batterie brushes lointaine",
    "country acoustique moderne, guitare twang, pedal steel léger, voix masculine, thème route et regrets",
    "bossa nova acoustique, guitare nylon bossa, voix féminine chuchotée, percussions main, soirée douce",
    "blues acoustique delta, slide guitare, voix grave, stomp board, saturation organique",
    "singer-songwriter piano-voix, Steinway sec, voix masculine confessional, thème addiction guérie",
    "unplugged R&B, guitare électro-acoustique jazz chords, voix masculine runs, basse upright légère",
    "flamenco pop fusion, palmas, guitare nylon rasgueado, voix passionnée, claps percussifs",
    "bluegrass moderne, banjo, mandoline, contrebasse, harmonies trio, énergie porch",
    "acoustique lo-fi, guitare nylon enreg room, voix whisper, crackle léger, nuit pluvieuse",
    "duo acoustique homme-femme, deux guitares, harmonies tierces, thème amour mature",
    "unplugged rock ballad, guitare clean arpégée, batterie soft, voix masculine power chorus",
    "celtic acoustique, tin whistle, guitare dreadnought, bodhran, thème mer et légendes",
    "afro-acoustique, kora, guitare rythmique, voix masculine, groove léger mains",
    "chanson à texte moderne, voix féminine parlée-chantée, guitare folk, thème société",
    "unplugged soul, guitare jazz voicings, voix féminine gospel touches, claps main",
    "instrumental acoustique ciné, guitare 12 cordes, reverb hall, thème voyage intérieur",
    "pop acoustique TikTok, guitare ukulele, voix Gen Z, hook whistle, production minimal",
  ],
};

const SONG_URBAN: PromptCategory = {
  id: "urban",
  label: "Rap, trap & drill",
  mode: "song",
  prompts: [
    "hyperpop, lead synth glitché, 808 distordue, voix féminine brillante, refrain accrocheur, drums punchy",
    "UK drill, flow rap masculin froid, 808 glissante, piano sparse, strings ciné sombres, 140 BPM",
    "rap mélodique, voix masculine émotionnelle, guitare mineure, pads aériens, 808 glissante, hook space",
    "trap mélodique, voix masculine introspective, nuit pluvieuse, piano mineur, 808 glissante",
    "boom bap, sample soul coupé, thème conscient, voix spoken-word, swing MPC, texture vinyle",
    "trap mélodique style Travis Scott, plucks spacey, 808 psychédélique, reverb lourde, hook auto-tuné",
    "jersey club, hooks vocaux chopped, kicks punchy, énergie bounce, voix hype, edit club",
    "cloud rap, pads dreamy, 808 soft, voix masculine flottante, drums minimales, mix éthéré",
    "rap français mélancolique, couplets introspectifs, piano sombre, 808 lourde, banlieue nuit",
    "drill mélodique, voix masculine storytelling, piano chromatique, 808 slide, tension froide",
    "rage rap, voix masculine agressive, synth lead distordu, 808 saturée, énergie moshpit",
    "trap soul, voix masculine vulnérable, rhodes, 808 smooth, pads atmos, fin de nuit",
    "pluggnb, voix féminine airy, plucks brillants, 808 bounce soft, drums légers, mood rêveur",
    "emo rap, guitare clean palm mute, voix masculine cracked, 808 lourde, thème anxiété",
    "afrotrap, voix masculine, percussions afro, 808 trap, mélodie mineure, énergie rue",
    "latin trap, voix masculine espagnole, dembow hints, 808, plucks sombres, mood nocturne",
    "grime UK, flow rap rapide masculin, bass wobble, synth lead minimal, énergie froide",
    "phonk rap, voix masculine grave, cowbell, 808 distordue, saturation Memphis, drive nocturne",
    "rap conscience, sample spoken old, batterie boom bap, basse upright, message société",
    "trap hyperpop, voix féminine glitch, 808 distordue, leads arcade, mix compressé maximal",
    "drill français, voix masculine froide, piano staccato, 808 glissante, ambiance paris 3h",
    "melodic rap français, autotune léger, guitare nylon loop, 808, thème ambition",
    "trap cinématique, voix masculine epic, strings hits, 808, montée trailer, hook heroïque",
    "jersey drill, kicks clusters, vocal chops, 808 drill, bounce agressif, club NY",
    "sample drill storytelling, voix masculine grave, loop soul, 808 slide, mood film urbain",
  ],
};

const SONG_POP_RNB: PromptCategory = {
  id: "pop_rnb",
  label: "Pop, R&B & soul",
  mode: "song",
  prompts: [
    "dark alt-pop, pads sombres, progression mineure, voix féminine breathy, tension ciné, mix radio",
    "pop TikTok, refrain court accrocheur, synthés glossy, voix Gen Z, drums punchy, stéréo large",
    "pop moderne, harmonies féminines empilées, chorus supersaw, lead auto-tuné, énergie stade",
    "R&B contemporain, runs vocaux masculins soyeux, accords rhodes, sub chaud, heartbreak",
    "neo soul, voix féminine smooth, rhodes jazzy, basse live pocket, synthés futuristes, mix intime",
    "R&B contemporain, voix féminine breathy, piano rhodes, thème ghost, drums doux, mix chaleureux",
    "lo-fi R&B, drums dusty, crackle vinyle, nuit d'étude, voix masculine mellow, tape saturation",
    "house pop, kick four-on-the-floor, voix féminine uplifting, plucks brillants, été",
    "neo soul, voix féminine confiante, basse funky, rhodes, chorus cathartique, nouveau départ",
    "dance pop, topline catchy, résilience, voix féminine brillante, kick punchy, mix radio",
    "chanson pop française, voix féminine douce, piano, cordes, refrain mélancolique, ex qui revient",
    "90s R&B, voix masculine smooth, nouvelle jack swing, synth brass, thème slow dance",
    "future R&B, voix féminine processed, pads glitch, basse sub, mood cyber romance",
    "gospel pop, chœur femmes, lead soprano, orgue léger, claps, montée spirituelle",
    "synthpop rétro 80s, voix féminine, arp synth, gated reverb drums, néon nostalgique",
    "bedroom pop, voix féminine whisper, guitare clean, lo-fi drums, thème introversion",
    "K-pop ballad, voix féminine, strings orchestra, piano, montée chorus dramatique",
    "disco pop moderne, basse funky, strings, voix féminine, four-on-floor, glitter night",
    "indie pop, voix masculine douce, synth arp, batterie live, thème petite ville",
    "latin pop, voix féminine bilingue, reggaeton léger, guitare nylon, été romantique",
    "dark R&B, voix masculine grave, pads mineurs, 808 soft, thème toxic love",
    "afro R&B, voix masculine, percussion shakers, chords warm, groove sensuel",
    "pop rock féminine, guitare drive, voix power, batterie arena, thème liberté",
    "vapor soul, voix féminine reverbed, rhodes, slow jam, nuit néon pluie",
    "French touch pop, voix féminine, filter house chords, talkbox, chic parisien",
  ],
};

const SONG_WORLD: PromptCategory = {
  id: "world",
  label: "Afro, latin & monde",
  mode: "song",
  prompts: [
    "amapiano, basse log drum, stabs piano jazzy, shaker groove, voix masculine, club été",
    "reggaeton, rythme dembow, pluck brillant, voix masculine latine, bounce perreo, sub lourd",
    "afrobeats, voix masculine, talking drum, guitare highlife, groove dansant, festival sunset",
    "dancehall, voix masculine patois, riddim bounce, basse lourde, summer street party",
    "bachata romantique, guitare nylon arpège, bongo, voix masculine espagnole, slow dance",
    "salsa moderne, piano montuno, cuivres, voix masculine, énergie danse sociale",
    "cumbia électro, accordéon synth, guiro, voix féminine, bounce latin club",
    "rai pop, voix masculine, synth oriental, darbuka, mélodie maghrébine, nuit Oran",
    "kizomba, voix masculine, pads sensuels, groove lent, thème slow dance intime",
    "samba pop, cuica, violon brésilien, voix féminine, carnaval joie",
    "highlife pop, guitare africaine, voix masculine, horns section, groove accra",
    "arabic pop, voix masculine melismatic, oud, synth pads, quarter tone hooks",
    "bhangra pop, dhol drums, voix masculine punjabi, synth lead, wedding energy",
    "dembow dominicain, voix masculine, 808 lourd, perreo raw, rue chaude",
    "zouk moderne, voix féminine, synth brass, groove antillais, romance caraïbe",
    "afro house vocal, voix féminine, log drum, piano chords, sunrise ibiza",
    "latin trap soul, voix masculine, guitare flamenco touches, 808, nuit madrid",
    "amapiano vocal, voix féminine, log bass, piano jazz, deep club pretoria",
    "kompa pop, voix masculine, guitare clean, synth brass, danse couple",
    "afro drill fusion, voix masculine UK, percussions west africa, 808 slide, hybrid",
  ],
};

const SONG_ROCK: PromptCategory = {
  id: "rock",
  label: "Rock, punk & metal",
  mode: "song",
  prompts: [
    "indie sleaze, guitare électrique crue, batterie live, voix féminine rauque, nuit downtown",
    "pop-punk, guitares distordues, burnout, vocals shoutés, drums rapides, mix raw",
    "alternative rock, voix masculine, guitare delay, basse drive, thème suburban angst",
    "post-punk revival, basse melodic, guitare chorus, voix masculine detached, cold wave",
    "hard rock moderne, riffs palm mute, voix masculine gravel, double kick, arena energy",
    "emo pop rock, voix masculine cracked, guitare arp clean/distort, drums explosive chorus",
    "grunge 90s revival, guitare fuzz, voix masculine lazy, batterie loose, thème apathie",
    "metalcore mélodique, scream verse, clean chorus féminin, breakdown drop, guitare djent",
    "stoner rock, riff lent fuzz, voix masculine grave, groove hypnotique, wah lead",
    "garage rock, voix masculine, guitare crunchy, batterie one mic, énergie cave",
    "shoegaze pop, voix féminine buried, guitares mur wall, drums distant, rêve dense",
    "punk rock français, voix masculine, power chords, batterie rapide, thème révolte quotidienne",
    "prog rock court, signatures 7/8, synth lead, voix masculine, solo guitare virtuose",
    "blues rock, lead guitare overdrive, voix masculine, shuffle drums, solo long",
    "stadium rock, chœur massif, guitare anthem, voix masculine, montée finale",
  ],
};

const SONG_ELECTRONIC: PromptCategory = {
  id: "electronic",
  label: "Électro & club",
  mode: "song",
  prompts: [
    "house vocale, kick four-on-floor, voix féminine, piano chords, summer terrace",
    "UK garage, voix féminine chopped, skippy drums, bass bouncy, 2-step feel",
    "drum and bass vocal, voix masculine, breakbeats, sub rolling, rush euphoric",
    "techno pop, voix féminine, arp acid, kick hard, warehouse night",
    "trance vocal, voix féminine, supersaw, build long, drop uplifting",
    "electro swing, voix masculine, brass samples, swing drums, charleston modern",
    "synthwave, voix masculine, arp neon, gated snare, retro 80s drive",
    "future bass, voix féminine, chord stabs, drop wobble, emotional lift",
    "hyperpop club, voix féminine, 808, leads glitch, BPM rapide, chaos coloré",
    "deep house, voix masculine spoken, pads warm, bass groove, afterhours",
    "vocal jersey x house, voix chopped, kick bounce, stabs, NY club",
    "eurodance revival, voix féminine, lead synth, kick pounding, festival 2000s",
    "ambient pop electronic, voix féminine whisper, pads immenses, beat soft, flottant",
    "breakbeat pop, voix masculine, breaks chopped, bass reese, énergie big beat",
    "French touch vocale, voix féminine, filter disco sample, vocoder, chic électro",
  ],
};

const SONG_IMPRESSIVE: PromptCategory = {
  id: "impressive",
  label: "Impressionnant & pointu",
  mode: "song",
  prompts: [
    "hybrid orchestral trap, chœur latin, 808 sous cordes, montée epic, voix masculine hero",
    "jazz fusion vocale, solo sax ténor, basse fretless, voix scat, impro complexe",
    "opéra pop crossover, soprano lead, synth pads, drop trap chorus, contrast dramatique",
    "musique celtique epic, bodhran, fiddle, voix masculine, chœur gaélique, bataille brume",
    "middle eastern trap, oud plucks, darbuka, 808, voix masculine melismatic, desert night",
    "baroque pop, harpe, cordes chambre, voix féminine, contrebasse, ornamentation riche",
    "psytrance vocal, voix masculine chamanique, arp acid, kick rolling, festival desert",
    "noise pop art, voix féminine, distorsion contrôlée, drums chaos, beauté abrasive",
    "tango électro, bandoneon synth, voix masculine, double bass, passion Buenos Aires",
    "gamelan fusion, metallophones, voix féminine, sub bass, trance bali moderne",
    "choral drill, chœur gospel, 808 slide, voix lead rap, contraste sacré-rue",
    "unplugged orchestral, guitare acoustique, cordes live, voix masculine, pont intime-epic",
    "microtonal ambient song, voix féminine, saz turc, pads, émotion hors tonalité",
    "marching band hip-hop, cuivres fanfare, snare line, voix masculine, halftime show",
    "waterphone horror pop, voix féminine, piano, drop bass trap, cute meets creepy",
    "slide guitar blues cinematic, voix masculine, cordes western, duel sunset orchestral",
    "throat singing electronic, voix masculine harmoniques, synth drone, beat tribal slow",
    "glass harmonica dream pop, voix féminine, pads cristallins, bells, surreal beauty",
    "808 x harpe classique, voix féminine, trap drums, arpèges baroques, clash luxe",
    "vocoder symphony, voix processed, orchestra hits, disco bass, futur rétro grandiose",
  ],
};

const BEAT_URBAN: PromptCategory = {
  id: "urban",
  label: "Trap, drill & rap",
  mode: "beat",
  prompts: [
    "trap mélodique style Travis Scott, plucks spacey, 808 psychédélique, drums trap durs, reverb large",
    "trap soul style Drake, rhodes moody, 808 smooth, hi-hats serrés, vibe trap R&B nocturne",
    "rage trap style Carti, 808 distordue, lead synth chaotique, hats agressifs, énergie moshpit",
    "dark trap style Metro, strings ciné, basse 808 glissante, snare crisp, piano mineur",
    "UK drill style Central Cee, piano froid sparse, 808 glissante, hats syncopés, mix minimal",
    "trap mélodique style Future, mélodie mineure toxique, 808 bounce dure, drums punchy, mood sombre",
    "dark trap style 21 Savage, stabs piano sinistres, slides 808, drums durs, basse menaçante",
    "trap mélodique style Lil Uzi, plucks cloche spacey, accords mineurs, 808 bounce, pads aériens",
    "trap français style Skread, mélodie mineure glaciale, slides 808 dures, hats crisp, paris froid",
    "trap mélodique style Kore, pluck guitare ensoleillé, 808 bounce, mix chaud poli",
    "cloud trap style Weedim, pads dreamy, 808 soft, drums minimales, vibe flottante",
    "drill français style Le Motif, piano froid, 808 glissante, hats drill, tension ciné",
    "boom bap style J Dilla, sample soul coupé, drums dusty, swing MPC, texture vinyle",
    "UK drill style M1OnTheBeat, motif piano froid, 808 glissante, snare sharp, 140 BPM",
    "phonk, 808 distordue, pattern cowbell, lead synth sombre, énergie agressive, mix raw",
    "jersey club, bed-squeak sample, kick clusters, one-shots vocaux, bounce groove, club",
    "sample drill, loop soul coupée, slides 808 drill, snare dure, texture gritty, mood sombre",
    "cloud rap, pads reverb, 808 soft, drums trap minimales, plucks dreamy, stéréo large",
    "trap ciné, hook viral court, 808 dure, hats crisp, montée tension, edit TikTok",
    "pluggnb, plucks brillants, 808 bounce soft, drums légers, pads airy, hook space",
    "emo trap, guitare palm mute, 808 lourde, pads sombres, mélodie mineure, mood anxiété",
    "afrotrap, percussions afro, 808 trap, mélodie pentatonique, groove rue chaude",
    "latin trap, dembow hints, plucks mineurs, 808, bass lourd, nuit latino",
    "grime instrumental, bass wobble, synth minimal, drums skippy, froid londonien",
    "Memphis phonk, cowbell hook, drums trap sombres, basse distordue, saturation tape gritty",
  ],
};

const BEAT_CINEMATIC: PromptCategory = {
  id: "cinematic",
  label: "Ciné & épique",
  mode: "beat",
  prompts: [
    "trap ciné, riser tension, hit orchestral, drop 808 dur, arrangement sync-ready, trailer",
    "cinematic trap, short viral loop hook, hard 808, crisp hats, tension build, TikTok edit",
    "orchestral hybrid trap, brass stabs, taiko hits, 808 sub, epic montage energy",
    "horror trap, dissonant strings, sub drone, sudden silence drop, 808 impact, jump scare",
    "western trap, guitare acoustique dry, harmonica, 808 sous cordes, duel sunset",
    "sci-fi trap, arp glacé, synth choir, 808, pads immenses, exploration spatiale",
    "piano trap épique, motif mineur répétitif, montée cordes, drop 808, hero theme",
    "drill cinématique, piano staccato, strings legato, 808 slide, mood film policier",
    "anime type beat, J-rock guitars, drums double kick, synth lead, opening energy",
    "bollywood trap fusion, sitar pluck, tabla, 808, brass hits, drama festif",
    "war drums trap, snare militaire, brass grave, 808, tension battlefield",
    "fantasy orchestral loop, flute, harp arp, soft 808, quest adventure",
    "noir jazz trap, sax sample, upright bass, 808 lazy, pluie neon",
    "disaster movie pulse, heartbeat kick, rising strings, drop impact, survival tension",
    "video game boss, chip arp, orchestral hit, 808, phase fight intense",
  ],
};

const BEAT_ACOUSTIC: PromptCategory = {
  id: "acoustic",
  label: "Guitare & acoustique",
  mode: "beat",
  prompts: [
    "unplugged guitar loop, fingerstyle steel-string, percussion main, room reverb, hook mélodique",
    "acoustic trap, guitare nylon arp, 808 soft, hats légers, fusion chaud organique",
    "folk trap, guitare open tuning, banjo pluck, 808 sub, stomp clap, country moderne",
    "flamenco trap, palmas, nylon rasgueado, 808, castanettes, passion espagnole",
    "bossa trap, guitare bossa chords, shakers, 808 smooth, nuit rio",
    "blues loop acoustique, slide guitar, kick minimal, harmonica, bar smoke",
    "celtic guitar, tin whistle layer, bodhran soft, 808 sub léger, brume irlandaise",
    "classical guitar neoclassical, arpèges, cordes synth, 808, pont baroque trap",
    "ukulele pop beat, strum joyeux, kick soft, claps, summer tiktok",
    "12-string ambient, harmoniques, pads, 808 distant, voyage introspectif",
    "acoustic drill, piano-guitare hybrid, 808 slide, hats drill, contraste doux-dur",
    "kora loop afro, guitare rythmique, 808, percussion, groove ouest-africain",
  ],
};

const BEAT_ELECTRONIC: PromptCategory = {
  id: "electronic",
  label: "House, DnB & électro",
  mode: "beat",
  prompts: [
    "jersey club x house, kick four-on-the-floor, stabs coupés, bounce club, edit-ready",
    "amapiano, basse log drum, shakers, stabs piano jazzy, groove deep house, été",
    "hyperpop trap, stabs synth glitchés, 808 distordue, leads colorés, sound design internet",
    "drill ambient, pads reverb lourds, drums drill sparse, mélodie mineure, polish streaming",
    "lo-fi hip-hop, drums dusty, chop jazz sample, crackle vinyle, accords mellow, study",
    "UK garage instrumental, skippy drums, bass bouncy, chord stabs, 2-step shuffle",
    "drum and bass, breakbeats rolling, sub reese, arp lead, rave energy 174",
    "techno trap hybrid, kick hard, acid arp, 808 overlay, warehouse dark",
    "future bass, chord stabs emotional, drop wobble, arp bright, festival lift",
    "deep house, pads warm, bass groove, percussions congas, afterhours hypnotic",
    "electro swing, brass samples, swing drums, bass upright synth, charleston",
    "synthwave trap, arp neon, gated snare, 808, retro drive night",
    "French touch house, filter disco loop, talkbox lead, kick four, chic paris",
    "breakbeat hybrid, breaks chopped, bass reese, stabs, big beat energy",
    "ambient club, pads immenses, kick soft, texture granular, float dancefloor",
  ],
};

const BEAT_WORLD: PromptCategory = {
  id: "world",
  label: "Afro, latin & global",
  mode: "beat",
  prompts: [
    "reggaeton style Bad Bunny, pattern dembow, lead pluck brillant, sub chaud, club été",
    "afrobeats style Burna Boy, log drum groove, guitare rythmique, accords chauds, percussion",
    "pop-trap style Nyda, bounce dembow, plucks brillants, pop urbaine française, mix glossy",
    "afrobeats, licks guitare brillants, talking drum, sub chaud, bounce uplifting, festival",
    "dancehall riddim, bass heavy, skank guitar, claps, summer street",
    "bachata loop, nylon arp, bongo, guira, romance mid-tempo",
    "cumbia electro, accordéon synth, guiro, bounce latin, club",
    "rai trap, synth oriental, darbuka, 808, groove maghrébin",
    "samba break, cuica, surdo, whistle, carnaval bounce",
    "highlife guitar, horns stabs, groove accra, shakers, sunny",
    "dembow raw, kick dembow, 808, perreo minimal, rue chaude",
    "zouk instrumental, synth brass, groove lent, basse round, caraïbe",
    "afro house, log drum, piano chords, percussion shekere, ibiza sunrise",
    "latin jazz trap, piano montuno, 808, congas, nuit havane",
    "middle eastern trap, oud pluck, darbuka, 808, desert pulse",
  ],
};

const BEAT_POP_RNB: PromptCategory = {
  id: "pop_rnb",
  label: "R&B & pop instrumentale",
  mode: "beat",
  prompts: [
    "neo soul, accords rhodes, basse live pocket, drums brossées, swing laid-back, analog chaud",
    "slow jam R&B, rhodes soyeux, kick soft, basse chaude, fin de nuit, mix smooth",
    "instrumental R&B contemporain, espace couplet ouvert, accords lift chorus, 808 smooth",
    "pop-trap moderne, polish radio-ready, synth signature, drums serrés, motif catchy",
    "contemporary R&B beat, rhodes, 808 glide, hats tight, hook chord lift",
    "90s R&B instrumental, juno pads, drum machine swing, bass synth, slow jam",
    "future R&B, pads glitch, sub deep, pluck sparse, cyber soul",
    "bedroom pop beat, guitare clean, lo-fi drums, synth arp, intime",
    "gospel trap soul, organ chords, 808, claps, uplift spirituel",
    "dark R&B instrumental, pads mineurs, 808 soft, piano sparse, toxic mood",
  ],
};

const BEAT_ROCK: PromptCategory = {
  id: "rock",
  label: "Rock & punk",
  mode: "beat",
  prompts: [
    "pop punk type beat, power chords, drums rapides, basse pick, énergie skatepark",
    "indie rock loop, guitare arp delay, batterie live, basse melodic, dream drive",
    "hard rock riff, palm mute, double kick, lead overdrive, arena stomp",
    "emo guitar beat, clean/distort switch, drums explosive, pads sad, heartbreak",
    "garage rock one mic, crunchy guitare, batterie loose, énergie cave raw",
    "post-punk bass, guitare chorus, drums dry, cold atmosphere, 80s revival",
    "stoner riff slow, fuzz wall, groove hypnotique, wah lead sparse",
    "metalcore breakdown, djent palm mute, drop tuning, double kick, pit energy",
    "blues rock shuffle, lead guitare overdrive, batterie swing, organ faint",
    "shoegaze wall, guitars dense, drums distant, pads, float heavy",
  ],
};

const BEAT_IMPRESSIVE: PromptCategory = {
  id: "impressive",
  label: "Pointu & fusion",
  mode: "beat",
  prompts: [
    "g-funk, lead talk box, basse synth funky, drums crisp, west coast sunny, mix poli",
    "orchestral drill, strings staccato, 808 slide, choir hit, clash classique-rue",
    "jazz fusion trap, solo sax sample, rhodes, 808, walking bass synth, impro loop",
    "baroque trap, harpe arp, cordes chambre, 808, contrebasse, ornamenté",
    "tango trap, bandoneon synth, double bass, 808, passion argentine",
    "gamelan electronic, metallophone, sub bass, kick soft, trance bali",
    "microtonal beat, saz pluck, drone pad, 808 sparse, hors gamme",
    "marching band trap, snare line, brass fanfare, 808, halftime epic",
    "waterphone horror beat, clusters, sub drop, 808, creepy cute",
    "808 x harpe classique, arp baroque, trap drums, luxe clash",
    "throat singing drone, tribal percussion, 808 minimal, steppe vast",
    "glass harmonica ambient, bells, pads cristal, kick soft, surreal",
    "vocoder disco trap, orchestra hit, filter bass, four kick, futur retro",
    "slide guitar western trap, harmonica, 808, cordes, duel ciné",
    "intro type beat, motif hook mémorable, drums punchy clean, YouTube-ready",
  ],
};

const HERO = [
  "contemporary R&B, joyful resignation energy, rhodes chords, stacked female harmonies, warm sub, polished radio mix",
  "modern pop, ghosted-at-midnight heartbreak, breathy female lead, glossy synth hook, punchy drums, TikTok chorus",
  "melodic trap, rainy night introspection, minor piano loop, sliding 808, crisp hats, cold wide mix",
  "vocal house, turning-the-page uplift, four-on-floor kick, piano chord stabs, bright female lead, summer terrace",
  "neo soul, missed-train frustration groove, jazzy rhodes, live bass pocket, smooth male vocal, warm vinyl tone",
  "UK drill, come-up storytelling, cold male flow space, sparse piano, 808 slides, icy reverb tail",
  "afrobeats, summer sunset festival, talking drum accents, bright guitar licks, male vocal hooks, danceable groove",
  "lo-fi hip hop, late-night study focus, dusty boom bap drums, warm chords, vinyl crackle, calm steady pocket",
  "unplugged acoustic, road-trip freedom, steel-string guitar, raw male vocal, live room, harmonics, intimate mix",
  "epic trailer score, project launch anthem, taiko percussion, orchestral strings, brass fanfare, IMAX-width mix",
  "cinematic breakup, emotional piano motif, legato strings, sub drones, rising tension, cathartic crescendo",
  "Italian summer family joy, latin pop warmth, nylon guitar, bright percussion, singalong chorus, golden-hour mix",
  "folk acoustic, growing-up nostalgia, fingerstyle guitar, soft female vocal, campfire mood, warm saturation",
  "Brazilian phonk, night-drive aggression, cowbell pattern, distorted 808, raw club energy, hard-hitting drums",
  "gospel pop, gratitude for mom, female choir stacks, organ pads, claps, spiritual lift, warm hall reverb",
  "reggaeton, beach perreo energy, dembow kick, bright pluck melody, male latin vocal, heavy sub bounce",
  "melodic drill, city-at-3am coldness, emotional minor melody, 808 slides, crisp drill hats, hook space",
  "film scoring tension beat, dissonant strings, heartbeat sub pulse, sparse piano, slow-burn suspense, dramatic mix",
  "pop punk, burnout scream release, distorted power chords, shouted male vocal, fast drums, raw garage energy",
  "amapiano, kitchen dance groove, log drum bass, jazzy piano stabs, shaker rhythm, deep club warmth",
  "modern western, desert duel sunset, dry acoustic guitar, harmonica, wood percussion, cinematic wide mix",
  "trap soul, 3am overthinking, vulnerable male vocal, rhodes warmth, soft 808, nocturnal bedroom atmosphere",
  "French touch house, chic parisian night, filter disco chords, talkbox accents, four-on-floor, elegant bounce",
  "boom bap rap, first-apartment dreams, soul sample chop, MPC swing drums, conscious male flow, vinyl texture",
  "piano ballad, absence and longing, solo grand piano, breathy female lead, satin strings, tearful chorus lift",
  "jersey club, club bounce energy, chopped vocal hooks, kick clusters, 808 drill pocket, NY night drive",
  "anime opening, J-rock orchestral surge, melodic guitar lead, energetic male vocal, dramatic chorus rise",
  "acoustic loop beat, unplugged guitar motif, clean punchy drums, warm bass glue, hook-ready headroom",
  "wedding ballad, elegant romantic lift, piano and strings, female lead, stacked harmonies, luminous polish",
  "liquid dnb, running euphoria, rolling breaks, warm sub glide, airy pads, uplifting 174 energy",
  "folk autumn, golden leaves mood, acoustic strumming, soft male vocal, mandolin accents, bittersweet warmth",
  "horror cute beat, eerie music-box motif, sub drop hits, playful creepy contrast, sparse 808, unsettling mix",
  "K-pop gloss, French pop crossover, stacked female doubles, orchestral lift, catchy synth hook, wide shine",
  "conscious boom bap, society reflection, dusty soul sample, upright bass, spoken-word cadence, swing pocket",
  "synthwave, nostalgic neon drive, arp synth lead, gated snare, analog warmth, retro-futuristic mix",
  "afro house, sunrise terrace lift, log-drum groove, warm piano chords, hypnotic bass, ibiza morning energy",
  "playful pop, loyal dog energy, bright ukulele hook, cheerful female vocal, claps, feel-good singalong",
  "cinematic trap epic, orchestral hits, choir swells, 808 under strings, hero-rise drop, trailer-scale mix",
] as const;

export const CATEGORIZED_FR: CategorizedLocalePools = {
  song: [
    SONG_NATURAL,
    SONG_CINEMATIC,
    SONG_ACOUSTIC,
    SONG_URBAN,
    SONG_POP_RNB,
    SONG_WORLD,
    SONG_ROCK,
    SONG_ELECTRONIC,
    SONG_IMPRESSIVE,
    buildGenreMenuCategory("song", "Tous les genres du menu", "fr"),
  ],
  beat: [
    BEAT_URBAN,
    BEAT_CINEMATIC,
    BEAT_ACOUSTIC,
    BEAT_ELECTRONIC,
    BEAT_WORLD,
    BEAT_POP_RNB,
    BEAT_ROCK,
    BEAT_IMPRESSIVE,
    buildGenreMenuCategory("beat", "Tous les genres du menu", "fr"),
  ],
  hero: HERO,
};
