/**
 * Viral Shorts concepts — funny source texts + ACE generation prompts.
 * Each concept is reusable; planner rotates without repeating recent picks.
 */

import { VIRAL_CONCEPTS_EXTENDED } from "./viralContentCatalogExtended.mjs";

/** @typedef {import('./viralSeriesTypes.mjs').VIRAL_SERIES} _unused */

/**
 * @typedef {{
 *   id: string;
 *   series: 'comment_to_song' | 'absurd_to_song' | 'guess_prompt';
 *   sourceText: string;
 *   displayName: string;
 *   genre: string;
 *   bpm: number;
 *   isSong: boolean;
 *   aceCaption: string;
 *   sampleQuery: string;
 *   lyrics?: string;
 *   hookOpen?: string;
 *   hookReveal?: string;
 * }} ViralConcept
 */

/** @type {ViralConcept[]} */
export const VIRAL_CONCEPTS = [
  // ─── Série 1 : Commentaire → chanson ───
  {
    id: "cmt_boss_fired",
    series: "comment_to_song",
    sourceText: "My boss fired me over a one-line email.",
    displayName: "Fired Over Email",
    genre: "Country Pop",
    bpm: 92,
    isSong: true,
    aceCaption: "country pop breakup, acoustic guitar, emotional male vocal, Nashville heartbreak, 92 BPM, singable chorus",
    sampleQuery: "A funny-but-sad country song about getting fired by your boss in a one-line email",
  },
  {
    id: "cmt_cat_cables",
    series: "comment_to_song",
    sourceText: "My cat eats ethernet cables for breakfast.",
    displayName: "Cat vs WiFi",
    genre: "Hyperpop",
    bpm: 150,
    isSong: true,
    aceCaption: "chaotic hyperpop, pitched vocal chops, glitchy synths, comedic energy, 150 BPM, catchy hook",
    sampleQuery: "A chaotic funny hyperpop song about a cat that destroys ethernet cables every morning",
  },
  {
    id: "cmt_driving_test",
    series: "comment_to_song",
    sourceText: "I failed my driving test 4 times.",
    displayName: "4th Time's the Charm",
    genre: "Pop Punk",
    bpm: 168,
    isSong: true,
    aceCaption: "pop punk anthem, distorted guitars, shout-sing vocals, self-deprecating humor, 168 BPM",
    sampleQuery: "A pop punk anthem about failing your driving exam four times and still believing",
  },
  {
    id: "cmt_ex_hoodie",
    series: "comment_to_song",
    sourceText: "My ex wants their hoodie back. It's mine now.",
    displayName: "The Hoodie Stays",
    genre: "R&B",
    bpm: 78,
    isSong: true,
    aceCaption: "melodic R&B, smooth female vocal, petty but catchy, 78 BPM, emotional chorus",
    sampleQuery: "A petty R&B song about keeping your ex's hoodie forever",
  },
  {
    id: "cmt_rent_due",
    series: "comment_to_song",
    sourceText: "Rent is due tomorrow. I have $3 and vibes.",
    displayName: "$3 and Vibes",
    genre: "Drill",
    bpm: 140,
    isSong: true,
    aceCaption: "UK drill comedy rap, dark 808s, deadpan delivery, 140 BPM, viral hook",
    sampleQuery: "A funny drill song about having three dollars when rent is due tomorrow",
  },
  {
    id: "cmt_roommate_dishes",
    series: "comment_to_song",
    sourceText: "My roommate hasn't done dishes since January.",
    displayName: "January Dishes",
    genre: "Funk",
    bpm: 110,
    isSong: true,
    aceCaption: "funk diss track, groovy bass, sassy vocals, passive-aggressive humor, 110 BPM",
    sampleQuery: "A funky passive-aggressive song about a roommate who never washes dishes",
  },
  {
    id: "cmt_crush_liked",
    series: "comment_to_song",
    sourceText: "My crush liked my photo from 2019 at 2am.",
    displayName: "2019 at 2am",
    genre: "Bedroom Pop",
    bpm: 95,
    isSong: true,
    aceCaption: "bedroom pop, soft synths, whisper vocals, late-night overthinking, 95 BPM",
    sampleQuery: "A bedroom pop song about your crush liking your photo from six years ago at 2am",
  },
  {
    id: "cmt_mom_whatsapp",
    series: "comment_to_song",
    sourceText: "My dad refuses to learn WhatsApp.",
    displayName: "Dad vs WhatsApp",
    genre: "Folk",
    bpm: 88,
    isSong: true,
    aceCaption: "acoustic folk comedy, warm male vocal, storytelling, generational tech gap, 88 BPM",
    sampleQuery: "A funny folk song about a dad who refuses to learn WhatsApp",
  },
  {
    id: "cmt_gym_monday",
    series: "comment_to_song",
    sourceText: "I said I'd start gym Monday. It's been 47 Mondays.",
    displayName: "47 Mondays",
    genre: "Motivational Pop",
    bpm: 124,
    isSong: true,
    aceCaption: "motivational pop, big chorus, self-roasting lyrics, 124 BPM, ironic hype",
    sampleQuery: "A self-roasting motivational pop song about postponing the gym for 47 Mondays",
  },
  {
    id: "cmt_hater_comment",
    series: "comment_to_song",
    sourceText: "Someone said my music sounds like a microwave.",
    displayName: "Microwave Music",
    genre: "Experimental Pop",
    bpm: 128,
    isSong: true,
    aceCaption: "experimental pop, metallic textures, playful vocals, meme energy, 128 BPM",
    sampleQuery: "A playful song embracing the insult that your music sounds like a microwave",
  },
  {
    id: "cmt_late_wedding",
    series: "comment_to_song",
    sourceText: "I was 2 hours late to my own wedding.",
    displayName: "Late to My Wedding",
    genre: "Soul",
    bpm: 84,
    isSong: true,
    aceCaption: "soul ballad, gospel harmonies, apologetic romantic vocal, 84 BPM",
    sampleQuery: "A soul ballad apologizing for being two hours late to your own wedding",
  },
  {
    id: "cmt_best_friend_dog",
    series: "comment_to_song",
    sourceText: "Make a song about my dog judging my life choices.",
    displayName: "Dog Judge",
    genre: "Indie Pop",
    bpm: 118,
    isSong: true,
    aceCaption: "indie pop, quirky lyrics, bouncy rhythm, comedic pet perspective, 118 BPM",
    sampleQuery: "An indie pop song from the perspective of a dog judging its owner's life choices",
  },

  // ─── Série 2 : Texte absurde → chanson ───
  {
    id: "abs_apple_tos",
    series: "absurd_to_song",
    sourceText: "Apple Terms & Conditions — Section 4.2",
    displayName: "Apple ToS: The Musical",
    genre: "Epic Orchestral",
    bpm: 96,
    isSong: true,
    aceCaption: "epic orchestral cinematic, choir, dramatic strings, absurd legal document energy, 96 BPM",
    sampleQuery: "An epic orchestral song treating Apple Terms and Conditions like a dramatic movie trailer",
  },
  {
    id: "abs_receipt",
    series: "absurd_to_song",
    sourceText: "RECEIPT: 2 energy drinks, 1 regret, $11.47",
    displayName: "Receipt Rap",
    genre: "Trap",
    bpm: 142,
    isSong: true,
    aceCaption: "hard trap, 808 slides, monotone rap flow, convenience store aesthetic, 142 BPM",
    sampleQuery: "A trap song built from a grocery receipt listing energy drinks and regret",
  },
  {
    id: "abs_weather",
    series: "absurd_to_song",
    sourceText: "Forecast: rain all week. Mood: also rain.",
    displayName: "Rain All Week",
    genre: "Emo",
    bpm: 80,
    isSong: true,
    aceCaption: "emo ballad, rainy day guitars, dramatic vocals, weather report lyrics, 80 BPM",
    sampleQuery: "An emo ballad using a weather forecast that says rain all week",
  },
  {
    id: "abs_lease",
    series: "absurd_to_song",
    sourceText: "Apartment lease — quiet hours: 10pm–8am",
    displayName: "Lease Agreement Jazz",
    genre: "Jazz",
    bpm: 120,
    isSong: true,
    aceCaption: "smooth jazz, saxophone lead, landlord-tenant comedy, 120 BPM, lounge vibe",
    sampleQuery: "A smooth jazz song about apartment lease quiet hours rules",
  },
  {
    id: "abs_ikea",
    series: "absurd_to_song",
    sourceText: "IKEA instructions: insert tab A into slot B. Cry.",
    displayName: "IKEA Instructions",
    genre: "Techno",
    bpm: 128,
    isSong: true,
    aceCaption: "minimal techno, robotic vocal samples, assembly frustration, 128 BPM, club energy",
    sampleQuery: "A techno track about the emotional pain of IKEA furniture assembly instructions",
  },
  {
    id: "abs_checkbox",
    series: "absurd_to_song",
    sourceText: "☑ I have read and agree to the terms",
    displayName: "Terms Checkbox Gospel",
    genre: "Gospel",
    bpm: 88,
    isSong: true,
    aceCaption: "gospel choir, organ, satirical devotion, nobody-reads-the-terms energy, 88 BPM",
    sampleQuery: "A gospel choir song about clicking 'I agree' without reading the terms",
  },
  {
    id: "abs_parking_ticket",
    series: "absurd_to_song",
    sourceText: "PARKING VIOLATION — expired 4 minutes",
    displayName: "4 Minutes Late",
    genre: "Reggae",
    bpm: 92,
    isSong: true,
    aceCaption: "reggae protest song, laid-back groove, bureaucratic injustice, 92 BPM",
    sampleQuery: "A reggae protest song about a parking ticket for being four minutes expired",
  },
  {
    id: "abs_spam_email",
    series: "absurd_to_song",
    sourceText: "You have inherited $4.7M from a prince. Click here.",
    displayName: "Nigerian Prince Pop",
    genre: "Disco",
    bpm: 118,
    isSong: true,
    aceCaption: "disco funk, scam email lyrics, ironic sparkle, 118 BPM, danceable",
    sampleQuery: "A disco song using classic spam email about inheriting millions from a prince",
  },
  {
    id: "abs_wifi_password",
    series: "absurd_to_song",
    sourceText: "WiFi password: SorryNoWiFi2024!",
    displayName: "WiFi Password Ballad",
    genre: "Power Ballad",
    bpm: 72,
    isSong: true,
    aceCaption: "80s power ballad, soaring chorus, tragic wifi password, 72 BPM",
    sampleQuery: "An 80s power ballad about a WiFi password that says SorryNoWiFi",
  },
  {
    id: "abs_out_of_office",
    series: "absurd_to_song",
    sourceText: "Out of office until further notice. Probably forever.",
    displayName: "Out of Office Forever",
    genre: "Lo-Fi",
    bpm: 78,
    isSong: true,
    aceCaption: "lo-fi hip hop, mellow beat, corporate escape fantasy, 78 BPM, cozy",
    sampleQuery: "A lo-fi song about an out-of-office reply that says probably forever",
  },
  {
    id: "abs_calorie_label",
    series: "absurd_to_song",
    sourceText: "Nutrition facts: serving size — your entire personality",
    displayName: "Nutrition Facts",
    genre: "Comedy Rap",
    bpm: 95,
    isSong: true,
    aceCaption: "comedy rap, punchline bars, food label structure, 95 BPM",
    sampleQuery: "A comedy rap song structured like nutrition facts with serving size your entire personality",
  },
  {
    id: "abs_terms_privacy",
    series: "absurd_to_song",
    sourceText: "Privacy Policy — we may share data with partners. Who?",
    displayName: "Privacy Policy Blues",
    genre: "Blues",
    bpm: 86,
    isSong: true,
    aceCaption: "blues guitar, weary vocal, tech privacy paranoia, 86 BPM",
    sampleQuery: "A blues song about privacy policies that share your data with mysterious partners",
  },

  // ─── Série 3 : Devine le prompt ───
  {
    id: "guess_grandma_dragon",
    series: "guess_prompt",
    sourceText: "A grandma fighting dragons in Switzerland",
    displayName: "Grandma vs Dragons",
    genre: "Baroque Drill",
    bpm: 140,
    isSong: true,
    aceCaption: "baroque strings meets drill, epic absurd fusion, cinematic drops, 140 BPM",
    sampleQuery: "An epic absurd song about a Swiss grandma fighting dragons",
    hookReveal: "A grandma fighting dragons in Switzerland",
  },
  {
    id: "guess_breakup_k",
    series: "guess_prompt",
    sourceText: "Breakup text that just says k",
    displayName: "Just K",
    genre: "Sad Pop",
    bpm: 90,
    isSong: true,
    aceCaption: "minimal sad pop, sparse piano, deadpan vocal, one-letter heartbreak, 90 BPM",
    sampleQuery: "A devastating pop song about a breakup text that only says k",
    hookReveal: "Breakup text that just says k",
  },
  {
    id: "guess_alien_walmart",
    series: "guess_prompt",
    sourceText: "Alien first day working at Walmart",
    displayName: "Alien at Walmart",
    genre: "Synthwave",
    bpm: 110,
    isSong: true,
    aceCaption: "retro synthwave, quirky narrative vocals, retail comedy sci-fi, 110 BPM",
    sampleQuery: "A synthwave song about an alien's first day working at Walmart",
    hookReveal: "Alien first day working at Walmart",
  },
  {
    id: "guess_villain_monologue",
    series: "guess_prompt",
    sourceText: "Disney villain quitting their job",
    displayName: "Villain Resignation",
    genre: "Musical Theatre",
    bpm: 104,
    isSong: true,
    aceCaption: "musical theatre, dramatic villain vocals, Broadway comedy, 104 BPM",
    sampleQuery: "A Broadway-style song about a Disney villain quitting their evil job",
    hookReveal: "Disney villain quitting their job",
  },
  {
    id: "guess_toddler_ceo",
    series: "guess_prompt",
    sourceText: "Toddler accidentally becomes CEO",
    displayName: "Toddler CEO",
    genre: "Corporate Trap",
    bpm: 130,
    isSong: true,
    aceCaption: "corporate trap beat, baby voice adlibs, boardroom chaos, 130 BPM",
    sampleQuery: "A trap song about a toddler who accidentally becomes a company CEO",
    hookReveal: "Toddler accidentally becomes CEO",
  },
  {
    id: "guess_pigeon_mafia",
    series: "guess_prompt",
    sourceText: "Pigeon mafia running the city",
    displayName: "Pigeon Mafia",
    genre: "Italian Rap",
    bpm: 98,
    isSong: true,
    aceCaption: "Italian mob movie soundtrack, operatic rap, pigeon crime syndicate, 98 BPM",
    sampleQuery: "An Italian mob-style rap song about pigeons running a city crime syndicate",
    hookReveal: "Pigeon mafia running the city",
  },
  {
    id: "guess_time_travel_barista",
    series: "guess_prompt",
    sourceText: "Time-traveling barista who only serves regrets",
    displayName: "Regret Barista",
    genre: "Jazz Hop",
    bpm: 88,
    isSong: true,
    aceCaption: "jazz hop, smoky vocals, time travel coffee shop, 88 BPM, noir vibe",
    sampleQuery: "A jazz hop song about a time-traveling barista who only serves drinks of regret",
    hookReveal: "Time-traveling barista who only serves regrets",
  },
  {
    id: "guess_gym_mirror",
    series: "guess_prompt",
    sourceText: "Gym mirror giving life advice",
    displayName: "Mirror Coach",
    genre: "EDM Pop",
    bpm: 126,
    isSong: true,
    aceCaption: "EDM pop, motivational drop, sentient gym mirror, 126 BPM",
    sampleQuery: "An EDM pop song about a gym mirror that gives unsolicited life advice",
    hookReveal: "Gym mirror giving life advice",
  },
  {
    id: "guess_romcom_end",
    series: "guess_prompt",
    sourceText: "Rom-com where nobody falls in love",
    displayName: "No Love Rom-Com",
    genre: "Indie Folk",
    bpm: 102,
    isSong: true,
    aceCaption: "indie folk, anti-climax romance, acoustic warmth, 102 BPM",
    sampleQuery: "An indie folk song about a rom-com where absolutely nobody falls in love",
    hookReveal: "Rom-com where nobody falls in love",
  },
  {
    id: "guess_zombie_accountant",
    series: "guess_prompt",
    sourceText: "Zombie who just wants to do taxes",
    displayName: "Tax Zombie",
    genre: "Horror Pop",
    bpm: 116,
    isSong: true,
    aceCaption: "horror pop, spooky but wholesome, tax season undead, 116 BPM",
    sampleQuery: "A horror pop song about a zombie whose only passion is doing people's taxes",
    hookReveal: "Zombie who just wants to do taxes",
  },
  {
    id: "guess_influencer_cave",
    series: "guess_prompt",
    sourceText: "Influencer apologizing in a cave",
    displayName: "Cave Apology",
    genre: "Ambient Pop",
    bpm: 84,
    isSong: true,
    aceCaption: "ambient pop, reverb-heavy apology, dramatic influencer energy, 84 BPM",
    sampleQuery: "An ambient pop song about an influencer filming an apology video in a cave",
    hookReveal: "Influencer apologizing in a cave",
  },
  {
    id: "guess_four_words",
    series: "guess_prompt",
    sourceText: "Sad frog. Loud dubstep.",
    displayName: "Sad Frog Dubstep",
    genre: "Dubstep",
    bpm: 140,
    isSong: false,
    aceCaption: "melodic dubstep, meme frog energy, emotional drop, 140 BPM, instrumental hook",
    sampleQuery: "Melancholic dubstep about a sad frog with an absurdly loud drop",
    hookReveal: "Sad frog. Loud dubstep.",
  },
  {
    id: "cmt_situationship",
    series: "comment_to_song",
    sourceText: "We're not dating but you can't talk to anyone else.",
    displayName: "Situationship Anthem",
    genre: "Alt R&B",
    bpm: 82,
    isSong: true,
    aceCaption: "alt R&B, toxic situationship lyrics, smooth but petty vocal, 82 BPM",
    sampleQuery: "An alt R&B song about a situationship where you're not dating but they can't talk to anyone else",
  },
  {
    id: "cmt_group_chat",
    series: "comment_to_song",
    sourceText: "Turn my group chat drama into a song.",
    displayName: "Group Chat Drama",
    genre: "Pop Rap",
    bpm: 105,
    isSong: true,
    aceCaption: "pop rap, chaotic energy, group chat screenshots as lyrics, 105 BPM",
    sampleQuery: "A pop rap song about absolute chaos in a friend group chat",
  },
  {
    id: "abs_dm_seen",
    series: "absurd_to_song",
    sourceText: "Seen at 11:47 PM. Reply at 3:14 AM. Sorry I was asleep.",
    displayName: "Seen DM Ballad",
    genre: "Synth Pop",
    bpm: 118,
    isSong: true,
    aceCaption: "synth pop, passive aggressive DM lyrics, late night energy, 118 BPM",
    sampleQuery: "A synth pop song about leaving someone on seen then replying hours later with sorry I was asleep",
  },
  {
    id: "abs_meeting",
    series: "absurd_to_song",
    sourceText: "Calendar invite: Quick sync (will take 2 hours)",
    displayName: "Quick Sync",
    genre: "Elevator Jazz",
    bpm: 100,
    isSong: true,
    aceCaption: "elevator jazz corporate nightmare, calendar invite lyrics, 100 BPM",
    sampleQuery: "An elevator jazz song about a calendar invite called quick sync that takes two hours",
  },
  ...VIRAL_CONCEPTS_EXTENDED,
];

export function conceptsForSeries(seriesId) {
  return VIRAL_CONCEPTS.filter((c) => c.series === seriesId);
}

export function conceptById(id) {
  return VIRAL_CONCEPTS.find((c) => c.id === id) ?? null;
}

export function allConceptIds() {
  return VIRAL_CONCEPTS.map((c) => c.id);
}
