/**
 * Artist-inspired presets for ProducerHit.
 * Each preset provides a detailed ACE-Step caption + musical metadata
 * so the LM + diffusion model can replicate the artist's sonic signature.
 *
 * BPM / key / time_signature are passed separately in audioConfig
 * (not embedded in the prompt) — the LM infers arrangement from the caption.
 *
 * @see https://huggingface.co/ACE-Step/acestep-v15-xl-base
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ArtistRegion = "fr" | "us";

export interface ArtistPreset {
  /** Unique slug e.g. "sza", "tiakola" */
  id: string;
  /** Display name e.g. "SZA-inspired", "Tiakola-inspired" */
  display: string;
  /** Full artist name */
  artistName: string;
  /** Region / catalog */
  region: ArtistRegion;
  /** Primary genre tag */
  genre: string;
  /** ACE-Step caption — prose description of the sonic world */
  caption: string;
  /** Recommended BPM (will be sent in audioConfig) */
  bpm: number;
  /** Recommended key */
  key: string;
  /** Scale */
  scale: string;
  /** Time signature */
  timeSignature: string;
  /** Recommended duration in seconds */
  duration: number;
  /** Vocal language code */
  vocalLanguage: string;
  /** Vocal style direction */
  vocalStyle: string;
  /** Chips / tags for quick search */
  tags: readonly string[];
}

// ---------------------------------------------------------------------------
// France / Francophone — 50 artists
// ---------------------------------------------------------------------------

const FR_PRESETS: readonly ArtistPreset[] = [
  {
    id: "tiakola",
    display: "Tiakola-inspired",
    artistName: "Tiakola",
    region: "fr",
    genre: "Afro-R&B",
    caption:
      "Afro-melodic French R&B with warm nylon guitar, round sub bass, lush pads, syncopated Afro percussion, smooth male topline with soft melodic runs, warm tape saturation, intimate vocal space, gentle kick-snare pocket, dreamy reverb tails, catchy singable hook",
    bpm: 105,
    key: "F",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["afro", "r&b", "melodic", "guitar", "smooth"],
  },
  {
    id: "werenoi",
    display: "Werenoi-inspired",
    artistName: "Werenoi",
    region: "fr",
    genre: "Dark Rap",
    caption:
      "Dark French rap with minimalist melodies, heavy 808 sub bass, sparse piano motif, cold atmospheric pads, tight snare rolls, minor key tension, introspective male vocal delivery, cinematic textures, deep reverb, slow building arrangement, haunting vocal doubles",
    bpm: 130,
    key: "G",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["dark", "rap", "minimalist", "heavy 808", "cinematic"],
  },
  {
    id: "gazo",
    display: "Gazo-inspired",
    artistName: "Gazo",
    region: "fr",
    genre: "Drill FR",
    caption:
      "French drill with sliding 808 bass, rapid hi-hat triplets, dark piano stabs, cold aggressive atmosphere, sharp snare, syncopated kick pattern, menacing minor key melody, sparse strings, hard-hitting male rap vocal, dark reverb, tension-building breakdowns",
    bpm: 140,
    key: "D",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["drill", "dark", "808", "aggressive", "cold"],
  },
  {
    id: "ninho",
    display: "Ninho-inspired",
    artistName: "Ninho",
    region: "fr",
    genre: "Melodic Trap",
    caption:
      "Melodic French trap with emotional piano, deep rolling 808, atmospheric synth pads, catchy singable hook, warm sub bass, tight trap drums, hi-hat rolls, minor key melody with hopeful undertones, polished production, clean vocal mixing, space for topline",
    bpm: 138,
    key: "A",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["melodic", "trap", "piano", "emotional", "hook"],
  },
  {
    id: "sdm",
    display: "SDM-inspired",
    artistName: "SDM",
    region: "fr",
    genre: "Heavy Trap",
    caption:
      "Heavy French trap with dry tight drums, aggressive distorted 808, minimal melody, punchy kick, sharp snare, sparse arrangement, cold energy, menacing bass texture, minimal hi-hats, dark atmosphere, hard male rap delivery, low reverb, in-your-face mix",
    bpm: 140,
    key: "E",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["heavy", "trap", "aggressive", "dry", "hard"],
  },
  {
    id: "theodora",
    display: "Theodora-inspired",
    artistName: "Theodora",
    region: "fr",
    genre: "Pop R&B Urbain",
    caption:
      "Urban French pop R&B with Afro-influenced percussion, electronic textures, catchy chorus, warm bassline, shimmering synths, bright vocal production, danceable groove, polished arrangement, ear candy elements, modern vocal chops, radio-ready hook, clean mix",
    bpm: 108,
    key: "Bb",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["pop", "r&b", "afro", "catchy", "urban"],
  },
  {
    id: "plk",
    display: "PLK-inspired",
    artistName: "PLK",
    region: "fr",
    genre: "Melodic Rap",
    caption:
      "Melodic French trap-pop with atmospheric synths, emotional chord progressions, deep 808 bass, tight hi-hats, smooth vocal delivery blending rap and singing, ambient pads, melancholic undertones, polished modern production, catchy melodic hook, warm low end",
    bpm: 132,
    key: "C",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["melodic", "trap", "pop", "atmospheric", "emotional"],
  },
  {
    id: "rnboi",
    display: "RnBoi-inspired",
    artistName: "RnBoi",
    region: "fr",
    genre: "French R&B",
    caption:
      "Modern French R&B with Afro-influenced groove, soft kick-snare pocket, warm Rhodes chords, melodic male vocal, gentle bassline, airy pads, laid-back tempo, smooth vocal runs, intimate production, light hi-hats, dreamy atmosphere, catchy melodic hook",
    bpm: 95,
    key: "Db",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["r&b", "afro", "smooth", "melodic", "groove"],
  },
  {
    id: "aya-nakamura",
    display: "Aya Nakamura-inspired",
    artistName: "Aya Nakamura",
    region: "fr",
    genre: "Afro-Pop R&B",
    caption:
      "Afro-pop French R&B with syncopated percussion, bright guitar stabs, simple catchy bassline, danceable groove, repetitive earworm hook, warm production, playful vocal delivery, club-ready energy, shaker patterns, polished pop mixing, vibrant and uplifting",
    bpm: 102,
    key: "G",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["afro", "pop", "r&b", "danceable", "catchy"],
  },
  {
    id: "franglish",
    display: "Franglish-inspired",
    artistName: "Franglish",
    region: "fr",
    genre: "Afro-Swing R&B",
    caption:
      "French R&B with Afro-swing rhythm, bright guitar melodies, romantic chord progressions, warm bassline, swing hi-hats, melodic vocal delivery, feel-good energy, smooth groove, catchy chorus, polished modern production, danceable yet laid-back pocket",
    bpm: 100,
    key: "Eb",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["r&b", "afro-swing", "guitar", "romantic", "smooth"],
  },
  {
    id: "dadju",
    display: "Dadju-inspired",
    artistName: "Dadju",
    region: "fr",
    genre: "Afro-Pop R&B",
    caption:
      "Afro-pop R&B with emotional piano, bright guitar arpeggios, big melodic chorus, warm sub bass, polished production, smooth vocal harmonies, danceable Afro groove, uplifting energy, catchy hook, radio-ready arrangement, rich vocal layering",
    bpm: 105,
    key: "F",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["r&b", "afro", "piano", "emotional", "polished"],
  },
  {
    id: "gims",
    display: "GIMS-inspired",
    artistName: "GIMS",
    region: "fr",
    genre: "Pop Urbaine",
    caption:
      "Urban Afro-pop with massive anthemic chorus, pristine clean production, bright synths, punchy drums, deep sub bass, catchy melodic hook, polished vocal layering, uplifting energy, stadium-ready arrangement, vibrant instrumentation, radio-ready mix",
    bpm: 108,
    key: "D",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["pop", "urban", "anthemic", "polished", "catchy"],
  },
  {
    id: "hamza",
    display: "Hamza-inspired",
    artistName: "Hamza",
    region: "fr",
    genre: "Dark R&B",
    caption:
      "Nocturnal trap-R&B with foggy atmospheric pads, deep rolling sub bass, hazy dreamy textures, slow groove, dark minor key, intimate vocal delivery, reverb-drenched vocals, melancholic mood, sparse arrangement, warm analog synth, late-night vibe, sensual tension",
    bpm: 85,
    key: "Ab",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["dark", "r&b", "nocturnal", "atmospheric", "sensual"],
  },
  {
    id: "damso",
    display: "Damso-inspired",
    artistName: "Damso",
    region: "fr",
    genre: "Introspective Rap",
    caption:
      "Introspective French rap with cinematic dark harmonies, heavy sub bass, orchestral textures, deep piano, atmospheric pads, sparse trap drums, brooding minor key, spoken-word vocal delivery, philosophical mood, tension and release, noir atmosphere, minimal yet rich",
    bpm: 120,
    key: "F#",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["introspective", "cinematic", "dark", "orchestral", "deep"],
  },
  {
    id: "luidji",
    display: "Luidji-inspired",
    artistName: "Luidji",
    region: "fr",
    genre: "Neo-Soul Rap",
    caption:
      "Neo-soul French rap with rich jazz-influenced chords, organic bass, warm Rhodes, introspective mood, laid-back groove, deep melodic bassline, spacious arrangement, textured production, soulful vocal delivery, vinyl warmth, contemplative atmosphere, subtle percussion",
    bpm: 90,
    key: "E",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["neo-soul", "jazz", "introspective", "warm", "organic"],
  },
  {
    id: "josman",
    display: "Josman-inspired",
    artistName: "Josman",
    region: "fr",
    genre: "Alt Rap",
    caption:
      "Alternative French rap with analog synth textures, funky groovy bassline, dark undertones, retro-modern production, tight snare, syncopated hi-hats, minor key, moody atmospheric pads, distinctive vocal flow, experimental arrangements, warm tape saturation",
    bpm: 110,
    key: "B",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["alternative", "funky", "analog", "experimental", "moody"],
  },
  {
    id: "la-feve",
    display: "La Fève-inspired",
    artistName: "La Fève",
    region: "fr",
    genre: "Modern Trap",
    caption:
      "Modern French trap with spacious atmospheric production, soft 808 slides, ethereal pads, wide stereo field, melodic motifs, dreamy textures, trap drums with swing, deep sub bass, hypnotic groove, minimal yet rich arrangement, clean modern mix",
    bpm: 135,
    key: "A",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["trap", "modern", "atmospheric", "spacious", "dreamy"],
  },
  {
    id: "l2b",
    display: "L2B-inspired",
    artistName: "L2B",
    region: "fr",
    genre: "Melodic Rap",
    caption:
      "Young melodic French rap with bouncy energy, round warm 808, catchy hooks, bright synth stabs, playful rhythm, upbeat pocket, youthful vocal delivery, polished pop-rap production, ear candy accents, danceable groove, radio-friendly arrangement",
    bpm: 130,
    key: "C",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["melodic", "bounce", "young", "catchy", "playful"],
  },
  {
    id: "genezio",
    display: "Genezio-inspired",
    artistName: "Genezio",
    region: "fr",
    genre: "Afro-Rap",
    caption:
      "Afro-rap French sound with infectious melodies, danceable percussion patterns, bright rhythmic guitar, catchy singable hook, warm bassline, uplifting energy, Afrobeat-influenced drums, vibrant production, party-ready groove, polished vocal mixing, feel-good vibe",
    bpm: 108,
    key: "G",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["afro", "rap", "danceable", "catchy", "vibrant"],
  },
  {
    id: "naza",
    display: "Naza-inspired",
    artistName: "Naza",
    region: "fr",
    genre: "Afro-Pop Rap",
    caption:
      "Afro-pop French rap with festive bounce groove, bouncy bassline, African percussion, bright guitar riffs, catchy party hook, high energy, danceable rhythm, upbeat tempo, warm vocal delivery, vibrant colorful production, club-ready arrangement, feel-good energy",
    bpm: 112,
    key: "D",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["afro", "pop", "party", "bounce", "festive"],
  },
  {
    id: "niska",
    display: "Niska-inspired",
    artistName: "Niska",
    region: "fr",
    genre: "Afro-Trap",
    caption:
      "Afro-trap French sound with percussive aggressive drums, club energy, heavy 808, bouncy kick pattern, dark minor key, hard-hitting snare, infectious rhythm, raw vocal delivery, minimal melody, high-energy arrangement, street-level production, powerful bass",
    bpm: 130,
    key: "Eb",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["afro", "trap", "aggressive", "club", "hard"],
  },
  {
    id: "keblack",
    display: "KeBlack-inspired",
    artistName: "KeBlack",
    region: "fr",
    genre: "Afro-R&B",
    caption:
      "Sentimental Afro-R&B with warm piano chords, emotional guitar melodies, smooth vocal delivery, gentle bassline, tender mood, romantic atmosphere, polished production, heartfelt chorus, melodic hooks, soft percussion, intimate arrangement, lush harmonies",
    bpm: 92,
    key: "Bb",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["afro", "r&b", "sentimental", "piano", "romantic"],
  },
  {
    id: "kalash",
    display: "Kalash-inspired",
    artistName: "Kalash",
    region: "fr",
    genre: "Dancehall Afro-Caribbean",
    caption:
      "Dancehall Afro-Caribbean with tropical percussion, heavy bass, syncopated rhythms, island groove, bright steel drum accents, bouncy kick, warm sub bass, party energy, Caribbean-flavored vocal delivery, festive arrangement, rhythmic guitar stabs, dancehall riddim",
    bpm: 100,
    key: "F",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["dancehall", "caribbean", "tropical", "party", "bass"],
  },
  {
    id: "leto",
    display: "Leto-inspired",
    artistName: "Leto",
    region: "fr",
    genre: "Dark Trap",
    caption:
      "Dark French trap with powerful 808 bass, minimalist synth stabs, cold atmospheric textures, menacing minor key, sparse arrangement, tight drums, sharp snare, hard-hitting kick, menacing mood, street energy, dark reverb, raw vocal delivery, minimal melody",
    bpm: 140,
    key: "G",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["dark", "trap", "minimal", "hard", "cold"],
  },
  {
    id: "zola",
    display: "Zola-inspired",
    artistName: "Zola",
    region: "fr",
    genre: "Cold Trap",
    caption:
      "Cold minimal French trap with dry 808, dark atmospheric synths, sparse cold arrangement, menacing minor key, sharp dry snare, tight hi-hats, minimal melody, cold spacious mix, dark energy, tight pocket, raw vocal delivery, minimal reverb, hard-hitting kick",
    bpm: 138,
    key: "D",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["cold", "trap", "minimal", "dark", "dry"],
  },
  {
    id: "sch",
    display: "SCH-inspired",
    artistName: "SCH",
    region: "fr",
    genre: "Cinematic Trap",
    caption:
      "Cinematic French trap with dark piano motifs, deep sub bass, orchestral string arrangements, cinematic tension, heavy 808, dramatic atmosphere, minor key, sparse percussion, noir mood, storytelling vocal delivery, orchestral buildup, powerful bass drops",
    bpm: 125,
    key: "C",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["cinematic", "trap", "orchestral", "dark", "dramatic"],
  },
  {
    id: "booba",
    display: "Booba-inspired",
    artistName: "Booba",
    region: "fr",
    genre: "Minimal Rap",
    caption:
      "Minimal French rap with massive heavy bass, cold minimal synth textures, sparse arrangement, powerful kick, minimal drums, deep sub frequencies, authoritative vocal delivery, dark atmosphere, cold production, minimal melody, regal commanding presence, deep bass weight",
    bpm: 95,
    key: "Ab",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["minimal", "rap", "heavy bass", "cold", "authoritative"],
  },
  {
    id: "kaaris",
    display: "Kaaris-inspired",
    artistName: "Kaaris",
    region: "fr",
    genre: "Hardcore Trap",
    caption:
      "Hardcore French trap with distorted 808 bass, aggressive drums, heavy kick distortion, dark menacing atmosphere, violent energy, hard-hitting snare, minimal melody, industrial textures, aggressive vocal delivery, raw intensity, dark minor key, powerful arrangement",
    bpm: 145,
    key: "F#",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["hardcore", "trap", "aggressive", "distorted", "intense"],
  },
  {
    id: "djadja-dinaz",
    display: "Djadja & Dinaz-inspired",
    artistName: "Djadja & Dinaz",
    region: "fr",
    genre: "Melodic Rap",
    caption:
      "Melodic French rap with melancholic piano, emotional chord progression, trap drums, 808 bass, mellow atmosphere, sentimental vocal delivery, catchy melodic hook, smooth flow, minor key, reflective mood, polished production, heartfelt arrangement",
    bpm: 130,
    key: "E",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["melodic", "rap", "piano", "melancholic", "emotional"],
  },
  {
    id: "maes",
    display: "Maes-inspired",
    artistName: "Maes",
    region: "fr",
    genre: "Dark Melodic Rap",
    caption:
      "Dark melodic French rap with emotional piano motif, trap mid-tempo groove, deep 808, atmospheric pads, melancholic mood, introspective vocal delivery, dark minor key, polished production, catchy melodic hook, reflective arrangement, warm low end, smooth flow",
    bpm: 125,
    key: "Bb",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["melodic", "dark", "piano", "introspective", "trap"],
  },
  {
    id: "heuss-lenfoire",
    display: "Heuss L'enfoiré-inspired",
    artistName: "Heuss L'enfoiré",
    region: "fr",
    genre: "Festive Rap",
    caption:
      "Festive energetic French rap with bouncy bounce groove, catchy direct hook, high-energy drums, punchy kick, bright synth stabs, party atmosphere, direct vocal delivery, upbeat arrangement, danceable rhythm, crowd-energy production, loud and proud, fun vibe",
    bpm: 120,
    key: "G",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["festive", "bounce", "party", "energetic", "catchy"],
  },
  {
    id: "guy2bezbar",
    display: "Guy2Bezbar-inspired",
    artistName: "Guy2Bezbar",
    region: "fr",
    genre: "Urban Funk Rap",
    caption:
      "Urban French rap-funk with groovy danceable bassline, funk guitar stabs, bouncy rhythm, bright production, catchy hook, playful vocal delivery, upbeat energy, retro-modern groove, warm bass, tight drums, feel-good atmosphere, party-ready arrangement",
    bpm: 110,
    key: "A",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["funk", "urban", "groovy", "danceable", "party"],
  },
  {
    id: "mhd",
    display: "MHD-inspired",
    artistName: "MHD",
    region: "fr",
    genre: "Afro-Trap",
    caption:
      "Afro-trap pioneer sound with African percussion layers, synth bass, bouncy rhythmic pattern, bright melodic motif, danceable groove, afrobeat-influenced drums, catchy hook, vibrant production, high energy, African-influenced vocal chants, festive atmosphere, rhythmic guitar",
    bpm: 120,
    key: "F",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["afro-trap", "percussion", "african", "danceable", "vibrant"],
  },
  {
    id: "orelsan",
    display: "Orelsan-inspired",
    artistName: "Orelsan",
    region: "fr",
    genre: "Pop Rap",
    caption:
      "Pop-rap with organic instrumentation, storytelling arrangement, warm acoustic textures, live-feeling drums, subtle bass, narrative vocal delivery, clever lyrics, emotional buildups, chorus hook, polished yet authentic production, introspective moments, dynamic arrangement",
    bpm: 110,
    key: "D",
    scale: "Major",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["pop", "rap", "storytelling", "organic", "introspective"],
  },
  {
    id: "dinos",
    display: "Dinos-inspired",
    artistName: "Dinos",
    region: "fr",
    genre: "Introspective Rap",
    caption:
      "Introspective French rap with emotional piano, rich arrangements, deep bass, atmospheric pads, reflective mood, detailed production, dynamic buildup, heartfelt vocal delivery, minor key, cinematic moments, emotional crescendos, thoughtful arrangement, layered textures",
    bpm: 105,
    key: "G",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["introspective", "emotional", "piano", "cinematic", "deep"],
  },
  {
    id: "tayc",
    display: "Tayc-inspired",
    artistName: "Tayc",
    region: "fr",
    genre: "Afro-R&B",
    caption:
      "Sensual Afro-R&B with soft smooth drums, warm bass, gentle percussion, intimate vocal delivery, sensual groove, warm Rhodes chords, laid-back pocket, romantic mood, melodic topline, seductive arrangement, smooth transitions, lush harmonies, late-night vibe",
    bpm: 92,
    key: "Eb",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["afro", "r&b", "sensual", "smooth", "intimate"],
  },
  {
    id: "vacra",
    display: "Vacra-inspired",
    artistName: "Vacra",
    region: "fr",
    genre: "Alt R&B",
    caption:
      "Alternative R&B with airy ethereal vocals, minimalist production, afro-influenced textures, delicate arrangement, spacious mix, dreamy pads, soft kick, gentle bass, afloat feeling, stripped-back instrumentation, intimate recording, raw vocal emotion, reverb-drenched",
    bpm: 88,
    key: "A",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["alt-r&b", "minimal", "airy", "ethereal", "intimate"],
  },
  {
    id: "willy-lancien",
    display: "Willy L'Ancien-inspired",
    artistName: "Willy L'Ancien",
    region: "fr",
    genre: "Afro-Rap Minimal",
    caption:
      "Minimal Afro-rap with nocturnal groove, high-pitched vocal texture used as instrument, deep bassline, sparse arrangement, hypnotic rhythm, dark atmosphere, minimal drums, afro-influenced percussion, moody pads, distinctive vocal tone, late-night energy, raw production",
    bpm: 98,
    key: "B",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["afro", "rap", "minimal", "nocturnal", "distinctive"],
  },
  {
    id: "eva",
    display: "Eva-inspired",
    artistName: "Eva",
    region: "fr",
    genre: "Pop R&B",
    caption:
      "Pop-R&B with afro-influenced rhythm, bright shimmering synths, catchy accrocheur chorus, polished production, danceable groove, warm bassline, playful energy, radio-ready arrangement, feminine vocal power, ear candy details, modern production, feel-good atmosphere",
    bpm: 105,
    key: "C",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["pop", "r&b", "afro", "catchy", "bright"],
  },
  {
    id: "meryl",
    display: "Meryl-inspired",
    artistName: "Meryl",
    region: "fr",
    genre: "Afro-Caribbean R&B",
    caption:
      "Afro-Caribbean R&B with tropical percussion, warm melodic vocal, rhythmic guitar, laid-back groove, island-influenced drums, smooth bassline, breezy atmosphere, singable hook, warm production, light and airy arrangement, feel-good Caribbean energy, melodic flow",
    bpm: 98,
    key: "G",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["afro", "caribbean", "r&b", "tropical", "smooth"],
  },
  {
    id: "lala-ce",
    display: "Lala &ce-inspired",
    artistName: "Lala &ce",
    region: "fr",
    genre: "Alt R&B Experimental",
    caption:
      "Alternative experimental R&B with trap textures, electronic sound design, unconventional rhythms, glitchy accents, atmospheric pads, bold vocal delivery, genre-blending production, moody undertones, experimental arrangement, deep bass, unique textures, avant-garde feel",
    bpm: 100,
    key: "F#",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["alt-r&b", "experimental", "trap", "atmospheric", "bold"],
  },
  {
    id: "chilla",
    display: "Chilla-inspired",
    artistName: "Chilla",
    region: "fr",
    genre: "Melodic Rap R&B",
    caption:
      "Melodic rap-R&B with emotional piano, storytelling arrangement, warm bass, heartfelt vocal delivery, sentimental mood, catchy melodic hook, smooth flow, intimate production, gentle percussion, polished mix, emotional buildups, reflective lyrics, soft dynamics",
    bpm: 100,
    key: "Db",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["melodic", "r&b", "piano", "emotional", "storytelling"],
  },
  {
    id: "moussa",
    display: "Moussa-inspired",
    artistName: "Moussa",
    region: "fr",
    genre: "Afro-Pop R&B",
    caption:
      "Afro-pop R&B with gentle guitar melodies, soft groove, warm bassline, laid-back arrangement, mellow percussion, sweet vocal delivery, romantic mood, smooth transitions, pleasant atmosphere, clean production, singable hook, gentle dynamics, feel-good energy",
    bpm: 96,
    key: "A",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["afro", "pop", "r&b", "smooth", "romantic"],
  },
  {
    id: "ronisia",
    display: "Ronisia-inspired",
    artistName: "Ronisia",
    region: "fr",
    genre: "Afro-R&B Dancehall",
    caption:
      "Afro-R&B with light dancehall influence, highly melodic topline, rhythmic percussion, warm guitar, smooth vocal delivery, catchy hook, modern production, bouncy groove, sensual energy, polished arrangement, island-influenced rhythm, feel-good atmosphere",
    bpm: 100,
    key: "Eb",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["afro", "r&b", "dancehall", "melodic", "sensual"],
  },
  {
    id: "himra",
    display: "Himra-inspired",
    artistName: "Himra",
    region: "fr",
    genre: "Afro-Rap",
    caption:
      "Afro-rap with percussive rhythmic patterns, modern energy, bright melodic accents, bouncy groove, catchy hook, warm bassline, contemporary production, tight drums, danceable rhythm, youthful vocal delivery, vibrant arrangement, afro-influenced textures",
    bpm: 115,
    key: "F",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["afro", "rap", "percussive", "modern", "bouncy"],
  },
  {
    id: "kerchak",
    display: "Kerchak-inspired",
    artistName: "Kerchak",
    region: "fr",
    genre: "Jersey Drill",
    caption:
      "Jersey-drill hybrid with fast drums, syncopated bass, kick clusters, stop-start arrangement, sliding 808, dark melodic motif, bouncy pocket, aggressive energy, rapid hi-hats, dark minor key, hard-hitting snare, street-level intensity, raw vocal delivery",
    bpm: 145,
    key: "D",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["jersey", "drill", "fast", "aggressive", "syncopated"],
  },
  {
    id: "la-mano",
    display: "La Mano 1.9-inspired",
    artistName: "La Mano 1.9",
    region: "fr",
    genre: "Dark Drill",
    caption:
      "Dark drill with 808 slides, street-level atmosphere, aggressive drums, minor key piano, menacing mood, hard-hitting kick, sharp snare, cold production, raw vocal delivery, dark reverb, sparse arrangement, deep bass weight, gritty textures",
    bpm: 142,
    key: "Bb",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Rapper",
    tags: ["drill", "dark", "street", "aggressive", "808"],
  },
  {
    id: "zamdane",
    display: "Zamdane-inspired",
    artistName: "Zamdane",
    region: "fr",
    genre: "Emotional Rap",
    caption:
      "Emotional French rap with lo-fi textures, warm piano, gentle guitar, introspective mood, heartfelt vocal delivery, melancholic atmosphere, soft trap drums, deep bass, reflective arrangement, lo-fi warmth, intimate production, nostalgic undertones, raw emotion",
    bpm: 100,
    key: "E",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["emotional", "lo-fi", "piano", "introspective", "warm"],
  },
  {
    id: "soolking",
    display: "Soolking-inspired",
    artistName: "Soolking",
    region: "fr",
    genre: "Raï Afro-Pop",
    caption:
      "Raï-influenced afro-pop with oriental melodic scales, rhythmic danceable beat, warm strings, synthesizer accents, melismatic vocal delivery, catchy hook, vibrant energy, fusion production, North African melody, modern trap elements, celebratory atmosphere, bouncy rhythm",
    bpm: 105,
    key: "A",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer",
    tags: ["raï", "afro", "pop", "oriental", "danceable"],
  },
  {
    id: "vegedream",
    display: "Vegedream-inspired",
    artistName: "Vegedream",
    region: "fr",
    genre: "Afro-Pop",
    caption:
      "Afro-pop with unifying anthemic chorus, summer energy, percussive groove, bright production, danceable rhythm, uplifting vibe, warm bassline, catchy hook, party atmosphere, crowd-ready arrangement, polished vocal mixing, vibrant instrumentation, feel-good energy",
    bpm: 108,
    key: "G",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "fr",
    vocalStyle: "Singer-Rapper",
    tags: ["afro", "pop", "summer", "anthemic", "party"],
  },
] as const;

// ---------------------------------------------------------------------------
// US / English — 50 artists
// ---------------------------------------------------------------------------

const US_PRESETS: readonly ArtistPreset[] = [
  {
    id: "sza",
    display: "SZA-inspired",
    artistName: "SZA",
    region: "us",
    genre: "Alternative R&B",
    caption:
      "Alternative R&B with complex neo-soul harmonies, sparse minimalist percussion, warm sub bass, intimate female vocal space, atmospheric pads, lush chord voicings, laid-back groove, dreamy textures, raw emotional vulnerability, lo-fi warmth, introspective mood, spacious arrangement",
    bpm: 72,
    key: "Db",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["alt-r&b", "neo-soul", "atmospheric", "intimate", "minimal"],
  },
  {
    id: "brent-faiyaz",
    display: "Brent Faiyaz-inspired",
    artistName: "Brent Faiyaz",
    region: "us",
    genre: "Dark R&B",
    caption:
      "Dark sensual R&B with warm sub bass, slow grooving tempo, intimate vocal delivery, nocturnal atmosphere, moody chord progressions, sparse production, toxic romantic energy, velvet vocal texture, minor key tension, atmospheric pads, deep bass weight, late-night vibe",
    bpm: 78,
    key: "Ab",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["dark", "r&b", "sensual", "nocturnal", "intimate"],
  },
  {
    id: "the-weeknd",
    display: "The Weeknd-inspired",
    artistName: "The Weeknd",
    region: "us",
    genre: "Dark Pop R&B",
    caption:
      "Dark cinematic pop-R&B with synthwave influences, deep pulsing sub bass, atmospheric pads, reverb-drenched vocals, dramatic arrangement, dark romantic mood, minor key, glossy production, cinematic tension and release, 80s-inspired synths, powerful bass drops, moody textures",
    bpm: 100,
    key: "F#",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["dark", "pop", "r&b", "cinematic", "synthwave"],
  },
  {
    id: "tyla",
    display: "Tyla-inspired",
    artistName: "Tyla",
    region: "us",
    genre: "Afro-R&B Amapiano",
    caption:
      "Afro-R&B amapiano fusion with log drums, warm rhythmic bass, shaker percussion, danceable groove, bright vocal production, catchy hook, South African-influenced rhythm, playful energy, smooth vocal delivery, party-ready arrangement, bouncy bassline, polished pop mixing",
    bpm: 112,
    key: "C",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["afro", "r&b", "amapiano", "danceable", "catchy"],
  },
  {
    id: "tems",
    display: "Tems-inspired",
    artistName: "Tems",
    region: "us",
    genre: "Afro-R&B",
    caption:
      "Afro-R&B with organic warm bass, spacious atmospheric pads, ethereal female vocals, afloat textures, minimalist percussion, meditative mood, rich harmonic depth, Nigerian-influenced melodies, dreamy arrangement, deep emotional resonance, wide stereo field, spiritual undertones",
    bpm: 85,
    key: "G",
    scale: "Major",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["afro", "r&b", "ethereal", "organic", "spacious"],
  },
  {
    id: "kehlani",
    display: "Kehlani-inspired",
    artistName: "Kehlani",
    region: "us",
    genre: "Modern R&B",
    caption:
      "Modern R&B with smooth gentle drums, rich vocal harmonies, warm bass, lush chord progressions, polished production, emotional delivery, soulful undertones, catchy melodic hook, clean mix, laid-back groove, intimate vocal layering, feel-good energy",
    bpm: 88,
    key: "Bb",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["modern", "r&b", "smooth", "harmonies", "soulful"],
  },
  {
    id: "giveon",
    display: "GIVĒON-inspired",
    artistName: "GIVĒON",
    region: "us",
    genre: "Soul R&B",
    caption:
      "Deep soulful R&B with warm piano, velvet baritone vocal, warm sub bass, spacious vocal atmosphere, minimal arrangement, intimate recording, emotional depth, minor key, slow-building arrangement, lush harmonies, soulful chord progressions, stripped-back production",
    bpm: 75,
    key: "Eb",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["soul", "r&b", "piano", "intimate", "deep"],
  },
  {
    id: "leon-thomas",
    display: "Leon Thomas-inspired",
    artistName: "Leon Thomas",
    region: "us",
    genre: "Neo-Soul R&B",
    caption:
      "Neo-soul modern R&B with jazzy chord voicings, organic live-feeling drums, warm Rhodes keys, intricate harmony, smooth vocal runs, laid-back pocket, sophisticated arrangement, warm bass, vintage warmth, soulful delivery, musical richness, expressive dynamics",
    bpm: 85,
    key: "D",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["neo-soul", "jazz", "r&b", "organic", "sophisticated"],
  },
  {
    id: "victoria-monet",
    display: "Victoria Monét-inspired",
    artistName: "Victoria Monét",
    region: "us",
    genre: "R&B Funk",
    caption:
      "R&B-funk with groovy syncopated bassline, sophisticated arrangements, funky guitar stabs, tight drum pocket, bright horns, polished production, powerful vocal delivery, danceable groove, retro-modern fusion, ear candy details, dynamic buildup, feel-good energy",
    bpm: 108,
    key: "F",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["r&b", "funk", "groovy", "sophisticated", "polished"],
  },
  {
    id: "summer-walker",
    display: "Summer Walker-inspired",
    artistName: "Summer Walker",
    region: "us",
    genre: "Nocturnal R&B",
    caption:
      "Nocturnal intimate R&B with gentle guitar, soft 808, warm bass, intimate whispery vocals, moody atmosphere, late-night energy, melancholic chord progressions, lo-fi textures, stripped-back production, emotional vulnerability, smooth transitions, personal confession vibe",
    bpm: 80,
    key: "B",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["nocturnal", "r&b", "intimate", "moody", "guitar"],
  },
  {
    id: "coco-jones",
    display: "Coco Jones-inspired",
    artistName: "Coco Jones",
    region: "us",
    genre: "Vocal R&B",
    caption:
      "Vocal powerhouse modern R&B with rich instrumentation, soulful delivery, lush arrangement, dynamic vocal performance, polished production, warm bass, powerful chorus, gospel-influenced runs, emotional intensity, clean mix, melodic hooks, vibrant energy",
    bpm: 90,
    key: "C",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["vocal", "r&b", "soul", "powerful", "polished"],
  },
  {
    id: "kali-uchis",
    display: "Kali Uchis-inspired",
    artistName: "Kali Uchis",
    region: "us",
    genre: "R&B Latin Soul",
    caption:
      "Latin-influenced R&B soul with vintage synth textures, warm grooving bass, dreamy atmosphere, sensual vocal delivery, retro-modern fusion, lush production, romantic mood, bouncy rhythm, colorful instrumentation, silky vocal layers, playful energy, bilingual charm",
    bpm: 95,
    key: "A",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["latin", "r&b", "vintage", "sensual", "dreamy"],
  },
  {
    id: "ravyn-lenae",
    display: "Ravyn Lenae-inspired",
    artistName: "Ravyn Lenae",
    region: "us",
    genre: "Alt Pop R&B",
    caption:
      "Alt-pop R&B with Y2K-inspired synth textures, airy ethereal vocals, light shimmering production, dreamy pads, gentle groove, delicate percussion, nostalgic warmth, floaty arrangement, intimate recording, soft dynamics, sparkle accents, nostalgic undertones",
    bpm: 92,
    key: "E",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["alt-pop", "r&b", "y2k", "airy", "dreamy"],
  },
  {
    id: "steve-lacy",
    display: "Steve Lacy-inspired",
    artistName: "Steve Lacy",
    region: "us",
    genre: "Indie R&B",
    caption:
      "Indie R&B with funky rhythmic guitar, round warm bass, minimalist drums, lo-fi textures, playful vocal delivery, quirky arrangements, analog warmth, syncopated groove, raw production, catchy hook, guitar-driven melody, indie-pop crossover, experimental touches",
    bpm: 105,
    key: "G",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["indie", "r&b", "funky", "guitar", "lo-fi"],
  },
  {
    id: "daniel-caesar",
    display: "Daniel Caesar-inspired",
    artistName: "Daniel Caesar",
    region: "us",
    genre: "Neo-Soul",
    caption:
      "Neo-soul with rich harmonic depth, warm guitar, tender piano, lush vocal harmonies, intimate recording, spiritual atmosphere, gospel-influenced chords, laid-back groove, smooth bass, stripped-back arrangement, emotional vulnerability, warm analog textures, contemplative mood",
    bpm: 78,
    key: "Db",
    scale: "Major",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["neo-soul", "guitar", "piano", "intimate", "spiritual"],
  },
  {
    id: "6lack",
    display: "6LACK-inspired",
    artistName: "6LACK",
    region: "us",
    genre: "Dark R&B Trap",
    caption:
      "Dark trap-R&B with cold synth textures, deep 808, moody atmospheric pads, minimalist production, introspective vocal delivery, dark minor key, sparse arrangement, low-end weight, chill yet tense energy, emotional depth, smooth low-key flow, nighttime vibe",
    bpm: 95,
    key: "F",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer-Rapper",
    tags: ["dark", "r&b", "trap", "minimal", "moody"],
  },
  {
    id: "jhene-aiko",
    display: "Jhené Aiko-inspired",
    artistName: "Jhené Aiko",
    region: "us",
    genre: "Dreamy R&B",
    caption:
      "Dreamy ethereal R&B with meditative pads, gentle guitar, whispery vocals, spacious atmospheric production, ambient textures, spiritual undertones, laid-back tempo, warm sub bass, contemplative mood, zen-like arrangement, soft dynamics, healing energy, floating sensation",
    bpm: 70,
    key: "A",
    scale: "Major",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["dreamy", "r&b", "meditative", "ethereal", "spiritual"],
  },
  {
    id: "doja-cat",
    display: "Doja Cat-inspired",
    artistName: "Doja Cat",
    region: "us",
    genre: "Pop R&B Hybrid",
    caption:
      "Pop-R&B-hip-hop hybrid with funky bassline, playful unpredictable arrangements, bright synths, catchy hooks, versatile vocal delivery, genre-blending production, high energy, danceable groove, bold attitude, polished mixing, ear candy moments, fun playful vibe",
    bpm: 115,
    key: "Eb",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer-Rapper",
    tags: ["pop", "r&b", "funky", "playful", "hybrid"],
  },
  {
    id: "doechii",
    display: "Doechii-inspired",
    artistName: "Doechii",
    region: "us",
    genre: "Experimental Rap",
    caption:
      "Experimental hip-hop with funky basslines, unexpected rhythm changes, bold vocal delivery, genre-blending production, creative arrangements, energetic and playful, eclectic sound design, dynamic contrasts, confident attitude, hard-hitting drums, creative sampling, unique textures",
    bpm: 125,
    key: "D",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["experimental", "rap", "funky", "bold", "creative"],
  },
  {
    id: "megan-thee-stallion",
    display: "Megan Thee Stallion-inspired",
    artistName: "Megan Thee Stallion",
    region: "us",
    genre: "Southern Rap",
    caption:
      "Southern rap with massive 808 bass, aggressive drums, hard-hitting kick, confident powerful vocal delivery, high-energy arrangement, bold attitude, bouncy pocket, sharp snare, assertive rhythm, club-ready energy, big chorus moments, empowering vibe, raw intensity",
    bpm: 130,
    key: "G",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["southern", "rap", "aggressive", "808", "bold"],
  },
  {
    id: "cardi-b",
    display: "Cardi B-inspired",
    artistName: "Cardi B",
    region: "us",
    genre: "Mainstream Rap",
    caption:
      "Mainstream hip-hop with heavy bass, club-ready percussion, punchy kick, bright synth stabs, high energy, bold vocal delivery, catchy hook, party atmosphere, hard-hitting drums, bouncy arrangement, confident attitude, radio-friendly production, danceable rhythm",
    bpm: 128,
    key: "F#",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["mainstream", "rap", "club", "bold", "catchy"],
  },
  {
    id: "nicki-minaj",
    display: "Nicki Minaj-inspired",
    artistName: "Nicki Minaj",
    region: "us",
    genre: "Pop Rap",
    caption:
      "Theatrical pop-rap with colorful synth textures, bold bass, dramatic arrangements, versatile vocal performance, playful attitude, catchy melodic hooks, hard-hitting drums, high energy, show-stopping moments, dynamic switches, polished pop production, larger-than-life vibe",
    bpm: 120,
    key: "C",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["pop", "rap", "theatrical", "colorful", "bold"],
  },
  {
    id: "kendrick-lamar",
    display: "Kendrick Lamar-inspired",
    artistName: "Kendrick Lamar",
    region: "us",
    genre: "Experimental Hip-Hop",
    caption:
      "Experimental hip-hop with jazz-funk influences, evolving arrangements, live-feeling instrumentation, deep lyrical content, complex rhythmic patterns, atmospheric textures, dynamic shifts, soulful samples, progressive structure, conceptual depth, raw authenticity, musical richness",
    bpm: 90,
    key: "Bb",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 240,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["experimental", "hip-hop", "jazz", "complex", "conceptual"],
  },
  {
    id: "j-cole",
    display: "J. Cole-inspired",
    artistName: "J. Cole",
    region: "us",
    genre: "Boom Bap Modern",
    caption:
      "Modern boom-bap with soulful samples, organic bass, warm Rhodes chords, introspective vocal delivery, laid-back pocket, storytelling arrangement, smooth transitions, soul-influenced harmonies, nostalgic warmth, polished yet authentic, reflective mood, musical depth",
    bpm: 88,
    key: "E",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["boom-bap", "soul", "introspective", "organic", "smooth"],
  },
  {
    id: "drake",
    display: "Drake-inspired",
    artistName: "Drake",
    region: "us",
    genre: "Rap R&B",
    caption:
      "Rap-R&B fusion with atmospheric pads, deep 808, melodic vocal delivery, catchy hook, moody undertones, polished production, smooth transitions, emotional range, bouncy rhythm, wide stereo field, club-ready yet introspective, versatile arrangement, mainstream appeal",
    bpm: 100,
    key: "A",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "en",
    vocalStyle: "Singer-Rapper",
    tags: ["rap", "r&b", "atmospheric", "melodic", "polished"],
  },
  {
    id: "future",
    display: "Future-inspired",
    artistName: "Future",
    region: "us",
    genre: "Dark Trap",
    caption:
      "Dark trap with massive sub bass, minimalist dark synths, hypnotic melodic motif, heavy 808, auto-tuned vocal delivery, repetitive hooks, sparse arrangement, dark nocturnal atmosphere, drug-induced haze, cold minor key, raw emotion, Atlanta sound, deep bass weight",
    bpm: 140,
    key: "G",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer-Rapper",
    tags: ["dark", "trap", "minimalist", "808", "hypnotic"],
  },
  {
    id: "metro-boomin",
    display: "Metro Boomin-inspired",
    artistName: "Metro Boomin",
    region: "us",
    genre: "Cinematic Trap",
    caption:
      "Cinematic trap production with dark bells, massive 808, cinematic buildups, dark synths, dramatic arrangements, atmospheric tension, orchestral elements, hard-hitting drums, tag drops, suspenseful atmosphere, epic drops, polished mix, signature dark melodies, powerful bass",
    bpm: 140,
    key: "D",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["cinematic", "trap", "dark", "bells", "dramatic"],
  },
  {
    id: "travis-scott",
    display: "Travis Scott-inspired",
    artistName: "Travis Scott",
    region: "us",
    genre: "Psychedelic Trap",
    caption:
      "Psychedelic trap with spatial synthesizers, massive distorted bass, cosmic textures, trippy effects, dark atmospheric pads, reverb-drenched vocals, heavy 808, stadium energy, immersive sound design, psychedelic transitions, wide stereo, experimental production, psychedelic energy",
    bpm: 135,
    key: "F#",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["psychedelic", "trap", "cosmic", "spatial", "experimental"],
  },
  {
    id: "don-toliver",
    display: "Don Toliver-inspired",
    artistName: "Don Toliver",
    region: "us",
    genre: "Psychedelic Trap R&B",
    caption:
      "Psychedelic trap-R&B with floating synth melodies, deep 808, dreamy atmospheric textures, auto-tuned melodic vocals, hypnotic arrangement, spacey production, smooth transitions, ethereal pads, melodic hooks, cosmic undertones, laid-back pocket, wide reverb, hypnotic groove",
    bpm: 130,
    key: "Bb",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer-Rapper",
    tags: ["psychedelic", "trap", "r&b", "dreamy", "hypnotic"],
  },
  {
    id: "playboi-carti",
    display: "Playboi Carti-inspired",
    artistName: "Playboi Carti",
    region: "us",
    genre: "Rage Trap",
    caption:
      "Rage minimalist trap with saturated distorted synths, aggressive drums, punk energy, high-pitched vocal ad-libs, minimal melody, hard-hitting 808, raw intensity, mosh-pit energy, stripped-back arrangement, chaotic moments, bold production choices, underground feel",
    bpm: 150,
    key: "E",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["rage", "trap", "minimal", "aggressive", "punk"],
  },
  {
    id: "yeat",
    display: "Yeat-inspired",
    artistName: "Yeat",
    region: "us",
    genre: "Rage Trap",
    caption:
      "Rage trap with massive distorted 808, synthy aggressive textures, high energy drops, unique vocal delivery, experimental sound design, dark atmospheric undertones, bouncy rhythm, hard-hitting kick, distorted bass, futuristic production, chaotic but catchy, bold arrangements",
    bpm: 145,
    key: "A",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["rage", "trap", "distorted", "futuristic", "aggressive"],
  },
  {
    id: "lil-uzi-vert",
    display: "Lil Uzi Vert-inspired",
    artistName: "Lil Uzi Vert",
    region: "us",
    genre: "Melodic Trap",
    caption:
      "Melodic trap with futuristic synth textures, high-energy delivery, pop-influenced hooks, colorful sound design, bouncing 808, bright pads, catchy melodies, punk-rock energy, electric guitar accents, dynamic arrangement, fun playful vibe, anime-inspired aesthetics",
    bpm: 140,
    key: "C",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["melodic", "trap", "futuristic", "pop", "energetic"],
  },
  {
    id: "gunna",
    display: "Gunna-inspired",
    artistName: "Gunna",
    region: "us",
    genre: "Luxury Trap",
    caption:
      "Luxury trap with smooth rounded 808, precise hi-hat patterns, polished sleek production, laid-back flow, rich melodic textures, melodic vocal delivery, confident energy, clean mix, melodic ad-libs, warm bass, luxurious atmosphere, smooth transitions, high-end production",
    bpm: 130,
    key: "F",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer-Rapper",
    tags: ["luxury", "trap", "smooth", "polished", "melodic"],
  },
  {
    id: "lil-baby",
    display: "Lil Baby-inspired",
    artistName: "Lil Baby",
    region: "us",
    genre: "Modern Trap",
    caption:
      "Modern Atlanta trap with deep 808, minimal piano or synth, tight trap drums, emotional vocal delivery, catchy hook, smooth flow, minor key, warm bass, polished production, hard-hitting kick, hi-hat rolls, confident energy, street-smart arrangement, authentic vibe",
    bpm: 138,
    key: "Bb",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["trap", "modern", "atlanta", "emotional", "polished"],
  },
  {
    id: "21-savage",
    display: "21 Savage-inspired",
    artistName: "21 Savage",
    region: "us",
    genre: "Dark Trap",
    caption:
      "Dark minimalist trap with deep spacious 808, cold atmospheric textures, dry tight drums, menacing minor key, sparse arrangement, ominous melodies, calm menacing vocal delivery, minimal melody, heavy bass weight, dark energy, sharp snare, cold production, underground feel",
    bpm: 140,
    key: "G",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["dark", "trap", "minimal", "cold", "menacing"],
  },
  {
    id: "tyler-the-creator",
    display: "Tyler, The Creator-inspired",
    artistName: "Tyler, The Creator",
    region: "us",
    genre: "Alt Hip-Hop",
    caption:
      "Alternative hip-hop with jazz-funk influences, colorful arrangements, live-feeling instrumentation, soul samples, creative production, bold sonic palette, nostalgic warmth, playful experimentation, brass stabs, Rhodes chords, progressive structure, artistic depth, genre-bending",
    bpm: 95,
    key: "D",
    scale: "Major",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["alt", "hip-hop", "jazz", "funk", "creative"],
  },
  {
    id: "baby-keem",
    display: "Baby Keem-inspired",
    artistName: "Baby Keem",
    region: "us",
    genre: "Experimental Rap",
    caption:
      "Experimental rap with off-kilter drum patterns, aggressive synths, unpredictable arrangements, raw vocal delivery, dynamic shifts, unconventional structures, bold sound design, hard-hitting bass, creative production, punk energy, emotional range, unique cadence, artistic choices",
    bpm: 130,
    key: "C#",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["experimental", "rap", "aggressive", "creative", "unpredictable"],
  },
  {
    id: "central-cee",
    display: "Central Cee-inspired",
    artistName: "Central Cee",
    region: "us",
    genre: "UK Drill Crossover",
    caption:
      "UK-NY drill crossover with sliding 808 bass, dark piano melody, rapid hi-hats, cold aggressive atmosphere, sharp snare, bouncy pocket, catchy melodic hook, street-level energy, minor key tension, slick vocal delivery, modern drill drums, UK-influenced rhythm, polished mix",
    bpm: 142,
    key: "E",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["drill", "uk", "dark", "sliding", "melodic"],
  },
  {
    id: "asap-rocky",
    display: "A$AP Rocky-inspired",
    artistName: "A$AP Rocky",
    region: "us",
    genre: "Psychedelic Rap",
    caption:
      "Psychedelic hip-hop with soul samples, deep atmospheric bass, trippy textures, dark moody atmosphere, layered production, creative sampling, fashion-forward sound, experimental arrangements, reverb-drenched elements, fashion-meets-music aesthetic, artistic depth, hypnotic loops",
    bpm: 100,
    key: "Ab",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Rapper",
    tags: ["psychedelic", "rap", "soul", "atmospheric", "creative"],
  },
  {
    id: "ty-dolla-sign",
    display: "Ty Dolla $ign-inspired",
    artistName: "Ty Dolla $ign",
    region: "us",
    genre: "R&B Hip-Hop",
    caption:
      "R&B-hip-hop fusion with warm bass, rich vocal harmonies, melodic hooks, versatile delivery, catchy chorus, smooth production, multi-layered vocals, groovy rhythm, warm textures, feel-good energy, polished mix, radio-friendly, melodic ad-libs, collaborative energy",
    bpm: 100,
    key: "F",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer-Rapper",
    tags: ["r&b", "hip-hop", "harmonies", "smooth", "melodic"],
  },
  {
    id: "chris-brown",
    display: "Chris Brown-inspired",
    artistName: "Chris Brown",
    region: "us",
    genre: "R&B Dance",
    caption:
      "R&B-dance fusion with punchy drums, funky bassline, upbeat energy, smooth vocal delivery, catchy melodic hook, polished pop production, danceable groove, dynamic arrangement, high-energy chorus, club-ready rhythm, vibrant instrumentation, party atmosphere, polished mix",
    bpm: 115,
    key: "G",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["r&b", "dance", "funky", "upbeat", "catchy"],
  },
  {
    id: "justin-bieber",
    display: "Justin Bieber-inspired",
    artistName: "Justin Bieber",
    region: "us",
    genre: "Pop R&B",
    caption:
      "Pop-R&B with modern drum production, bright guitar, catchy melodic hooks, smooth vocal delivery, polished mainstream production, warm bass, radio-ready arrangement, feel-good energy, clean mix, dynamic buildup, singable chorus, youthful vibe, crossover appeal",
    bpm: 105,
    key: "A",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["pop", "r&b", "catchy", "polished", "mainstream"],
  },
  {
    id: "bruno-mars",
    display: "Bruno Mars-inspired",
    artistName: "Bruno Mars",
    region: "us",
    genre: "Funk R&B Pop",
    caption:
      "Funk-R&B-pop with live-feeling drums, groovy bassline, bright brass stabs, retro-modern fusion, high-energy arrangement, infectious groove, dynamic vocal performance, feel-good party energy, funk guitar, polished production, crowd-pleasing hook, vintage warmth, danceable rhythm",
    bpm: 110,
    key: "Eb",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["funk", "r&b", "pop", "groovy", "retro"],
  },
  {
    id: "ariana-grande",
    display: "Ariana Grande-inspired",
    artistName: "Ariana Grande",
    region: "us",
    genre: "Pop R&B",
    caption:
      "Pop-R&B with trap-soul influences, bright shimmering synths, powerful vocal performance, tight production, catchy hooks, trap hi-hats, warm bass, glossy polished mix, high-energy chorus, dynamic range, ear candy details, radio-ready, pop perfection, vocal agility",
    bpm: 108,
    key: "C",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["pop", "r&b", "trap-soul", "bright", "polished"],
  },
  {
    id: "rihanna",
    display: "Rihanna-inspired",
    artistName: "Rihanna",
    region: "us",
    genre: "Pop R&B Dancehall",
    caption:
      "Pop-R&B-dancehall fusion with Caribbean-influenced percussion, deep bass, catchy hook, bold vocal delivery, danceable groove, island rhythm, polished production, high-energy arrangement, empowering anthem, club-ready beat, vibrant instrumentation, confident energy, crossover appeal",
    bpm: 100,
    key: "D",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["pop", "r&b", "dancehall", "bold", "danceable"],
  },
  {
    id: "beyonce",
    display: "Beyoncé-inspired",
    artistName: "Beyoncé",
    region: "us",
    genre: "R&B Pop",
    caption:
      "R&B-pop with gospel-influenced vocal power, soul arrangements, polished powerful production, dynamic vocal performance, anthemic chorus, rich harmonies, high-energy arrangement, empowering energy, sophisticated instrumentation, stadium-ready, live-feeling drums, cultural impact",
    bpm: 105,
    key: "Bb",
    scale: "Major",
    timeSignature: "4/4",
    duration: 200,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["r&b", "pop", "gospel", "powerful", "anthemic"],
  },
  {
    id: "tate-mcrae",
    display: "Tate McRae-inspired",
    artistName: "Tate McRae",
    region: "us",
    genre: "Pop R&B",
    caption:
      "Danceable pop-R&B with punchy drums, catchy immediate hooks, modern production, high-energy rhythm, dynamic arrangement, confident vocal delivery, bright synths, polished mix, club-ready beat, ear candy details, radio-friendly, youthful energy, memorable chorus",
    bpm: 118,
    key: "F",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["pop", "r&b", "danceable", "catchy", "modern"],
  },
  {
    id: "pinkpantheress",
    display: "PinkPantheress-inspired",
    artistName: "PinkPantheress",
    region: "us",
    genre: "UK Garage Pop",
    caption:
      "UK garage 2-step pop with breakbeats, Y2K-inspired textures, short catchy hooks, soft vocal delivery, nostalgic warmth, bouncy bass, syncopated drums, dreamy atmosphere, lo-fi charm, bubblegum pop energy, light percussion, earworm melody, bedroom pop aesthetic",
    bpm: 130,
    key: "G",
    scale: "Major",
    timeSignature: "4/4",
    duration: 150,
    vocalLanguage: "en",
    vocalStyle: "Singer",
    tags: ["uk-garage", "pop", "y2k", "catchy", "nostalgic"],
  },
  {
    id: "flo",
    display: "FLO-inspired",
    artistName: "FLO",
    region: "us",
    genre: "Y2K R&B",
    caption:
      "Y2K-inspired R&B with rich vocal harmonies, modern drum production, nostalgic warmth, catchy hooks, polished girl-group energy, smooth vocal layering, feel-good groove, polished production, bright arrangement, retro-modern fusion, singable chorus, joyful energy",
    bpm: 100,
    key: "Eb",
    scale: "Major",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Choir",
    tags: ["y2k", "r&b", "harmonies", "nostalgic", "polished"],
  },
  {
    id: "tory-lanez",
    display: "Tory Lanez-inspired",
    artistName: "Tory Lanez",
    region: "us",
    genre: "R&B Hip-Hop",
    caption:
      "R&B-hip-hop fusion with soulful vocal melodies, trap-influenced drums, warm bass, versatile delivery, melodic hooks, smooth arrangements, emotional depth, polished production, dynamic range, sing-rap hybrid, catchy chorus, introspective moments, genre-blending creativity",
    bpm: 105,
    key: "Bb",
    scale: "Minor",
    timeSignature: "4/4",
    duration: 180,
    vocalLanguage: "en",
    vocalStyle: "Singer-Rapper",
    tags: ["r&b", "hip-hop", "soul", "melodic", "versatile"],
  },
] as const;

// ---------------------------------------------------------------------------
// Combined catalog
// ---------------------------------------------------------------------------

export const ALL_ARTIST_PRESETS: readonly ArtistPreset[] = [...FR_PRESETS, ...US_PRESETS];

/** French presets only */
export const FR_ARTIST_PRESETS: readonly ArtistPreset[] = FR_PRESETS;

/** US presets only */
export const US_ARTIST_PRESETS: readonly ArtistPreset[] = US_PRESETS;

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/** Find a preset by id (slug) */
export function findArtistPresetById(id: string): ArtistPreset | undefined {
  return ALL_ARTIST_PRESETS.find((p) => p.id === id);
}

/** Find a preset by display name (case-insensitive) */
export function findArtistPresetByDisplay(display: string): ArtistPreset | undefined {
  const lower = display.trim().toLowerCase();
  return ALL_ARTIST_PRESETS.find((p) => p.display.toLowerCase() === lower);
}

/** Filter presets by region */
export function getArtistPresetsByRegion(region: ArtistRegion): readonly ArtistPreset[] {
  return region === "fr" ? FR_ARTIST_PRESETS : US_ARTIST_PRESETS;
}

/** Search presets by tag or name (case-insensitive) */
export function searchArtistPresets(query: string): readonly ArtistPreset[] {
  const lower = query.trim().toLowerCase();
  if (!lower) return ALL_ARTIST_PRESETS;
  return ALL_ARTIST_PRESETS.filter(
    (p) =>
      p.artistName.toLowerCase().includes(lower) ||
      p.genre.toLowerCase().includes(lower) ||
      p.tags.some((t) => t.includes(lower)),
  );
}

/** Build the ACE-Step caption from a preset (ready for prompt injection) */
export function buildArtistPresetCaption(preset: ArtistPreset): string {
  return preset.caption;
}
