/** Building blocks for infinite ACE prose prompts (Suno-style opener + production tail). */

export type AceProseMode = "song" | "beat";

export const ACE_PROSE_MOODS = [
  "Dark",
  "Bright",
  "Cold",
  "Warm",
  "Raw",
  "Glossy",
  "Cinematic",
  "Ethereal",
  "Aggressive",
  "Melancholic",
  "Euphoric",
  "Hypnotic",
  "Intimate",
  "Epic",
  "Nocturnal",
  "Dusty",
  "Polished",
  "Haunting",
  "Playful",
  "Brooding",
  "Dreamy",
  "Tense",
  "Soulful",
  "Rebellious",
  "Nostalgic",
  "Futuristic",
  "Organic",
  "Minimal",
  "Lush",
  "Gritty",
  "Seductive",
  "Defiant",
  "Fragile",
  "Triumphant",
  "Anxious",
  "Serene",
  "Bittersweet",
  "Volatile",
  "Moody",
  "Radiant",
] as const;

export const ACE_PROSE_MOODS_B = [
  "emotional",
  "atmospheric",
  "hard-hitting",
  "hook-first",
  "underground",
  "radio-ready",
  "cathartic",
  "cinematic",
  "introspective",
  "anthemic",
  "experimental",
  "dancefloor",
  "street-level",
  "luxury",
  "raw",
  "sparse",
  "layered",
  "driving",
  "floating",
  "toxic",
  "hopeful",
  "vengeful",
  "confessional",
  "rebellious",
  "sun-drenched",
  "winter-cold",
  "neon-lit",
  "warehouse",
  "coastal",
  "suburban",
] as const;

export const ACE_PROSE_GENRES_SONG = [
  "trap",
  "melodic trap",
  "dark trap",
  "UK drill",
  "NY drill",
  "melodic drill",
  "boom bap",
  "trap soul",
  "contemporary R&B",
  "neo soul",
  "afrobeats",
  "amapiano",
  "house pop",
  "UK garage",
  "reggaeton",
  "phonk",
  "cloud rap",
  "emo rap",
  "hyperpop",
  "pluggnb",
  "rage rap",
  "jersey club",
  "lo-fi hip-hop",
  "cinematic trap",
  "afro house",
  "dancehall",
  "latin trap",
  "French drill",
  "sample drill",
  "gospel trap",
  "synthwave pop",
  "future bass",
  "drum and bass",
  "deep house",
  "indie pop",
  "pop punk",
  "alternative rock",
  "metalcore",
  "blues rock",
  "jazz fusion",
  "dark R&B",
  "bedroom pop",
  "K-pop ballad",
  "dance pop",
  "vapor soul",
  "orchestral pop",
  "country pop",
  "bachata pop",
  "arabic pop",
  "amapiano vocal",
  "afro R&B",
  "electro pop",
  "shoegaze pop",
  "folk pop",
  "gospel pop",
  "trap metal",
  "drill soul",
  "ambient pop",
  "city pop",
] as const;

export const ACE_PROSE_GENRES_BEAT = [
  "trap",
  "melodic trap",
  "dark trap",
  "UK drill",
  "NY drill",
  "melodic drill",
  "boom bap",
  "trap soul",
  "R&B",
  "neo soul",
  "afrobeats",
  "amapiano",
  "house",
  "UK garage",
  "reggaeton",
  "phonk",
  "cloud rap",
  "jersey club",
  "lo-fi hip-hop",
  "cinematic trap",
  "afro house",
  "dancehall",
  "latin trap",
  "French drill",
  "sample drill",
  "gospel trap",
  "synthwave",
  "future bass",
  "drum and bass",
  "deep house",
  "pop-trap",
  "pluggnb",
  "rage trap",
  "emo trap",
  "orchestral trap",
  "acoustic trap",
  "techno trap",
  "breakbeat",
  "electro swing",
  "French touch house",
  "ambient drill",
  "phonk drift",
  "baile funk",
  "highlife",
  "rai trap",
  "middle eastern trap",
  "g-funk",
  "jazz fusion trap",
  "baroque trap",
  "western trap",
] as const;

export const ACE_PROSE_THEMES = [
  "betrayal and loneliness",
  "the solo drive home after the party",
  "quitting a toxic job with no backup plan",
  "missing someone living in another timezone",
  "a first kiss on a Brooklyn rooftop",
  "street ambition after public failure",
  "ghosting after three perfect dates",
  "surviving exam week on cold coffee",
  "a van road trip along the Atlantic coast",
  "scoring the winning penalty in extra time",
  "your cat walking across the MIDI keyboard",
  "hearing your own song in a stranger's headphones",
  "a rooftop proposal under city lights",
  "burnout that ends with quitting on Monday",
  "two best friends drifting apart after college",
  "a summer terrace that never wants to end",
  "revenge after being underestimated",
  "forgiveness after a brutal argument",
  "a long-distance love that still feels close",
  "finding peace after years of noise",
  "a warehouse party at 4am",
  "childhood memories in grandma's kitchen",
  "a breakup walk through neon rain",
  "starting over in a new apartment",
  "the anxiety before sending an important DM",
  "your first BeatStars sale at twenty-nine dollars",
  "a festival sunset that changes everything",
  "a gym session that saves your mental health",
  "a late studio night when the beat finally clicks",
  "a Zoom meeting that should have been an email",
  "a heartbreak playlist on shuffle",
  "falling for your best friend's honesty",
  "a debt-free morning after years of stress",
  "a protest march turned into hope",
  "a motorcycle ride through desert heat",
  "a snowy cabin with no phone signal",
  "a crush in the concert queue",
  "a father teaching you to drive at dusk",
  "a mother's voice on a crackly voicemail",
  "a wedding dance that feels like floating",
  "a funeral song that celebrates a life",
  "a graduation night you'll never forget",
  "a locker-room speech before the final",
  "a midnight swim that resets your mind",
  "a stolen hoodie that still smells like them",
  "a bar fight apology at closing time",
  "a small-town dream of making it out",
  "a luxury hotel room with empty champagne",
  "a backseat confession during a thunderstorm",
  "a prayer whispered before a risky leap",
  "a protest love story in the crowd",
  "a stolen glance across a crowded club",
  "a diary entry you almost deleted",
  "a voicemail you replay too often",
  "a passport stamp and a promise kept",
  "a kitchen dance at 2am in socks",
  "a parking-lot freestyle that goes viral",
  "a mentor who believed before you did",
  "a rival who pushed you to be sharper",
  "a lie that finally comes out",
  "a truth told too late",
  "a second chance you didn't deserve",
  "a mirror talk before a big interview",
  "a panic attack in the supermarket aisle",
  "a therapy breakthrough on a Tuesday",
  "a sober anniversary worth celebrating",
  "a relapse night you barely survived",
  "a sibling rivalry that becomes respect",
  "a neighborhood block party after the storm",
  "a power outage that sparks romance",
  "a blackout city under full moon",
  "a hitchhiker story with no ending",
  "a train platform goodbye",
  "a delayed flight that changes your path",
  "a suitcase packed in silence",
  "a tattoo you got on impulse",
  "a scar with a story behind it",
  "a lighthouse beam in coastal fog",
  "a bonfire confession with old friends",
  "a hiking trail that clears your head",
  "a mountain summit at golden hour",
  "a desert highway with no destination",
  "a Paris metro ride at rush hour",
  "a Lagos market buzzing with color",
  "a Seoul night market food crawl",
  "a Mumbai monsoon from a taxi window",
  "a Havana balcony with worn guitar",
  "a Berlin warehouse after the wall",
  "a London fog and a missed train",
  "a Miami heatwave and iced coffee",
  "a Tokyo crosswalk in the rain",
  "a Mexico City mural that inspires you",
  "a São Paulo traffic jam meditation",
  "a Cape Town coastline at dawn",
  "a Marrakech rooftop slow jam",
  "a Dublin pub session till sunrise",
  "a Nashville session musician's grind",
  "a Detroit revival after the collapse",
  "a Atlanta studio all-nighter",
  "a Chicago winter that tests your grit",
  "a Houston slab culture night drive",
  "a Seattle grey sky and hot ramen",
  "a Portland bookstore crush",
  "a Vegas lights and bad decisions",
  "a Monaco yacht party emptiness",
  "a ski trip romance on the lift",
  "a surf dawn patrol alone",
  "a skatepark session that heals you",
  "a graffiti wall that speaks your truth",
  "a protest chant that becomes a hook",
  "a church pew and a secret doubt",
  "a Sunday gospel after Saturday sins",
  "a Ramadan night of quiet gratitude",
  "a Diwali lights family reunion",
  "a Hanukkah candle and old wounds",
  "a Christmas Eve airport reunion",
  "a New Year's kiss with a stranger",
  "a birthday alone that still feels full",
  "a surprise party that almost failed",
  "a prank that goes too far",
  "a inside joke that becomes a chorus",
  "a meme that accidentally defines you",
  "a algorithm that doesn't get you anymore",
  "a stream count milestone at 3am",
  "a sync deal that saves the month",
  "a beat battle round you'll never lose",
  "a sample flip that honors the past",
  "a collab that almost didn't happen",
  "a feature verse that steals the show",
  "a hook written in the shower",
  "a melody hummed on a bus",
  "a voice note saved for years",
  "a demo sent to the wrong person",
  "a manager call that changes trajectory",
  "a label meeting that feels like theater",
  "a indie release day nerves",
  "a world tour bus homesickness",
  "a backstage green room silence",
  "a crowd singalong you'll chase forever",
  "a mosh pit moment of pure release",
  "a slow dance in a loud club",
  "a DJ drop that owns the room",
  "a soundcheck echo in an empty arena",
  "a broken string mid-performance",
  "a encore you didn't plan for",
  "a documentary crew filming your flaws",
  "a biopic montage of small wins",
  "a anime opening energy for your arc",
  "a film noir scene in your own life",
  "a western duel at sunset",
  "a horror chase through concrete halls",
  "a sci-fi loneliness on a space station",
  "a fantasy quest leaving the village",
  "a superhero origin in plain clothes",
  "a villain monologue you almost respect",
  "a heist crew planning in whispers",
  "a spy lounge with hidden danger",
  "a courtroom verdict held breath",
  "a hospital waiting room clock",
  "a fire escape stargazing",
  "a elevator tension with a stranger",
  "a laundromat conversation that matters",
  "a gas station coffee pilgrimage",
  "a thrift store jacket with history",
  "a vinyl find that rewires your taste",
  "a cassette tape from an ex",
  "a polaroid fading on the fridge",
  "a photo booth strip in your wallet",
  "a love letter never sent",
  "a text left on read for weeks",
  "a blocked number you still memorize",
  "a saved contact you can't delete",
  "a shared playlist that hurts to open",
  "a song that ruins every grocery run",
  "a chorus stuck in your head for days",
  "an Uber that smells like vanilla and regret",
  "the laundromat line on a Saturday",
  "your roommate cooking at 1am",
  "a utility bill that grounds you",
] as const;

export const ACE_PROSE_PRODUCTION_SONG = [
  "Heavy 808, cinematic atmosphere, deep male vocal",
  "Sliding 808, minor piano, airy pads, introspective male vocal",
  "Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Distorted 808, rage synth lead, aggressive male vocal",
  "Soft 808 bounce, bright plucks, breathy female vocal",
  "Four-on-the-floor kick, glossy synths, stacked female harmonies",
  "Log drum groove, jazzy piano stabs, warm male vocal",
  "Dembow rhythm, bright pluck, Latin male vocal",
  "Skippy 2-step drums, chopped vocal texture, bouncy bass",
  "Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Rolling breakbeats, reese sub, urgent male vocal",
  "Sidechain pads, supersaw chorus, euphoric female vocal",
  "Muted trumpet, rhodes chords, silky male vocal",
  "Nylon guitar arps, soft percussion, intimate female vocal",
  "Distorted guitar layers, live drums, raspy male vocal",
  "Orchestral string hits, hard 808 drop, epic male vocal",
  "Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Vinyl crackle, mellow rhodes, lo-fi male vocal",
  "Cowbell hook, Memphis saturation, grave male vocal",
  "Choir pads, organ stabs, gospel female lead",
  "Acid arp, warehouse kick, detached male vocal",
  "Filter disco sample, talkbox lead, chic female vocal",
  "Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Oud plucks, darbuka pulse, melismatic male vocal",
  "Banjo drive, stomp claps, harmony trio vocals",
  "Synth brass, funky bass, confident female vocal",
  "Sparse piano, deep sub, whisper female vocal",
  "Taiko hits, brass fanfare, heroic male vocal",
  "Shimmer arps, glossy chords, futuristic female vocal",
  "Tape-saturated rhodes, brushed drums, soulful male vocal",
] as const;

export const ACE_PROSE_PRODUCTION_BEAT = [
  "Heavy 808, cinematic atmosphere, wide reverb, hook-ready space",
  "Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Dembow kick pattern, bright pluck lead, warm sub, perreo energy",
  "Skippy UKG drums, bouncy bassline, vocal chop stabs, 2-step swing",
  "Rolling breakbeats, reese sub, arp lead, 174 rave drive",
  "Four-on-the-floor kick, piano chords, sidechain pump, terrace vibe",
  "Distorted 808, cowbell pattern, dark synth lead, phonk aggression",
  "Airy pads, soft 808, minimal drums, floating stereo width",
  "Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Punchy kick clusters, bed squeak sample, jersey bounce, edit energy",
  "Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Acid arp, hard techno kick, warehouse tension, hypnotic groove",
  "Nylon guitar arp, soft 808 sub, organic fusion, warm room",
  "Oud melody, darbuka percussion, trap 808, desert night pulse",
  "Funk synth bass, talkbox lead, crisp drums, west-coast haze",
  "Glitch edits, stutter hats, bright leads, hyperpop chaos",
  "Muted trumpet sample, upright bass, lazy swing, noir lounge",
  "Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Banjo pluck, 808 sub, stomp clap, country-trap contrast",
  "Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Filtered disco loop, vocoder stab, four kick, French touch chic",
  "Amen break chops, industrial noise bursts, breakcore adrenaline",
  "Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Detuned synth pads, tape wow, vapor haze, nostalgic drift",
  "Punchy snare, 808 slide, dark piano motif, drill pressure",
] as const;

export const ACE_PROSE_VOCALS_EXTRA = [
  "deep male vocal",
  "raspy male vocal",
  "smooth male vocal",
  "aggressive male vocal",
  "breathy female vocal",
  "stacked female harmonies",
  "autotuned hook vocal",
  "spoken-word vocal",
  "gospel choir lead",
  "whisper female vocal",
  "gravel male vocal",
  "silky male vocal runs",
  "powerful female belt",
  "intimate male falsetto",
  "duet male and female vocal",
] as const;
