/** Auto-generated — npx tsx scripts/generate-ace-prose-pool.ts */
export const ACE_PROSE_SONG_POOL: readonly string[] = [
  "Radiant introspective future bass song about your cat walking across the MIDI keyboard. Sliding 808, minor piano, airy pads, introspective male vocal",
  "Triumphant underground NY drill song about a broken string mid-performance. Choir pads, organ stabs, gospel female lead, spoken-word vocal",
  "Bright warehouse country pop song about a sibling rivalry that becomes respect. Nylon guitar arps, soft percussion, intimate female vocal",
  "Cold warehouse latin trap song about a soundcheck echo in an empty arena. Log drum groove, jazzy piano stabs, warm male vocal",
  "Futuristic hard-hitting French drill song about a Detroit revival after the collapse. Orchestral string hits, hard 808 drop, epic male vocal",
  "Triumphant layered reggaeton song about a rooftop proposal under city lights. Nylon guitar arps, soft percussion, intimate female vocal",
  "Nocturnal floating orchestral pop song about a warehouse party at 4am. Orchestral string hits, hard 808 drop, epic male vocal",
  "Tense late-night pluggnb song about burnout that ends with quitting on Monday. Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Glossy hard-hitting afro house song about a summer terrace that never wants to end. Dembow rhythm, bright pluck, Latin male vocal",
  "Aggressive emotional dancehall song about a film noir scene in your own life. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Cold sun-drenched UK drill song about a shared playlist that hurts to open. Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Euphoric toxic pluggnb song about a London fog and a missed train. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Haunting neon-lit bedroom pop song about a label meeting that feels like theater. Sliding 808, minor piano, airy pads, introspective male vocal",
  "Cinematic luxury K-pop ballad song about a voicemail you replay too often. Nylon guitar arps, soft percussion, intimate female vocal",
  "Gritty cathartic contemporary R&B song about a Ramadan night of quiet gratitude. Distorted guitar layers, live drums, raspy male vocal",
  "Brooding toxic bedroom pop song about a rainy late-night drive home. Synth brass, funky bass, confident female vocal",
  "Dusty floating phonk song about a late studio night when the beat finally clicks. Soft 808 bounce, bright plucks, breathy female vocal",
  "Intimate radio-ready reggaeton song about a Sunday gospel after Saturday sins. Cowbell hook, Memphis saturation, grave male vocal",
  "Tense vengeful electro pop song about a melody hummed on a bus. Sliding 808, minor piano, airy pads, introspective male vocal",
  "Gritty radio-ready afrobeats song about a tattoo you got on impulse. Sliding 808, minor piano, airy pads, introspective male vocal",
  "Melancholic hard-hitting cloud rap song about scoring the winning penalty in extra time. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Triumphant street-level jazz fusion song about a passport stamp and a promise kept. Sparse piano, deep sub, whisper female vocal",
  "Raw dancefloor pop punk song about a melody hummed on a bus. Rolling breakbeats, reese sub, urgent male vocal",
  "Glossy emotional UK garage song about a voice note saved for years. Vinyl crackle, mellow rhodes, lo-fi male vocal",
  "Radiant street-level deep house song about a desert highway with no destination. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Nocturnal introspective contemporary R&B song about a chorus stuck in your head for days. Distorted 808, rage synth lead, aggressive male vocal",
  "Defiant anthemic country pop song about a film noir scene in your own life. Sparse piano, deep sub, whisper female vocal",
  "Seductive introspective hyperpop song about a Berlin warehouse after the wall. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Seductive underground pop punk song about a meme that accidentally defines you. Distorted guitar layers, live drums, raspy male vocal",
  "Aggressive underground phonk song about childhood memories in grandma's kitchen. Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Gritty neon-lit city pop song about a motorcycle ride through desert heat. Sparse piano, deep sub, whisper female vocal",
  "Glossy vengeful city pop song about a Miami heatwave and iced coffee. Cowbell hook, Memphis saturation, grave male vocal",
  "Melancholic atmospheric electro pop song about betrayal and loneliness. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Haunting vengeful bachata pop song about a motorcycle ride through desert heat. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Haunting atmospheric bedroom pop song about a Havana balcony with worn guitar. Distorted 808, rage synth lead, aggressive male vocal",
  "Tense anthemic cinematic trap song about a church pew and a secret doubt. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Bright suburban vapor soul song about a blackout city under full moon. heavy 808, cinematic atmosphere, crisp hi-hats, Taiko hits, brass fanfare, heroic male vocal",
  "Defiant vengeful dance pop song about a long-distance love that still feels close. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Triumphant anthemic jersey club song about a Chicago winter that tests your grit. Heavy 808, cinematic atmosphere, deep male vocal",
  "Seductive winter-cold synthwave pop song about a Hanukkah candle and old wounds. Orchestral string hits, hard 808 drop, epic male vocal",
  "Lush cinematic deep house song about a Monaco yacht party emptiness. Acid arp, warehouse kick, detached male vocal",
  "Playful driving afro R&B song about a Seattle grey sky and hot ramen. heavy 808, cinematic atmosphere, crisp hi-hats, Oud plucks, darbuka pulse, melismatic male vocal",
  "Bright coastal orchestral pop song about a biopic montage of small wins. Nylon guitar arps, soft percussion, intimate female vocal",
  "Bright street-level afro house song about a prank that goes too far. Sliding 808, minor piano, airy pads, introspective male vocal",
  "Triumphant hopeful cinematic trap song about a relapse night you barely survived. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Bittersweet radio-ready electro pop song about a label meeting that feels like theater. Four-on-the-floor kick, glossy synths, stacked female harmonies, raspy male vocal",
  "Bright cathartic cloud rap song about a therapy breakthrough on a Tuesday. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Organic emotional ambient pop song about a lighthouse beam in coastal fog. Skippy 2-step drums, chopped vocal texture, bouncy bass",
  "Haunting floating shoegaze pop song about a skatepark session that heals you. Heavy 808, cinematic atmosphere, deep male vocal",
  "Euphoric luxury deep house song about a biopic montage of small wins. heavy 808, cinematic atmosphere, crisp hi-hats, Filter disco sample, talkbox lead, chic female vocal",
  "Aggressive late-night electro pop song about a church pew and a secret doubt. heavy 808, cinematic atmosphere, crisp hi-hats, Taiko hits, brass fanfare, heroic male vocal",
  "Nostalgic hopeful emo rap song about a song that ruins every grocery run. Skippy 2-step drums, chopped vocal texture, bouncy bass",
  "Cold hard-hitting cloud rap song about a anime opening energy for your arc. heavy 808, cinematic atmosphere, crisp hi-hats, Oud plucks, darbuka pulse, melismatic male vocal",
  "Soulful cathartic amapiano vocal song about a Nashville session musician's grind. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Dreamy emotional pluggnb song about a gym session that saves your mental health. Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Euphoric sun-drenched future bass song about a stream count milestone at 3am. Heavy 808, cinematic atmosphere, deep male vocal",
  "Aggressive anthemic future bass song about a fire escape stargazing. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Glossy confessional future bass song about a Christmas Eve airport reunion. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Minimal layered vapor soul song about a whistle hook that owns summer. heavy 808, cinematic atmosphere, crisp hi-hats, Taiko hits, brass fanfare, heroic male vocal",
  "Hypnotic coastal trap soul song about a hospital waiting room clock. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Radiant coastal dance pop song about a graduation night you'll never forget. Nylon guitar arps, soft percussion, intimate female vocal",
  "Glossy anthemic trap metal song about a indie release day nerves. Cowbell hook, Memphis saturation, grave male vocal",
  "Aggressive toxic boom bap song about a soundcheck echo in an empty arena. Dembow rhythm, bright pluck, Latin male vocal",
  "Moody experimental bedroom pop song about a Tokyo crosswalk in the rain. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Haunting experimental vapor soul song about a film noir scene in your own life. Orchestral string hits, hard 808 drop, epic male vocal",
  "Volatile sun-drenched pop punk song about a gym session that saves your mental health. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Glossy rebellious arabic pop song about a indie release day nerves. Dembow rhythm, bright pluck, Latin male vocal",
  "Radiant sun-drenched melodic drill song about a Mumbai monsoon from a taxi window. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Nostalgic hopeful drum and bass song about a mentor who believed before you did. Soft 808 bounce, bright plucks, breathy female vocal",
  "Lush vengeful French drill song about a second chance you didn't deserve. Nylon guitar arps, soft percussion, intimate female vocal",
  "Haunting raw country pop song about a anime opening energy for your arc. Distorted guitar layers, live drums, raspy male vocal",
  "Euphoric suburban gospel pop song about a luxury hotel room with empty champagne. Vinyl crackle, mellow rhodes, lo-fi male vocal",
  "Moody neon-lit pluggnb song about a melody hummed on a bus. heavy 808, cinematic atmosphere, crisp hi-hats, Shimmer arps, glossy chords, futuristic female vocal",
  "Cold experimental trap song about a courtroom verdict held breath. Soft 808 bounce, bright plucks, breathy female vocal",
  "Triumphant vengeful emo rap song about a whistle hook kids repeat on the block. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Volatile emotional latin trap song about a debt-free morning after years of stress. heavy 808, cinematic atmosphere, crisp hi-hats, Shimmer arps, glossy chords, futuristic female vocal",
  "Bright coastal country pop song about a voicemail you replay too often. Skippy 2-step drums, chopped vocal texture, bouncy bass",
  "Lush street-level vapor soul song about a Cape Town coastline at dawn. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Defiant radio-ready gospel trap song about a graduation night you'll never forget. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Seductive cinematic jersey club song about a surprise party that almost failed. Orchestral string hits, hard 808 drop, epic male vocal",
  "Triumphant neon-lit future bass song about a late studio night when the beat finally clicks. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Dreamy sun-drenched pluggnb song about a rainy late-night drive home. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Melancholic suburban shoegaze pop song about a Tokyo crosswalk in the rain. heavy 808, cinematic atmosphere, crisp hi-hats, Oud plucks, darbuka pulse, melismatic male vocal",
  "Haunting emotional arabic pop song about a sober anniversary worth celebrating. Soft 808 bounce, bright plucks, breathy female vocal",
  "Ethereal introspective gospel trap song about a Dublin pub session till sunrise. Nylon guitar arps, soft percussion, intimate female vocal",
  "Ethereal suburban dark R&B song about burnout that ends with quitting on Monday. Muted trumpet, rhodes chords, silky male vocal",
  "Ethereal suburban melodic drill song about your cat walking across the MIDI keyboard. Dembow rhythm, bright pluck, Latin male vocal",
  "Epic luxury dark R&B song about a broken string mid-performance. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Soulful warehouse orchestral pop song about a horror chase through concrete halls. Synth brass, funky bass, confident female vocal",
  "Futuristic hopeful K-pop ballad song about a anime opening energy for your arc. Heavy 808, cinematic atmosphere, deep male vocal",
  "Raw vengeful bachata pop song about a mountain summit at golden hour. Heavy 808, cinematic atmosphere, deep male vocal",
  "Nocturnal vengeful gospel trap song about a delayed flight that changes your path. heavy 808, cinematic atmosphere, crisp hi-hats, Shimmer arps, glossy chords, futuristic female vocal",
  "Gritty experimental NY drill song about a late studio night when the beat finally clicks. Vinyl crackle, mellow rhodes, lo-fi male vocal",
  "Glossy rebellious arabic pop song about a Seattle grey sky and hot ramen. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Playful introspective country pop song about a wedding dance that feels like floating. Cowbell hook, Memphis saturation, grave male vocal",
  "Aggressive radio-ready reggaeton song about a spy lounge with hidden danger. Distorted guitar layers, live drums, raspy male vocal",
  "Defiant radio-ready cloud rap song about a Marrakech rooftop slow jam. heavy 808, cinematic atmosphere, crisp hi-hats, Banjo drive, stomp claps, harmony trio vocals, aggressive male vocal",
  "Organic floating dancehall song about a documentary crew filming your flaws. Synth brass, funky bass, confident female vocal",
  "Serene raw afro house song about a Houston slab culture night drive. Muted trumpet, rhodes chords, silky male vocal",
  "Cold sparse afro house song about a Zoom meeting that should have been an email. heavy 808, cinematic atmosphere, crisp hi-hats, Taiko hits, brass fanfare, heroic male vocal",
  "Nostalgic driving arabic pop song about a whistle hook kids repeat on the block. Distorted guitar layers, live drums, raspy male vocal",
  "Bright hard-hitting contemporary R&B song about a blocked number you still memorize. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Dusty radio-ready phonk song about a Seoul night market food crawl. Sparse piano, deep sub, whisper female vocal",
  "Dreamy neon-lit pop punk song about a rainy late-night drive home. Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Playful raw arabic pop song about a elevator tension with a stranger. Distorted guitar layers, live drums, raspy male vocal",
  "Lush experimental folk pop song about a slow dance in a loud club. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Hypnotic underground reggaeton song about a delayed flight that changes your path. Synth brass, funky bass, confident female vocal",
  "Brooding underground afro house song about a Zoom meeting that should have been an email. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Warm winter-cold pluggnb song about forgiveness after a brutal argument. Cowbell hook, Memphis saturation, grave male vocal",
  "Dreamy warehouse reggaeton song about your cat walking across the MIDI keyboard. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Nocturnal cathartic electro pop song about a documentary crew filming your flaws. Soft 808 bounce, bright plucks, breathy female vocal",
  "Dreamy vengeful trap metal song about a saved contact you can't delete. Soft 808 bounce, bright plucks, breathy female vocal",
  "Melancholic neon-lit country pop song about a vinyl find that rewires your taste. Muted trumpet, rhodes chords, silky male vocal",
  "Warm atmospheric afro R&B song about a Vegas lights and bad decisions. heavy 808, cinematic atmosphere, crisp hi-hats, Taiko hits, brass fanfare, heroic male vocal",
  "Hypnotic radio-ready NY drill song about a Atlanta studio all-nighter. heavy 808, cinematic atmosphere, crisp hi-hats, Banjo drive, stomp claps, harmony trio vocals, breathy female vocal",
  "Volatile radio-ready drill soul song about a whistle hook at the cookout. heavy 808, cinematic atmosphere, crisp hi-hats, Taiko hits, brass fanfare, heroic male vocal",
  "Hypnotic cinematic orchestral pop song about a Nashville session musician's grind. heavy 808, cinematic atmosphere, crisp hi-hats, Filter disco sample, talkbox lead, chic female vocal",
  "Triumphant warehouse UK garage song about a Havana balcony with worn guitar. Distorted 808, rage synth lead, aggressive male vocal",
  "Brooding rebellious rage rap song about a Hanukkah candle and old wounds. Four-on-the-floor kick, glossy synths, stacked female harmonies, autotuned hook vocal",
  "Melancholic suburban hyperpop song about a skatepark session that heals you. Cowbell hook, Memphis saturation, grave male vocal",
  "Gritty atmospheric gospel trap song about a summer terrace that never wants to end. heavy 808, cinematic atmosphere, crisp hi-hats, Oud plucks, darbuka pulse, melismatic male vocal",
  "Volatile suburban cloud rap song about a meme that accidentally defines you. Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Ethereal floating blues rock song about a Atlanta studio all-nighter. Distorted guitar layers, live drums, raspy male vocal",
  "Intimate hard-hitting pop punk song about childhood memories in grandma's kitchen. Synth brass, funky bass, confident female vocal",
  "Radiant layered neo soul song about a text left on read for weeks. heavy 808, cinematic atmosphere, crisp hi-hats, Oud plucks, darbuka pulse, melismatic male vocal",
  "Futuristic layered melodic trap song about a Seattle grey sky and hot ramen. heavy 808, cinematic atmosphere, crisp hi-hats, Shimmer arps, glossy chords, futuristic female vocal",
  "Bright emotional afro R&B song about a Seoul night market food crawl. Four-on-the-floor kick, glossy synths, stacked female harmonies, spoken-word vocal",
  "Cold neon-lit house pop song about a sync deal that saves the month. Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Futuristic hopeful bachata pop song about a debt-free morning after years of stress. heavy 808, cinematic atmosphere, crisp hi-hats, Shimmer arps, glossy chords, futuristic female vocal",
  "Nostalgic suburban cinematic trap song about finding peace after years of noise. Heavy 808, cinematic atmosphere, deep male vocal",
  "Raw confessional contemporary R&B song about a van road trip along the Atlantic coast. Cowbell hook, Memphis saturation, grave male vocal",
  "Volatile experimental city pop song about a text left on read for weeks. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Nostalgic coastal blues rock song about a algorithm that doesn't get you anymore. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Volatile layered synthwave pop song about a graffiti wall that speaks your truth. Orchestral string hits, hard 808 drop, epic male vocal",
  "Dusty layered afro R&B song about a Marrakech rooftop slow jam. Heavy 808, cinematic atmosphere, deep male vocal",
  "Moody emotional jazz fusion song about a Hanukkah candle and old wounds. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Bright layered indie pop song about a Hanukkah candle and old wounds. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Cinematic winter-cold afro R&B song about a rainy late-night drive home. Acid arp, warehouse kick, detached male vocal",
  "Defiant underground orchestral pop song about a protest chant that becomes a hook. Heavy 808, cinematic atmosphere, deep male vocal",
  "Nostalgic luxury electro pop song about two best friends drifting apart after college. Nylon guitar arps, soft percussion, intimate female vocal",
  "Nostalgic street-level bedroom pop song about a desert highway with no destination. Cowbell hook, Memphis saturation, grave male vocal",
  "Cold anthemic electro pop song about a protest love story in the crowd. heavy 808, cinematic atmosphere, crisp hi-hats, Shimmer arps, glossy chords, futuristic female vocal",
  "Dreamy driving gospel trap song about a relapse night you barely survived. Four-on-the-floor kick, glossy synths, stacked female harmonies, whisper female vocal",
  "Bright vengeful deep house song about a Hanukkah candle and old wounds. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Warm luxury metalcore song about a villain monologue you almost respect. Synth brass, funky bass, confident female vocal",
  "Gritty emotional alternative rock song about a whistle hook that owns summer. Distorted guitar layers, live drums, raspy male vocal",
  "Fragile experimental K-pop ballad song about a photo booth strip in your wallet. Sliding 808, minor piano, airy pads, introspective male vocal",
  "Triumphant floating emo rap song about a saved contact you can't delete. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Minimal luxury dance pop song about a algorithm that doesn't get you anymore. Rolling breakbeats, reese sub, urgent male vocal",
  "Melancholic introspective amapiano vocal song about a saved contact you can't delete. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Volatile driving UK drill song about a diary entry you almost deleted. Cowbell hook, Memphis saturation, grave male vocal",
  "Bittersweet sparse alternative rock song about a prayer whispered before a risky leap. Sparse piano, deep sub, whisper female vocal",
  "Intimate floating sample drill song about a New Year's kiss with a stranger. heavy 808, cinematic atmosphere, crisp hi-hats, Oud plucks, darbuka pulse, melismatic male vocal",
  "Haunting street-level lo-fi melodic trap song about a horror chase through concrete halls. Sliding 808, minor piano, airy pads, introspective male vocal",
  "Glossy coastal house pop song about a London fog and a missed train. Rolling breakbeats, reese sub, urgent male vocal",
  "Seductive cinematic rage rap song about your cat walking across the MIDI keyboard. Acid arp, warehouse kick, detached male vocal",
  "Rebellious luxury emo rap song about a locker-room speech before the final. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Hypnotic warehouse gospel trap song about a Marrakech rooftop slow jam. Muted trumpet, rhodes chords, silky male vocal",
  "Organic warehouse folk pop song about a luxury hotel room with empty champagne. Cowbell hook, Memphis saturation, grave male vocal",
  "Raw warehouse amapiano vocal song about a label meeting that feels like theater. Soft 808 bounce, bright plucks, breathy female vocal",
  "Hypnotic confessional jazz fusion song about a anime opening energy for your arc. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Raw suburban amapiano vocal song about revenge after being underestimated. Rolling breakbeats, reese sub, urgent male vocal",
  "Moody cathartic trap song about a Havana balcony with worn guitar. heavy 808, cinematic atmosphere, crisp hi-hats, Filter disco sample, talkbox lead, chic female vocal",
  "Aggressive experimental sample drill song about a debt-free morning after years of stress. Vinyl crackle, mellow rhodes, lo-fi male vocal",
  "Playful suburban sample drill song about a Atlanta studio all-nighter. Cowbell hook, Memphis saturation, grave male vocal",
  "Euphoric confessional latin trap song about a Hanukkah candle and old wounds. Heavy 808, cinematic atmosphere, deep male vocal",
  "Intimate layered ambient pop song about a chorus stuck in your head for days. Heavy 808, cinematic atmosphere, deep male vocal",
  "Hypnotic rebellious alternative rock song about a text left on read for weeks. Distorted 808, rage synth lead, aggressive male vocal",
  "Ethereal experimental deep house song about childhood memories in grandma's kitchen. Skippy 2-step drums, chopped vocal texture, bouncy bass",
  "Cinematic raw sample drill song about a bonfire confession with old friends. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Dark toxic afro house song about a Seattle grey sky and hot ramen. Sparse piano, deep sub, whisper female vocal",
  "Dusty raw emo rap song about a second chance you didn't deserve. Sliding 808, minor piano, airy pads, introspective male vocal",
  "Dark suburban latin trap song about a broken string mid-performance. Dembow rhythm, bright pluck, Latin male vocal",
  "Rebellious street-level latin trap song about finding peace after years of noise. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Aggressive floating shoegaze pop song about a festival sunset that changes everything. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Nostalgic winter-cold gospel trap song about a gas station coffee pilgrimage. Dembow rhythm, bright pluck, Latin male vocal",
  "Raw raw cloud rap song about a spy lounge with hidden danger. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Dark street-level synthwave pop song about a demo sent to the wrong person. Rolling breakbeats, reese sub, urgent male vocal",
  "Nostalgic floating amapiano song about a Houston slab culture night drive. Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Futuristic confessional drill soul song about a birthday alone that still feels full. heavy 808, cinematic atmosphere, crisp hi-hats, Banjo drive, stomp claps, harmony trio vocals, silky male vocal runs",
  "Radiant warehouse hyperpop song about a photo booth strip in your wallet. Synth brass, funky bass, confident female vocal",
  "Tense coastal jersey club song about a lie that finally comes out. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Intimate hard-hitting K-pop ballad song about falling for your best friend's honesty. Acid arp, warehouse kick, detached male vocal",
  "Moody radio-ready synthwave pop song about a slow dance in a loud club. Muted trumpet, rhodes chords, silky male vocal",
  "Radiant underground house pop song about childhood memories in grandma's kitchen. Synth brass, funky bass, confident female vocal",
  "Hypnotic cinematic vapor soul song about a fantasy quest leaving the village. Four-on-the-floor kick, glossy synths, stacked female harmonies, gravel male vocal",
  "Polished sparse cloud rap song about a hospital waiting room clock. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Polished sparse electro pop song about a Chicago winter that tests your grit. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Cinematic dancefloor bedroom pop song about a lie that finally comes out. Vinyl crackle, mellow rhodes, lo-fi male vocal",
  "Futuristic anthemic cinematic trap song about a DJ drop that owns the room. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Anxious neon-lit gospel trap song about a inside joke that becomes a chorus. Cowbell hook, Memphis saturation, grave male vocal",
  "Raw dancefloor synthwave pop song about a power outage that sparks romance. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Playful rebellious hyperpop song about a villain monologue you almost respect. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Cinematic experimental amapiano vocal song about a van road trip along the Atlantic coast. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Seductive driving pop punk song about hearing your own song in a stranger's headphones. Heavy 808, cinematic atmosphere, deep male vocal",
  "Melancholic anthemic electro pop song about a small-town dream of making it out. Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Triumphant raw arabic pop song about a rival who pushed you to be sharper. heavy 808, cinematic atmosphere, crisp hi-hats, Taiko hits, brass fanfare, heroic male vocal",
  "Anxious raw afrobeats song about a stolen hoodie that still smells like them. Log drum groove, jazzy piano stabs, warm male vocal",
  "Lush vengeful city pop song about a biopic montage of small wins. Crisp trap drums, warm rhodes, smooth male vocal runs",
  "Bright floating blues rock song about a Lagos market buzzing with color. Synth brass, funky bass, confident female vocal",
  "Volatile vengeful afrobeats song about a polaroid fading on the fridge. Soft 808 bounce, bright plucks, breathy female vocal",
  "Tense experimental dark R&B song about a Berlin warehouse after the wall. Orchestral string hits, hard 808 drop, epic male vocal",
  "Gritty radio-ready amapiano vocal song about a stolen glance across a crowded club. Distorted guitar layers, live drums, raspy male vocal",
  "Euphoric neon-lit drum and bass song about a villain monologue you almost respect. Soft 808 bounce, bright plucks, breathy female vocal",
  "Lush floating orchestral pop song about a villain monologue you almost respect. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Epic raw sample drill song about a hiking trail that clears your head. Nylon guitar arps, soft percussion, intimate female vocal",
  "Bittersweet hopeful drum and bass song about a funeral song that celebrates a life. heavy 808, cinematic atmosphere, crisp hi-hats, Shimmer arps, glossy chords, futuristic female vocal",
  "Epic coastal pluggnb song about a festival sunset that changes everything. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Serene dancefloor ambient pop song about a desert highway with no destination. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Melancholic anthemic future bass song about a summer terrace that never wants to end. Soft 808 bounce, bright plucks, breathy female vocal",
  "Seductive luxury dance pop song about a western duel at sunset. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Rebellious introspective future bass song about a diary entry you almost deleted. Choir pads, organ stabs, gospel female lead, spoken-word vocal",
  "Seductive toxic bedroom pop song about a ski trip romance on the lift. Skippy 2-step drums, chopped vocal texture, bouncy bass",
  "Ethereal luxury hyperpop song about a tattoo you got on impulse. Log drum groove, jazzy piano stabs, warm male vocal",
  "Soulful luxury bedroom pop song about a Houston slab culture night drive. Rolling breakbeats, reese sub, urgent male vocal",
  "Tense dancefloor arabic pop song about a panic attack in the supermarket aisle. Distorted 808, rage synth lead, aggressive male vocal",
  "Futuristic layered contemporary R&B song about a mother's voice on a crackly voicemail. Heavy 808, cinematic atmosphere, deep male vocal",
  "Anxious coastal trap song about surviving exam week on cold coffee. heavy 808, cinematic atmosphere, crisp hi-hats, Taiko hits, brass fanfare, heroic male vocal",
  "Euphoric experimental country pop song about a surf dawn patrol alone. Heavy 808, cinematic atmosphere, deep male vocal",
  "Radiant luxury vapor soul song about a graffiti wall that speaks your truth. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Melancholic introspective afrobeats song about a soundcheck echo in an empty arena. Choir pads, organ stabs, gospel female lead, autotuned hook vocal",
  "Serene dancefloor electro pop song about a rainy late-night drive home. Cowbell hook, Memphis saturation, grave male vocal",
  "Epic coastal synthwave pop song about a suitcase packed in silence. Soft 808 bounce, bright plucks, breathy female vocal",
  "Bright sun-drenched rage rap song about a graffiti wall that speaks your truth. Muted trumpet, rhodes chords, silky male vocal",
  "Nostalgic anthemic future bass song about street ambition after public failure. Synth brass, funky bass, confident female vocal",
  "Dreamy vengeful ambient pop song about a parking-lot freestyle that goes viral. Distorted guitar layers, live drums, raspy male vocal",
  "Nostalgic underground folk pop song about a encore you didn't plan for. Synth brass, funky bass, confident female vocal",
  "Lush hopeful bedroom pop song about a Nashville session musician's grind. Synth brass, funky bass, confident female vocal",
  "Futuristic driving ambient pop song about quitting a toxic job with no backup plan. Distorted guitar layers, live drums, raspy male vocal",
  "Intimate atmospheric melodic trap song about a villain monologue you almost respect. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Dusty luxury drill soul song about a hiking trail that clears your head. Sliding 808, minor piano, airy pads, introspective male vocal",
  "Polished anthemic bachata pop song about a horror chase through concrete halls. Soft 808 bounce, bright plucks, breathy female vocal",
  "Dark dancefloor emo rap song about a hitchhiker story with no ending. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Polished underground gospel pop song about a warehouse party at 4am. Palm-muted guitar, heavy 808, cracked emo male vocal",
  "Anxious dancefloor cloud rap song about a long-distance love that still feels close. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Dark toxic gospel pop song about a mother's voice on a crackly voicemail. Orchestral string hits, hard 808 drop, epic male vocal",
  "Glossy neon-lit reggaeton song about a parking-lot freestyle that goes viral. heavy 808, cinematic atmosphere, crisp hi-hats, Oud plucks, darbuka pulse, melismatic male vocal",
  "Serene layered UK drill song about a tattoo you got on impulse. heavy 808, cinematic atmosphere, crisp hi-hats, Taiko hits, brass fanfare, heroic male vocal",
  "Organic floating contemporary R&B song about a crowd singalong you'll chase forever. Vinyl crackle, mellow rhodes, lo-fi male vocal",
  "Organic coastal indie pop song about a Vegas lights and bad decisions. Dembow rhythm, bright pluck, Latin male vocal",
  "Dark confessional lo-fi melodic trap song about a heartbreak playlist on shuffle. Orchestral string hits, hard 808 drop, epic male vocal",
  "Dusty neon-lit gospel pop song about a mother's voice on a crackly voicemail. Four-on-the-floor kick, glossy synths, stacked female harmonies, aggressive male vocal",
  "Lush experimental house pop song about a Mexico City mural that inspires you. Glitch synth stabs, hyper-compressed mix, bright female vocal",
  "Organic anthemic dark R&B song about a DJ drop that owns the room. Sidechain pads, supersaw chorus, euphoric female vocal",
  "Polished dancefloor afro house song about a bar fight apology at closing time. Tape-saturated rhodes, brushed drums, soulful male vocal",
  "Defiant atmospheric gospel pop song about your first BeatStars sale at twenty-nine dollars. heavy 808, cinematic atmosphere, crisp hi-hats, Banjo drive, stomp claps, harmony trio vocals, smooth male vocal",
  "Anxious hopeful boom bap song about a saved contact you can't delete. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Playful rebellious jazz fusion song about a São Paulo traffic jam meditation. Acid arp, warehouse kick, detached male vocal",
  "Hypnotic introspective rage rap song about a surprise party that almost failed. Dusty boom-bap drums, soul sample chop, spoken-word vocal",
  "Brooding sparse neo soul song about a stream count milestone at 3am. heavy 808, cinematic atmosphere, crisp hi-hats, Filter disco sample, talkbox lead, chic female vocal"
] as const;

export const ACE_PROSE_BEAT_POOL: readonly string[] = [
  "Gritty warehouse breakbeat beat about a ski trip romance on the lift. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Serene underground electro swing beat about a tattoo you got on impulse. Dembow kick pattern, bright pluck lead, warm sub, perreo energy",
  "Polished vengeful baile funk beat about a luxury hotel room with empty champagne. Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Seductive late-night highlife beat about a tattoo you got on impulse. Detuned synth pads, tape wow, vapor haze, nostalgic drift",
  "Cinematic hopeful phonk beat about a backstage green room silence. heavy 808, cinematic atmosphere, wide reverb, Glitch edits, stutter hats, bright leads, hyperpop chaos",
  "Euphoric floating baile funk beat about a Sunday gospel after Saturday sins. Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Moody emotional cloud rap beat about a summer terrace that never wants to end. Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Intimate radio-ready jazz fusion trap beat about betrayal and loneliness. heavy 808, cinematic atmosphere, wide reverb, Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Dark sparse phonk beat about a Seattle grey sky and hot ramen. heavy 808, cinematic atmosphere, wide reverb, Amen break chops, industrial noise bursts, breakcore adrenaline",
  "Radiant neon-lit rai trap beat about a truth told too late. Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Glossy driving jersey club beat about a protest chant that becomes a hook. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Raw cathartic latin trap beat about a song that ruins every grocery run. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Polished neon-lit deep house beat about a laundromat conversation that matters. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Triumphant underground gospel trap beat about a protest march turned into hope. Heavy 808, cinematic atmosphere, wide reverb, hook-ready space",
  "Tense neon-lit UK garage beat about a funeral song that celebrates a life. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Rebellious rebellious rage trap beat about a midnight swim that resets your mind. heavy 808, cinematic atmosphere, wide reverb, Amen break chops, industrial noise bursts, breakcore adrenaline",
  "Futuristic dancefloor future bass beat about a relapse night you barely survived. Punchy kick clusters, bed squeak sample, jersey bounce, edit energy",
  "Triumphant floating drum and bass beat about the anxiety before sending an important DM. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Epic rebellious rai trap beat about a long-distance love that still feels close. Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Fragile vengeful melodic drill beat about a western duel at sunset. Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Melancholic rebellious R&B beat about a manager call that changes trajectory. Oud melody, darbuka percussion, trap 808, desert night pulse",
  "Melancholic late-night techno trap beat about a locker-room speech before the final. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Rebellious luxury gospel trap beat about a Chicago winter that tests your grit. Acid arp, hard techno kick, warehouse tension, hypnotic groove",
  "Tense layered afrobeats beat about a saved contact you can't delete. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Organic emotional amapiano beat about a photo booth strip in your wallet. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Dreamy radio-ready ambient drill beat about missing someone living in another timezone. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Raw vengeful lo-fi melodic trap beat about a scar with a story behind it. Banjo pluck, 808 sub, stomp clap, country-trap contrast",
  "Warm toxic R&B beat about a prayer whispered before a risky leap. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Polished winter-cold baile funk beat about a broken string mid-performance. Banjo pluck, 808 sub, stomp clap, country-trap contrast",
  "Dusty suburban amapiano beat about your cat walking across the MIDI keyboard. heavy 808, cinematic atmosphere, wide reverb, Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Defiant introspective dancehall beat about a chorus stuck in your head for days. Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Volatile suburban deep house beat about falling for your best friend's honesty. Skippy UK garage drums, bouncy bassline, vocal chop stabs, 2-step swing",
  "Defiant coastal western trap beat about a shared playlist that hurts to open. Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Seductive hopeful breakbeat beat about a text left on read for weeks. Distorted 808, cowbell pattern, dark synth lead, phonk aggression",
  "Bittersweet underground boom bap beat about a Seoul night market food crawl. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Gritty sun-drenched baroque trap beat about a chorus stuck in your head for days. Distorted 808, cowbell pattern, dark synth lead, phonk aggression",
  "Anxious dancefloor French drill beat about a anime opening energy for your arc. Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Intimate introspective jersey club beat about a encore you didn't plan for. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Defiant cathartic deep house beat about a rival who pushed you to be sharper. Funk synth bass, talkbox lead, crisp drums, west-coast haze",
  "Melancholic experimental rai trap beat about a protest love story in the crowd. Skippy UK garage drums, bouncy bassline, vocal chop stabs, 2-step swing",
  "Cold floating western trap beat about a bar fight apology at closing time. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Polished radio-ready dancehall beat about surviving exam week on cold coffee. Distorted 808, cowbell pattern, dark synth lead, phonk aggression",
  "Anxious luxury breakbeat beat about a biopic montage of small wins. Oud melody, darbuka percussion, trap 808, desert night pulse",
  "Volatile warehouse cinematic trap beat about a hook written in the shower. Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Dark warehouse deep house beat about a sci-fi loneliness on a space station. Acid arp, hard techno kick, warehouse tension, hypnotic groove",
  "Haunting layered melodic trap beat about a ski trip romance on the lift. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Raw rebellious future bass beat about a late studio night when the beat finally clicks. Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Melancholic layered jersey club beat about a funeral song that celebrates a life. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Dark confessional French drill beat about a sibling rivalry that becomes respect. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Radiant suburban cinematic trap beat about a heist crew planning in whispers. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Warm hard-hitting orchestral trap beat about burnout that ends with quitting on Monday. Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Bright dancefloor NY drill beat about a São Paulo traffic jam meditation. Muted trumpet sample, upright bass, lazy swing, noir lounge",
  "Dreamy anthemic deep house beat about a Christmas Eve airport reunion. Airy pads, soft 808, minimal drums, floating stereo width",
  "Minimal driving phonk drift beat about a western duel at sunset. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Nocturnal late-night breakbeat beat about a broken string mid-performance. Distorted 808, cowbell pattern, dark synth lead, phonk aggression",
  "Aggressive anthemic neo soul beat about a gym session that saves your mental health. Acid arp, hard techno kick, warehouse tension, hypnotic groove",
  "Moody neon-lit sample drill beat about a Cape Town coastline at dawn. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Nocturnal floating baile funk beat about missing someone living in another timezone. Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Playful warehouse cinematic trap beat about childhood memories in grandma's kitchen. Nylon guitar arp, soft 808 sub, organic fusion, warm room",
  "Anxious cinematic UK drill beat about a prank that goes too far. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Volatile experimental R&B beat about betrayal and loneliness. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Ethereal introspective baile funk beat about missing someone living in another timezone. Funk synth bass, talkbox lead, crisp drums, west-coast haze",
  "Moody coastal middle eastern trap beat about a meme that accidentally defines you. Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Dark sparse UK drill beat about a horror chase through concrete halls. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Defiant emotional French drill beat about a kitchen dance at 2am in socks. Dembow kick pattern, bright pluck lead, warm sub, perreo energy",
  "Hypnotic introspective pluggnb beat about a whistle hook in the group chat. heavy 808, cinematic atmosphere, wide reverb, Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Ethereal coastal electro swing beat about a tattoo you got on impulse. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Minimal sparse UK drill beat about a mother's voice on a crackly voicemail. Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Dark warehouse pop-trap beat about a song that ruins every grocery run. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Bright radio-ready dancehall beat about a delayed flight that changes your path. Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Futuristic underground emo trap beat about a Tokyo crosswalk in the rain. Dembow kick pattern, bright pluck lead, warm sub, perreo energy",
  "Euphoric radio-ready synthwave beat about a father teaching you to drive at dusk. Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Ethereal layered techno trap beat about a chorus stuck in your head for days. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Nostalgic toxic neo soul beat about a whistle hook at the cookout. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Epic street-level amapiano beat about forgiveness after a brutal argument. Detuned synth pads, tape wow, vapor haze, nostalgic drift",
  "Bittersweet introspective g-funk beat about a mosh pit moment of pure release. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Melancholic street-level afro house beat about a train platform goodbye. Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Bittersweet luxury UK garage beat about a gym session that saves your mental health. heavy 808, cinematic atmosphere, wide reverb, Glitch edits, stutter hats, bright leads, hyperpop chaos",
  "Glossy street-level breakbeat beat about a collab that almost didn't happen. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Playful underground dark trap beat about a long-distance love that still feels close. Punchy kick clusters, bed squeak sample, jersey bounce, edit energy",
  "Radiant layered dark trap beat about a prayer whispered before a risky leap. Rolling breakbeats, reese sub, arp lead, 174 rave drive",
  "Soulful coastal drum and bass beat about a summer terrace that never wants to end. Funk synth bass, talkbox lead, crisp drums, west-coast haze",
  "Fragile confessional R&B beat about a Dublin pub session till sunrise. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Tense toxic phonk beat about two best friends drifting apart after college. heavy 808, cinematic atmosphere, wide reverb, Amen break chops, industrial noise bursts, breakcore adrenaline",
  "Triumphant emotional baile funk beat about a lighthouse beam in coastal fog. Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Minimal winter-cold latin trap beat about a long-distance love that still feels close. heavy 808, cinematic atmosphere, wide reverb, Glitch edits, stutter hats, bright leads, hyperpop chaos",
  "Fragile winter-cold western trap beat about betrayal and loneliness. Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Fragile dancefloor techno trap beat about childhood memories in grandma's kitchen. Dembow kick pattern, bright pluck lead, warm sub, perreo energy",
  "Triumphant coastal drum and bass beat about a summer terrace that never wants to end. Four-on-the-floor kick, piano chords, sidechain pump, terrace vibe",
  "Glossy dancefloor middle eastern trap beat about a meme that accidentally defines you. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Volatile floating pluggnb beat about a Mexico City mural that inspires you. Acid arp, hard techno kick, warehouse tension, hypnotic groove",
  "Cold sparse afrobeats beat about a rainy late-night drive home. heavy 808, cinematic atmosphere, wide reverb, Amen break chops, industrial noise bursts, breakcore adrenaline",
  "Brooding rebellious sample drill beat about a mother's voice on a crackly voicemail. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Raw neon-lit afro house beat about a funeral song that celebrates a life. Skippy UK garage drums, bouncy bassline, vocal chop stabs, 2-step swing",
  "Intimate confessional neo soul beat about a mountain summit at golden hour. Skippy UK garage drums, bouncy bassline, vocal chop stabs, 2-step swing",
  "Glossy anthemic cloud rap beat about a whistle hook at the cookout. Banjo pluck, 808 sub, stomp clap, country-trap contrast",
  "Lush luxury trap soul beat about a surf dawn patrol alone. Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Minimal dancefloor cinematic trap beat about a label meeting that feels like theater. Four-on-the-floor kick, piano chords, sidechain pump, terrace vibe",
  "Brooding confessional baile funk beat about a graduation night you'll never forget. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Gritty raw techno trap beat about a sibling rivalry that becomes respect. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Bright warehouse pluggnb beat about a sibling rivalry that becomes respect. heavy 808, cinematic atmosphere, wide reverb, Amen break chops, industrial noise bursts, breakcore adrenaline",
  "Nocturnal emotional afro house beat about a van road trip along the Atlantic coast. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Haunting radio-ready deep house beat about a love letter never sent. Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Warm suburban middle eastern trap beat about a crush in the concert queue. Nylon guitar arp, soft 808 sub, organic fusion, warm room",
  "Volatile cinematic highlife beat about a diary entry you almost deleted. Filtered disco loop, vocoder stab, four kick, French touch chic",
  "Dusty hopeful melodic trap beat about a wedding dance that feels like floating. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Melancholic hard-hitting melodic trap beat about a broken string mid-performance. Airy pads, soft 808, minimal drums, floating stereo width",
  "Moody late-night cloud rap beat about a Detroit revival after the collapse. Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Epic layered R&B beat about a Tokyo crosswalk in the rain. Nylon guitar arp, soft 808 sub, organic fusion, warm room",
  "Melancholic raw sample drill beat about a power outage that sparks romance. Four-on-the-floor kick, piano chords, sidechain pump, terrace vibe",
  "Cold floating R&B beat about a father teaching you to drive at dusk. heavy 808, cinematic atmosphere, wide reverb, Glitch edits, stutter hats, bright leads, hyperpop chaos",
  "Euphoric street-level drum and bass beat about starting over in a new apartment. Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Playful experimental reggaeton beat about a whistle hook in the group chat. Four-on-the-floor kick, piano chords, sidechain pump, terrace vibe",
  "Epic sparse dark trap beat about a sync deal that saves the month. Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Playful street-level reggaeton beat about a motorcycle ride through desert heat. Filtered disco loop, vocoder stab, four kick, French touch chic",
  "Gritty hopeful trap soul beat about a Sunday gospel after Saturday sins. Rolling breakbeats, reese sub, arp lead, 174 rave drive",
  "Melancholic cathartic sample drill beat about a protest love story in the crowd. Detuned synth pads, tape wow, vapor haze, nostalgic drift",
  "Triumphant driving gospel trap beat about a festival sunset that changes everything. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Playful vengeful orchestral trap beat about a church pew and a secret doubt. Airy pads, soft 808, minimal drums, floating stereo width",
  "Radiant emotional reggaeton beat about a lighthouse beam in coastal fog. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Rebellious emotional dark trap beat about a Monaco yacht party emptiness. Distorted 808, cowbell pattern, dark synth lead, phonk aggression",
  "Futuristic floating western trap beat about a suitcase packed in silence. Skippy UK garage drums, bouncy bassline, vocal chop stabs, 2-step swing",
  "Dreamy coastal gospel trap beat about a suitcase packed in silence. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Nocturnal rebellious boom bap beat about a Tokyo crosswalk in the rain. Rolling breakbeats, reese sub, arp lead, 174 rave drive",
  "Warm radio-ready phonk beat about a rainy late-night drive home. Rolling breakbeats, reese sub, arp lead, 174 rave drive",
  "Serene vengeful acoustic trap beat about a Vegas lights and bad decisions. Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Fragile vengeful drum and bass beat about a text left on read for weeks. heavy 808, cinematic atmosphere, wide reverb, Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Triumphant street-level sample drill beat about a inside joke that becomes a chorus. Funk synth bass, talkbox lead, crisp drums, west-coast haze",
  "Bright atmospheric UK garage beat about a sync deal that saves the month. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Volatile warehouse afrobeats beat about a feature verse that steals the show. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Hypnotic floating techno trap beat about a lie that finally comes out. Muted trumpet sample, upright bass, lazy swing, noir lounge",
  "Intimate emotional afrobeats beat about a late studio night when the beat finally clicks. Muted trumpet sample, upright bass, lazy swing, noir lounge",
  "Melancholic hard-hitting house beat about a parking-lot freestyle that goes viral. Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Rebellious suburban western trap beat about scoring the winning penalty in extra time. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Playful street-level pluggnb beat about a saved contact you can't delete. Nylon guitar arp, soft 808 sub, organic fusion, warm room",
  "Nostalgic layered jersey club beat about a Chicago winter that tests your grit. heavy 808, cinematic atmosphere, wide reverb, Amen break chops, industrial noise bursts, breakcore adrenaline",
  "Moody hard-hitting melodic trap beat about a hiking trail that clears your head. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Organic late-night French drill beat about a whistle hook at the cookout. Funk synth bass, talkbox lead, crisp drums, west-coast haze",
  "Radiant sparse gospel trap beat about a train platform goodbye. heavy 808, cinematic atmosphere, wide reverb, Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Melancholic radio-ready orchestral trap beat about your first BeatStars sale at twenty-nine dollars. heavy 808, cinematic atmosphere, wide reverb, Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Defiant radio-ready breakbeat beat about a diary entry you almost deleted. Muted trumpet sample, upright bass, lazy swing, noir lounge",
  "Hypnotic hard-hitting emo trap beat about a panic attack in the supermarket aisle. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Haunting emotional French touch house beat about a horror chase through concrete halls. Banjo pluck, 808 sub, stomp clap, country-trap contrast",
  "Moody radio-ready gospel trap beat about two best friends drifting apart after college. Detuned synth pads, tape wow, vapor haze, nostalgic drift",
  "Radiant dancefloor middle eastern trap beat about scoring the winning penalty in extra time. Acid arp, hard techno kick, warehouse tension, hypnotic groove",
  "Cinematic atmospheric dark trap beat about a spy lounge with hidden danger. Skippy UK garage drums, bouncy bassline, vocal chop stabs, 2-step swing",
  "Defiant anthemic ambient drill beat about a Tokyo crosswalk in the rain. Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Moody underground melodic drill beat about a Vegas lights and bad decisions. Rolling breakbeats, reese sub, arp lead, 174 rave drive",
  "Anxious hopeful latin trap beat about a inside joke that becomes a chorus. Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Melancholic driving highlife beat about a Ramadan night of quiet gratitude. Four-on-the-floor kick, piano chords, sidechain pump, terrace vibe",
  "Tense suburban baroque trap beat about a second chance you didn't deserve. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Ethereal underground afrobeats beat about a western duel at sunset. Dembow kick pattern, bright pluck lead, warm sub, perreo energy",
  "Glossy coastal techno trap beat about a London fog and a missed train. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Ethereal toxic afro house beat about a saved contact you can't delete. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Rebellious sparse lo-fi melodic trap beat about a mirror talk before a big interview. heavy 808, cinematic atmosphere, wide reverb, Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Hypnotic sparse reggaeton beat about a long-distance love that still feels close. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Cinematic layered orchestral trap beat about your cat walking across the MIDI keyboard. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Seductive confessional reggaeton beat about a spy lounge with hidden danger. heavy 808, cinematic atmosphere, wide reverb, Glitch edits, stutter hats, bright leads, hyperpop chaos",
  "Polished hopeful rage trap beat about a funeral song that celebrates a life. Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Minimal coastal g-funk beat about a train platform goodbye. Banjo pluck, 808 sub, stomp clap, country-trap contrast",
  "Euphoric sun-drenched jersey club beat about a mosh pit moment of pure release. Heavy 808, cinematic atmosphere, wide reverb, hook-ready space",
  "Euphoric vengeful boom bap beat about a mosh pit moment of pure release. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Dusty underground ambient drill beat about a gas station coffee pilgrimage. Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Melancholic experimental jersey club beat about a melody hummed on a bus. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Intimate layered gospel trap beat about a whistle hook in the group chat. Dembow kick pattern, bright pluck lead, warm sub, perreo energy",
  "Euphoric atmospheric reggaeton beat about a Cape Town coastline at dawn. heavy 808, cinematic atmosphere, wide reverb, Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Soulful hard-hitting amapiano beat about a Seattle grey sky and hot ramen. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Minimal luxury lo-fi melodic trap beat about a scar with a story behind it. Four-on-the-floor kick, piano chords, sidechain pump, terrace vibe",
  "Dreamy coastal French touch house beat about a whistle hook in the group chat. Airy pads, soft 808, minimal drums, floating stereo width",
  "Melancholic sparse western trap beat about revenge after being underestimated. Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Glossy emotional orchestral trap beat about a Cape Town coastline at dawn. Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Fragile dancefloor cinematic trap beat about a superhero origin in plain clothes. Nylon guitar arp, soft 808 sub, organic fusion, warm room",
  "Glossy winter-cold trap soul beat about a Hanukkah candle and old wounds. Oud melody, darbuka percussion, trap 808, desert night pulse",
  "Anxious sun-drenched electro swing beat about a western duel at sunset. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Minimal radio-ready melodic drill beat about a skatepark session that heals you. Shaker percussion, highlife guitar, horn stabs, Accra sunshine",
  "Dusty warehouse rage trap beat about a prayer whispered before a risky leap. Dembow kick pattern, bright pluck lead, warm sub, perreo energy",
  "Melancholic hard-hitting phonk beat about burnout that ends with quitting on Monday. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Hypnotic anthemic baroque trap beat about a panic attack in the supermarket aisle. Oud melody, darbuka percussion, trap 808, desert night pulse",
  "Melancholic sun-drenched pluggnb beat about hearing your own song in a stranger's headphones. Rolling breakbeats, reese sub, arp lead, 174 rave drive",
  "Glossy hard-hitting acoustic trap beat about a wedding dance that feels like floating. Detuned synth pads, tape wow, vapor haze, nostalgic drift",
  "Melancholic coastal afrobeats beat about a church pew and a secret doubt. Oud melody, darbuka percussion, trap 808, desert night pulse",
  "Fragile vengeful future bass beat about a tattoo you got on impulse. Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Playful radio-ready techno trap beat about a graduation night you'll never forget. Distorted 808, cowbell pattern, dark synth lead, phonk aggression",
  "Gritty winter-cold pluggnb beat about a whistle hook kids repeat on the block. Oud melody, darbuka percussion, trap 808, desert night pulse",
  "Rebellious late-night gospel trap beat about a protest chant that becomes a hook. Distorted 808, cowbell pattern, dark synth lead, phonk aggression",
  "Warm confessional gospel trap beat about a label meeting that feels like theater. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Bittersweet sparse phonk beat about a photo booth strip in your wallet. Acid arp, hard techno kick, warehouse tension, hypnotic groove",
  "Moody introspective trap soul beat about a backseat confession during a thunderstorm. Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Intimate introspective g-funk beat about a cassette tape from an ex. Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Glossy experimental house beat about a first kiss on a Brooklyn rooftop. heavy 808, cinematic atmosphere, wide reverb, Amen break chops, industrial noise bursts, breakcore adrenaline",
  "Futuristic atmospheric cinematic trap beat about surviving exam week on cold coffee. Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Gritty late-night house beat about a desert highway with no destination. Skippy UK garage drums, bouncy bassline, vocal chop stabs, 2-step swing",
  "Euphoric cinematic western trap beat about a Hanukkah candle and old wounds. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Rebellious cinematic pluggnb beat about a Ramadan night of quiet gratitude. Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Serene confessional amapiano beat about a warehouse party at 4am. Funk synth bass, talkbox lead, crisp drums, west-coast haze",
  "Aggressive sparse boom bap beat about a Vegas lights and bad decisions. Punchy kick clusters, bed squeak sample, jersey bounce, edit energy",
  "Organic neon-lit orchestral trap beat about a hiking trail that clears your head. heavy 808, cinematic atmosphere, wide reverb, Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Fragile neon-lit dark trap beat about a warehouse party at 4am. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Serene anthemic cinematic trap beat about a whistle hook at the cookout. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Minimal cathartic lo-fi melodic trap beat about a film noir scene in your own life. Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Tense radio-ready jersey club beat about a kitchen dance at 2am in socks. heavy 808, cinematic atmosphere, wide reverb, Chip arp layer, orchestral stab, boss-fight intensity, game-ready",
  "Dreamy warehouse phonk beat about a slow dance in a loud club. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Minimal raw western trap beat about a birthday alone that still feels full. Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Ethereal cinematic jazz fusion trap beat about a festival sunset that changes everything. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Cinematic rebellious R&B beat about a hitchhiker story with no ending. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Polished late-night rai trap beat about a slow dance in a loud club. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Radiant hard-hitting latin trap beat about a melody hummed on a bus. Acid arp, hard techno kick, warehouse tension, hypnotic groove",
  "Euphoric layered orchestral trap beat about a relapse night you barely survived. Punchy kick clusters, bed squeak sample, jersey bounce, edit energy",
  "Organic raw afro house beat about a documentary crew filming your flaws. heavy 808, cinematic atmosphere, wide reverb, Amen break chops, industrial noise bursts, breakcore adrenaline",
  "Polished introspective afro house beat about a superhero origin in plain clothes. Funk synth bass, talkbox lead, crisp drums, west-coast haze",
  "Serene floating lo-fi melodic trap beat about a Portland bookstore crush. Steel guitar, pedal steel swells, trap hats, cinematic western",
  "Aggressive rebellious baile funk beat about a anime opening energy for your arc. Filtered disco loop, vocoder stab, four kick, French touch chic",
  "Gritty layered melodic drill beat about a luxury hotel room with empty champagne. Nylon guitar arp, soft 808 sub, organic fusion, warm room",
  "Bright floating pluggnb beat about a heist crew planning in whispers. Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Ethereal coastal cinematic trap beat about a snowy cabin with no phone signal. Rolling breakbeats, reese sub, arp lead, 174 rave drive",
  "Cold experimental boom bap beat about a chorus stuck in your head for days. Filtered disco loop, vocoder stab, four kick, French touch chic",
  "Soulful sparse cloud rap beat about a delayed flight that changes your path. Rolling breakbeats, reese sub, arp lead, 174 rave drive",
  "Polished cathartic dancehall beat about quitting a toxic job with no backup plan. Four-on-the-floor kick, piano chords, sidechain pump, terrace vibe",
  "Cold hopeful French drill beat about a delayed flight that changes your path. Log drum bass, shaker groove, jazzy piano, summer club bounce",
  "Polished neon-lit acoustic trap beat about a cassette tape from an ex. Orchestral hits, taiko layer, 808 under strings, trailer rise",
  "Epic cathartic melodic drill beat about surviving exam week on cold coffee. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Haunting suburban deep house beat about a label meeting that feels like theater. Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Triumphant dancefloor emo trap beat about a church pew and a secret doubt. Four-on-the-floor kick, piano chords, sidechain pump, terrace vibe",
  "Lush hopeful phonk drift beat about a São Paulo traffic jam meditation. Airy pads, soft 808, minimal drums, floating stereo width",
  "Serene emotional g-funk beat about quitting a toxic job with no backup plan. Heavy 808, cinematic atmosphere, wide reverb, hook-ready space",
  "Anxious warehouse baile funk beat about a prayer whispered before a risky leap. Detuned synth pads, tape wow, vapor haze, nostalgic drift",
  "Organic hard-hitting French drill beat about your first BeatStars sale at twenty-nine dollars. Funk synth bass, talkbox lead, crisp drums, west-coast haze",
  "Bright neon-lit amapiano beat about a crowd singalong you'll chase forever. Distorted 808, cowbell pattern, dark synth lead, phonk aggression",
  "Futuristic introspective rai trap beat about a skatepark session that heals you. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Organic underground NY drill beat about a superhero origin in plain clothes. Sliding 808, sparse piano stabs, syncopated hi-hats, cold tension",
  "Aggressive toxic French touch house beat about a Sunday gospel after Saturday sins. Rolling breakbeats, reese sub, arp lead, 174 rave drive",
  "Bright late-night melodic drill beat about a bonfire confession with old friends. heavy 808, cinematic atmosphere, wide reverb, Glitch edits, stutter hats, bright leads, hyperpop chaos",
  "Gritty warehouse western trap beat about a collab that almost didn't happen. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Nostalgic vengeful phonk drift beat about a Paris metro ride at rush hour. Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Epic anthemic future bass beat about a lighthouse beam in coastal fog. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Volatile warehouse jersey club beat about a skatepark session that heals you. Punchy snare, 808 slide, dark piano motif, drill pressure",
  "Radiant hard-hitting baroque trap beat about a text left on read for weeks. Hard trap drums, minor guitar loop, 808 glides, late-night mood",
  "Bittersweet hard-hitting amapiano beat about a luxury hotel room with empty champagne. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Dusty hopeful jersey club beat about a small-town dream of making it out. Dusty drums, chopped soul sample, vinyl texture, MPC swing",
  "Glossy rebellious future bass beat about a Marrakech rooftop slow jam. Wobble bass, half-time snare, sound-design drops, dubstep weight",
  "Intimate luxury techno trap beat about scoring the winning penalty in extra time. Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Tense suburban gospel trap beat about a Vegas lights and bad decisions. Acid arp, hard techno kick, warehouse tension, hypnotic groove",
  "Dreamy cathartic NY drill beat about a stream count milestone at 3am. Airy pads, soft 808, minimal drums, floating stereo width",
  "Warm late-night dancehall beat about a therapy breakthrough on a Tuesday. Harp arpeggios, chamber strings, trap drums, baroque clash",
  "Fragile introspective future bass beat about a love letter never sent. Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Rebellious luxury orchestral trap beat about a Diwali lights family reunion. heavy 808, cinematic atmosphere, wide reverb, Glitch edits, stutter hats, bright leads, hyperpop chaos",
  "Futuristic toxic house beat about betrayal and loneliness. Detuned synth pads, tape wow, vapor haze, nostalgic drift",
  "Cinematic neon-lit g-funk beat about a western duel at sunset. Skippy UK garage drums, bouncy bassline, vocal chop stabs, 2-step swing",
  "Euphoric anthemic highlife beat about a sample flip that honors the past. Plucky synths, soft bounce 808, light hats, pluggnb sparkle",
  "Dreamy sun-drenched French touch house beat about a cassette tape from an ex. Filtered disco loop, vocoder stab, four kick, French touch chic"
] as const;
