import type { LocalePromptPools } from "../localePools/types";

const SONG = [
  "Euphorische Hymne, um den WM-Sieg deines Landes 2026 zu feiern",
  "Song über ein Finale im Elfmeterschießen — Stadiontränen und pure Freude",
  "Track für ein TikTok-Reel: POV du hast um 4 Uhr morgens einen Beat fertig",
  "R&B-Ballade für einen Heiratsantrag auf einem Rooftop, modern und nicht kitschig",
  "Lustiger Song über einen Collaborator, der überall denselben Hi-Hat benutzt",
  "Melodischer Trap über die Angst kurz vor dem Senden einer wichtigen DM",
  "Gospel-Pop-Song für einen Sonntag nach der Straßenparty im Viertel",
  "Feel-good-Ukulele-Song für eine Markenwerbung mit echtem menschlichem Warmherz",
  "Corridos tumbados über das Comeback eines Familienunternehmens",
  "Glossy K-Pop-Song für eine Dance-Challenge, die viral gehen muss",
  "Slow Jam für eine standesamtliche Hochzeit auf einem Rooftop in Marrakesch",
  "Song darüber, um Mitternacht KI-Musik zu entdecken und nie wieder zu schlafen",
  "Back-to-work-Hymne für Indie-Creator, die endlich ihr Projekt releasen",
  "Song für eine Doku über Straßenkünstler — rohe Stimme, Respekt",
  "Electro-Pop über einen europäischen Festival-Sommer und kollektive Euphorie",
  "Drill plus Streicher für eine lokale Sportwerbung, die Gänsehaut macht",
  "Song zum 30. Geburtstag eines Vaters — Rap-Fan, zart und ein bisschen old-school",
  "Track über deinen ersten BeatStars-Verkauf für 29 $ — Stolz und Unglaube",
  "Phonk-Song für einen Nachtfahrt-Car-Edit, Drift und Neon",
  "Feel-good Amapiano für einen Abend auf der Terrasse mit Freunden",
  "Song über deine Producer-Katze, die über die MIDI-Tastatur läuft",
  "Ironischer French-Pop über Zoom-Meetings, die eine E-Mail hätten sein können",
  "Afrobeats-Song für eine Hochzeits-Afterparty, die zur Tanzparty eskaliert",
  "Klavierballade über einen Ex, der deine Demos hörte, aber nie antwortete",
  "Hymne für dein Sonntags-Fußballteam vor dem entscheidenden Spiel",
  "Reggaeton-Song für einen Junggesellenabschied in Barcelona — fun, nicht cringe",
  "Neo-Soul über einen Crush, den du in der Konzert-Schlange kennengelernt hast",
  "Cinematic Song für einen Indie-Trailer — Aufbau und dann brutale Stille",
  "Lustiger Song darüber, dass dein Spotify-Algorithmus dich nicht mehr versteht",
  "French-Touch-House-Song für eine Pariser Modemarke",
  "Song über Wut und dann Vergebung nach einem Paarstreit",
  "Folk-Song über Oma, die beim Kochen Radio hörte",
  "Jersey-Club-Song für eine New-York-Nacht — Selbstvertrauen und Bounce",
  "Song darüber, einen Elfmeter zu verwandeln und die ganze Bar zum Weinen zu bringen",
  "Pop-Punk über Burnout, der mit „Ich kündige am Montag“ endet",
  "Lo-fi-Song für eine Prüfungsnacht mit Ramen und Hoffnung",
  "Slow R&B über Ghosting nach drei perfekten Dates",
  "Epischer Song für den Launch deines ersten EP",
  "Roadtrip-Van-Song an der Atlantikküste — Fenster auf, Salzluft",
  "Respektvoller Drill-Song über ein Viertel-Comeback, Stolz ohne Klischee",
  "Akustische Melodie, um Danke zu sagen, ohne zu kitschig zu sein",
  "Song über Regen in Paris und einen kaputten Regenschirm — sanfte Melancholie",
  "Afro-House für den Sonnenaufgang nach einer langen Clubnacht",
  "Song über Seelenverwandte auf Distanz — Zeitzonen und Sehnsucht",
  "Playful Pop über einen Hund, der bellt, sobald du als WAV exportierst",
  "Song für eine Energy-Drink-Werbung — jung, urban, ohne Aggression",
  "Track darüber, deinen eigenen Song zum ersten Mal in der Öffentlichkeit zu hören",
  "Moderner Tango-Song für eine Film-Noir-Szene",
  "WM-Hymne für Fans, die alles gegeben haben",
  "Italien-Song: Pasta, Roller, Liebesstreit und Sonnenuntergang",
] as const;

const BEAT = [
  "Type Beat zum Feiern eines WM-Siegs — Hörner, 808, Stadionenergie",
  "Loop für einen Fußball-YouTube-Edit: Spannungsaufbau und euphorischer Drop",
  "Dusty Boom-Bap-Beat für einen Sonntags-Freestyle-Cypher",
  "Jersey-Club-Beat für einen TikTok-Dance-Edit, der viral gehen muss",
  "Amapiano-Instrumental für ein Sommer-Terrassen-DJ-Set",
  "Phonk-Drift-Beat für einen Nachtfahrt-Car-Montage",
  "Lo-fi-Loop für einen 8-Stunden-Study-Stream, Regen und Vinyl-Crackle",
  "French-Touch-House-Beat für eine Pariser Mode-Werbung",
  "Cinematic Trap für einen lokalen Serien-Trailer — Spannung und Impact",
  "Afro-House-Beat für eine Hochzeits-Afterparty, die zur Rave-Party wird",
  "Type Beat „erste Session mit einem echten Mixing Engineer“",
  "Dunkler Drill-Beat für eine urbane Doku — Respekt und Gewicht",
  "Jazz-Rap-Beat für ein Kultur-Podcast-Intro",
  "UK-Garage-Loop für einen kompetitiven Gaming-Montage",
  "Beat, bei dem die 808 die Hauptfigur ist — lustig, aber hart",
  "Type Beat für ein POV-Reel: Mix fertig, WAV exportiert",
  "Melodischer Trap mit regnerischer Paris-Stimmung, Piano und gleitende 808",
  "Reggaeton-Beat für ein Strandvideo — tighter Kick und Dembow",
  "Cinematic Loop für einen Low-Budget-Indie-Trailer",
  "Dembow-Beat für eine Sommer-TikTok-Challenge",
  "Drake-moody Type Beat — Nacht, Introspektion, Platz für den Hook",
  "Peak-Time-Techno-Beat für Warehouse-Afterhours",
  "Acoustic-Trap-Loop für einen Artist, der drauf singen will",
  "Corridos-tumbados-Beat für eine Familienunternehmens-Geschichte",
  "Type Beat „als hätte Metro 2007 produziert“",
  "Jersey-Beat für einen Küchen-Dance-Edit",
  "Phonk-Loop für eine JDM-Drift-Montage",
  "Afroswing-Beat mit UK-Radio-Feel",
  "Type Beat für eine Gen-Z-Sneaker-Werbung — Energie ohne Aggression",
  "Organischer House-Beat für ein Festival-Sunset-Set",
  "Melodischer Drill-Loop für UK- oder US-Artists",
  "Lo-fi Boom-Bap-Beat für Instagram-Live-Freestyle",
  "WM-Finale Type Beat — moderne Fanfare und 808",
  "Trap-Soul-Beat für Late-Night-R&B-Vocals",
  "Amapiano-Log-Drum-Loop für ein heißes Club-Set",
  "Experimenteller Beat für ein Reel „Producer testet KI“",
  "Pop-Punk Type Beat für eine Burnout-Hymne",
  "UK-Garage-2-Step-Beat für einen Streetwear-Edit",
  "Cinematic Western-Trap-Loop für eine lokale Werbung",
  "K-Pop-Instrumental-Beat für eine Dance-Challenge",
  "Type Beat „erster Beat verkauft auf BeatStars“",
  "Hyperpop-Glitch-Beat für einen absurden TikTok-Edit",
  "Deep-House-Loop für ein Premium-Podcast-Intro",
  "Boom-Bap Nas-Energy Type Beat für ernsten Freestyle",
  "Romantischer Reggaeton Type Beat für einen Sommer-Song",
  "Phonk-Cowbell-Beat für eine Gym-PR-Montage",
  "Orchestral-Trap-Loop für einen Sport-Trailer",
  "French-Filter-House-Beat für eine Lifestyle-Marke",
  "Type Beat „3-Uhr-morgens-Studio-Session, kalter Kaffee“",
  "Melodischer R&B Type Beat für einen Fernbeziehungs-Lovesong",
] as const;

export const CURATED_DE: LocalePromptPools = { song: SONG, beat: BEAT, hero: [] };
