import type { LocalePromptPools } from "../localePools/types";

const FR_SONG: readonly string[] = [
  "Hymne euphorique pour célébrer la victoire du pays à la Coupe du monde 2026",
  "Chanson sur la finale en prolongations, émotion de stade et larmes de joie",
  "Son pour un reel TikTok « POV : tu viens de finir un beat à 4h du mat »",
  "Ballade R&B pour une demande en mariage sur un rooftop, moderne pas cucul",
  "Chanson drôle sur ton collègue qui met le même hi-hat sur tous ses sons",
  "Trap mélodique sur l'angoisse avant d'envoyer un DM important",
  "Chanson gospel pop pour un dimanche après la fête de quartier",
  "Ukulele feel-good pour une pub marque qui veut du vrai « human touch »",
  "Corridos tumbados sur une histoire de family business qui se relève",
  "Chanson K-pop glossy pour un challenge dance qui doit percer",
  "Slow jam pour un mariage civil en rooftop à Marrakech",
  "Chanson sur découvrir une IA musicale à minuit et ne plus dormir",
  "Anthem rentrée pour créateurs indépendants qui sortent enfin leur projet",
  "Chanson pour un docu sur des artistes de rue, voix brute et respect",
  "Electro-pop sur un été européen de festivals et d'excitation collective",
  "Mélange drill et cordes pour une pub sport locale qui donne des frissons",
  "Chanson pour les 30 ans d'un père fan de rap, tendre et un peu old-school",
  "Son sur la première vente BeatStars à 29 $ — fierté et disbelief",
  "Chanson phonk pour un montage voiture nuit, drift et néons",
  "Amapiano feel-good pour une soirée terrace entre potes",
  "Chanson sur ton chat producteur qui marche sur le clavier MIDI",
  "Pop française ironique sur les réunions Zoom qui auraient pu être un mail",
  "Chanson afrobeat pour un after mariage qui part en danse totale",
  "Ballade piano sur un ex qui écoutait tes demos sans jamais répondre",
  "Hymne pour ton équipe de foot du dimanche, avant le match décisif",
  "Chanson reggaeton pour un EVG à Barcelone, fun sans cliché lourd",
  "Neo-soul sur un crush rencontré dans une file d'attente de concert",
  "Chanson ciné pour une bande-annonce indie, montée et silence brutal",
  "Drôle : une chanson sur ton algorithme Spotify qui ne te comprend plus",
  "Chanson house française touch pour une marque mode parisienne",
  "Son sur la colère puis le pardon après une engueulade de couple",
  "Chanson folk sur grand-mère qui écoutait la radio en cuisinant",
  "Jersey club pour une nuit New York, énergie et confiance",
  "Chanson sur scorer en penalty et faire pleurer tout le bar",
  "Pop punk sur un burnout qui finit par un « j'démissionne lundi »",
  "Chanson lo-fi pour une nuit d'examens avec ramen et espoir",
  "Slow R&B sur un ghosting après trois dates parfaites",
  "Chanson épique pour le lancement de ton premier EP",
  "Son sur un road trip van Atlantique, fenêtres ouvertes et vent salé",
  "Chanson drill respectueuse sur une relève de quartier, fierté sans cliché",
  "Mélodie acoustique pour dire merci à quelqu'un sans être lourd",
  "Chanson sur la pluie à Paris et un parapluie cassé — mélancolie douce",
  "Afro-house pour un lever de soleil après une nuit club",
  "Chanson sur deux âmes sœurs à distance, timezone et manque",
  "Pop playful sur un chien qui aboie quand tu exportes en WAV",
  "Chanson pour une pub boisson énergisante, jeune et urbaine sans être agressive",
  "Son sur la première fois qu'on entend son propre morceau en public",
  "Chanson tango moderne pour une scène de film noir",
  "Hymne Coupe du monde pour les supporters qui ont tout donné",
  "Chanson sur l'Italie : pasta, scooter, dispute amoureuse et coucher de soleil",
];

const FR_BEAT: readonly string[] = [
  "Type beat pour célébrer la victoire à la Coupe du monde — cuivres, 808, stade",
  "Loop pour un edit YouTube foot : montée tension puis drop euphorique",
  "Beat boom bap dusty pour un cypher freestyle du dimanche",
  "Jersey club pour un edit TikTok danse qui doit percer",
  "Instrumental amapiano pour un DJ set terrace en été",
  "Beat phonk drift pour montage voiture nuit, néons et vitesse",
  "Loop lo-fi pour study stream 8h, pluie et vinyl crackle",
  "House française touch pour une pub mode parisienne",
  "Trap ciné pour trailer série locale, tension et impact",
  "Afro-house pour l'after d'un mariage qui part en danse",
  "Type beat « première session avec un vrai ingé son »",
  "Drill sombre pour documentaire urbain, respect et gravité",
  "Beat jazz rap pour intro podcast culture",
  "Loop UK garage pour montage gaming compétitif",
  "Beat où le 808 est le personnage principal — drôle mais hard",
  "Type beat pour un reel « POV : mix terminée, export WAV »",
  "Melodic trap pluie parisienne, piano et 808 glissants",
  "Beat reggaeton pour un clip plage, kick sec et dembow",
  "Loop cinematic pour bande-annonce indie low-budget",
  "Beat dembow pour un challenge TikTok été",
  "Type beat Drake moody — nuit, introspection, hook space",
  "Beat techno peak pour after warehouse",
  "Loop acoustic trap pour un artiste qui veut chanter dessus",
  "Beat corridos tumbados pour histoire family business",
  "Type beat « si Metro avait produit en 2007 »",
  "Beat jersey pour edit danse fille/garçon en cuisine",
  "Loop phonk pour montage drift JDM",
  "Beat afroswing pour un son radio UK feel",
  "Type beat pour pub sneakers Gen Z, énergie sans agressivité",
  "Beat house organique pour set festival sunset",
  "Loop drill mélodique pour artiste UK ou FR",
  "Beat lo-fi boom bap pour freestyle Instagram live",
  "Type beat finale Coupe du monde — fanfare moderne et 808",
  "Beat trap soul pour chanson R&B late night",
  "Loop amapiano log drum pour set club chaud",
  "Beat experimental pour reel « producteur qui teste l'IA »",
  "Type beat pop punk pour chanson burnout",
  "Beat UK garage 2-step pour edit mode streetwear",
  "Loop cinematic western trap pour pub locale",
  "Beat K-pop instrumental pour challenge dance",
  "Type beat « premier beat vendu sur BeatStars »",
  "Beat hyperpop glitch pour edit TikTok absurde",
  "Loop deep house pour podcast intro premium",
  "Beat boom bap Nas energy pour freestyle sérieux",
  "Type beat reggaeton romantique pour chanson été",
  "Beat phonk cowbell pour montage gym PR",
  "Loop trap orchestral pour trailer sport",
  "Beat french touch filter house pour marque lifestyle",
  "Type beat « session studio 3h du mat, café froid »",
];

const EN_SONG: readonly string[] = [
  "Euphoric anthem to celebrate your country winning the 2026 World Cup",
  "Song about a final that goes to penalties — stadium tears and joy",
  "Track for a TikTok reel: POV you finished a beat at 4am",
  "R&B ballad for a rooftop proposal, modern not cheesy",
  "Funny song about a collaborator who uses the same hi-hat on everything",
  "Melodic trap about anxiety before sending an important DM",
  "Gospel-pop song for a Sunday after the block party",
  "Feel-good ukulele song for a brand ad that wants real human warmth",
  "Corridos tumbados about a family business comeback",
  "Glossy K-pop song for a dance challenge that needs to blow up",
  "Slow jam for a civil wedding rooftop in Marrakech",
  "Song about discovering AI music at midnight and never sleeping again",
  "Back-to-work anthem for indie creators finally shipping their project",
  "Song for a street-artist documentary — raw voice, respect",
  "Electro-pop about a European summer of festivals and collective hype",
  "Drill plus strings for a local sports ad that gives chills",
  "Song for a dad's 30th birthday — he's a rap head, keep it tender",
  "Track about your first BeatStars sale at $29 — pride and disbelief",
  "Phonk song for a night-drive car edit, drift and neon",
  "Feel-good amapiano for a terrace hang with friends",
  "Song about your producer cat walking on the MIDI keyboard",
  "Ironic French pop about Zoom meetings that should've been an email",
  "Afrobeats song for a wedding after-party that turns into a dance riot",
  "Piano ballad about an ex who listened to your demos but never replied",
  "Hymn for your Sunday football team before the decisive match",
  "Reggaeton song for a Barcelona bachelor party — fun, not cringe",
  "Neo-soul about a crush met in a concert queue",
  "Cinematic song for an indie trailer — rise then brutal silence",
  "Funny song about your Spotify algorithm not getting you anymore",
  "French-touch house song for a Paris fashion brand",
  "Song about anger then forgiveness after a couple fight",
  "Folk song about grandma listening to radio while cooking",
  "Jersey club song for a New York night — confidence and bounce",
  "Song about scoring a penalty and making the whole bar cry",
  "Pop punk about burnout ending with I quit on Monday",
  "Lo-fi song for an exam all-nighter with ramen and hope",
  "Slow R&B about getting ghosted after three perfect dates",
  "Epic song for launching your first EP",
  "Road-trip van song along the Atlantic — windows down, salt air",
  "Respectful drill song about a neighborhood comeback, pride without cliché",
  "Acoustic melody to say thank you without being heavy",
  "Song about rain in Paris and a broken umbrella — soft melancholy",
  "Afro-house for sunrise after a long club night",
  "Long-distance soulmates song — time zones and missing you",
  "Playful pop about a dog barking whenever you export WAV",
  "Song for an energy drink ad — young urban without being aggressive",
  "Track about hearing your own song in public for the first time",
  "Modern tango song for a film-noir scene",
  "World Cup hymn for supporters who gave everything",
  "Italy song: pasta, scooter, lovers' spat and sunset",
];

const EN_BEAT: readonly string[] = [
  "Type beat to celebrate a World Cup win — horns, 808, stadium energy",
  "Loop for a football YouTube edit: tension build then euphoric drop",
  "Dusty boom bap beat for a Sunday freestyle cypher",
  "Jersey club beat for a TikTok dance edit that needs to pop",
  "Amapiano instrumental for a summer terrace DJ set",
  "Phonk drift beat for night-drive car montage",
  "Lo-fi loop for an 8-hour study stream, rain and vinyl crackle",
  "French-touch house beat for a Paris fashion ad",
  "Cinematic trap for a local series trailer — tension and impact",
  "Afro-house beat for a wedding after-party that turns into a rave",
  "Type beat first session with a real mixing engineer",
  "Dark drill beat for an urban documentary — respect and weight",
  "Jazz rap beat for a culture podcast intro",
  "UK garage loop for competitive gaming montage",
  "Beat where the 808 is the main character — funny but hard",
  "Type beat for a POV mix finished export WAV reel",
  "Melodic trap rainy Paris mood, piano and sliding 808",
  "Reggaeton beat for a beach video — tight kick and dembow",
  "Cinematic loop for a low-budget indie trailer",
  "Dembow beat for a summer TikTok challenge",
  "Drake moody type beat — night, introspection, hook space",
  "Peak-time techno beat for warehouse afterhours",
  "Acoustic trap loop for an artist who wants to sing on top",
  "Corridos tumbados beat for a family business story",
  "Type beat if Metro produced in 2007",
  "Jersey beat for a kitchen dance edit",
  "Phonk loop for JDM drift montage",
  "Afroswing beat with UK radio feel",
  "Type beat for a Gen Z sneakers ad — energy without aggression",
  "Organic house beat for a festival sunset set",
  "Melodic drill loop for UK or US artists",
  "Lo-fi boom bap beat for Instagram live freestyle",
  "World Cup final type beat — modern fanfare and 808",
  "Trap soul beat for late-night R&B vocals",
  "Amapiano log drum loop for a hot club set",
  "Experimental beat for AI producer testing reel",
  "Pop punk type beat for a burnout anthem",
  "UK garage 2-step beat for streetwear edit",
  "Cinematic western trap loop for a local ad",
  "K-pop instrumental beat for a dance challenge",
  "Type beat first beat sold on BeatStars",
  "Hyperpop glitch beat for absurd TikTok edit",
  "Deep house loop for a premium podcast intro",
  "Boom bap Nas energy type beat for serious freestyle",
  "Romantic reggaeton type beat for a summer song",
  "Phonk cowbell beat for gym PR montage",
  "Orchestral trap loop for a sports trailer",
  "French filter house beat for a lifestyle brand",
  "Type beat 3am studio session cold coffee",
];


export const CURATED_EN: LocalePromptPools = { song: EN_SONG, beat: EN_BEAT, hero: [] };
export const CURATED_FR: LocalePromptPools = { song: FR_SONG, beat: FR_BEAT, hero: [] };
