import type { LocalePromptPools } from "../localePools/types";

const SONG: readonly string[] = [
  "Himno eufórico para celebrar que tu país gane el Mundial 2026",
  "Canción sobre una final que se va a penaltis — lágrimas en el estadio y alegría",
  "Tema para un reel de TikTok: POV terminaste un beat a las 4 de la mañana",
  "Balada R&B para una pedida de mano en una azotea, moderna y sin cursilería",
  "Canción graciosa sobre un colaborador que usa el mismo hi-hat en todo",
  "Trap melódico sobre la ansiedad antes de mandar un DM importante",
  "Canción gospel-pop para un domingo después de la fiesta del barrio",
  "Ukulele feel-good para un anuncio de marca que busca calidez humana de verdad",
  "Corridos tumbados sobre el resurgir de un negocio familiar",
  "Canción K-pop brillante para un reto de baile que tiene que petarlo",
  "Slow jam para una boda civil en azotea en Marrakech",
  "Canción sobre descubrir música con IA a medianoche y no volver a dormir",
  "Himno de vuelta al trabajo para creadores indie que por fin publican su proyecto",
  "Canción para un documental de artistas callejeros — voz cruda, respeto",
  "Electro-pop sobre un verano europeo de festivales y hype colectivo",
  "Drill con cuerdas para un anuncio deportivo local que pone la piel de gallina",
  "Canción para los 30 años de un padre rapero — tierna y un poco old school",
  "Tema sobre tu primera venta en BeatStars a $29 — orgullo e incredulidad",
  "Canción phonk para un montaje nocturno de coche, drift y neón",
  "Amapiano feel-good para una terraza con amigos",
  "Canción sobre tu gato productor caminando sobre el teclado MIDI",
  "Pop irónico sobre reuniones de Zoom que podrían haber sido un email",
  "Canción afrobeats para un after de boda que se convierte en fiesta total",
  "Balada de piano sobre un ex que escuchaba tus demos pero nunca respondía",
  "Himno para tu equipo de fútbol del domingo antes del partido decisivo",
  "Reggaetón para despedida de soltero en Barcelona — divertido, sin cursi",
  "Neo-soul sobre un crush conocido en la fila de un concierto",
  "Canción cinematográfica para un tráiler indie — subida y silencio brutal",
  "Canción graciosa sobre tu algoritmo de Spotify que ya no te entiende",
  "Canción house french-touch para una marca de moda parisina",
  "Canción sobre la rabia y luego el perdón después de una pelea de pareja",
  "Canción folk sobre la abuela escuchando la radio mientras cocina",
  "Jersey club para una noche en Nueva York — confianza y bounce",
  "Canción sobre marcar un penalti y hacer llorar a todo el bar",
  "Pop punk sobre un burnout que acaba en «renuncio el lunes»",
  "Canción lo-fi para una noche de exámenes con ramen y esperanza",
  "Slow R&B sobre un ghosting después de tres citas perfectas",
  "Canción épica para el lanzamiento de tu primer EP",
  "Canción de road trip en furgoneta por la costa atlántica — ventanas abiertas, brisa salada",
  "Canción drill respetuosa sobre el resurgir de un barrio — orgullo sin clichés",
  "Melodía acústica para decir gracias sin ser pesado",
  "Canción sobre lluvia en París y un paraguas roto — melancolía suave",
  "Afro-house para un amanecer después de una larga noche de club",
  "Canción de almas gemelas a distancia — husos horarios y añoranza",
  "Pop juguetón sobre un perro que ladra cada vez que exportas en WAV",
  "Canción para un anuncio de bebida energética — joven y urbana sin ser agresiva",
  "Tema sobre escuchar tu propia canción en público por primera vez",
  "Tango moderno para una escena de cine negro",
  "Himno de Mundial para los supporters que dieron todo",
  "Canción sobre Italia: pasta, scooter, pelea de enamorados y atardecer",
];

const BEAT: readonly string[] = [
  "Type beat para celebrar una victoria en el Mundial — metales, 808, energía de estadio",
  "Loop para un edit de fútbol en YouTube: subida de tensión y drop eufórico",
  "Beat boom bap dusty para un cypher freestyle de domingo",
  "Beat jersey club para un edit de baile en TikTok que tiene que petarlo",
  "Instrumental amapiano para un DJ set en terraza de verano",
  "Beat phonk drift para montaje nocturno de coche",
  "Loop lo-fi para un study stream de 8 horas, lluvia y crackle de vinilo",
  "Beat house french-touch para un anuncio de moda parisina",
  "Trap cinematográfica para tráiler de serie local — tensión e impacto",
  "Beat afro-house para un after de boda que se convierte en rave",
  "Type beat «primera sesión con un ingeniero de mezcla de verdad»",
  "Beat drill oscuro para documental urbano — respeto y peso",
  "Beat jazz rap para intro de podcast de cultura",
  "Loop UK garage para montaje de gaming competitivo",
  "Beat donde el 808 es el protagonista — gracioso pero duro",
  "Type beat para un reel POV «mezcla terminada, export WAV»",
  "Trap melódica mood lluvia parisina, piano y 808 deslizante",
  "Beat reggaetón para vídeo de playa — kick seco y dembow",
  "Loop cinematográfico para tráiler indie low-budget",
  "Beat dembow para un reto de TikTok de verano",
  "Type beat moody estilo Drake — noche, introspección, espacio para hook",
  "Beat techno peak para afterhours en warehouse",
  "Loop acoustic trap para un artista que quiere cantar encima",
  "Beat corridos tumbados para historia de negocio familiar",
  "Type beat «si Metro hubiera producido en 2007»",
  "Beat jersey para edit de baile en la cocina",
  "Loop phonk para montaje drift JDM",
  "Beat afroswing con vibe de radio UK",
  "Type beat para anuncio de sneakers Gen Z — energía sin agresión",
  "Beat organic house para set de festival al atardecer",
  "Loop drill melódico para artistas UK o US",
  "Beat lo-fi boom bap para freestyle en Instagram live",
  "Type beat final de Mundial — fanfarria moderna y 808",
  "Beat trap soul para vocales R&B nocturnas",
  "Loop amapiano log drum para set caliente en club",
  "Beat experimental para reel «productor probando IA»",
  "Type beat pop punk para himno de burnout",
  "Beat UK garage 2-step para edit de streetwear",
  "Loop cinematic western trap para anuncio local",
  "Beat instrumental K-pop para reto de baile",
  "Type beat «primer beat vendido en BeatStars»",
  "Beat hyperpop glitch para edit absurdo de TikTok",
  "Loop deep house para intro premium de podcast",
  "Type beat energía boom bap estilo Nas para freestyle serio",
  "Type beat reggaetón romántico para canción de verano",
  "Beat phonk cowbell para montaje de PR en gym",
  "Loop trap orquestal para tráiler deportivo",
  "Beat french filter house para marca lifestyle",
  "Type beat «sesión de estudio a las 3 de la mañana, café frío»",
];

export const CURATED_ES: LocalePromptPools = { song: SONG, beat: BEAT, hero: [] };
