import type { LocalePromptPools } from "../localePools/types";

const SONG = [
  "Inno euforico per celebrare la vittoria del tuo paese ai Mondiali 2026",
  "Canzone su una finale ai rigori — lacrime da stadio e gioia pura",
  "Brano per un reel TikTok: POV hai finito un beat alle 4 del mattino",
  "Ballata R&B per una proposta sul rooftop, moderna e non sdolcinata",
  "Canzone divertente su un collaboratore che usa lo stesso hi-hat su tutto",
  "Trap melodica sull'ansia prima di mandare un DM importante",
  "Canzone gospel-pop per una domenica dopo la festa di quartiere",
  "Canzone ukulele feel-good per uno spot che vuole calore umano autentico",
  "Corridos tumbados su un ritorno in auge di un'attività di famiglia",
  "Canzone K-pop glossy per una dance challenge che deve esplodere",
  "Slow jam per un matrimonio civile su un rooftop a Marrakech",
  "Canzone su scoprire la musica IA a mezzanotte e non dormire più",
  "Inno back-to-work per creator indipendenti che finalmente pubblicano il progetto",
  "Canzone per un documentario su artisti di strada — voce cruda, rispetto",
  "Electro-pop su un'estate europea di festival ed euforia collettiva",
  "Drill con archi per uno spot sportivo locale che fa venire la pelle d'oca",
  "Canzone per i 30 anni di un papà fan di rap, tenera e un po' old-school",
  "Brano sulla prima vendita su BeatStars a 29 $ — orgoglio e incredulità",
  "Canzone phonk per un edit notturno in auto, drift e neon",
  "Amapiano feel-good per una serata in terrazza con gli amici",
  "Canzone sul tuo gatto producer che cammina sulla tastiera MIDI",
  "Pop ironico sulle riunioni Zoom che potevano essere un'email",
  "Canzone afrobeats per un after di matrimonio che diventa una festa totale",
  "Ballata al piano su un ex che ascoltava le tue demo ma non rispondeva mai",
  "Inno per la tua squadra di calcio della domenica, prima della partita decisiva",
  "Canzone reggaeton per un addio al celibato a Barcellona — divertente, non cringe",
  "Neo-soul su una crush incontrata in coda a un concerto",
  "Canzone cinematografica per un trailer indie — crescendo e poi silenzio brutale",
  "Canzone divertente sul tuo algoritmo Spotify che non ti capisce più",
  "Canzone house french touch per un brand di moda parigino",
  "Canzone su rabbia e poi perdono dopo una lite di coppia",
  "Canzone folk sulla nonna che ascoltava la radio mentre cucinava",
  "Canzone jersey club per una notte a New York — energia e sicurezza",
  "Canzone su segnare un rigore e far piangere tutto il bar",
  "Pop punk su un burnout che finisce con «mi licenzio lunedì»",
  "Canzone lo-fi per una notte d'esami con ramen e speranza",
  "Slow R&B su un ghosting dopo tre appuntamenti perfetti",
  "Canzone epica per il lancio del tuo primo EP",
  "Canzone road trip in van sull'Atlantico — finestre aperte e aria salata",
  "Canzone drill rispettosa su una ripresa di quartiere, orgoglio senza cliché",
  "Melodia acustica per dire grazie senza essere pesante",
  "Canzone sulla pioggia a Parigi e un ombrello rotto — malinconia dolce",
  "Afro-house per un'alba dopo una lunga notte in club",
  "Canzone su due anime gemelle a distanza — fusi orari e mancanza",
  "Pop giocosa su un cane che abbaia ogni volta che esporti in WAV",
  "Canzone per uno spot di bevanda energetica — giovane e urbano senza aggressività",
  "Brano sulla prima volta che senti la tua canzone in pubblico",
  "Canzone tango moderna per una scena da film noir",
  "Inno Mondiali per i tifosi che hanno dato tutto",
  "Canzone sull'Italia: pasta, scooter, litigio d'amore e tramonto",
] as const;

const BEAT = [
  "Type beat per celebrare una vittoria ai Mondiali — ottoni, 808, energia da stadio",
  "Loop per un edit calcistico su YouTube: tensione crescente e drop euforico",
  "Beat boom bap dusty per un cypher freestyle della domenica",
  "Beat jersey club per un edit danza TikTok che deve spaccare",
  "Strumentale amapiano per un DJ set estivo in terrazza",
  "Beat phonk drift per un montaggio notturno in auto",
  "Loop lo-fi per uno study stream di 8 ore, pioggia e crackle del vinile",
  "Beat house french touch per uno spot di moda parigino",
  "Trap cinematografica per un trailer di serie locale — tensione e impatto",
  "Beat afro-house per un after di matrimonio che diventa un rave",
  "Type beat «prima sessione con un vero ingegnere del suono»",
  "Beat drill scuro per un documentario urbano — rispetto e peso",
  "Beat jazz rap per l'intro di un podcast cultura",
  "Loop UK garage per un montaggio gaming competitivo",
  "Beat dove l'808 è il protagonista — divertente ma duro",
  "Type beat per un reel POV: mix finito, export WAV",
  "Trap melodica mood pioggia parigina, piano e 808 scivolanti",
  "Beat reggaeton per un video in spiaggia — kick secco e dembow",
  "Loop cinematografico per un trailer indie low-budget",
  "Beat dembow per una challenge TikTok estiva",
  "Type beat Drake moody — notte, introspezione, spazio per l'hook",
  "Beat techno peak-time per after warehouse",
  "Loop acoustic trap per un artista che vuole cantarci sopra",
  "Beat corridos tumbados per una storia di attività di famiglia",
  "Type beat «se Metro avesse prodotto nel 2007»",
  "Beat jersey per un edit danza in cucina",
  "Loop phonk per un montaggio drift JDM",
  "Beat afroswing con feel da radio UK",
  "Type beat per uno spot sneakers Gen Z — energia senza aggressività",
  "Beat house organico per un set festival al tramonto",
  "Loop drill melodico per artisti UK o US",
  "Beat lo-fi boom bap per freestyle live su Instagram",
  "Type beat finale Mondiali — fanfara moderna e 808",
  "Beat trap soul per voci R&B notturne",
  "Loop amapiano log drum per un set club caldo",
  "Beat sperimentale per un reel «producer che testa l'IA»",
  "Type beat pop punk per un inno sul burnout",
  "Beat UK garage 2-step per un edit streetwear",
  "Loop cinematic western trap per uno spot locale",
  "Beat strumentale K-pop per una dance challenge",
  "Type beat «primo beat venduto su BeatStars»",
  "Beat hyperpop glitch per un edit TikTok assurdo",
  "Loop deep house per un intro podcast premium",
  "Type beat boom bap energia Nas per freestyle serio",
  "Type beat reggaeton romantico per una canzone estiva",
  "Beat phonk cowbell per un montaggio PR in palestra",
  "Loop trap orchestrale per un trailer sportivo",
  "Beat french filter house per un brand lifestyle",
  "Type beat «sessione in studio alle 3 di notte, caffè freddo»",
  "Type beat R&B melodico per una canzone d'amore a distanza",
] as const;

export const CURATED_IT: LocalePromptPools = { song: SONG, beat: BEAT, hero: [] };
