import type { LocalePromptPools } from "../localePools/types";

const SONG = [
  "Hino eufórico para celebrar o seu país vencendo a Copa do Mundo de 2026",
  "Música sobre uma final nos pênaltis — lágrimas de estádio e alegria pura",
  "Faixa para um reel no TikTok: POV você terminou um beat às 4 da manhã",
  "Balada de R&B para um pedido de casamento no rooftop, moderna e sem melosidade",
  "Música engraçada sobre um colaborador que usa o mesmo hi-hat em tudo",
  "Trap melódico sobre a ansiedade antes de mandar uma DM importante",
  "Música gospel-pop para um domingo depois da festa de rua do bairro",
  "Música de ukulele feel-good para um comercial de marca com calor humano de verdade",
  "Corridos tumbados sobre a retomada de um negócio de família",
  "Música K-pop glossy para um dance challenge que precisa estourar",
  "Slow jam para um casamento civil no rooftop em Marrakech",
  "Música sobre descobrir música com IA à meia-noite e nunca mais dormir",
  "Hino de volta ao trabalho para criadores independentes finalmente lançando o projeto",
  "Música para um documentário sobre artistas de rua — voz crua, respeito",
  "Electro-pop sobre um verão europeu de festivais e hype coletivo",
  "Drill com cordas para um comercial esportivo local que arrepia",
  "Música para os 30 anos de um pai fã de rap, carinhosa e meio old-school",
  "Faixa sobre sua primeira venda no BeatStars por US$ 29 — orgulho e incredulidade",
  "Música phonk para um edit de carro à noite, drift e neon",
  "Amapiano feel-good para uma noite na varanda com os amigos",
  "Música sobre seu gato producer pisando no teclado MIDI",
  "Pop irônico sobre reuniões no Zoom que poderiam ter sido um e-mail",
  "Música afrobeats para um after de casamento que vira uma festa dançante",
  "Balada de piano sobre um ex que ouvia suas demos mas nunca respondia",
  "Hino para o seu time de futebol de domingo, antes do jogo decisivo",
  "Música reggaeton para um chá de panela em Barcelona — divertida, sem cringe",
  "Neo-soul sobre uma paixão encontrada na fila de um show",
  "Música cinematográfica para um trailer indie — subida e depois silêncio brutal",
  "Música engraçada sobre o algoritmo do Spotify que não te entende mais",
  "Música house french touch para uma marca de moda parisiense",
  "Música sobre raiva e depois perdão depois de uma briga de casal",
  "Música folk sobre a vovó ouvindo rádio enquanto cozinhava",
  "Música jersey club para uma noite em Nova York — confiança e gingado",
  "Música sobre marcar um pênalti e fazer o bar inteiro chorar",
  "Pop punk sobre burnout terminando com «vou pedir demissão na segunda»",
  "Música lo-fi para uma noite de prova com miojo e esperança",
  "Slow R&B sobre ghosting depois de três encontros perfeitos",
  "Música épica para o lançamento do seu primeiro EP",
  "Música de road trip de van pelo Atlântico — janelas abertas e ar salgado",
  "Música drill respeitosa sobre a retomada de um bairro, orgulho sem clichê",
  "Melodia acústica para agradecer alguém sem ficar pesado",
  "Música sobre chuva em Paris e um guarda-chuva quebrado — melancolia suave",
  "Afro-house para o nascer do sol depois de uma longa noite de balada",
  "Música sobre almas gêmeas à distância — fusos horários e saudade",
  "Pop divertido sobre um cachorro que late toda vez que você exporta em WAV",
  "Música para um comercial de energético — jovem e urbano sem ser agressivo",
  "Faixa sobre ouvir sua própria música em público pela primeira vez",
  "Música de tango moderno para uma cena de film noir",
  "Hino da Copa do Mundo para torcedores que deram tudo de si",
  "Música sobre a Itália: massa, scooter, briga de amor e pôr do sol",
] as const;

const BEAT = [
  "Type beat para celebrar uma vitória na Copa — metais, 808, energia de estádio",
  "Loop para um edit de futebol no YouTube: tensão crescente e drop eufórico",
  "Beat boom bap dusty para um cypher de freestyle de domingo",
  "Beat jersey club para um edit de dança no TikTok que precisa bombar",
  "Instrumental amapiano para um DJ set de verão na varanda",
  "Beat phonk drift para montagem de carro à noite",
  "Loop lo-fi para uma live de estudo de 8 horas, chuva e crackle de vinil",
  "Beat house french touch para um comercial de moda parisiense",
  "Trap cinematográfico para trailer de série local — tensão e impacto",
  "Beat afro-house para um after de casamento que vira rave",
  "Type beat «primeira sessão com um engenheiro de mixagem de verdade»",
  "Beat drill sombrio para documentário urbano — respeito e peso",
  "Beat jazz rap para intro de podcast de cultura",
  "Loop UK garage para montagem de gaming competitivo",
  "Beat onde o 808 é o personagem principal — engraçado mas pesado",
  "Type beat para um reel POV: mix pronto, export WAV",
  "Trap melódico clima chuvoso em Paris, piano e 808 deslizantes",
  "Beat reggaeton para um vídeo na praia — kick firme e dembow",
  "Loop cinematográfico para trailer indie low-budget",
  "Beat dembow para um challenge de verão no TikTok",
  "Type beat Drake moody — noite, introspecção, espaço pro hook",
  "Beat techno peak-time para after em galpão",
  "Loop acoustic trap para um artista que quer cantar por cima",
  "Beat corridos tumbados para história de negócio de família",
  "Type beat «se o Metro tivesse produzido em 2007»",
  "Beat jersey para edit de dança na cozinha",
  "Loop phonk para montagem de drift JDM",
  "Beat afroswing com vibe de rádio UK",
  "Type beat para comercial de tênis Gen Z — energia sem agressividade",
  "Beat house orgânico para set de festival no pôr do sol",
  "Loop drill melódico para artistas do UK ou dos EUA",
  "Beat lo-fi boom bap para freestyle ao vivo no Instagram",
  "Type beat final da Copa do Mundo — fanfarra moderna e 808",
  "Beat trap soul para vocais de R&B de madrugada",
  "Loop amapiano log drum para um set quente de club",
  "Beat experimental para reel «producer testando IA»",
  "Type beat pop punk para um hino de burnout",
  "Beat UK garage 2-step para edit de streetwear",
  "Loop cinematic western trap para comercial local",
  "Beat instrumental K-pop para dance challenge",
  "Type beat «primeiro beat vendido no BeatStars»",
  "Beat hyperpop glitch para edit absurdo no TikTok",
  "Loop deep house para intro premium de podcast",
  "Type beat boom bap energia Nas para freestyle sério",
  "Type beat reggaeton romântico para uma música de verão",
  "Beat phonk cowbell para montagem de PR na academia",
  "Loop trap orquestral para trailer esportivo",
  "Beat french filter house para marca lifestyle",
  "Type beat «sessão de estúdio às 3 da manhã, café frio»",
  "Type beat de R&B melódico para uma música de amor à distância",
] as const;

export const CURATED_PT: LocalePromptPools = { song: SONG, beat: BEAT, hero: [] };
