import type { LocalePromptPools } from "../localePools/types";

const SONG = [
  "庆祝国家在2026世界杯夺冠的振奋人心赞歌",
  "关于点球大战的决赛 — 球场泪水与喜悦之歌",
  "TikTok短视频：POV 凌晨4点刚做完一个beat",
  "天台求婚用的R&B抒情曲，现代不俗套",
  "调侃合作者每首歌都用同一个踩镲的搞笑歌曲",
  "发重要私信前的焦虑，旋律陷阱曲",
  "街区派对后周日的福音流行歌",
  "品牌广告想要真实人情味的轻松尤克里里曲",
  "家族生意东山再起的科里多斯通巴多斯",
  "需要爆火的舞蹈挑战用光泽感K-pop曲",
  "马拉喀什天台民事婚礼的慢节奏情歌",
  "半夜发现AI音乐再也睡不着的故事",
  "独立创作者终于发布作品的回归赞歌",
  "街头艺术家纪录片 — 原始嗓音与尊重",
  "欧洲夏日音乐节与集体狂热的电子流行",
  "本地体育广告用钻头乐加弦乐，让人起鸡皮疙瘩",
  "说唱老爸30岁生日 — 温柔带点老派",
  "BeatStars第一笔29美元收入 — 骄傲与不敢相信",
  "夜间驾车剪辑用的phonk曲，漂移与霓虹",
  "露台朋友聚会的轻快amapiano",
  "制作人猫咪走在MIDI键盘上的歌",
  "讽刺本可以发邮件的Zoom会议的法式流行",
  "婚礼After派对变成全民跳舞的afrobeats",
  "前任听你的demo却从不回复的钢琴抒情曲",
  "周日足球队决战前的赞歌",
  "巴塞罗那单身派对雷鬼顿 — 有趣不尴尬",
  "演唱会排队遇见心动对象的neo-soul",
  "独立电影预告片用电影感歌曲 — 高潮后骤然静默",
  "搞笑歌：Spotify算法再也搞不懂你了",
  "巴黎时尚品牌的法式touch house",
  "情侣吵架后从愤怒到原谅的歌",
  "奶奶边做饭边听广播的民谣",
  "纽约之夜，自信与律动的Jersey club",
  "点球破门让整个酒吧落泪的歌",
  "倦怠到决定周一辞职的流行朋克",
  "考试通宵、泡面与希望的lo-fi曲",
  "三次完美约会后被ghost的慢节奏R&B",
  "首发EP上线的史诗感歌曲",
  "大西洋沿岸面包车公路旅行 — 摇下车窗、咸咸海风",
  "尊重地讲述社区复兴的drill，没有刻板印象",
  "不沉重地说谢谢的原声旋律",
  "巴黎的雨与坏掉的伞 — 轻柔忧郁",
  "夜店通宵后的日出，afro-house",
  "异地恋灵魂伴侣 — 时区与思念",
  "每次导出WAV就狂叫的狗，俏皮流行曲",
  "能量饮料广告 — 年轻都市但不攻击性",
  "第一次在公共场合听到自己作品的歌",
  "黑色电影场景的现代探戈",
  "献给全力以赴球迷的世界杯赞歌",
  "意大利之歌：意面、小摩托、恋人拌嘴与日落",
] as const;

const BEAT = [
  "庆祝世界杯夺冠的type beat — 铜管、808、球场能量",
  "足球YouTube剪辑用loop：紧张铺垫后欢腾drop",
  "周日freestyle cypher用的复古boom bap beat",
  "需要爆火的TikTok舞蹈剪辑Jersey club beat",
  "夏日露台DJ set的amapiano器乐",
  "夜间驾车蒙太奇的phonk漂移beat",
  "8小时学习直播lo-fi loop，雨声与黑胶杂音",
  "巴黎时尚广告法式touch house beat",
  "本地剧集预告电影感trap，紧张与冲击",
  "婚礼After派对变狂欢的afro-house beat",
  "第一次跟真正混音师进棚的type beat",
  "城市纪录片暗黑drill — 尊重与厚重",
  "文化播客片头爵士说唱beat",
  "竞技游戏剪辑UK garage loop",
  "808当主角的beat — 搞笑但够硬",
  "POV 混音完成导出WAV短视频type beat",
  "巴黎雨夜旋律trap，钢琴与滑动808",
  "海滩视频雷鬼顿beat，紧实kick与dembow",
  "低成本独立预告片电影感loop",
  "夏日TikTok挑战dembow beat",
  "Drake moody type beat — 夜晚、内省、留hook空间",
  "仓库after派对高峰时段techno beat",
  "想在上面唱歌的艺人用原声trap loop",
  "家族生意故事科里多斯通巴多斯beat",
  "假如Metro在2007年制作的type beat",
  "厨房跳舞剪辑Jersey beat",
  "JDM漂移蒙太奇phonk loop",
  "有英国电台感的afroswing beat",
  "Z世代球鞋广告type beat，有能量不攻击性",
  "音乐节日落set有机house beat",
  "英美艺人旋律drill loop",
  "Instagram直播freestyle lo-fi boom bap beat",
  "世界杯决赛type beat — 现代号角与808",
  "深夜R&B人声trap soul beat",
  "热场club set的amapiano log drum loop",
  "AI制作人实验短视频实验beat",
  "倦怠颂歌流行朋克type beat",
  "街头服饰剪辑UK garage 2-step beat",
  "本地广告电影感西部trap loop",
  "舞蹈挑战K-pop器乐beat",
  "BeatStars第一笔售出beat的type beat",
  "荒诞TikTok剪辑hyperpop glitch beat",
  "高端播客片头deep house loop",
  "认真freestyle Nas能量boom bap type beat",
  "夏日情歌浪漫雷鬼顿type beat",
  "健身房PR蒙太奇phonk cowbell beat",
  "体育预告片管弦trap loop",
  "生活方式品牌法式filter house beat",
  "凌晨3点棚里冷咖啡的type beat",
  "制作人猫咪踩MIDI键盘瞬间的type beat",
] as const;

export const CURATED_ZH: LocalePromptPools = { song: SONG, beat: BEAT, hero: [] };
